### PR TITLE
Make CI a reusable workflow

### PR DESCRIPTION
**Pull request by mathiasvr**
One of the reasons I moved the nightly build into a separate file was to avoid having a 'skipped' nightly build step shown on every pull request. Now however there is a skipped nightly job for every pull request under the Actions tab.

This makes the CI workflow only run on pull requests, but also makes it reusable by a workflow that only runs on push events and releases the nightly build. This separation avoids skipping jobs and steps based on conditionals.

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Comment by McGiverGim** [comment]
I think this is confusing for me. Now the pull requests will appear as CI and the nightlies as push?
I prefer that pull requests appear as pull requests and nightlies as nightlies.
I understand that you want to reuse the CI. Maybe is possible to use the CI file without triggers and add a new pull requests file that only includes that?
And maybe change the CI file to Build or something similar I think will be more clear for all.

**Comment by mathiasvr** [comment]
@McGiverGim Yes I considered something like that, but while the file structure makes more sense, I think the CI reports becomes more confusing. E.g. reports on master commits will appear overall as nightly with subtasks of build, test, etc. Here i went with "Push" with lack of a better name, since CI is already inherited and shown and build/test is also already shown as job. PR reports and checks also gets a bit more confusing because of the indirection of steps and jobs.
Sorry if this doesn't make any sense, I can maybe try taking some screenshots.

However, I think making the CI workflow not have triggers and adding a separate PR workflow similar to the Push workflow isn't too bad and might be the least confusing when considering both file structure and job reports. I will update and compare.

**Comment by mathiasvr** [comment]
After taking a look I think renaming the push workflow to nightly makes sense if we consider that to be its main job.

So at first this PR would show push jobs like this:

Screenshot 2022-02-01 at 23 03 37

And PR jobs looked like this:

Screenshot 2022-02-01 at 22 58 46

Now with the new changes I added, push is changed to nightly:

Screenshot 2022-02-02 at 00 09 41

And the PR will look similar by now having the "PR" name prepended like "PR / CI / Build", which is probably fine.

However, now we need to merge it before it will work because the shared workflow is included from the master branch.

**Review by McGiverGim — APPROVED** [review]
It looks good to me now. I will prefer to call "build" the CI one, but is only my preference. So I approve it :)

**Review by Asizon — APPROVED** [review]

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Review by ctzsnooze — APPROVED** [review]

**Review by blckmn — APPROVED** [review]

**Comment by McGiverGim** [comment]
@mathiasvr now that this has been merged, I think is time to create the PR to remove the Azure pipelines?

We will need to create the auth toketn too for the action, to be able to publish the artifacts:
> Error: Parameter token or opts.auth is required

**Comment by mathiasvr** [comment]
@McGiverGim Sure, I will make a PR.

**Pull request merged**
