### PR TITLE
Revise handling of msp CRC errors to prevent referencing undefined objects and allow blackbox packets to retry

### PR DESCRIPTION
**Pull request by etracer65**
Reworked how CRC errors are handled in MSP message handling.  Previously CRC errors were detected but not handled and would lead to the handlers/callbacks referencing undefined objects causing runtime errors.  This would cause the Configurator to hang and was the underlying problem with blackbox downloads freezing.  Additionally this would cause random freezes in the Configurator if a normal MSP message happened to encounter a CRC error.

Now CRC errors are detected and the data is dropped and the handlers/callbacks don't attempt to process the message.  Blackbox download has been enhanced to retry the packet and continue the download.  In the future the opportunity is there to address other types of messages and strategically decide how to handle the CRC error - possibly retry the message if appropriate or respond in some other way.

### CODE REVIEW

**Comment by mikeller** [comment]
Works well for me, merged. Thank you very much, @etracer65.

**Comment by etracer65** [comment]
@mikeller No problem - glad to help.  Turned into a much larger fix than originally intended, but ended up a much more robust solution.  In the process I learned a lot about the Configurator code base so hopefully I can help more in the future.

**Comment by basdelfos** [comment]
Good news is this solution works in a way that it successfully downloaded a 5.1MB dataflash file that is readable in Blackbox Explorer.

Things I noticed
- Slow, it took almost 15 minutes to download (it's slow anyhow)
- 495 packet errors
- Port util. D: 91-99%
- Cycle time occasionally jumps from 128 to 13099 or higher and back
- CPU stable at 30-32% (normally around 27%)

XRACERSPI with BF 3.1.3

**Comment by etracer65** [comment]
@basdelfos I think you something else going on.  495 packet errors is not normal at all.  Most people who were having problems downloading (myself included) tend to get 2-3 packet errors at most.  The problem was before that even a single packet error would cause the Configurator to hang - that's what has been fixed.  I don't have an XRACERSPI target to test.

Can you try a different computer/USB cable?  Try on a different platform?  Not sure what you're using now but man OSX users (like me) were having problems.  Do you have DSHOT enabled?

**Comment by basdelfos** [comment]
I have a MacBook. No Dshot on this quad, it uses multishot. I tried different cable but that did not change anything. 
Just tried on my really old laptop with Win7 and it works perfect with the same cable. Took 5 minutes to download the same dataflash file with 0 packet errors.
Definitely something MacBook/macOS related.

**Comment by mikeller** [comment]
@basdelfos That really sounds like something weird going on with your MacBook there. If you feel like investigating some more, you could create a bootable USB stick with Linux and boot your MacBook into that, and see if dataflash download still gives you errors. That way you'll know if it's hardware or software on your MacBook.

**Comment by basdelfos** [comment]
I tried on a VMWare image running Win7. The two times i tried this way, it stopped downloading completely and the configurator froze up. I don't know if WMWare bypasses the macOS driver or not. 
It's weird indeed. When i have time i will investigate more. For now it is fixed as i successfully downloaded the dataflash.

**Comment by etracer65** [comment]
All indications point towards a SiLabs VCP Mac OS X driver bug.  I'm thinking it's a flow control related issue that's being exacerbated by the jumbo packets that speed up blackbox downloads.  I think this issue may be related:

http://community.silabs.com/t5/Interface/Mac-VCP-driver-DTR-RTS-issue/td-p/185769

SiLabs acknowledged a bug in DTR/RTS handling but doesn't have a fix timeline yet.  Not 100% sure this is the problem for us but maybe we'll get lucky.

**Comment by mikeller** [comment]
@etracer65: Good find. This looks a lot like it could be the culprit.

**Comment by etracer65** [comment]
@mikeller Unfortunately as I investigate further I've come to the conclusion that the underlying cause of the serial corruption **does not appear** to be SiLabs driver related.  Specifically I've been able to replicate the problem using VCP targets ruling out the SiLabs drivers.  I've been heavily investigating and to keep the discussion focused I'll open a new issue with my findings so far.

**Comment by mikeller** [comment]
:-( And the hunt goes on. Was this all on Mac, or what OS are you running the configurator on? (Asking because I've had any dataflash download errors on my setups (linux on x86), except when setting the bitrate too high on CP210x targets.

**Comment by etracer65** [comment]
All reports and my testing indicates problems only on Mac.  I've started a new issue with the investigation.

https://github.com/betaflight/betaflight-configurator/issues/435

I think I'm making progress though…  Or at least I have a theory…  just have to finish some testing.

**Pull request merged**
