### PR TITLE
Added internationalisation support for the sliders mode drop down.

### PR DESCRIPTION
**Pull request by mikeller**
image

### CODE REVIEW

**Comment by haslinghuis** [comment]
Thanks. I tried but failed to move class `sm-min` otherwise the select was hidden.

**Comment by haslinghuis** [comment]
I've fiddled around and found another bug on line 4006. This will fix it:
```
    "pidTuningAbsoluteControlGainHelp": {
        "message": "This feature solves some underlying problems of $t(pidTuningItermRotation.message) and should hopefully replace it at some point. This feature accumulates the absolute gyro error in quad coordinates and mixes a proportional correction into the setpoint. For it to work you need to enable AirMode and $t(pidTuningItermRelax.message) (for $t(pidTuningOptionRP.message)). If you combine this feature with $t(pidTuningIntegratedYaw.message), you can set $t(pidTuningItermRelax.message) enabled for $t(pidTuningOptionRPY.message)."
    },

```
Screenshot from 2021-10-10 20-36-01

We should have enough room to fit all elements on one row if we use an extra header in the first column and adjust width (about 8% + 12%).
Also think we need to adjust the second column to go down on smaller screens at around 600px to fit other labels too.

Working diff:
```
diff --git a/src/css/tabs/pid_tuning.css b/src/css/tabs/pid_tuning.css
index 936c8cae..ebfcc79a 100644
--- a/src/css/tabs/pid_tuning.css
+++ b/src/css/tabs/pid_tuning.css
@@ -817,7 +817,12 @@
 }
 
 .tab-pid_tuning .tuningPIDSliders .pid_titlebar th:first-child {
-    width: 20%;
+    width: 6%;
+    text-align: left;
+    border-right: none;
+}
+.tab-pid_tuning .tuningPIDSliders .pid_titlebar th:nth-child(2) {
+    width: 14%;
     border-right: none;
 }
 
@@ -826,7 +831,7 @@
     border-right: none;
 }
 
-.tab-pid_tuning .tuningPIDSliders .pid_titlebar th:nth-child(2),
+.tab-pid_tuning .tuningPIDSliders .pid_titlebar th:nth-child(3),
 .tab-pid_tuning .tuningFilterSliders .pid_titlebar th:nth-child(2) {
     width: 30px;
 }
@@ -897,7 +902,7 @@
 }
 
 .tab-pid_tuning .subtab-pid .cf_column {
-    min-width: 472px;
+    min-width: 600px; /* 472px; */
     flex: 1;
 }
 
diff --git a/src/tabs/pid_tuning.html b/src/tabs/pid_tuning.html
index 10b2dca4..2402eea2 100644
--- a/src/tabs/pid_tuning.html
+++ b/src/tabs/pid_tuning.html
@@ -174,6 +174,8 @@
                             <tr>
                                 <th scope="col">
                                     <div i18n="pidTuningSliderPidsMode" class="sm-min"></div>
+                                </th>
+                                <th>
                                     <select id="sliderPidsModeSelect" class="sliderMode">
                                         <option value="0" i18n="pidTuningOptionOff"></option>
                                         <option value="1" i18n="pidTuningOptionRP"></option>
```

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> PASS
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> PASS

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> PASS
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> PASS

**Pull request merged**
