### PR TITLE
More virtual information

### PR DESCRIPTION
**Pull request by HThuren**
**Show more sensors, cpu temp on Setup tab**
image
(Sensor will show with #3731)

**Show more realistic battery info on Power tab**
image

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Comment by ctzsnooze** [comment]
Is this a bugfix (4.5) or a new feature (4.6) ?

**Comment by HThuren** [comment]
> Is this a bugfix (4.5) or a new feature (4.6) ?

improvement, see data in some of the new features

**Comment by McGiverGim** [comment]
I think this has sense if it goes with the version that has the new values. If we wait one version it will be outdated always.
So to me this must go in the current release.

**Comment by nerdCopter** [comment]
before/after screenshot please.

**Comment by HThuren** [comment]
> supply before/after screenshot please.

@nerdCopter here you go

**Review by nerdCopter — APPROVED** [review]

**Comment by nerdCopter** [comment]
> Is this a bugfix (4.5) or a new feature (4.6) ?

this is nothing except virtual-data for virtual-mode.

**Review by haslinghuis — APPROVED** [review]

**Review by ctzsnooze — APPROVED** [review]
Thanks!

**Pull request merged**
