### PR TITLE
Motor Output Limit and Profile Cell Count

### PR DESCRIPTION
**Pull request by Asizon**
Added `motor_output_limit` and `auto_profile_cell_count` configurable parameters. I know there is no place at all appropriate to add it, happy to hear opinions and discuss this :)

motoroutputlimitfinal

### CODE REVIEW

**Comment by dridsfpv** [comment]
LIMIT: limits the maximum output signal for the motors. In order to use batteries with more cells than those the motor theoretically supports (make sure the electronics supports the voltage). Less than 100% limit causes a linear reduction in the motor drive signal.
LIMIT =desired KV / real KV * 100 
Example: LIMIT=1800/2700*100=67

CELL COUNT: it allows to assign profiles for different type batteries (with different number of cells). Betaflight automatically detects de voltage of the battery when plugged in the quad and it will select the according profile.

**Comment by mikeller** [comment]
Just a cosmetic remark: Wouldn't it be better to add the tooltips to the fields themselves:

image

This will also make it easier to maintain when fields are moved around.

**Comment by Asizon** [comment]
Yes @mikeller ,much better like that, thanks!
tooltipmotoroutput

**Comment by mikeller** [comment]
@McGiverGim: What do you think about the Sonar 'bugs' reported on this pull request?

**Comment by McGiverGim** [comment]
Until now we have ignored this HTML bugs but we can try to fix them. @Asizon can you look at the Sonar link and try to fix them? If you click on the issue there is an explanation about the problem and how to fix it.

**Comment by Asizon** [comment]
I will try it now! And need to revise the tootltip, what do you think about the above @dridsfpv proposal?

**Comment by mikeller** [comment]
@McGiverGim: Not 100% sure this is the right approach. Pretty much all of these 'bugs' seem to be aim at making content and applications available to vision impaired users through screen readers. While this is a good and important thing for general purpose users, I am reasonably sure that there is only very little overlap between users who can not read text on a screen and users who fly racing drones, therefore I am not sure it is good use of time to fix these 'bugs' - maybe we should just ignore them in the sonar config?

**Comment by McGiverGim** [comment]
True. We can disable them in Sonar to limit this kind of errors.

**Comment by Asizon** [comment]
@mikeller what do you think about these ctzsnooze suggested names??

suggestedmotoroutput

**Comment by mikeller** [comment]
@Asizon: Looks good to me - I think for these settings it is important that the help texts are good, as the things that are controlled by them are relatively complex.

**Comment by ctzsnooze** [comment]
This is really great!
Although it's called `motor_output_limit` in the CLI, it's a linear attenuation of motor outputs, and at max there is a limit.  But it's important to know that it attenuates below the limit.  Hence suggesting that we write 'Attenuation %' to indicate that it isn't a simple 'hard cutoff' limit.  Maybe that will convey a bit better what it actually achieves.

**Comment by mikeller** [comment]
@ctzsnooze: The CLI name is not very good in reality - we should flog they guy who put it in in the first place in betaflight/betaflight#7482 - oh wait. :thinking: 
'Attenuation' is much better indeed. In CLI I'd have concerns about this being a term that isn't necessarily familiar with non-English speakers, whereas in the UI we can address this with translations.

**Comment by ctzsnooze** [comment]
For the info messages, maybe something like:
LIMIT: Attenuates motor commands by the set percentage.  Reduces ESC current and motor heat when using higher cell count batteries, e.g. for a 6S battery on a 4S build, try 66%; for a 4S battery on a 3S build, use 75%.
CELL COUNT: Automatically activates the first profile that has a cell count equal to the connected battery.

**Comment by mikeller** [comment]
@ctzsnooze: Looks good - we probably don't need the 'LIMIT' / 'CELL COUNT' headers _in_ the tooltip - it is clear enough what they belong to.
@Asizon: Do you want to change the texts to @ctzsnooze's proposals?

**Comment by Asizon** [comment]
Yes @mikeller i have updated to ctzsnooze suggested texts :) and squashed. Thanks for your suggestions @ctzsnooze

**Comment by Juzzle1** [comment]
The new tool tip states:
LIMIT: Attenuates motor commands **by** the set percentage. 

Surely this should read 
LIMIT: Attenuates motor commands **to** the set percentage. 

In my mind the current wording implies a value of 100% will attenuate the output by 100% and therefore be zero?

**Comment by mikeller** [comment]
@Juzzle1: You are correct - calling this 'attenuation' is actually not a good term for it anyway, as this is 'the amount of reduction'.

**Comment by Juzzle1** [comment]
I think the term 'limit' is also very confusing, as this suggests  a cap on the peak output power, rather than linear scaling. 

I'd suggest:

Frame title:
_Motor Output Scaling_

Setting Label:
_Scaling Factor_


Tip text: 
_SCALE FACTOR: Motor Output Linear Scale Factor (%). Reduces ESC current and motor heat when using higher cell count batteries, e.g. for similar performance from a 6S battery on a 4S build, try 66%; for a 4S battery on a 3S build, try 75%.
CELL COUNT: Automatically activates the first profile that has a cell count equal to the connected battery._

**Comment by mikeller** [comment]
@Juzzle1: Yes, that sounds better - can I get you to open a pull request for these changes?

**Comment by Asizon** [comment]
Sure that we want to change now all feature name?also @Juzzle1  take acount that the current tooltip is not that, last update is on https://github.com/betaflight/betaflight-configurator/pull/1977

**Comment by mikeller** [comment]
For what I can see this is only used in 2 places, `pidTuningMotorLimit` and `pidTuningMotorLimitHelp`, so the fallout should be benign. And @Juzzle1 is right, 'attenuation' is the wrong term for this - e.g. if you attenuate the output by 20% you are left with 80% of the output.

**Comment by Asizon** [comment]
Yes, i agree that attenuation is wrong and we must change it. But I see that @Juzzle1  also want to change `Motor Output Limit` to `Motor Output Scaling`? .

**Comment by Juzzle1** [comment]
'Limit' is also used in the CLI (`motor_output_limit`) , so don't want to make things more confusing, however I don't think this is the correct terminology for what the feature actually does.

**Pull request merged**
