### PR TITLE
Fix GPS waiting info margin

### PR DESCRIPTION
**Pull request by haslinghuis**
Fixes: #3524

Added some colors in second commit:

image

### CODE REVIEW

**Comment by HThuren** [comment]
Would have approved if I did have the ability ...

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by TheIsotopes — APPROVED** [review]

**Review by blckmn — APPROVED** [review]

**Review by nerdCopter — APPROVED** [review]

**Comment by HThuren** [comment]
@haslinghuis seems to have trouble when translated, the construction like `used.startsWith('used')` don't catch 'used' since it translated.
If you use  `used.startsWith(i18n.getMessage(gnssUsedUsed))` 
example
image

**Comment by HThuren** [comment]
Do you want 'locked' to be green as well, when Used are stated ?
image

**Comment by HThuren** [comment]
> Would like to have orange for locked and yellow for searching :)
> 
> Otherwise only want fully locked, used and healthy to be green: 1st column: unusable, no signal, searching, locked and fully locked 2nd column: unused, used 3d column: non healthy, healthy

#3566 do the job :-)

**Pull request merged**
