### PR TITLE
Filter MSP Output while opening CLI

### PR DESCRIPTION
**Pull request by haslinghuis**
Firmware CLI output starts with `CRLF` so lets check on that to start recording output in CLI and filter MSP data in the CLI output.

Before:
image

After:
Screenshot from 2021-04-01 03-16-02

Now also works with native autocomplete.

### CODE REVIEW

**Comment by TheIsotopes** [comment]
Thanks for fixing it, unfortunately this garbage is now displayed in the input line below. 

Zwischenablagebild

**Comment by McGiverGim** [comment]
Great idea! 

I think remember this was used somehow when enabled some passthrough to see if there is data. For example a passthrough for gps. I suppose this will not be possible with this fix.

**Comment by haslinghuis** [comment]
Thanks. Output on Linux is clean. Will check on Windows and if it doesn't break passthrough. While cliValid is false this is skipping output until a CRLF is encountered.

**Comment by haslinghuis** [comment]
Thanks. Tested output in CLI on Linux and Windows with Matek F411 / F722 Mini and result is clean.
Passthrough should work. While `cliValid` is false it is not echoing data to console until a `CR or LF` is encountered.

@McGiverGim This code only processes on initialization so passthrough should work
@TheIsotopes can you please try a non H7 FC to see I you can reproduce? Also what's missing in your output is
```
#
# Building AutoComplete Cache ... Done!
#
```

**Comment by McGiverGim** [comment]
I don't say passthrough will not work. I only say that I think remember that one way to know if it is working is looking at CLI, you must see the garbage passing by the passthrough.
Now this option does not exist I suspect. I only wanted to notice that. 
But I say all of this by memory, I've not used passthrough since a long, long time ago.

**Comment by TheIsotopes** [comment]
> @TheIsotopes can you please try a non H7 FC to see I you can reproduce? Also what's missing in your output is

Tested now with MatekF405-Mini, same problem. I have disabled the AutoComplete option therefore there is no output. 

MatekF405mini

**Comment by haslinghuis** [comment]
@TheIsotopes should be fixed now.

**Comment by haslinghuis** [comment]
@McGiverGim good point,  this patch is only suppressing output if !cliValid until a `CRLF` is encountered and then starts processing. Tested on 2 platforms with native or advanced autocomplete and no garbage in output anymore. After initialization and processing has started all bytes are allowed for processing. Using `gpspassthrough` should work as processing has already begun.

**Comment by TheIsotopes** [comment]
@haslinghuis ok, it seems to work now. thx 👍

**Comment by haslinghuis** [comment]
@TheIsotopes . Fixed and tested on Windows/Linux.

**Comment by TheIsotopes** [comment]
now works as expected 👍

**Review by McGiverGim — APPROVED** [review]

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - Github identifies PR as mergeable -> PASS
 - PR is not in draft -> PASS
 - Assigned to a milestone -> FAIL
 - cooling off period lapsed (5/05/2021 04:47:41) -> PASS
 - commit count less or equal to three (1 commits) -> PASS
 - 'Don't merge' label NOT found -> PASS
 - 'Needs coordination with betaflight' label NOT found -> PASS
 - At least one 'RN:' label found -> FAIL
 - 'Tested' label found -> FAIL
 - assigned to an approver (None) -> FAIL
 - approver count at least three (1 approvers) -> FAIL

**Review by mikeller — APPROVED** [review]
Tested, works as intended.

**Review by limonspb — APPROVED** [review]

**Pull request merged**
