### PR TITLE
Added new fonts to dropdown list, started using the new symbols.

### PR DESCRIPTION
**Pull request by mikeller**
image

To go with betaflight/betaflight#8159.

### CODE REVIEW

**Comment by mikeller** [comment]
All good, I wanted to test fly them, and did not find them. :stuck_out_tongue:

**Comment by Jetrell** [comment]
> 
> 
> All good, I wanted to test fly them, and did not find them.

I'm envious....Got to wait till August to use them :-(

**Comment by McGiverGim** [comment]
You don't need to. If you want a build ask for it 😉

**Comment by Jetrell** [comment]
> 
> 
> You don't need to. If you want a build ask for it wink

 Absolutely... I have a couple of `FuryF4OSD`. That would be great!   Thanks heaps !

**Comment by mikeller** [comment]
@Jetrell: Grab the latest configurator from https://ci.betaflight.tech/job/BetaFlight_Configurator/lastSuccessfulBuild/artifact/release/, and then go like this:

image

**Pull request merged**
