### PR TITLE
Improvements to analytics collection.

### PR DESCRIPTION
**Pull request by mikeller**
- fix 'Connect' failing before analytics are initialised;
- add tracking for changeset Id to analytics (can add it to the display at a later stage);
- add tracking for 'show development versions for configurator'.

### CODE REVIEW

**Comment by Jakeler** [comment]
This change makes it impossible to build from the release source tar.gz/zip, because the call to `git log` fails outside of a repository. 
Would it be possible to do this without calling git in the build, at least for the release version it should not be neccessary?
Thanks

**Comment by mikeller** [comment]
Yes, it is needed exactly for the release version. Also, there is little point in doing development work outside of a git repository, so building outside of one does not make much sense - if you are developing, just clone the git repository. If not, use the released versions.

**Comment by Jakeler** [comment]
I am asking because i maintain the package for Archlinux (AUR), so there are people who are not doing any development work, but still want to build the stable versions from source (for various reasons). We usually use the released source archives, because it is more efficient than cloning the git repository.

**Comment by mikeller** [comment]
Building this package from the source for a user install is excruciatingly inefficient to start with, so I think doing it properly and cloning the repository will not add much overhead, compared to the download of ~300 MB of libraries and tools that is required to build the package.

But we can look into displaying an appropriate text instead of the changeset id for builds outside of a git repository.

**Pull request merged**
