### PR TITLE
Adjust plot colors

### PR DESCRIPTION
**Pull request by haslinghuis**
- Make colors more readable for light mode when out in the field in motors and sensors tab.

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by nerdCopter** [comment]
my eyes are 50+ years old and i find the dark lines harder to see on dark background.

**Comment by ctzsnooze** [comment]
Background to this is that I was out in the field and trying to read the debug traces in bright sunlight, and I simply could not read the white-on-pale-green numbers.

I regret to say that I'm a 'day theme' user with white background to the traces, and there a darker trace stands out nicely, and the text is easy to read.

Screen Shot 2023-09-17 at 11 47 40

I accept that in night mode it is now a *lot* harder to read these traces:

Screen Shot 2023-09-17 at 11 49 26

Looks like the pale colours work best in night mode, but the darker colours are better in day mode.

The numbers are easier to read in both modes, and its the numbers I had most difficulty with.

Maybe... two options:
- different colours for dark vs light theme (? a lot of work?)
- show the values with a black background always, and put the colour either behind the 'X' 'Y' or 'Z', or in a little square object of it's own?

Not sure what's best here.

PS looking at those images, it's obvious that at some point it would be super nice if the debug listing showed the name of the debug field...  that would be a lot of work though :-)

**Comment by nerdCopter** [comment]
> different colours for dark vs light theme [...]

agree.
i see a new commit but i did not test.

**Review by nerdCopter — APPROVED** [review]

**Comment by nerdCopter** [comment]
:+1: 
image
image

**Review by ctzsnooze — APPROVED** [review]

**Comment by ctzsnooze** [comment]
Looks great!  Thank you @haslinghuis!  Together with the Debug names showing up properly, the sensors tab is now much more useful!

**Pull request merged**
