### PR TITLE
Fix virtual disconnect

### PR DESCRIPTION
**Pull request by haslinghuis**

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by haslinghuis** [comment]
@chmelevskij This is obvious a hack to make it working, need more time to debug and make a logic change :)

**Review by blckmn — APPROVED** [review]

**Comment by haslinghuis** [comment]
@nerdCopter It was not possible to disconnect from virtual connection.

**Comment by HThuren** [comment]
@haslinghuis great catch, I working on a PR with more virtuel data, and this is a great improvement :-)

**Pull request merged**
