### PR TITLE
native (nwjs)

### PR DESCRIPTION
**Pull request by nathantsoi**
tested on macosx (dev mode and release package)

### CODE REVIEW

**Comment by nathantsoi** [comment]
instructions are here: https://github.com/nathantsoi/betaflight-configurator/tree/native#developers

**Comment by borisbstyle** [comment]
npm WARN enoent ENOENT: no such file or directory, open 'D:\development\package.json'
npm WARN development No description
npm WARN development No repository field.
npm WARN development No README data
npm WARN development No license field.

**Comment by borisbstyle** [comment]
it struggles finding package.json and its looking in the wrong directory for it

**Comment by borisbstyle** [comment]
Never mind.....i was working in wrong dir

**Comment by borisbstyle** [comment]
fails for me too btw....

**Comment by nathantsoi** [comment]
not sure why the serial thing was broken in chrome, but it's working now. could use some more cleanup, but its a good first step

**Comment by mikeller** [comment]
Does it have a build target for the Chrome app now?

**Comment by nathantsoi** [comment]
What do you mean? For the chrome extension or the nwjs app? It's the same as before, just build and it works in both.

**Comment by mikeller** [comment]
So how do you build the zip file that you submit to google?

**Comment by nathantsoi** [comment]
fixed noslider ui... well not really fixed... but made it work. features should be on par w/ master, best i can tell... it would be great if some folks would try it.

as for building the zip... whatever you did before? just zip it up i guess?

**Comment by mikeller** [comment]
Considering the size of the dist folder is > 300MB (compared to ~20MB for the entire repo before this patch), I don't think that 'just zip it' is a good solution for submission to the chrome web store. We need to find a way to strip this down to a reasonable size for distribution through a web store.

**Pull request closed without merging**
