### PR TITLE
Added warning for problematic setpoint transition values.

### PR DESCRIPTION
**Pull request by mikeller**

### CODE REVIEW

**Comment by etracer65** [comment]
@ctzsnooze You originally raised this issue.  Any thoughts on the warning text?

**Comment by ctzsnooze** [comment]
Maybe "Setting transition below 0.2 may cause transient, uncommanded deviations in the attitude of the quad when the sticks are moved smoothly and quickly across the transition zone, and will cause reduced stick responsiveness around centre stick, compared to further out."

**Comment by etracer65** [comment]
That's a little verbose for a warning that appears below the sliders.  How about:

> The use of a D Setpoint transition greater than 0 and  less than 0.1 is highly discouraged. Doing so may lead to some instability as the sticks cross the center point.

I also changed the "between" to be more explicit that 0 is not a problem.

**Comment by ctzsnooze** [comment]
I do get a bit verbose  :-)  Also good to indicate that 0 isn't a problem.  How about the even less verbose: 
`D setpoint transition greater than zero, but less than 0.1, may cause instability around centre stick.`

**Pull request merged**
