### PR TITLE
Adjust header bar in mobile devices

### PR DESCRIPTION
**Pull request by McGiverGim**
Simply adjust some CSS in mobile to pass from here:
image
to:
image

### CODE REVIEW

**Review by haslinghuis — APPROVED** [review]

**Review by chmelevskij — APPROVED** [review]

**Comment by haslinghuis** [comment]
@kennyk1011 we do not have the means to do that for you - you have to unsubscribe yourself.

**Comment by haslinghuis** [comment]
Screenshot_20240501-121323

**Comment by haslinghuis** [comment]
Root cause seems to me the image size of the logos, maybe this helps https://www.smashingmagazine.com/2021/10/object-fit-background-size-css/#logos-list

Nokia G60 5G:

_Display. In terms of display, Nokia G60 5G has a 6.58-inches display installed on it. The IPS LCD has a refresh rate of 120Hz, 400 nits (typ) brightness, and a resolution of 1080 x 2408 pixels, 20:9 ratio (~401 ppi density)._

**Comment by McGiverGim** [comment]
It the screen capture was for the Android version (apk, Cordova) the Cordova code hides the port picker and the flash button because they didn't work in Cordova. My code simply adjust it for the PWA version, this version does not hide them.

**Review by haslinghuis — APPROVED** [review]

**Review by blckmn — APPROVED** [review]

**Comment by pfeerick** [comment]
> I've asked and unsubscribed from each individual person and all together. Please get me off the mailing list.

@kennyk1011 If you are getting notified of PRs/Issues that you haven't even commented in or subscribed to, it probably means you have your watch settings (configured via the "Watch" button at the top of the page https://github.com/betaflight/betaflight-configurator set to "All Activity" rather than "Participating and @mentions"

**Pull request merged**
