### PR TITLE
Fix for failsafe feature.

### PR DESCRIPTION
**Pull request by mikeller**

### CODE REVIEW

**Comment by mikeller** [comment]
Fixes #152.

**Comment by skaman82** [comment]
@mikeller thanks, it works now but the layout got broken.
bildschirmfoto 2016-07-27 um 10 13 42

**Comment by skaman82** [comment]
@mikeller this is how it supposed to look like. Somehow the first switch is now in a table, it should be in a DIV construct instead. 
bildschirmfoto 2016-07-27 um 10 17 06

**Comment by mikeller** [comment]
@skaman82: Yes, the layout does not look quite right now, but the functionality is right again. The reason it's a table now is that the DOM elements are generated by the same code in `js/Feature.js` that is used to generate the features that are in the configuration and PID tuning tabs. We will have to look into making the layout look ok, the 'SUPEREXPO_RATES` feature in the PID tuning tab also doesn't look quite right yet.

**Pull request merged**
