### PR TITLE
Merge pull request messages.json in Korean

### PR DESCRIPTION
**Pull request by fixmania**
This is the file messages.json translated in Korean matching configurator 10.0.0.

And some .html and osd.js files in 'tabs' folder need i18n codes. 
(gps.html, landing.html, led_strip.html, osd.js, pid_tuning.html, firmware_flasher.html, receiver_msp.html)

If you find them and change i18n codes in English, I also could translate it next time.

### CODE REVIEW

**Comment by McGiverGim** [comment]
HI! We have created a webapp to help translate the configurator: http://betaflight.oneskyapp.com 

If you want, I can upload your korean file to this site and since then, the translations will be taken from there.

**Comment by fixmania** [comment]
Hi, there.

That's a good sound.

I want you upload my file on your app.

Already in Korea many people use only my file since configurator 3.1.1.

Thank you. ^^

2017. 12. 21. 오후 5:29에 "Míguel Ángel Mulero Martínez" <
notifications@github.com>님이 작성:

HI! We have created a webapp to help translate the configurator:
http://betaflight.oneskyapp.com

If you want, I can upload your korean file to this site and since then, the
translations will be taken from there.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/betaflight/betaflight-configurator/pull/811#issuecomment-353289322>,
or mute the thread

**Comment by fixmania** [comment]
@McGiverGim 

Hi, Mc

That's a good sound.
I want you upload my file on your app.

Already in Korea many people use only my file since configurator 3.1.1.

Thank you. ^^

**Comment by McGiverGim** [comment]
Uploaded, if you go there http://betaflight.oneskyapp.com, you will see your strings and some new strings that we have moved to the messages file in the new version and you can translate them.
We have a channel  #team_translation in the slack chat, if you need to say something ;)

**Comment by fixmania** [comment]
@McGiverGim Thank you. ;)

**Comment by mikeller** [comment]
@fixmania, @McGiverGim: What should be done with this now? I am happy to merge this pull request, but I think in the future, Korean translations should be maintained in OneSky, and the pull request for updated translations generated from there.
Thoughts?

**Comment by McGiverGim** [comment]
The translation has been uploaded, and some new strings were translated there. I prefer to use the file from OneSky (is more up to date). Maybe @fixmania can finish the translation (a few phrases are missing) and update this PR, or if he wants, close this PR and I will open a new one when the translation in OneSky is finished.

Another option is to merge this, and since then update it from OneSky only when the new version is coming.

**Comment by fixmania** [comment]
@mikeller @McGiverGim I am trying to translate remainings in OneSky expected 1~2 days more. I'll update this PR when I finish it. :-)

**Comment by fixmania** [comment]
@McGiverGim @mikeller I have done it finally in OneSky and verify by myself too. (I found that some phrases not matched with <class phrase... in my original file. -.- and revising all that.) 

Thank you for all. Please update it. :-)

**Comment by mikeller** [comment]
@fixmania: Thank you very much for your efforts. @McGiverGim and I can take this from here on, and create / merge a pull request from OneSky to update the remaining phrases.

**Comment by fixmania** [comment]
@mikeller I have not only translated remaining phrases but also modified existed phrases in OneSky application not here. So please download messages.json file from OneSky, and full change it all please. It means this attached file here is no more available.

Thank you. ^^

**Comment by mikeller** [comment]
@fixmania: No problem. The translations will be amended shortly when we merge the file generated from OneSky. I just merged this to show your big contribution to the Korean translation.

**Comment by fixmania** [comment]
@mikeller Oh my, maybe I love all. When I download .json file from OneSky, it shows 'unicode' format. I concerned how shows it on web page(included configurator google app.). When you upload the file on website, please check it shown readable. Thank you again so much. ^^ ;-)

**Comment by mikeller** [comment]
@fixmania: We can do a test build for you before the pull request, to make sure that this is working all right.

**Comment by McGiverGim** [comment]
I usually have an more or less updated version with latest translations here:
https://drive.google.com/drive/folders/1w-mtfc0xV-IN62YLVxJ0kOEaJ8u0wbSV?usp=sharing
It seems good for me, but I don't know nothing about korean ;)
You can test it if you want. It has been generated from the latest master and the latest file from OneSky.

**Comment by fixmania** [comment]
@McGiverGim I have tested the lastest version with the korean translation from sharing files. It seems perfect for me. Thanks a lot. ^^

**Comment by McGiverGim** [comment]
@fixmania I've added a comment to a translation into korean in OneSky. The question is about the "Betaflight Configurator" string. This string is the windows app title:
> Usually we prefer that this string is left in english, is the window title, and usually the program names are not translated (photoshop, microsoft windows, etc.) but we don't know anything about not latin  alphabets. Is correct/better to translate it to korean alphabet?

**Pull request merged**
