### PR TITLE
Changes to make translations more equal

### PR DESCRIPTION
**Pull request by HThuren**
Translations when testing motors are now more similar, but also another word for throttle due to limited space in ex. EdgeTx translations

### CODE REVIEW

**Comment by haslinghuis** [comment]
@HThuren we only provide English text as translation is done using crowdIn volunteers.

See https://github.com/betaflight/betaflight-configurator/issues/859

**Comment by HThuren** [comment]
Yes, I know that, I'm the Danish crowdin translator, this just to make it more easy to make local bransh's

**Comment by haslinghuis** [comment]
@McGiverGim is handling translations.

**Comment by HThuren** [comment]
Well, this just not to make him work too much, :-)

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Pull request closed without merging**
