### PR TITLE
Remove FPORT from automatically included telemetry list

### LINKED ISSUE #3796: FPort telemetry not working after cloud build
### Describe the bug

since #3726 the fport telemetry is no longer working 

As you can see, the entry for the telemetry protocol is missing in the cloud build -> [buildlog](https://build.betaflight.com/api/builds/78006759ad777eef8e55f2a2ddc32534/log)

After entering the telemetry protocol in the custom defines line it works again -> [buildlog](https://build.betaflight.com/api/builds/3de576f28d121f65183a9fa4ae399669/log)

There is no automatic setting of the telemetry protocol as it works with the ghost protocol.

@haslinghuis pls can you check this

### To Reproduce

see describe the bug

### Expected behavior

insert telemetry protocol for fport radio protocol in cloud build

### Configurator version

latest master

### Flight controller configuration

_No response_

### Add any other context about the problem that you think might be relevant here

_No response_

### PR DESCRIPTION
**Pull request by haslinghuis**
Fixes #3796

### CODE REVIEW

**Review by nerdCopter — APPROVED** [review]

**Comment by nerdCopter** [comment]
if @blckmn modifies the backend, i presume this will be added again

**Comment by blckmn** [comment]
Do we want it included by default?

**Comment by nerdCopter** [comment]
there was this comment https://github.com/betaflight/betaflight-configurator/issues/3796#issuecomment-1943742787

**Comment by haslinghuis** [comment]
@blckmn yes please. FPORT has telemetry included as it does not work without SMARTPORT.

This was done on web so cannot change much here.

**Pull request closed without merging**
