### PR TITLE
Remove event listener for flashing using Enter key.

### PR DESCRIPTION
**Pull request by haslinghuis**
When using autocomplete the background does not observe darkmode. Also on enter to accept the field it triggers firmware flashing.

This PR
- disables autocomplete for the custom define field
- removes the keypress for flashing

image

### CODE REVIEW

**Comment by nerdCopter** [comment]
Well, i have made use of the autocomplete on occasion.  However, the `Enter` key is certainly a problem.

**Review by HThuren — APPROVED** [review]
Yes, now no autocomplete and Enter are disabled here (and not in other fields)

**Comment by haslinghuis** [comment]
@nerdCopter - you can still paste in text

**Comment by nerdCopter** [comment]
> @nerdCopter - you can still paste in text

understood. but easier when i don't have to search the settings :laughing: . 
i think it is this css, if i'm not mistaken:
image

**Comment by haslinghuis** [comment]
Could not find a[n easy] way in a hour to override the user agent style

**Comment by HThuren** [comment]
> Could not find a[n easy] way in a hour to override the user agent style

I'm not sure what you want to solve?

**Comment by haslinghuis** [comment]
Trying to keep autocomplete - not messing with dark mode

**Comment by HThuren** [comment]
I have no experience here, but maybe change in js, ie. $('input').attr('autocomplete','on');

**Comment by nerdCopter** [comment]
> Trying to keep autocomplete - not messing with dark mode

if you make this PR only about the `enter` key, then i can approve.  then the less-important theming could be separate/later/

**Review by nerdCopter — APPROVED** [review]

**Pull request merged**
