### PR TITLE
Motor wizard fix

### PR DESCRIPTION
**Pull request by YarosMallorca**
Fixes https://github.com/betaflight/betaflight-configurator/pull/4158#issuecomment-2333984343

### CODE REVIEW

**Review by haslinghuis — APPROVED** [review]

**Comment by nerdCopter** [comment]
can you correct the **_hover-over_** colors in the Motor Direction --> "wizard" versus "individually"? (light mode, i did not check dark-mode).
in "wizard" hover-over is a light yellow, barely distinguishable, and in "individually" hover-over is an ugly rust color.

**Comment by YarosMallorca** [comment]
@nerdCopter I will look into this later, thanks for pointing it out.

**Comment by YarosMallorca** [comment]
@nerdCopter fixed the highlight color in 82509d1a7fd9d2aea92b0429599aa640d7f164f7

**Review by nerdCopter — APPROVED** [review]

**Comment by YarosMallorca** [comment]
I was looking at why the image isn't rendering, but I can't figure it out. Maybe @limonspb has an idea on this?

**Comment by haslinghuis** [comment]
yarn && yarn preview does show it - yarn && yarn dev not

**Comment by limonspb** [comment]
> yarn && yarn preview does show it - yarn && yarn dev not

Could it be similar problem as was fixed here?  
https://github.com/betaflight/betaflight-configurator/pull/4158
Maybe some folder is not being copied?

**Pull request merged**
