### PR TITLE
ci.yml - workflow_dispatch

### PR DESCRIPTION
**Pull request by nerdCopter**
* allow manual trigger of github workflow action `ci.yml`.
* allows fork-owners to easily build all OS versions via actions tab.
* useful for fork-owner testing prior to making PR's.

image

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Review by haslinghuis — APPROVED** [review]

**Comment by McGiverGim** [comment]
Is a little strange to add this to the ci.yml action. This is usually a subflow executed from the other actions. I need to look at it deeply, now I'm on mobile.

**Comment by nerdCopter** [comment]
> Is a little strange to add this to the ci.yml action. This is usually a subflow executed from the other actions. I need to look at it deeply, now I'm on mobile.

understood.  it will not interfere with current anyone's workflow/triggers.  it simply adds a manual option useful for contributors on there own fork.

**Comment by blckmn** [comment]
> > Is a little strange to add this to the ci.yml action. This is usually a subflow executed from the other actions. I need to look at it deeply, now I'm on mobile.
> 
> understood. it will not interfere with current anyone's workflow/triggers. it simply adds a manual option useful for contributors on their own fork.

Probably better to perhaps add a manual-release.yml and call ci.yml?

**Comment by McGiverGim** [comment]
> Probably better to perhaps add a manual-release.yml and call ci.yml?

Yes, that is what I was thinking of. Probably a `manual.yml` or `manual-build.yml` (without `release`, because we are not releasing the artifact). 
The `ci.yml` is like a function used by several flows, this PR is like adding a main to this function, what is not very elegant. Better to add a new `manual-build.yml` that calls the `ci.yml`, like we don in `nightly.yml` or in others.

**Pull request closed without merging**
