### PR TITLE
Fix errors about using i18next before its properly initial…

### PR DESCRIPTION
**Pull request by Docteh**
…ized

Updating to i18next 18.0.1
Goes from lots of complaints down to just one.
https://github.com/i18next/i18next/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by McGiverGim** [comment]
But maybe because it only shows one error to not repeat them or because it has been fixed? I don't understand why it appears only one, it has not much sense. Or they appear all or none.

**Comment by mikeller** [comment]
@McGiverGim: I guess the point of this change is that the maintainer of i18next heeds to the fact that loading translations asynchronously is not a problem in itself, and does not need fixing, as long as this does not break the user experience. So instead of flooding the log with messages pertaining to asynchronous loading, having one warning to show that this is happening is enough. Forcing synchronous loading will increase the loading time for the application, so unless this is needed to fix something that is broken for the user it should not be done.

**Comment by Docteh** [comment]
`languageChanged` was triggering in the middle of the initialization process. If we add the hook afterwards there is no complaints.

I think this is part of what is "completely obvious" to people who like javascript modules.

**Comment by McGiverGim** [comment]
> `languageChanged` was triggering in the middle of the initialization process. If we add the hook afterwards there is no complaints.
> 
> I think this is part of what is "completely obvious" to people who like javascript modules.

Ahhhh I forgot about this change. Good catch. This is the reason why in the older Configurator we didn't have this errors.

**Comment by mikeller** [comment]
@Docteh: Rejected, the title is incorrect. :stuck_out_tongue:

**Pull request merged**
