### PR TITLE
Do not wait on reinitialize connection for firmware flasher tab

### PR DESCRIPTION
**Pull request by haslinghuis**
This PR is part of #3758

BEFORE:

```
Porthandler detected device Betaflight STM32F7x2 on port: /dev/ttyACM0
serial_backend.js:109 Connecting to: /dev/ttyACM0
serial.js:123 serial: connection opened with ID: 1 , Baud: 115200
serial_backend.js:335 Requesting configuration data
MSPHelper.js:1599 Arming disable
MSPHelper.js:1602 Real time clock set
Clipboard.js:18 NW GUI Clipboard available
serial.js:253 serial: closed connection with ID: 1, Sent: 251 bytes, Received: 67303 bytes
port_handler.js:177 PortHandler - Removed: [{"path":"/dev/ttyACM0","displayName":"Betaflight STM32F7x2","vendorId":1155,"productId":22336}]
port_handler.js:218 PortHandler - Found: [{"path":"/dev/ttyACM0","displayName":"Betaflight STM32F7x2","vendorId":1155,"productId":22336}]
serial.js:123 serial: connection opened with ID: 2 , Baud: 115200
firmware_flasher.js:484 board changed to SPEEDYBEEF7V3
serial.js:253 serial: closed connection with ID: 2, Sent: 38 bytes, Received: 158 bytes
==> serial_backend.js:818 failed to get serial connection, gave up after 10 seconds
```

AFTER:

```
Porthandler detected device Betaflight STM32F7x2 on port: /dev/ttyACM0
serial_backend.js:109 Connecting to: /dev/ttyACM0
serial.js:123 serial: connection opened with ID: 1 , Baud: 115200
serial_backend.js:335 Requesting configuration data
MSPHelper.js:1599 Arming disable
MSPHelper.js:1602 Real time clock set
Clipboard.js:18 NW GUI Clipboard available
serial.js:253 serial: closed connection with ID: 1, Sent: 246 bytes, Received: 67298 bytes
==> serial_backend.js:807 Serial connection available after 0 seconds
port_handler.js:177 PortHandler - Removed: [{"path":"/dev/ttyACM0","displayName":"Betaflight STM32F7x2","vendorId":1155,"productId":22336}]
port_handler.js:218 PortHandler - Found: [{"path":"/dev/ttyACM0","displayName":"Betaflight STM32F7x2","vendorId":1155,"productId":22336}]
serial.js:123 serial: connection opened with ID: 2 , Baud: 115200
firmware_flasher.js:484 board changed to SPEEDYBEEF7V3
serial.js:253 serial: closed connection with ID: 2, Sent: 38 bytes, Received: 158 bytes
```

### CODE REVIEW

**Comment by nerdCopter** [comment]
for records
`./locales/en/messages.json:3616`
```
"firmwareFlasherNoValidPort": {
"message": "<span class=\"message-negative\">Please select valid serial port</span>"
},
```

**Review by nerdCopter — APPROVED** [review]
- approving, everything still works

**Comment by haslinghuis** [comment]
To reproduce

- connect
- go to cli tab
- go to flasher tab
- press auto-detect

**Comment by nerdCopter** [comment]
master (`2fc64651`)
```
2024-01-12 @13:18:59 -- OS: Linux
2024-01-12 @13:18:59 -- Configurator: 10.10.0-debug-2fc64651
2024-01-12 @13:19:03 -- Serial port successfully opened with ID: 1
2024-01-12 @13:19:03 -- MultiWii API version: 1.46.0
2024-01-12 @13:19:03 -- Flight controller info, identifier: BTFL, version: 4.5.0
2024-01-12 @13:19:03 -- Running firmware released on: Jan 12 2024 18:51:41
2024-01-12 @13:19:03 -- Board: FOXE/FOXEERF405(STM32F405), version: 0
2024-01-12 @13:19:03 -- Unique device ID: 0x42004f4e48500920303452
2024-01-12 @13:19:03 -- Build Key: 1fd592f0a0189d8c7543bc9051d75e52
2024-01-12 @13:19:03 -- Craft name: craft
2024-01-12 @13:19:03 -- Arming Disabled
2024-01-12 @13:19:10 -- CLI mode detected
2024-01-12 @13:19:12 -- Serial port successfully closed
2024-01-12 @13:19:12 -- Device - Rebooting
2024-01-12 @13:19:12 -- Using cached builds information for https://build.betaflight.com/api/configurator/sponsors/light/landing.
2024-01-12 @13:19:12 -- Using cached builds information for https://build.betaflight.com/api/targets.
2024-01-12 @13:19:12 -- Using cached builds information for https://build.betaflight.com/api/configurator/sponsors/light/flash.
2024-01-12 @13:19:12 -- Using cached builds information for https://build.betaflight.com/api/targets.
2024-01-12 @13:19:13 -- Query board information to preselect right firmware
2024-01-12 @13:19:13 -- Chrome API Error: Failed to connect to the port..
2024-01-12 @13:19:13 -- Failed to open serial port
2024-01-12 @13:19:13 -- Query board information to preselect right firmware
2024-01-12 @13:19:13 -- MultiWii API version: 1.46.0
2024-01-12 @13:19:13 -- Configurator has successfully detected and verified the board: FOXEERF405
```


`ebad52d5`
```
2024-01-12 @13:20:20 -- OS: Linux
2024-01-12 @13:20:20 -- Configurator: 10.10.0-debug-ebad52d5
2024-01-12 @13:20:45 -- Serial port successfully opened with ID: 1
2024-01-12 @13:20:45 -- MultiWii API version: 1.46.0
2024-01-12 @13:20:45 -- Flight controller info, identifier: BTFL, version: 4.5.0
2024-01-12 @13:20:45 -- Running firmware released on: Jan 12 2024 18:51:41
2024-01-12 @13:20:45 -- Board: FOXE/FOXEERF405(STM32F405), version: 0
2024-01-12 @13:20:45 -- Unique device ID: 0x42004f4e48500920303452
2024-01-12 @13:20:45 -- Build Key: 1fd592f0a0189d8c7543bc9051d75e52
2024-01-12 @13:20:45 -- Craft name: craft
2024-01-12 @13:20:45 -- Arming Disabled
2024-01-12 @13:20:49 -- CLI mode detected
2024-01-12 @13:20:51 -- Serial port successfully closed
2024-01-12 @13:20:51 -- Device - Rebooting
2024-01-12 @13:20:51 -- Using cached builds information for https://build.betaflight.com/api/configurator/sponsors/light/landing.
2024-01-12 @13:20:51 -- Device - Ready
2024-01-12 @13:20:51 -- Using cached builds information for https://build.betaflight.com/api/targets.
2024-01-12 @13:20:51 -- Using cached builds information for https://build.betaflight.com/api/configurator/sponsors/light/flash.
2024-01-12 @13:20:51 -- Using cached builds information for https://build.betaflight.com/api/targets.
2024-01-12 @13:20:52 -- Query board information to preselect right firmware
2024-01-12 @13:20:52 -- MultiWii API version: 1.46.0
2024-01-12 @13:20:53 -- Configurator has successfully detected and verified the board: FOXEERF405
```

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Pull request closed without merging**
