### PR TITLE
Show warning on connect when ACC is not calibrated.

### PR DESCRIPTION
**Pull request by mikeller**
Presents a warning to the user when connecting if ACC is enabled and not calibrated:

image

I think this is a better alternative to betaflight/betaflight#9458, as it points the user to the instructions for a correct calibration.

The list of warnings is built dynamically, so that other problems, like insufficient filtering, can be added and displayed as well.

### CODE REVIEW

**Comment by McGiverGim** [comment]
Maybe add a comment about the quad will not arm if enabled and not calibrated?

**Comment by mikeller** [comment]
image

**Comment by mikeller** [comment]
@McGiverGim: Is this ok now?

**Comment by mikeller** [comment]
Added a check to only report missing acc calibration if ACC is enabled.

Also, made the warning a bit more wordy:

image

**Comment by Asizon** [comment]
@mikeller I discovered a bug that occurs right after this commit and I am not able to fix it. From what I have been able to analyze I think the error is inside `serial_backend.js`. Here is the problem after press `Flash Firmware` buttton:
flashbug

**Comment by Asizon** [comment]
ok, i got it! https://github.com/betaflight/betaflight-configurator/pull/1915

**Pull request merged**
