### PR TITLE
Remove backup and restore

### PR DESCRIPTION
**Pull request by haslinghuis**
Let's remove backup and restore buttons now we have much better options.

EDIT: We leave the code in for virtual mode and legacy firmware.

Consider this a bugfix as it never really worked great.

https://www.youtube.com/watch?v=nkOrVXiqefc

### CODE REVIEW

**Review by blckmn — APPROVED** [review]

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by limonspb — DISMISSED** [review]

**Review by Asizon — CHANGES_REQUESTED** [review]
Why remove these functionalities now?? I think restore option is useful and used for Virtualmode conection.

**Comment by haslinghuis** [comment]
@Asizon we have this functionality in presets now.

**Comment by McGiverGim** [comment]
To load the virtual FC too?

**Comment by haslinghuis** [comment]
@McGiverGim loosing this would be a loss to virtual mode, but otherwise it's pretty useless. Not sure if presets covers virtual mode as it uses cli serial mode.

**Comment by limonspb** [comment]
> @McGiverGim loosing this would be a loss to virtual mode, but otherwise it's pretty useless. Not sure if presets covers virtual mode as it uses cli serial mode.

@Asizon  @McGiverGim 

presets -> load/save backup works through CLI so it does not work in virtual FC.

However, the buttons on Setup Tab are really misleading. They do not work properly and can mess up a regular user who uses real FC. If these buttons are useful only for Virtual mode - let them be in Virtual mode **only** or remove them to avoid any confusion.

**Comment by McGiverGim** [comment]
They work too to really backup/restore (not everybody uses CLI). But the code needs to be modified with each MSP version so it usually gets outdated until someone does the changes from time to time.

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by haslinghuis** [comment]
EDIT: We leave the code in for virtual mode only.

We can use the functionality using presets now and also use something like https://bf43-safe-migration.robertodedomenico.it/

**Comment by phorensic** [comment]
Coming from an end user for a year, I had no idea using the backup feature on the first screen wasn't backing up other things. I watched JB's video linked in the OP and I was shocked for a year I was never backing up the other way, lol. Sure enough I did a backup from the first screen, and then one from the new Presets screen. Then I understood the issue, then I see this PR and I agree. Maybe to put it another way besides how OP worded it, why is there two backup buttons in the program now? At least make the first one less ambiguous? As a newbie, I guess the backup in Presets is what I want, but the files are so different when I compare them I don't know what I actually want, really. Anyway, just providing feedback for you guys.

**Review by limonspb — APPROVED** [review]

**Review by ctzsnooze — APPROVED** [review]

**Review by blckmn — APPROVED** [review]

**Comment by Asizon** [comment]
@haslinghuis How could I now save a backup of my fc and load it in virtualfc mode? e tested with presets backup and it is completely impossible to load it.

**Comment by phorensic** [comment]
That doesn't work, yet. Crashes the program.

**Comment by Asizon** [comment]
@haslinghuis what about backup_restore.js?it is unused now but not removed?
https://github.com/betaflight/betaflight-configurator/blob/master/src/js/backup_restore.js

**Comment by Asizon** [comment]
Yes @phorensic because we doenst update msp comands here for a long time

**Comment by haslinghuis** [comment]
It's there for < 4.3 firmware. Now we can use preset (backup / restore).

Also like to propose removing virtual mode as it's unmaintained and would require a lot of work to fix.

**Comment by McGiverGim** [comment]
Virtual mode is a new feature and I think that is useful. It was asked by several users. We must look at it and try to let at least a minimal functionality. Or at least not crash.

**Comment by haslinghuis** [comment]
Ok, we should restore the Backup button and remove the Activate Boot Loader / DFU button for virtual mode.

Are you ok with replacing the backup/restore functionality with the presets backup/restore method for firmware 4.3?

**Pull request merged**
