### PR TITLE
Extended Bidir Dshot

### PR DESCRIPTION
**Pull request by haslinghuis**
Details: https://github.com/betaflight/betaflight/pull/11694

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by Asizon — APPROVED** [review]
Interesting @haslinghuis , wich is the purposse of extended dshot bidir? Provide more information?

**Comment by haslinghuis** [comment]
@Asizon for details see first comment.

**Comment by KarateBrot** [comment]
> Interesting haslinghuis , wich is the purposse of extended dshot bidir? Provide more information?

ESC telemetry without telemetry cable for BLHeli_S, BLHeli_32, Bluejay and all ESC firmwares who are going to support it.

**Review by blckmn — APPROVED** [review]

**Pull request merged**
