### PR TITLE
Fix Vite globals

### PR DESCRIPTION
**Pull request by haslinghuis**
References:
- https://vitejs.dev/config/
- https://eslint.org/docs/latest/use/configure/language-options#using-configuration-files-1

### CODE REVIEW

**Review by blckmn — APPROVED** [review]

**Comment by haslinghuis** [comment]
Before merging see this with `yarn && yarn dev` (also on master - and with Android fix in place don't see the error anymore)

```
Error: The following dependencies are imported but could not be resolved:

  nw.gui (imported by /home/mark/dev/pr/configurator/fix-vite-globals/betaflight-configurator/src/js/gui.js)

Are they installed?
    at file:///home/mark/dev/pr/configurator/fix-vite-globals/betaflight-configurator/node_modules/vite/dist/node/chunks/dep-063880ad.js:45768:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/mark/dev/pr/configurator/fix-vite-globals/betaflight-configurator/node_modules/vite/dist/node/chunks/dep-063880ad.js:45176:38
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by chmelevskij — CHANGES_REQUESTED** [review]
This doesn’t fix it. I’ve seen this with @limonspb recently. Will create pr with proper fix

**Comment by haslinghuis** [comment]
Closing in favor of https://github.com/betaflight/betaflight-configurator/pull/3716

**Pull request closed without merging**
