### PR TITLE
Fix select2 css in firmware flasher

### PR DESCRIPTION
**Pull request by haslinghuis**
Before:
image

After:
image

### CODE REVIEW

**Review by McGiverGim — APPROVED** [review]

**Review by ctzsnooze — APPROVED** [review]

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by Asizon** [comment]
Umm, i have fixed that some months ago @haslinghuis, not sure what happens here, please wait and no merge i need to test that

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by Asizon — CHANGES_REQUESTED** [review]
@haslinghuis after looking at this, seems not the correct fix. The general font size established for all the parameters of this tab is being eliminated, so the target name looks smaller than the others and does not share aesthetics. I can't reproduce the error since it's on windows and my resolution works perfectly.

**Comment by haslinghuis** [comment]
@Asizon CSS is only applied to Windows now. Did you test on OSX or Linux?

**Comment by Asizon** [comment]
@haslinghuis i just tried on windows, but i think is more screen resolution dependig?? Maybe we need to made sone autonatic height for the box?

**Comment by haslinghuis** [comment]
@Asizon screenshot please.

**Comment by benlumley** [comment]
screenshots of the build above  (is this what was being requested? i can screenshot some other version if needed)

mac:

bfupd-select2-macos

ubuntu:

bfupd-select2-ubuntu

windows:

bfupd-select2-windows

**Comment by haslinghuis** [comment]
@benlumley from here we can see Mac has the issue too. Can you please select a board and give the main window on linux / windows some more width?

**Comment by benlumley** [comment]
Recommend #2837 is considered instead of merging this branch.

**Comment by haslinghuis** [comment]
Closing in favour of #2875

**Pull request closed without merging**
