### PR TITLE
Added bind button for receivers that support it.

### PR DESCRIPTION
**Pull request by mikeller**
To go with betaflight/betaflight#9437.

image

### CODE REVIEW

**Comment by Asizon** [comment]
I tried this and it works perfect, it is a great improvement. Only 2 points, when I press the bind button graphically it does nothing, I don't know if it is working or not, could a Binding message be launched ... here?
bindinfo
on the other hand, I don't know if it's normal or not, but the `Control Sticksl` button appears for 1 second
controlsticksrefresh

**Comment by mikeller** [comment]
@Asizon:

> I tried this and it works perfect, it is a great improvement. Only 2 points, when I press the bind button graphically it does nothing, I don't know if it is working or not, could a Binding message be launched ... here?

Yes, that is correct. The thing is that none of the protocols supporting bind through the firmware is currently set up to support feedback, and at least one of them (SRXL2) does not have any (publicly documented) facility to provide feedback, so for now giving feedback is probably going to be more confusing due to inconsistency than helpful.

> In the other hand, I don't know if it's normal or not, but the 'Control Sticks' button appears for 1 second:

Yes, this is just the slowness of the V8 engine in processing the initialisation - we'd get the same if we disabled it initially in cases where it needs to be shown.

**Comment by McGiverGim** [comment]
> Yes, that is correct. The thing is that none of the protocols supporting bind through the firmware is currently set up to support feedback, and at least one of them (SRXL2) does not have any (publicly documented) facility to provide feedback, so for now giving feedback is probably going to be more confusing due to inconsistency than helpful.

Maybe we can simply add a message of `Starting binding...` or something similar in the log panel. I suppose that the problem is that we press the button and we don't receive any confirmation of that. In this way at least we know that the binding has been asked to the FC.

**Comment by mikeller** [comment]
Ok, added a message to the log:

image

**Comment by RipperDrone** [comment]
This is a great addition to BF functionality and getting more and more less experienced users on board :-)

**Pull request merged**
