### PR TITLE
Fix tooltip

### PR DESCRIPTION
**Pull request by haslinghuis**
Fixes: #3162 
Fixes: #3169

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by McGiverGim — APPROVED** [review]
We are giving too much work to the translators ;) this changes are more for a beta version than for a RC :P

**Comment by haslinghuis** [comment]
Yes agree - Crowdin should be smart here (as we are just removing a sentence from already translated message).

Also need to address https://github.com/betaflight/betaflight-configurator/issues/3162

**Comment by McGiverGim** [comment]
> Yes agree - Crowdin should be smart here (as we are just removing a sentence from already translated message)

Yes, it is, but needs the proofreader intervention. It will invalidate the older translations, and suggest the new, but the proofreader needs to enter and approve it.

**Comment by haslinghuis** [comment]
Really need help with the `WIKI` button as it does not work like other tabs (while using main.less css)

**Review by sugaarK — APPROVED** [review]

**Pull request merged**
