### PR TITLE
Fix missing PID filter slider labels

### PR DESCRIPTION
**Pull request by haslinghuis**
image

### CODE REVIEW

**Review by nerdCopter — APPROVED** [review]

**Comment by HThuren** [comment]
Only issue are the on/off control slider above the troggle, do we move the slider below the toggle ?

**Comment by haslinghuis** [comment]
This is not a re-design - just adding missing labels.

**Review by HThuren — APPROVED** [review]

**Comment by TheIsotopes** [comment]
this is only working on dark theme ... pls can you fix this @haslinghuis 

Screenshot 2024-02-23 094552

**Comment by TheIsotopes** [comment]
@haslinghuis checked and working 👍

**Pull request merged**
