### PR TITLE
Made display of arming disabled reasons match number of beeps.

### PR DESCRIPTION
**Pull request by mikeller**

### CODE REVIEW

**Comment by DanNixon** [comment]
I'd left this internationally zero indexed to match the documentation on the wiki page.

**Comment by mikeller** [comment]
I see. I didn't even know about the list in the wiki until now.

It's probably going to lead to less confusion if the values are the same in all user facing places, so my suggestion would be to change the wiki to list the number of beeps.

Also, we should add the link to the wiki page to the tooltip.

Thoughts?

**Comment by DanNixon** [comment]
> It's probably going to lead to less confusion if the values are the same in all user facing places, so my suggestion would be to change the wiki to list the number of beeps.

Yes, that would be the better option.

Given that it is in the configurator now the manual lookup method should be removed from those pages, as no one should ever have to do that.

> Also, we should add the link to the wiki page to the tooltip.

Assuming links work from tooltips then yes, for me the tooltip always disappears when the control loses focus so I assumed any link would not be clickable.

**Comment by mikeller** [comment]
I've amended the Wiki page.

> Given that it is in the configurator now the manual lookup method should be removed from those pages, as no one should ever have to do that.

It might still be useful for users if they want to decode the hex returned by minimal CLI.

> Assuming links work from tooltips then yes, for me the tooltip always disappears when the control loses focus so I assumed any link would not be clickable.

Indeed they don't work (I'd never tried before). I've added a reference to the page name at least, to make finding it a bit easier.

**Pull request merged**
