### PR TITLE
Bump API_VERSION_ACCEPTED and semver cleanup

### PR DESCRIPTION
**Pull request by haslinghuis**
As discussed on Slack this PR removes support for firmware before version 4.0

We bump `API_VERSION_ACCEPTED` to `API_VERSION_1_41` (BF 4.0)

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by KarateBrot — APPROVED** [review]

**Review by blckmn — APPROVED** [review]

**Comment by sugaarK** [comment]
> I see the backup/restore buttons have disappear. How we can load values for the virtual FC now?

Use the load backup button on the preset tab same for saving

**Comment by McGiverGim** [comment]
Thanks! I didn't know it works for virtual FC.

**Comment by haslinghuis** [comment]
presets is using cli under the hood with it's own fancy cliEngine class.

Have made a follow up patch to address virtual restore.

**Pull request merged**
