### PR TITLE
Fix OSD

### PR DESCRIPTION
**Pull request by haslinghuis**
Adds versioning to changes made in https://github.com/betaflight/betaflight-configurator/pull/2974

### CODE REVIEW

**Comment by ZzyzxTek** [comment]
A quick initial test shows that the OSD display is not scrambled as I reported on discord channel. I will run through the different combinations I tried earlier tomorrow.

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by McGiverGim — APPROVED** [review]

**Comment by ZzyzxTek** [comment]
> A quick initial test shows that the OSD display is not scrambled as I reported on discord channel. I will run through the different combinations I tried earlier tomorrow.

OK, I went and recreated the same tests I posted yesterday above.
These are all with BF build 2781 + Windows Configurator from this PR 3035.
1. With only the default OSD elements, Configurator shows just the warnings element, and my actual OSD matches that (there wasn't a warning when I snapshotted the OSD, but it's there).
2. I added crosshairs, cell voltage, mAh drawn, compass bar, craft name in Configurator, my actual OSD matches that.
3. I recreated my giant GPS Rescue testing OSD with a bunch of elements, my actual OSD matches that exactly.
4. Restored my diff from BF 2765, which is the same OSD as 3 above, both Configurator and my actual OSD match what it was when running 2765.
I also checked the cli osd_xxx_pos settings at each test, and they matched what I was seeing.
So, as far as I can tell, everything is working correctly with 2781 + this PR 3035, yay!

**Review by howels — APPROVED** [review]

**Review by ctzsnooze — APPROVED** [review]

**Comment by ctzsnooze** [comment]
Thank you Mark.  This fixes the problem I had.  Well done!

**Review by Asizon — APPROVED** [review]

**Pull request merged**
