### PR TITLE
Added checking for latest configurator release and update notification.

### PR DESCRIPTION
**Pull request by mikeller**

### CODE REVIEW

**Comment by basdelfos** [comment]
Nice. How can I test this, is there a 'fake'  release to test this feature?

**Comment by mikeller** [comment]
@basdelfos: Just manually adjust the version in `manifest.json` (if using through chrome) or `package.json` (before building) to something old, then run.

**Comment by basdelfos** [comment]
Doh! Remember to self; do not write comments before my first coffee :(

**Comment by basdelfos** [comment]
I don't seem to get the update notification on the standalone app.
Changed in `package.json` the version to `"version": "9.0.0"`.

image

Am I missing something (do I need another coffee)?

**Comment by basdelfos** [comment]
Same with the chrome app, don't see the update notification
Changed in `manifest.json` the version to `"version": "9.0.0"` and `"version_name": "9.0.0-rc3"`.

**Comment by mikeller** [comment]
@basdelfos: Did you enable 'Show unstable configurator releases' in the options drop down? `9.0.0` is still greater than the latest stable release (`3.2.2`).

**Comment by basdelfos** [comment]
Yep, it's working.

image

Minor thing; for cosmetics and consistency throughout the app, I would add an 'OK' or 'Close' button to close the window.

**Comment by mikeller** [comment]
@basdelfos: Can you point out where we are using ok and close buttons on modal dialogues? I tried to find one, but all I could find was the use of `GUI.show_modal` which looks like this.

**Comment by basdelfos** [comment]
Here you are:

image

image

And some with 2 buttons:

image

image

But then, Font manager window is also not constant with the rest of the windows:

image

**Comment by mikeller** [comment]
Good stuff, will track down the sources of these and convert the two uses of the 'other' design that I know of. Will merge this for now, and do the UI consolidation in a separate ticket.

**Pull request merged**
