### PR TITLE
Style: UI Refresh

### PR DESCRIPTION
**Pull request by VitroidFPV**
This PR aims to: 
* Remove all of the old layout styles using outdated techniques in favor of flex- or grid-based layouts
* Remove hard-set size values where applicable
* And most noticeably, to refresh the old style for a more modern look, very close to the current website

Screenshots below:
image
image
Or use preview deploy in the comments.

Opening the PR with the Setup tab being converted to the new layout and different breakpoints for desktop, tablet and mobile as I work on the rest. More tabs will be converted and old styles will be removed/updated going forward.

Please leave lots of constructive feedback! This is a big change, but it was discussed a lot internally prior to the PR - we belive this is a good way forward

### CODE REVIEW

**Comment by McGiverGim** [comment]
Tested the mobile layout, and fixes the issue with the size. Thanks!
For the rest, it contains a lot of errors, I suppose that you don't want a review because it's a draft, or do you want some comments about the "Setup tab"?

**Comment by VitroidFPV** [comment]
@McGiverGim please comment as you wish 😅. For now, the Setup tab is the only one I tested across all sizes, the others not yet. I should have a couple done today, so I'll push them up

**Comment by nerdCopter** [comment]
save/reboot/etc is always left-aligned.

**Comment by McGiverGim** [comment]
Ok, some comments, about light that is what I use:
1. The combos in the header have some strange outlines, maybe the Vue components styles hardcoded conflicts?
image
2. The black text over gray looks strange, in the header. In the contents it seems more or less ok to me. I don't know exactly why. 
image
3. This seems disaligned to my eyes. I know is aligned with the top of the header, but maybe we can give some padding/margin on the top to the elements that don't have header to align with the body.
image
4. Similar here:
image
5. A little here too:
image
6. The letters of the buttons when hovering seem blur:
image
7. The ? that shows the tooltip when hovering, are not visible when the tooltip is open. I don't know if it's intended.

For the rest and incredible job. Maybe some color adjusting, but it's great. When it's more polished/finished I can give it another look.

**Comment by VitroidFPV** [comment]
@McGiverGim I was mostly working in dark mode, I'll fix the contrast issues, that does look pretty bad! As for the layout, for now, I wanted to make the big changes first and address the smaller alignments afterward when I can be sure it won't break some other thing

**Comment by McGiverGim** [comment]
I understand. It's s lot of work. Thanks for moving into this!

**Comment by McGiverGim** [comment]
One thing: please, don't forget the Radio Emulator for MSP. It's usually forgotten and now the style is broken in this PR.
You can see it if you select "MSP" as your radio protocol at the TX tab, and then a new button will appear at the bottom of the TX tab.

**Comment by McGiverGim** [comment]
There are some little glitches, for example in the servos tab the latest row has no outline:
image

But for the rest is usable, so I think we can merge it and fix this little things with more PRs, where we can collaborate.

**Review by McGiverGim — APPROVED** [review]

**Review by haslinghuis — APPROVED** [review]

**Comment by VitroidFPV** [comment]
I agree, I'll merge this while there are no other conflicts

**Pull request merged**
