### PR TITLE
Altered checkbox/radio accent color & size

### PR DESCRIPTION
**Pull request by YarosMallorca**
I made the checkboxes a bit bigger in some places & changed the colors of checkboxes and radio buttons to `primary-400`.

Screenshot 2024-10-01 at 20 34 20

Screenshot 2024-10-01 at 20 34 27

Screenshot 2024-10-01 at 20 35 43

### CODE REVIEW

**Comment by haslinghuis** [comment]
image

**Comment by haslinghuis** [comment]
image

**Review by nerdCopter — APPROVED** [review]

**Review by haslinghuis — APPROVED** [review]

**Comment by nerdCopter** [comment]
@YarosMallorca , want to solve this comment as well? https://github.com/betaflight/betaflight-configurator/pull/4158#issuecomment-2333984343

**Comment by YarosMallorca** [comment]
I will look into this!

**Pull request merged**
