### PR TITLE
Added trigger file for SonarCloud analysis.

### PR DESCRIPTION
**Pull request by mikeller**

### CODE REVIEW

**Comment by McGiverGim** [comment]
The SonarCloud plugin seems smart enough to only analyse source files:
image

But I think we need to get rid of the `libraries` folder, we have enough issues only with our own code :)

I'm not too sure, but I think that adding this will be enough:
```
sonar.exclusions=libraries/*
```
Another solution is to add:
```
sonar.sources=src,test
```
but with this we lost the gulpfile, changelog and other future files in the root path.

**Comment by Docteh** [comment]
I think excluding libraries is fine, the 7 security hotspots are worth running down. ...

So its just sonarcloud advocating care in regards to regular expressions.
3 in q.js, 1 in semver, 3 in switchery

I wonder if they've thought about writing a regular expression to detect badly written regular expressions....

**Comment by McGiverGim** [comment]
We can write our own rules, but I think is too much for what we want 😋

**Comment by mikeller** [comment]
@McGiverGim, @Docteh: Seeing that SonarCloud's analysis has been triggered on this branch based on the added file, I think the right approach is to establish an initial configuration on this branch, before it is merged - after the merge there will be a lot more 'noise' if every branch triggers false positives due to the configuration being incomplete.

Re scanning the libraries, I think we should be doing this, so that we get alerted if a pull request is introducing a new library that has risk. What we should look into is to either mitigate the risks in the libraries we have, or add specific exemptions if they are false positives.

In general, we should try to not add new libraries into the repository, and rather move the existing libraries from the repository into ones installed from npm - GitHub has a good system that is periodically scanning dependencies of projects, and alerting owners if any new vulnerabilities / risks surface.

**Comment by McGiverGim** [comment]
I don't think that this is the correct approach. Sonar is only for our code quality, not to detect problems in external libraries. Nobody will look into them, and nobody will try to fix them. It will complain about problems, but it will not tell how bad they are or if they are new versions or alternatives.

**Comment by mikeller** [comment]
@McGiverGim: I disagree there - SonarCloud reports on the _delta_ in code quality that every pull request brings (see https://github.com/betaflight/betaflight-configurator/pull/1792/checks?check_run_id=285725512 for an example).
Just as well as we don't want bad code to be dragged into `src/`, we don't want it dragged into `libraries/` - or rather we don't want any new code to be dragged into `libraries/` if it can be avoided. If we exclude `libraries/` we just make it harder to find and address problems with our in-repository libraries.

**Comment by mikeller** [comment]
@McGiverGim: See #1795 for a positive side-effect of getting visibility of bad in-repository library code.

**Pull request merged**
