### PR TITLE
Updated all dependencies and fixed resulting problem.

### PR DESCRIPTION
**Pull request by mikeller**

### CODE REVIEW

**Comment by TheIsotopes** [comment]
@McGiverGim not really 

tested this with latest master on windows 10

- on setup tab the model can only be seen as a rectangle
- after connect no tabs can be changed

@mikeller pls can you check this

**Comment by mikeller** [comment]
@TheIsotopes: Not sure what version of the source you are using, I cannot find 7116f2e7. But this branch is working fine in Windows:

image

**Comment by TheIsotopes** [comment]
@mikeller latest master + this pr -> 7116f2e7

**Comment by mikeller** [comment]
@TheIsotopes: Would you mind testing with just this branch: `git checkout 4672666226b48dc8996a66f67e18c94f0a6738fe`

**Comment by TheIsotopes** [comment]
@mikeller that does not work
```
git checkout 4672666226b48dc8996a66f67e18c94f0a6738fe
fatal: reference is not a tree: 4672666226b48dc8996a66f67e18c94f0a6738fe
```

**Comment by etracer65** [comment]
I tested this but unfortunately it doesn't fix the firmware flashing problem on MacOS. Still get the same behavior as https://github.com/betaflight/betaflight-configurator/issues/1892.

Tested on MacOS 10.13.6 (High Sierra).

**Comment by etracer65** [comment]
It looks like this may be a case of a non-error result code being interpreted as an error. When I comment out the check that leads to the failure then flashing works normally. For example in `src/js/protocols/stm32usbdfu.js`:

```
    chrome.usb.claimInterface(this.handle, interfaceNumber, function claimed() {
//        if(self.checkChromeError()) {
//            console.log('Failed to claim USB device!');
//            self.cleanup();
//        }

        console.log('Claimed interface: ' + interfaceNumber);
```

**Comment by etracer65** [comment]
Also not sure if this is related, but I see this warning in the console when the app opens.

```
DevTools failed to parse SourceMap: chrome-extension://ajdoecjhplhoahggfmgflfnlechcljoc/node_modules/jquery-textcomplete/dist/dist/jquery.textcomplete.min.map
```

**Comment by TheIsotopes** [comment]
i'm also have the same warning in the console like @etracer65 

working bfc from latest master
latest_master

not working bfc from latest master incl. this pr
latest_master+pr

**Comment by mikeller** [comment]
@TheIsotopes: Try this then:

```
git checkout -b mikeller-update_libraries master
git pull https://github.com/mikeller/betaflight-configurator.git update_libraries
```

(Fact is, the branch is working for me on Windows 10, and it's directly off `master`, so I cannot see how something could break it unless it's the merge going wrong.)

@etracer65:

> It looks like this may be a case of a non-error result code being interpreted as an error. When I comment out the check that leads to the failure then flashing works normally. For example in src/js/protocols/stm32usbdfu.js:

Looks like this is a MacOS - only problem, as I can go in and out of DFU mode on linux and Windows. Can I get you to try and get to the bottom of this? I do not have access to a Mac for debugging.

> Also not sure if this is related, but I see this warning in the console when the app opens.

No, most likely not - looks like a pathing issue in one of the dependencies:

`.../dist/dist/...`

Source map files are only used in the debug console, so this will not be affecting production builds of the software.

**Comment by TheIsotopes** [comment]
> Try this then:
> 
> ```
> git checkout -b mikeller-update_libraries master
> git pull https://github.com/mikeller/betaflight-configurator.git update_libraries
> ```
> 
> (Fact is, the branch is working for me on Windows 10, and it's directly off master, so I cannot see how something could break it unless it's the merge going wrong.)
> 

@mikeller nope, this does not solve the problem either

**Comment by mikeller** [comment]
@TheIsotopes: I start to suspect that the GPU drivers in your installation are the problem. Can you test with this installer please:

https://drive.google.com/open?id=1c1Tl0X1uDf3iCCjL6E2XL-HekUhNO9Cj

I confirmed that this is working fine on my local Windows 10 installation.

**Comment by TheIsotopes** [comment]
@mikeller tested now with the installer version ... but the same problem :((

**Comment by mikeller** [comment]
@TheIsotopes: Not sure if command line options for NW.js are actually working in Windows, but can you try starting it from the command line with `--disable-gpu `?

**Comment by TheIsotopes** [comment]
yyyeeessssss, with `--disable-gpu` working all perfect now 👍

**Comment by mikeller** [comment]
@TheIsotopes:

>  yyyeeessssss, with --disable-gpu working all perfect now ￼

That's good to hear - the bad news is that your GPU / graphics adapter drivers are potentially screwed, and might need a reinstall.

**Comment by TheIsotopes** [comment]
@mikeller I won't find any new drivers, the latest drivers are already installed.

the computer is definitely over twelve years old.

**Comment by mikeller** [comment]
@TheIsotopes:

> the computer is definitely over twelve years old.

:thinking: I can see how this could be a problem when trying to run the version of WebGL. :rofl:

**Pull request merged**
