### PR TITLE
Rate limits added ref. betaflight PR #6402

### PR DESCRIPTION
**Pull request by ianrmurphy**
As a counterpart to [https://github.com/betaflight/betaflight/pull/6402](https://github.com/betaflight/betaflight/pull/6402) I have updated the configurator to show the effect of the new CLI parameters in the PID Tuning tab.

I have not yet targeted a specific `CONFIG.apiVersion`, would appreciate some guidance here.

### CODE REVIEW

**Comment by McGiverGim** [comment]
The firmware PR has not defined the version, but supposing 4.0, the most probably MSP version will be 1.41

**Comment by mikeller** [comment]
It will only be possible to add this in the first release after 4.0, since 4.0 will not have MSP support for the rate limits.

**Comment by ianrmurphy** [comment]
OK understood, please advise how best to add this feature to the proposed future MSP version.

**Comment by mikeller** [comment]
We'll just have to hold off with this pull request until the MSP for the rate limits has been added.

**Comment by mikeller** [comment]
@ianrmurphy: From the look of it this is pretty much superseded by #1368. Which one of the two should be taken?

**Comment by ianrmurphy** [comment]
Yes this is superceded by https://github.com/betaflight/betaflight-configurator/pull/1368. Closed.

**Pull request closed without merging**
