### PR TITLE
Updated NW.js to 0.54.0.

### PR DESCRIPTION
**Pull request by mikeller**
To go with https://github.com/betaflight/blackbox-log-viewer/pull/518.

### CODE REVIEW

**Comment by Asizon** [comment]
@mikeller tested here on Windows10 but some weird is happens with report dialog size:

image

**Comment by Asizon** [comment]
Maybe we just need a small css fix on dialog "height" value to "fit-content"??not sure how this chrome update is afecting to other things.

**Comment by Asizon** [comment]
I think I got the cause, there are new style changes aplied to this dialog ID with the "user agent stylesheet"

image

**Comment by blckmn** [comment]
AUTOMERGE: (fail)
 - Github identifies PR as mergeable -> pass
 - PR is not in draft -> pass
 - Assigned to a milestone -> fail
 - cooling off period lapsed (9/06/2021 19:13:58) -> pass
 - commit count less or equal to three (1 commits) -> pass
 - 'Do not merge' label NOT found -> pass
 - 'Needs coordination with betaflight' label NOT found -> pass
 - At least one 'RN:' label found -> fail
 - 'Tested' label found -> fail
 - assigned to an approver (None) -> fail
 - approver count at least three (0 approvers) -> fail

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - Github identifies PR as mergeable -> pass
 - PR is not in draft -> pass
 - Assigned to a milestone -> fail
 - cooling off period lapsed (10/06/2021 00:44:55) -> pass
 - commit count less or equal to three (1 commits) -> pass
 - 'Do not merge' label NOT found -> pass
 - 'Needs coordination with betaflight' label NOT found -> pass
 - At least one 'RN:' label found -> fail
 - 'Tested' label found -> fail
 - assigned to an approver (None) -> fail
 - approver count at least three (0 approvers) -> fail

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - Github identifies PR as mergeable -> pass
 - PR is not in draft -> pass
 - Assigned to a milestone -> fail
 - cooling off period lapsed (10/06/2021 00:48:10) -> pass
 - commit count less or equal to three (1 commits) -> pass
 - 'Do not merge' label NOT found -> pass
 - 'Needs coordination with betaflight' label NOT found -> pass
 - At least one 'RN:' label found -> fail
 - 'Tested' label found -> fail
 - assigned to an approver (None) -> fail
 - approver count at least three (0 approvers) -> fail

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - Github identifies PR as mergeable -> pass
 - PR is not in draft -> pass
 - Assigned to a milestone -> fail
 - cooling off period lapsed (10/06/2021 00:50:33) -> pass
 - commit count less or equal to three (1 commits) -> pass
 - 'Do not merge' label NOT found -> pass
 - 'Needs coordination with betaflight' label NOT found -> pass
 - At least one 'RN:' label found -> fail
 - 'Tested' label found -> fail
 - assigned to an approver (None) -> fail
 - approver count at least three (0 approvers) -> fail

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - Github identifies PR as mergeable -> PASS
 - PR is not in draft -> PASS
 - Assigned to a milestone -> FAIL
 - cooling off period lapsed (10/06/2021 00:52:00) -> PASS
 - commit count less or equal to three (1 commits) -> PASS
 - 'Don't merge' label NOT found -> PASS
 - 'Needs coordination with betaflight' label NOT found -> PASS
 - At least one 'RN:' label found -> FAIL
 - 'Tested' label found -> FAIL
 - assigned to an approver (None) -> FAIL
 - approver count at least three (0 approvers) -> FAIL

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - Github identifies PR as mergeable -> FAIL
 - Assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - 'Don't merge' label NOT found -> PASS
 - At least one 'RN:' label found -> PASS
 - 'Tested' label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Comment by haslinghuis** [comment]
@Asizon how do you prefer to fix this? Already suggested two ways, as you showed another fix? Want to create a PR to fix this issue so this PR can go forward.

**Comment by Asizon** [comment]
I have share this issue with @McGiverGim lets see what is happens here.

**Comment by McGiverGim** [comment]
I prefer to fix it here, in the PR, but if mikeller can't do it now and you have a PR ready with the fix, I don't see a problem to merge this.

**Review by Asizon — APPROVED** [review]
Ok so LGTM, @haslinghuis then lets aply height: fit-content in the .dialog class in next PR

**Review by haslinghuis — APPROVED** [review]

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - Github identifies PR as mergeable -> FAIL
 - Assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - 'Don't merge' label NOT found -> PASS
 - At least one 'RN:' label found -> PASS
 - 'Tested' label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by McGiverGim — APPROVED** [review]

**Comment by blckmn** [comment]
AUTOMERGE: (PASS)
 - Github identifies PR as mergeable -> PASS
 - Assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - 'Don't merge' label NOT found -> PASS
 - At least one 'RN:' label found -> PASS
 - 'Tested' label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> PASS

**Pull request merged**
