### PR TITLE
Improved messaging if build request fails

### PR DESCRIPTION
**Pull request by blckmn**
To test, you can introduce an invalid char into the custom defines.

e.g. `TEST$ERROR` in custom defines.

### CODE REVIEW

**Comment by haslinghuis** [comment]
See lot of redefines in failed builds

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by haslinghuis — APPROVED** [review]

**Comment by nerdCopter** [comment]
Untitled

**Comment by haslinghuis** [comment]
image

Think we should add a link for the log

**Comment by nerdCopter** [comment]
i see, i missed the `$`. so this only reports failed builds, does not necessarily catch bad defines.

**Review by nerdCopter — APPROVED** [review]

**Comment by blckmn** [comment]
> log

There is no log at this point. It's the case where the build request itself is rejected, eg custom define formatting (invalid chars etc).

**Pull request merged**
