### PR TITLE
Fixed missing 'nw' devDependency.

### LINKED ISSUE #774: Building with the new node.js system
I've tried to execute it under windows, installed the latest version of `node.js`, execute a `npm install`without error, but after that, when executing the `npm start` I get an error, this is part of:
```
19 verbose node v9.2.0
20 verbose npm  v4.5.0
21 error code ELIFECYCLE
22 error errno 1
23 error betaflight-configurator@10.0.0-rc4 start: `node_modules/gulp/bin/gulp.js dist && node_modules/nw/bin/nw .`
23 error Exit status 1
24 error Failed at the betaflight-configurator@10.0.0-rc4 start script 'node_modules/gulp/bin/gulp.js dist && node_modules/nw/bin/nw .'.
```
Finally I've reach it to work doing two things:
- Executing this command `npm install nw` after `npm install` (it seems a dependency is missing somewhere?)
- Change this line in the package.json:
https://github.com/betaflight/betaflight-configurator/blob/040757b74e0c626f92eb929ce1f49b204f54dd74/package.json#L8
For this other:
```
"start": "node node_modules/gulp/bin/gulp.js dist && node node_modules/nw/bin/nw .",
```
I don't know if this is a problem of my system or not. Some idea?

### PR DESCRIPTION
**Pull request by mikeller**
Fixes #774.

### CODE REVIEW

**Comment by McGiverGim** [comment]
I don't know if this is needed. With the new execution system (with `gulp`) this dependency is not needed any more. And if I want to execute with the old way (`nw start`) at least in my system I needed to modify the script indicating the `node` command in the `start` parameter, as I said in the issue.

Maybe in other systems, like linux or mac, is not needed this second modification?

**Comment by mikeller** [comment]
@McGiverGim: It's possible that `npm start` never properly worked on windows - I never tested that. If that is the case it should be fixed in a separate pull request. This pull request just fixes what I broke earlier by removing too many dependencies, and restores the old functionality.

If `npm start` is not needed any more, then the broken code should be removed from `package.json`. Just leaving it broken is definitely *not* the way to go.

Thoughts?

**Comment by mikeller** [comment]
Try now. ;-)

**Comment by McGiverGim** [comment]
Yes! That solves the problem too, and works in windows without problem :)

**Comment by basdelfos** [comment]
OK, `npm start` does work again with this fix.
Only thing is there are now 2 ways to build & run a debug version, which eventually do the same.

**Pull request merged**
