### PR TITLE
Fix the landing page - again. And fix the tabs broken in the last fix.

### LINKED ISSUE #1961: broken configurator tabs
@mikeller  since #1956 a few tabs are no longer displayed correctly

I found this on the following tabs receiver, motors and blackbox

receiver_tab

motors_tab

blackbox_tab

### PR DESCRIPTION
**Pull request by mikeller**
Fixes #1961.

Thanks for @TheIsotopes for pointing this out in https://github.com/betaflight/betaflight-configurator/issues/1961#issue-598440703

image

### CODE REVIEW

**Comment by TheIsotopes** [comment]
yeah, looks neat again. 👍

**Comment by 0crap** [comment]
@mikeller Can this please be merged? All new configurator-nightlies are useless without this. :-(

**Comment by McGiverGim** [comment]
Now it conflicts because the message has changed here: https://github.com/betaflight/betaflight-configurator/pull/1973 the latest link has been modified.

**Comment by 0crap** [comment]
Thx!

**Pull request merged**
