### PR TITLE
Defer URL check

### PR DESCRIPTION
**Pull request by haslinghuis**
- Skip URL check before requesting information
- Create button for board information [thinking about moving to a better place - after selecting target - before build]

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by nerdCopter — APPROVED** [review]
* approving for when ready

**Comment by ctzsnooze** [comment]
I think that the new home for Wiki files, on betaflight.com, needs to be Support/Wiki, not Support/Archive.
Let's confirm that before this one.

**Review by chmelevskij — APPROVED** [review]

**Comment by nerdCopter** [comment]
> [...] Support/Wiki, not Support/Archive [...]

agree, imho.

**Pull request merged**
