### PR TITLE
chore: add debug config for vscode

### PR DESCRIPTION
**Pull request by chmelevskij**
Adds `launch.json` to repo with debug config for nwjs. Steps to get working:
1. launch app from terminal with `yarn start`
2. from debug menu launch `Attach to betaflight`
Screenshot 2023-12-20 at 18 36 01
3. Set breakpoints, you might need to restart the application with debug menu, my suspicion is that it's due to the fact that we load in tabs with `import` 
Screenshot 2023-12-20 at 18 38 29

### CODE REVIEW

**Comment by nerdCopter** [comment]
i don't use vscode, will leave to others for testing/approving unless specifically asked to approve.

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by haslinghuis** [comment]
:thinking: Need to open some ports

image

**Comment by haslinghuis** [comment]
Looking good here

image

**Review by haslinghuis — APPROVED** [review]

**Review by nerdCopter — APPROVED** [review]

**Pull request merged**
