### PR TITLE
Fix webview problem in the Android version.

### LINKED ISSUE #2581: Android application not loading on older devices
Reproduction:
- start the android app.

Expected behaviour:
- the loading screen (wasp in front of honeycomb) shows;
- it switches to the landing screen.

Actual behaviour:
- the landing screen stays on.

System information:
- hardware: Nexus 7 tablet;
- os: android 5.1.1;
- application version: betaflight-configurator_10.8.0-debug-5cc28aae

Error:
`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.`

image

### PR DESCRIPTION
**Pull request by mikeller**
Fixes #2581.

Screenshot from 2021-08-29 20-40-34

### CODE REVIEW

**Review by Asizon — APPROVED** [review]

**Review by haslinghuis — APPROVED** [review]

**Review by McGiverGim — APPROVED** [review]

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> PASS
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> FAIL
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> PASS

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> PASS
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> FAIL
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> PASS

**Comment by haslinghuis** [comment]
`Do not merge` label is applied as this builds upon #2577

**Comment by blckmn** [comment]
AUTOMERGE: (PASS)
 - github identifies PR as mergeable -> PASS
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> PASS

**Pull request merged**
