### PR TITLE
Add cordova-chrome-sockets-tcp

### PR DESCRIPTION
**Pull request by InsanePrawn**
Makes  `tcp://$IP:$PORT` work on android.

First contribution, only tested against netcat, not a real board.

Ref to #1685 as that's what I always found while looking for info on Android and TCP functionality.

### CODE REVIEW

**Comment by haslinghuis** [comment]
Can you please provide information about the Android device (including OS version) you have tested this on?

**Comment by InsanePrawn** [comment]
Just the standard Android (11) emulator, a friend was able to confirm this working with a Poco F1 (Android 10) and his speedybee f7 v2 through USB and socat though.

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Review by haslinghuis — APPROVED** [review]

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Comment by Asizon** [comment]
@InsanePrawn how I can test this functionality?

**Comment by InsanePrawn** [comment]
@Asizon:
> @InsanePrawn how I can test this functionality?

Acquire any serial<->tcp converter for your drone.
We are targetting the ESP8266 for this, but for testing, a PC with a unixlike OS (I'll assume a Debian-based Linux, e.g. a Ubuntu installer environment) and some way for it to speak serial to a drone (e.g. over USB) will do fine:

0. Acquire `socat`, e.g. `sudo apt-get update && sudo apt-get install socat`
1. Connect the drone to the PC. Figure out what the serial device is called, e.g. consult `sudo dmesg | tail -n 50`. For Linux and a USB device, it'll usually be `/dev/ttyUSB0`. OSX probably uses different names.
2. Find out your LAN IP. `ip a s`.
3. Expose the serial device as a TCP socket: `sudo socat TCP-LISTEN:8888 UNIX-CONNECT:/dev/ttyUSB0`
4. Connect to `tcp://your_ip:8888` from the app.

If you **just** want to see it working **in principle**, skip steps 0-3, open a tcp socket with netcat (`sudo apt-get install netcat-openbsd && nc -l -p 8888`) and connect the app to it, you'll see the app's raw data of trying to talk to a controller, while the `master` version does not connect to TCP at all.

**Comment by Asizon** [comment]
@InsanePrawn thankyou for the steps! This feature is really interesting, maybe we can make it more visual and easy configuration for the users? Definitelly it is wifi conection for android apk, maybe we can made some Wiki page with steps to use it?

**Comment by Asizon** [comment]
@WalcoFPV what do you think about this feature?

**Comment by InsanePrawn** [comment]
> @InsanePrawn thankyou for the steps! This feature is really interesting, maybe we can make it more visual and easy configuration for the users? Definitelly it is wifi conection for android apk, maybe we can made some Wiki page with steps to use it?

I appreciate and support these efforts, but for now I'd be happy to see this existing functionality work on android nightlies (again?) by merging this.
Beyond that, I'm not involved enough with betaflight and cordova development to make these changes. As of now, I don't even own a drone myself :)

**Comment by WalcoFPV** [comment]
@Asizon I agree with you. There is a real potential. If this cordova plugin works well, it could be useful on Android as well as IOS as the documentation mentioned

**Review by Asizon — APPROVED** [review]

**Review by McGiverGim — APPROVED** [review]

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> PASS
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> PASS

**Comment by blckmn** [comment]
AUTOMERGE: (PASS)
 - github identifies PR as mergeable -> PASS
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> PASS

**Pull request merged**
