### PR TITLE
tweaks to dark theme

### LINKED ISSUE #1306: Option for dark theme / skin
I run all of my software on dark mode or skins, use Dark Reader for Chrome, etc.  I would love to see such an option for Betaflight Configurator, as many of the configuration pages which are most of the screen space used, are still bright white backgrounds.   The color scheme used by the sidebar and header in the app have an excellent color scheme with light gray text and dark gray backgrounds.  Would love to see that same color scheme on the configuration pages as well! 

Thank you in advance for your consideration.

### PR DESCRIPTION
**Pull request by Docteh**
The feature request for dark mode is still open, so: Fixes #1306

Been giving the dark theme a bash, some quick tweaks

adjustments tab, color underneath the slider:
image

cli, colors for the text box at the bottom
image
image

firmware tab, target name was blue and hard to read:
image

motors
image

pid tuning
image

switchery, darkened the background of every switch, except the auto-connect one. Why? Looks like the DarkTheme status is loaded after that is drawn.
image

image

### CODE REVIEW

**Comment by IvoFPV** [comment]
@Docteh Looks good to me. BTW looking at your screenshots now, I also missed to make channel values 900-2100 text white and tab title text white in firmware tab.

**Comment by Docteh** [comment]
image
image

Not sure about the warning line,  leaving white text for now. 

Adjustments tab, not quite white but brighter
image

Brightened the help icon. Its a white version, so if the icon needs to be brighter the opacity will become higher than 0.2
imageimage

I can't find where you're making this question mark black, so I'm probably putting my tweaks to the question mark icon in the wrong spot. 
image

**Comment by IvoFPV** [comment]
@Docteh I would also leave Warning white there due to background being red.
I believe that help icon becomes black due to opacity being 0.9 for .helpicon:hover in main.css

**Comment by Docteh** [comment]
Chrome can help edit SVG files with a text editor.
image

**Comment by IvoFPV** [comment]
I think it would be better for help icons to be a bit more brighter, like 0.3 opacity seems fine. In adjustments tab sliders and channel values should also be the same in modes tab for mode ranges and links.

**Comment by Docteh** [comment]
Tweaked the opacity, and the pips. 
Oh, `.linkedTo`

**Comment by Docteh** [comment]
Older versions have a shared RC expo and RC rate for Roll and Pitch 3.1.7 is one of them. 
Here is a before. 
image

Forgot to get an after shot. But I've got all of the coloring moved out of the html into the css.

**Pull request merged**
