### PR TITLE
Fix compass calibration interval timeout

### PR DESCRIPTION
**Pull request by haslinghuis**
See also https://github.com/betaflight/betaflight/pull/13487

### CODE REVIEW

**Review by nerdCopter — APPROVED** [review]
approving untested

**Comment by ctzsnooze** [comment]
Tested, but seems to not get the behaviour quite right.

- if there is no movement, and the magCal process terminates at 15s, the button stays yellow for 30s.
- if there is movement, say at 10s after initiating, the button goes back to normal at 30s, not at 40s like it should.

In other words, it appears to not know when the cal process is complete.

It would be great if, on initiation (clicking the button), the text says, "Calibrate Magnetometer: waiting", or something like that.  If no movement (ie if data collection never starts because movement threshold is not reached), then it times out at 15s and says "Calibrate Magnetometer: failed" in the button name, or something like that.

One the other hand, if it works out, then once the cal is complete, we can say "Calibrate Magnetometer: success!" 

The button text could reset every time we enter the screen.

**Comment by haslinghuis** [comment]
Only have the CALIB armingDisableFlag as a measure to control the button. tCal in firmware would reset that flag.

**Comment by ctzsnooze** [comment]
@haslinghuis sorry my bad, initial test was accidentally with a build from Master.  Now I tested this branch correctly, it works great.  Approved.

**Review by ctzsnooze — APPROVED** [review]

**Pull request merged**
