### PR TITLE
Clarify arming disable readout in setup tab

### PR DESCRIPTION
**Pull request by DanNixon**
- Lists the flags without having to interpret the bit mask manually
- Adds a tooltip directing users to the Wiki

### CODE REVIEW

**Comment by basdelfos** [comment]
I was just thinking the same. After watching the movie from Joshua I immediately thought 'this is so user unfriendly, this has to change'. Started up my mac to make the change and promptly see you PR. This can not be coincident.

**Comment by basdelfos** [comment]
I pulled your PR and tested your changes. It is not yet as user friendly as I was hoping. Displaying a number is still not very obvious for a user and he still has to navigate to the wiki to search the answer what e.q. 2 means.

A more user friendly approach would be something similar to the pre-arming checks from iNav.

image

**Comment by DanNixon** [comment]
Yes, that is still planned, however it ideally requires firmware changes to be able to pull across the names of the flags.

Just as I type that I realise that's going to be an issue for low memory targets so maybe having an array of names in the configurator that must be kept up to date is the only effective way to do it. I'll take another look in the morning.

**Comment by basdelfos** [comment]
Yes, we must avoid adding more texts into the fw. In many more cases the names of flag need to be kept in sync, like features, beeper flag. So it is not uncommon.

**Comment by mikeller** [comment]
@DanNixon: Re-using the names that we already have in the firmware for CMS should be fine. And for targets without CMS, numbers will have to do.

**Pull request merged**
