### PR TITLE
Exempt issues and pull requests with a milestone from going stale.

### PR DESCRIPTION
**Pull request by mikeller**

### CODE REVIEW

**Comment by McGiverGim** [comment]
I suppose this is for a future? The `exempt-all-milestones: true` will only work when the PR that I linked is merged and published, it is not at this moment...

At this moment the only tag working...


>exempt-milestones:
>description: 'The milestones that mean an issue is exempt from being marked stale. Separate multiple milestones with commas (eg. "milestone1,milestone2").'

**Comment by mikeller** [comment]
@McGiverGim: Good point, yes. Let's wait...

**Comment by McGiverGim** [comment]
It has been merged, now we need to wait to the next release or use the main branch in the repo directly.

I think we can wait, but is your decision ;)

**Comment by mikeller** [comment]
@McGiverGim: Yeah, let's wait - once the release is out, will we have to do something to update our integration to it?

**Comment by McGiverGim** [comment]
I think that not, if the version does not pass to version 4:

https://github.com/betaflight/betaflight-configurator/blob/319dc429cabbb57e833c7a082480f4635f87ea7a/.github/workflows/stale.yaml#L12

**Comment by McGiverGim** [comment]
Release 3.0.17 is out with the change. We can merge this and verify if it works...

**Comment by mikeller** [comment]
@McGiverGim: As soon as it passes review. :laughing:

**Review by McGiverGim — APPROVED** [review]
True, I forgot... 🤭

**Comment by mikeller** [comment]
Removed the 'Has Milestone' label from https://github.com/betaflight/betaflight-configurator/pull/1324, watching.

**Pull request merged**
