### PR TITLE
Axis Logo Update

### PR DESCRIPTION
**Pull request by SupaflyFPV**
Uploaded the svg file for Axis feature on Team Sponsorship banner

### CODE REVIEW

**Review by asizon — CHANGES_REQUESTED** [review]
@SupaflyFPV can you share an screenshot to see how It shows please?

**Comment by SupaflyFPV** [comment]
`<?xml version="1.0" encoding="utf-8"?>

<svg version="1.2" baseProfile="tiny" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
	 x="0px" y="0px" viewBox="0 0 240.94 155.91" xml:space="preserve">
<path fill="#E30613" d="M158.42,47.63l-3.3,10c-0.24,0.72-0.91,1.21-1.67,1.21h-16.38c-0.75,0-1.29-0.74-1.05-1.45l3.36-10.11
	c0.15-0.47,0.59-0.78,1.08-0.78h17.14C158.18,46.5,158.6,47.08,158.42,47.63"/>
<polygon points="58.95,113.14 74.11,113.14 65.68,96.81 50.55,96.81 "/>
<polygon points="43.79,113.14 55.91,113.14 47.47,96.81 35.39,96.81 "/>
<polygon points="31,113.14 40.74,113.14 32.3,96.81 22.59,96.81 "/>
<polygon points="21.08,113.14 27.82,113.14 19.39,96.81 12.68,96.81 "/>
<path d="M103.85,113.14l104.32,0c1.25,0,2.35-0.8,2.74-1.99l2.66-12.52c0.38-1.17-0.49-2.36-1.71-2.36H95.37
	c-1.16,0-1.9,1.25-1.34,2.27l7.26,13.09C101.8,112.56,102.79,113.14,103.85,113.14 M193.94,105.92l0.69-2.11
	c0.34-1.04,0.83-1.77,1.43-2.17c0.62-0.4,1.6-0.61,2.92-0.61h2.64c0.82,0,1.43,0.04,1.8,0.11c0.31,0.06,0.54,0.17,0.68,0.3
	c0.13,0.14,0.2,0.32,0.21,0.57c0.01,0.28-0.06,0.65-0.2,1.09l-0.08,0.24h-1.81c0.04-0.37-0.11-0.58-0.25-0.69
	c-0.16-0.12-0.48-0.26-1.57-0.26h-1.38c-0.87,0-1.46,0.11-1.8,0.34c-0.35,0.23-0.63,0.68-0.86,1.38l-0.35,1.08
	c-0.22,0.67-0.2,1.14,0.07,1.43c0.25,0.28,0.77,0.41,1.63,0.41h1.36c0.72,0,1.23-0.07,1.57-0.21c0.37-0.15,0.63-0.43,0.76-0.81
	c0.02-0.05,0.04-0.13,0.04-0.2l0.21-0.42h-2.84l0.33-0.99h4.63l-0.71,2.16c-0.22,0.66-0.6,1.11-1.17,1.38
	c-0.59,0.29-1.55,0.43-2.84,0.43h-2.63c-0.78,0-1.35-0.04-1.68-0.12c-0.3-0.07-0.53-0.19-0.69-0.36c-0.19-0.19-0.29-0.43-0.31-0.73
	C193.69,106.85,193.77,106.43,193.94,105.92 M174.88,101.12h3.11l2.97,6.15l2.02-6.15h1.75l-2.36,7.16h-3.08l-3.02-6.09l-2.01,6.09
	h-1.76L174.88,101.12z M162.05,101.12h1.76l-2.35,7.16h-1.76L162.05,101.12z M143.95,101.12l1.61,3.24l3.87-3.24h1.91l-5.3,4.45
	l-0.06,0.05l-0.88,2.66h-1.76l0.83-2.52l-2.47-4.64H143.95z M126.79,101.12h1.76l-1.93,5.86h5.14l-0.43,1.3h-6.91L126.79,101.12z
	 M108.49,101.12h7.84l-0.43,1.31h-6.09l-0.65,1.96h5.74l-0.43,1.29h-5.73l-0.85,2.6h-1.76L108.49,101.12z"/>
<path d="M150.25,78.92c-0.88,0-1.5-0.86-1.23-1.69l4.44-14.07c0.11-0.35-0.15-0.7-0.51-0.7h-14.96h-2.18c-0.73,0-1.38,0.47-1.6,1.16
	l-7.87,23.96c-0.61,1.86,0.77,3.77,2.73,3.77h11.83h3.38h52.29c8.19,0,15.45-5.36,17.83-13.24c2.35-7.76-3.6-15.56-11.7-15.56
	h-18.94c-0.88,0-1.54-0.85-1.29-1.69c0.35-1.17,1.43-1.96,2.64-1.96h31.29c2.55,0,4.82-1.64,5.61-4.07l2.13-6.55
	c0.28-0.86-0.36-1.74-1.26-1.74h-40.56c-5.31,0-10.46,2.31-13.68,6.53c-7.46,9.77-0.41,22.13,10.34,22.13h16.53
	c0.96,0,1.63,0.95,1.31,1.85l-0.04,0.12c-0.38,1.08-1.4,1.81-2.55,1.81h-35.29L150.25,78.92z"/>
<path d="M90.23,46.52H80.01c-0.83,0-1.36,0.89-0.97,1.62l11.21,20.82l-11.42,9.47L62.99,48.86c-0.78-1.44-2.28-2.34-3.92-2.34H48.63
	c-1.41,0-2.73,0.7-3.53,1.87L17.38,89.3c-0.59,0.87,0.03,2.04,1.08,2.04h31.83c0.95,0,1.85-0.47,2.38-1.26l7.72-11.39h-2.62H47.53
	h-4.3l9.71-14.41l5.58,10.8h8.7l-4.94,7.29l15.88,30.76h19.29L85.73,91.29l11.51-9.55l3.92,7.24c0.79,1.46,2.31,2.36,3.97,2.36h8.79
	L90.23,46.52z"/>
<path fill="#E30613" d="M132.71,46.52H116.1c-1.07,0-2.11,0.38-2.94,1.06l-10.29,8.54l-4.26-7.87c-0.58-1.06-1.69-1.73-2.9-1.73
	h-3.49l23.68,44.82h3.94c0.95,0,1.55-1.01,1.09-1.84l-11.18-20.54l23.89-19.82C134.72,48.26,134.1,46.52,132.71,46.52"/>
</svg>`

**Comment by asizon** [comment]
> Screenshot 2023-08-29 at 11 21 38

I mean how It shows on Configurator firmware flasher tab,because sometimes It have unintended changes and we need to fix on css/html side

**Comment by SupaflyFPV** [comment]
> > Screenshot 2023-08-29 at 11 21 38
> 
> I mean how It shows on Configurator firmware flasher tab,because sometimes It have unintended changes and we need to fix on css/html side

I wanted to add the image to the repository, then I thought that someone would assist/advise on setup with the banner...it doesn't show currently...

**Comment by SupaflyFPV** [comment]
it didnt show on the version I DL from link above
Screenshot 2023-08-29 at 11 32 37

**Review by asizon — APPROVED** [review]

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Review by haslinghuis — APPROVED** [review]

**Comment by nerdCopter** [comment]
does it need less margin? i do notice other sponsor images have minimal margin.

image

**Comment by SupaflyFPV** [comment]
ok I cropped and replaced - let me know if its correct

**Comment by nerdCopter** [comment]
- probably good.
- wish i could directly test in UI.
- my image viewer shows this 
image
- github shows this, but i suspect it wrong
image

**Review by nerdCopter — APPROVED** [review]

**Comment by SupaflyFPV** [comment]
thanks to @KarateBrot for checking the file - now re-uploaded

**Review by blckmn — APPROVED** [review]

**Comment by blckmn** [comment]
We might like to add a white halo around the lettering. That way in dark mode you will still see it.

**Review by KarateBrot — CHANGES_REQUESTED** [review]
Not ready yet. Let's fix some things first

**Review by KarateBrot — APPROVED** [review]

**Pull request merged**
