### PR TITLE
[SonarCloud]Exclude html from duplications

### PR DESCRIPTION
**Pull request by Asizon**

### CODE REVIEW

**Review by limonspb — APPROVED** [review]

**Comment by McGiverGim** [comment]
This will not fix anything. If I'm not wrong, you want to "fix" the "failed" builds of the master branch.

image

This is simply a check against the "latest" code, for example in this case:

image

We need only to upload "good" code and the check will pass the Sonar verification.

**Comment by McGiverGim** [comment]
Maybe my explanation was not good: if I'm not wrong, if now you merge a "good" PR that is rebased against master, the check will pass again. Can you try with next merge to see if in this way the problem is fixed?

**Comment by Asizon** [comment]
@McGiverGim I think that the percentage of duplicate code remains in master and is added, so we will always get an error. The only way to test this PR is by merging with master.

**Comment by McGiverGim** [comment]
Yes, the total remains, but the Sonar only analyzes the "latest" branch against master to decide if ok or not. The latest merge is old, so it has a GPS code different than the master one, and complains about it. Sonar is a little stupid for this. Be sure to rebase the next merge and let's see.

This is what I think, maybe I'm wrong ;)

**Comment by McGiverGim** [comment]
I've seen that it continues complaining...
It's clear that at some moment it must remove the complaining, because we had this problem before, but I don't know when exactly :(

**Comment by McGiverGim** [comment]
It seems the new code is more or less three weeks:

image

Now is marking at 27th nov.

**Comment by Asizon** [comment]
@McGiverGim yes I think new code spans a month, but i think the idea of avoid code duplication test on HTML code is also good idea, what do you think?

**Comment by McGiverGim** [comment]
What I don't understand is why the Sonar complains for HTML blocks... I don't know how it wants to "fix" this... maybe add and `id` or `class` to each block? Generate it using javascript?
If we don't find the "right answer" I suppose this "workaround" can be acceptable.

**Comment by ctzsnooze** [comment]
I was thinking that if we had a specific id or class to each of those 'duplicate' blocks, it would, most likely, pass.
I'm good with not checking html for duplicates though, and will approve this.

**Review by ctzsnooze — APPROVED** [review]

**Review by haslinghuis — APPROVED** [review]

**Pull request merged**
