### PR TITLE
Fix autodetect for some older 4.5 firmware builds

### PR DESCRIPTION
**Pull request by haslinghuis**
Fixes: 
image

### CODE REVIEW

**Comment by nerdCopter** [comment]
"older 4.5"?  master working for 4.5.1, is this for something older like RC's?

**Review by nerdCopter — APPROVED** [review]
- irregardless of my last comment, it works, so approving.

**Comment by haslinghuis** [comment]
Yes should have made a screenshot. After making the change it solved it. But as it is flashed now cannot reproduce :wink:

**Comment by nerdCopter** [comment]
i did notice master had empty (white-space) drop-down dialog, maybe this?

**Review by chmelevskij — APPROVED** [review]

**Pull request merged**
