### PR TITLE
Fixed Windows per-user installation.

### PR DESCRIPTION
**Pull request by mikeller**
Requires installation of http://nsis.sourceforge.net/ShellExecAsUser_plug-in to work.

### CODE REVIEW

**Comment by mikeller** [comment]
@AndersHoglund, @wind0r: This will potentially break CI for windows, as the ShellExecAsUser NSIS plugin needs to be installed.

@McGiverGim: Are you happy for this to be merged as it is? It will need some more work in the uninstaller to make it work again.

**Comment by McGiverGim** [comment]
I'm not too sure, I need to execute it to see what provides and what not. You can merge it and I will work since it, or you can wait, maybe tomorrow I can take a deeper look to it.

**Comment by McGiverGim** [comment]
I had some minutes and played a little with this. The first problem that I see, is that we must decide what to do with i18n of the installer.

In the actual version, the installer is shown into the system language for the languages that the configurator supports.

If we add some "custom" page, we must make the translations and add them (there's not directly, but can be done).

This plugin has the "strings" hardcoded, so if I'm not wrong, it cannot be translated without modifying the code.

So if we want to use this library, we must decide:
- Remove the i18n from the installer. English for all.
- Let the translator with a mixed translation, some things translated, others not.
- Implement something similar by our own, but with translations.
- Others...

I need to take a in-depth look to it, but this is the first thing that I've seen. Thoughts?

**Comment by AndersHoglund** [comment]
@mikeller Thanks for the CI warning. I pulled this PR and sure enough builds fail. 
```
Packing release.
Installer for platform win64 finished with error 1: !include: could not find: "NsisMultiUser.nsh"

```
Downloaded the `ShellExecAsUser.zip` from the site you linked, but only a `ShellExecAsUser.dll` in there. Read up on NSIS Plugin installtion, and there should be two mandatory file, ,nsh and .dll, to copy. Seems this zip contains only half of a plugin (?) Installing/extracting only the .dll did not work, build still fail. A bit confusing names too, `NsisMultiUser.nsh` is missing but the plugin download is `ShellExecAsUser.dll` .
Are these two different plugins? Please advice.

**Comment by AndersHoglund** [comment]
Ahh, `NsisMultiUser` is a git sub-module.

**Comment by AndersHoglund** [comment]
Got it working. Only needed to extract the `ShellExecAsUser.dll`  to the correct place. No need for any .nsh it seems. Also of course init and update the git submodule. Three manual steps to do.

**Comment by mikeller** [comment]
@AndersHoglund: Sorry, forgot about the submodule that I'd added when trying to put together a version using this for the release.

@McGiverGim: Good point about the translation. Not sure if modifying the `NsisMultiUser` for multi language support is a good way to go - if we decide to go this way, we should probably contact the author of the plugin and see if he wants to republish the localised version - this way others will be able to benefit from our efforts.

I am in no hurry with this, it's a potential improvement over the current system, but we have time until the next release to decide if and how we are going to be using it. I'll just leave this open for now.

**Comment by mikeller** [comment]
Superseded, withdrawn.

**Pull request closed without merging**
