### PR TITLE
Use diff

### PR DESCRIPTION
**Pull request by haslinghuis**
Should we use `dump` or `diff` for `backup on flash`?

### CODE REVIEW

**Comment by sugaarK** [comment]
DIFF ..

**Comment by nerdCopter** [comment]
dump is a backup.
diff not necessarily a backup, although convenient, only good enough for major sem-versions.
could technically run both commands with some `#############################################` separator.
or maybe save both separately as well. :man_shrugging:

**Comment by sugaarK** [comment]
> `dump all` is a proper full backup. `diff` is not necessarily a backup, although convenient, only good enough for major sem-versions. could technically run both commands with some `#############################################` separator. or maybe save both separately as well. 🤷‍♂️

dump can break stuff version to version.. also if you ask me to look at an issue and give me a dump.. lols your on your own. if you need a dump then you know how to use the cli and if  your  afraid of the cli then you NEVER need a dump

**Comment by nerdCopter** [comment]
that is certainly fair!  my only consideration would be if some default has changed in a minor semver and excluded from diff.

**Comment by sugaarK** [comment]
> that is certainly fair! my only consideration would be if some default has changed in a minor semver and excluded from diff.

you just get an error and the item is reset though so its not dangerous.. your not over writing hardware settings etc

**Comment by nerdCopter** [comment]
this is only for the flashing tab correct? not the presets tab?

if only for the flashing tab, my original opinion stands as this is mainly for noobs.  we advanced users don't necessarily use this ever.

**Review by nerdCopter — APPROVED** [review]
- approving only based on fact that this was changed rather recently.
- noobs should get full `dump all` for "prosperity" backups (not necessarily to use them) when updating factory or old firmware, IMHO. i.e. my preference would be backup **_both_** `diff all`/`dump all`.

**Review by sugaarK — APPROVED** [review]

**Comment by ctzsnooze** [comment]
@sugaarK @haslinghuis 

A 'diff' only backs up the currently active profile and rate profile.  It does not include any data from inactive, but configured, profiles or rate profiles.  

Hence `diff` does NOT backup all your profiles, only the active one.

It seems to me we should use `diff all`, if we use diff for backup.

**Comment by McGiverGim** [comment]
I like to use `diff all defaults` because it adds the default value to compare with the current one.

**Pull request merged**
