### PR TITLE
Preparing for 10.8 final - commencing 10.9

### PR DESCRIPTION
**Pull request by blckmn**

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Comment by McGiverGim** [comment]
Only to not forget: Before that, we need to modify the changelog.html file and push one more time the latest translations.

**Comment by haslinghuis** [comment]
Don't we need to update the API version?
I already had it prepared here: https://github.com/betaflight/betaflight-configurator/pull/2835

**Comment by blckmn** [comment]
> Don't we need to update the API version? Already had it prepared here: #2835

Only if there is to be changes to the API no?

**Comment by McGiverGim** [comment]
Usually we always had. We have some PR pending for the next version ready that need incrementing version. If there is no version incremented, there is no new features in the Configurator, so usually we don't release a version. Can happen, but it's not habitual.

**Comment by haslinghuis** [comment]
Closed my PR as I found reference here: https://github.com/betaflight/betaflight-configurator/pull/2059

**Review by haslinghuis — CHANGES_REQUESTED** [review]
Please add `API_VERSION_1_44` as done in https://github.com/betaflight/betaflight-configurator/pull/2059

**Review by haslinghuis — APPROVED** [review]

**Pull request merged**
