### PR TITLE
Fix lost context

### LINKED ISSUE #3821: WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
### Describe the bug

image

### To Reproduce

Leave configurator open on setup tab (probably also receiver tab)

### Expected behavior

Library not losing context.

### Configurator version

master

### Flight controller configuration

```txt
defaults
```

### Add any other context about the problem that you think might be relevant here

image

### PR DESCRIPTION
**Pull request by haslinghuis**
Changes

- Fix calling render functions while disposed
- Do not double precision in `renderer.setSize`
- Fixes #3821 (at least to seem to occur less frequently)
- See: https://stackoverflow.com/questions/25219352/webgl-scene-doest-render-because-of-lost-context

### CODE REVIEW

**Comment by nerdCopter** [comment]
Tested `ca2967f8` on two machines.
- Debian with Intel-integrated HD:
  - one execution, stayed for 30+ minutes without lost-context.
  - my first execution had lost-context and seemingly reconnected as the quad render was still available and moving. (screencap below)
- Xubuntu with NVidia:
  - one execution 40+ minutes without lost-context.

Debian/Intel, first run:

**Comment by haslinghuis** [comment]
Self - healing :)

Removed the class usage of Model in `b6e36ac` - as configurator was stuck on the [setup] tab when context was lost. Switching tab now seems to restore context as before.

**Comment by nerdCopter** [comment]
Should i wait for Windows & OSX testing before approval?

**Comment by nerdCopter** [comment]
`b6e36ac1` after some time allowing other widows to be on top...
image

**Comment by haslinghuis** [comment]
Already have tried to include `import CanvasRenderer from 'three/examples/js/renderers/CanvasRenderer';`

**Comment by nerdCopter** [comment]
may be a bug when accidental USB disconnect (loose wire)
image

**Comment by haslinghuis** [comment]
Found that after nulling the renderer object it was still trying to rotate on it. Testing now.

**Review by HThuren — APPROVED** [review]
I can't get any errors, and seems well done

**Comment by nerdCopter** [comment]
- i left `2813a543` running for over an hour on 2 FC/PC's. Xubuntu, no issue. Debian, blank screen similar to comment https://github.com/betaflight/betaflight-configurator/pull/3824#issuecomment-1971444789 but without graphical grid background.

- awaiting new commits.

**Comment by haslinghuis** [comment]
Think adding event listeners to restore context would be over engineering here as switching tabs will restore context as overruns are halted now.

https://threejs.org/docs/#api/en/renderers/WebGLRenderer
https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_lose_context

**Comment by nerdCopter** [comment]
- `0f1dff74` no issues seen after 50 minutes, 2 FC/ 2 PC's.
- may need extended testing and testing other OS.

**Comment by haslinghuis** [comment]
No issues with HP Elite 840 Pro (Intel I5-4200U with16GB SODIMM and Samsung SSD 840 Pro 256GB) using MS Windows 10 Pro.

**Comment by haslinghuis** [comment]
Tested 90 minutes without issue. Only will remove the CSS change as the preview is too big for 1600x900

**Pull request merged**
