### PR TITLE
Iterm Relax Cutoff Update

### PR DESCRIPTION
**Pull request by Asizon**
This PR goes with the latest changes in https://github.com/betaflight/betaflight/pull/9482  updated Max cutoff to 50.
Also updated tooltip to add `Cutoff` tips, I would like to add a helpicon for Cutoff but I can't find the way to add it at the end inside the flex

### CODE REVIEW

**Comment by mikeller** [comment]
Something like a `<div>` inside the `<span>` isn't giving you what you want?

**Comment by Asizon** [comment]
@mikeller yes, but I cant align to the right under this flexbox
image-4

**Comment by mikeller** [comment]
@Asizon: Like so:

image

```
mikeller@pc:~/git/betaflight-configurator$ git diff
diff --git a/src/tabs/pid_tuning.html b/src/tabs/pid_tuning.html
index aaf3b01f..9fd025f6 100644
--- a/src/tabs/pid_tuning.html
+++ b/src/tabs/pid_tuning.html
@@ -537,6 +537,7 @@
                                         </label>
                                     </span>
 
+                                    <div class="helpicon cf_tip" i18n_title="pidTuningItermRelaxHelp"></div>
                                     <span class="itermRelaxCutoff suboption">
                                         <input type="number" name="itermRelaxCutoff" step="1" min="1" max="100" />
                                         <label for="itermRelaxCutoff">
```

**Comment by Asizon** [comment]
woow as simple as taking it out of ItermRelaxCutoff Span, thankyou, making changes now

**Comment by mikeller** [comment]
:grin:

**Pull request merged**
