### PR TITLE
Simplify Expert Mode

### PR DESCRIPTION
**Pull request by haslinghuis**
Expert mode should be set once only.

Screenshots:

image

image

image

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by nerdCopter** [comment]
@haslinghuis , can you describe what this does?
I've noticed the window-blind effect triggers twice each toggle: https://youtu.be/kywzSs0Qqws

**Comment by haslinghuis** [comment]
@nerdCopter I have noticed this too but that's is a separate issue.

Users were able to access custom defines field while in non-expert mode not having effect in the cloud build.

This PR fixes expert mode toggle working both ways and unifies permanent expert mode option.

**Review by nerdCopter — APPROVED** [review]

**Review by chmelevskij — APPROVED** [review]

**Review by nerdCopter — APPROVED** [review]
* seems to do what is expected.
* slightly odd to see `Development`, only when `Show release candidates` is enabled -- maybe this needs a different description :man_shrugging:  but i cannot really think of anything better that is not too wordy.

**Pull request merged**
