### PR TITLE
CI builds using azure pipelines.

### PR DESCRIPTION
**Pull request by si618**
Builds Betaflight Configurator on Windows, Linux and OSX using Azure Pipelines, which can then be published as a new Github release.

Example build pipeline:  https://si618.visualstudio.com/betaflight-configurator-ci
Example release repo: https://github.com/si618/betaflight-configurator-ci

Apologies for stuffing up the last pull request, I think this one is ok.  Have added Linux and OSX builds as I figured having all the platforms in one spot is better than spreading them out, but easy enough to change if not needed.

### CODE REVIEW

**Comment by mikeller** [comment]
Nice! I am surprised that Microsoft is offering Mac OS vms. But getting everything built in the same way is definitely a nice option.

**Comment by si618** [comment]
Missed the Mac OS .dmg deployment on the azure pipeline release.

Fixed now, demo build available in [v20190415.14 release](https://github.com/si618/betaflight-configurator-ci/releases/tag/20190415.14), although I don't have a mac to test this on.

**Comment by si618** [comment]
Mac user in our local club has tested the .dmg image and reported it works as expected.

Happy to add a betaflight dev as admin to that azure devops project to see how things are wired up, I think it just needs an email address to invite.

**Comment by mikeller** [comment]
@si618: Can you rebase / squash into one commit please?

**Comment by mikeller** [comment]
@si618: The squash did not quite work - try `rebase -i master`, then select `s` for all but one commit.

**Comment by si618** [comment]
Sorry to be a pain, see if that works now.

**Comment by mikeller** [comment]
@si618: Perfect!

**Pull request merged**
