### PR TITLE
Reset button when loading a new firmware

### PR DESCRIPTION
**Pull request by haslinghuis**

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by blckmn — CHANGES_REQUESTED** [review]
Prefer not to smash the healthcheck end point. It is not designed for configurator.

**Review by nerdCopter — APPROVED** [review]

**Comment by nerdCopter** [comment]
`no description provided`  but i do see the need.

it may need to be in another location as well.
to reproduce a problem on master and/or this PR:
1) load local hex
2) choose different flightcontroller in dialog (or auto-detect), flash button remains active which may be confusing or lead to bad flashing.

same does NOT happen for downloading cloud-builds. i.e. flash-button turned off appropriately.

**Comment by haslinghuis** [comment]
Thanks for testing - will check local flash procedure.

**Comment by haslinghuis** [comment]
Closing as this will be part of `#3745`

**Pull request closed without merging**
