### PR TITLE
Add current draw to status bar

### PR DESCRIPTION
**Pull request by LightningStalker**
Makes it easy to see during current sensor calibration

### CODE REVIEW

**Comment by LightningStalker** [comment]
Goes along with Feature request #965 
There are at least 2 better ways of doing this but the one I tried didn't work, mostly due to my unfamiliarity with js.

**Comment by McGiverGim** [comment]
I'm not too sure if this is a useful information for the status bar. Let's wait for other thoughts.

**Comment by mikeller** [comment]
I concur with @McGiverGim. Showing arbitrary information in the status bar isn't the way to go, and there probably is a case to be made for a lot of information that _could_ be shown there.

**Comment by LightningStalker** [comment]
I tend to agree. It would be better if it was on the Motors tab. Unfortunately I don't have enough proficiency with js to get that working.

**Comment by McGiverGim** [comment]
I will try to add it to the motors tab tomorrow if I have time.

**Comment by LightningStalker** [comment]
That would be great.
Updated to work on all tabs anyway before reading this

**Comment by McGiverGim** [comment]
Done in https://github.com/betaflight/betaflight-configurator/pull/973 

Can you test it please?

**Comment by LightningStalker** [comment]
It's working so far. Closing pull request

**Pull request closed without merging**
