### PR TITLE
Added switch to reverse motor direction

### PR DESCRIPTION
**Pull request by basdelfos**
image

Thanks to @fbohmann for changing the vector graphics.

### CODE REVIEW

**Comment by basdelfos** [comment]
See PR https://github.com/betaflight/betaflight-configurator/pull/554 for the vector graphics

**Comment by basdelfos** [comment]
Needs BF PR: https://github.com/betaflight/betaflight/pull/3559

**Comment by AndersHoglund** [comment]
Looking good!!! 
But is there not a high risk for misunderstandings when saying "Reverse motor direction" ? 
A lot of people might interpret that wrong and think it will actually reverse the motors. Not sure how to rephrase that to make it 100% clear that it is all about: "Yes, I have reversed the motors". Maybe: "Motors are reversed".

**Comment by wind0r** [comment]
it may should be named similar to the cli setting so users know that is "only" the cli setting

**Comment by fbohmann** [comment]
maybe something like "reverse motors configured at esc"

**Comment by AndersHoglund** [comment]
Help text is also misleading. ".... will reverse the motor direction ..." No, it will not reverse any motors.
Might instead read: "... will tell Betafight the motors are reversed." Or someething like that. Someone wuth a native English tongue might be of help here...

**Comment by basdelfos** [comment]
Yeah, I'm not totally happy with the help text either. All suggestions are welcome.

**Comment by wind0r** [comment]
"use reversed yaw motor direction" (yaw_motors_reversed)

**Comment by basdelfos** [comment]
Yep, maybe not a bad idea at all to just use something like the name of the cli setting

**Comment by AndersHoglund** [comment]
Nah, the cli parameter names and values are short (and cryptic) for firmware to use and interpret. A GUI is intended for a Human to interpret. A GUI should talk a human language.

**Comment by AndersHoglund** [comment]
When it comes to (G)UI, always try to take a step back and put on the newbee user hat. Try to forget and not knowing what is on the inside of the UI. It is hard, I know...
No point in displaying the cli stuff in just another format. A reference to the cli parameter name and values might be good in the help text though, connecting cli and GUI via a cross reference.

**Comment by jaapp** [comment]
I believe "Motor direction is reversed" is the best applicable caption. It's has the best match with the intended behavior the non-technological user will have.

- It does not ambiguously imply that you are reversing the motor direction
- It's relation to yaw-authority, while technically correct, is not relevant for the user experience

**Comment by AndersHoglund** [comment]
Much better now, but the help text is still saying "... will reverse....". Please re-phrase. 
Suggestion: 
"Enabling this option will tell Betaflight that motors and props are set to run ib the reverse direction. CAUTION: Make sure you test this with PROPS OFF!"
Not sure the warning is needed, nothing specific to this option. Props are dangerous in any direction.

**Pull request merged**
