### PR TITLE
Fix sponsor background on landing page

### PR DESCRIPTION
**Pull request by haslinghuis**
image

image

Not sure about Axis image - did some further investigation and both show light or dark mode - but still the axis image is flipped.

image

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by ctzsnooze** [comment]
the outcome may depend on the state of the images in btaflight.com?  Perhaps we need https://github.com/betaflight/betaflight.com/pull/315 merged before this can be finalised?

**Comment by KarateBrot** [comment]
> the outcome may depend on the state of the images in btaflight.com? Perhaps we need [betaflight/betaflight.com#315](https://github.com/betaflight/betaflight.com/pull/315) merged before this can be finalised?

no, we have independent file sources in erach project

**Review by nerdCopter — APPROVED** [review]

**Review by blckmn — APPROVED** [review]

**Comment by KarateBrot** [comment]
Works for me now as well

**Pull request merged**
