### PR TITLE
deleted latest microtime entry

### PR DESCRIPTION
**Pull request by TheIsotopes**
configurator hangs on port loading ... this pr will fix this

@chmelevskij was overlooked / forgotten in #2408

### CODE REVIEW

**Review by McGiverGim — APPROVED** [review]
I was sure it was deleted in the original PR, is clear that I was wrong...

**Comment by Asizon** [comment]
Yes, seems that it has been added in the latest rebases and force push

**Comment by haslinghuis** [comment]
Confirmed.

**Review by haslinghuis — APPROVED** [review]
Confirmed

**Review by McGiverGim — APPROVED** [review]

**Review by mikeller — APPROVED** [review]

**Pull request merged**
