### PR TITLE
Add language option

### LINKED ISSUE #4110: Easy language change after installation
### Is your feature request related to a problem? Please describe

I cannot change the language of the BF configurator. 

### Describe the solution you'd like

Drop-down menu in the settings tab

### Describe alternatives you've considered

Change during reinstallation

### Other information

Sorry if that's something that seems stupid but I tried to find the solution and even re-installation with clearing the installation path is not seeming to work. Thanks

### PR DESCRIPTION
**Pull request by haslinghuis**
- fixes #4110 
- adds language selection to options tab
- keeps language selection on landing tab.
- no refresh required
- For future improvement an icon could improve UX experience

### CODE REVIEW

**Comment by McGiverGim** [comment]
This adds the option without removing the selection on the initial page? I think we must let only one option, not both. At the first time this was in the options, it was changed to the main page, and now it seems we want to return to the options again.

The only problem for moving it to options, is that if for some reason you have a wrong language, like chinese or similar, it will be difficult to find the options text and select the language. In the welcome page it's always visible.

**Comment by nerdCopter** [comment]
:rocket: 
image

**Review by nerdCopter — APPROVED** [review]

**Comment by j4k0xb** [comment]
> In the welcome page it's always visible.

Initially that was the case, but nowadays it's outside the viewport due to more content or screen resolution:


> The only problem for moving it to options, is that if for some reason you have a wrong language, like chinese or similar, it will be difficult to find the options text and select the language

It either defaults to your system language or you're already on the options page and deliberately clicked on the dropdown.
Another common way to avoid confusion is to use icons:
image

**Comment by VitroidFPV** [comment]
I wanted to implement use of a proper icon pack after we update to Vue 3. I think there were some plans to do this internally, but it was recently done in #4169. Big thanks to @BoldBigflank, I will need to have a proper look at that as well. When we have Vue 3 and a proper icon pack it will be easy to make features like this more accessible regardless of the language selected. 

The landing page is also planned for a re-design/update, if the default is to follow system language anyway, I think it makes sense for the language option to be in a (properly indicated) options page, maybe with a small `Switch back to system language` button on the landing page which would not get localized. But overall I'm fine with the option being in either place, though it shouldn't be duplicated IMO - but let's let other people have their say in it a well

**Review by blckmn — APPROVED** [review]

**Pull request merged**
