### PR TITLE
Add dynamic lpf and dterm filters

### PR DESCRIPTION
**Pull request by McGiverGim**
Adds the dynamic filters to the filters TAB of the Configurator:

image

If selected, the static filter is disabled and the inverse. Maybe is not the best way to show them, but the actual template for filters don't let too much play here without redoing all.

EDIT: I change the image, it was in Spanish configurator :)

### CODE REVIEW

**Comment by mikeller** [comment]
Should we put the dynamic lowpass first, and then static 1 and 2? Or should we even hide static 1 when dynamic is active, and vice versa? @ctzsnooze, @joelucid

**Comment by McGiverGim** [comment]
Is not easy mantaining the actual structure/paradigm. 
Now we have an enable/disable for each filter. Without modifying the actual structure is difficult to do something like what you suggest because we can't add others switches without confusing the user what they do. 
Maybe we need a  different approach and revamping totally the filter tab?

**Comment by McGiverGim** [comment]
Maybe we can, as you say, change the order and hide the static, now it is disabled but not hidden.

**Comment by mikeller** [comment]
Yes, agreed, with the current paradigm hiding filters would be confusing. And changing of the order is just a suggestion, but it would fit with us trying to promote the use of dynamic filtering.

**Comment by McGiverGim** [comment]
The ideal will be a switch to select static-dynamic, but now is difficult to fit it in the actual design. But I can hide the dynamic if the static is selected and the inverse, in place of disabling them. Hiding things can cause confusion because the user can search for a filter and he does not see it and is not evident in the actual design where it is. 

It seems ok to me to reorder the filters and include the dynamic first. I will change it later.

About the hiding, finally what do you think? Disable (like now) or hide?

**Comment by mikeller** [comment]
I think you are right and disabling is fine.

**Comment by McGiverGim** [comment]
Reordered filters:

image

**Comment by klutvott123** [comment]
A little unrelated, but can we have D Term lowpass 2 type too?

I'm a little confused. Are the dynamic lowpass filters completely separate from the static ones and do they override the static filters if enabled? What I'm getting from this is that you're not supposed to use both at the same time. Would it maybe be better to get rid of the static filters and instead having an option to make the dynamic filters static by syncing min/max or disabling max cutoffs?

**Comment by McGiverGim** [comment]
The D Term lowpass 2 type is not here because if I'm not wrong, it can't be configured in the firmware neither. 

In the PR that added the Dyn filters, we discussed if the dynamic and static were the same filter (thus allowing us to reusing some parameters) or a different one. The discussion ended with the decision that they are different filters, so this is what I represented in the Configurator.

**Comment by klutvott123** [comment]
@McGiverGim I think it can be configured in firmware. Maybe the option was recently added. I don't know. 🙂 
From cli:
```
dterm_lowpass2_type = PT1
profile 0
Allowed values: PT1, BIQUAD
Default value: BIQUAD
```

**Comment by McGiverGim** [comment]
True. I will look into the firmware to see if it is available under MSP, we need it to be in the Configurator.

**Comment by mikeller** [comment]
@klutvott123, @McGiverGim: I think the confusion can largely be dealt with by adding an explanation of how the dynamic / static filter configurations are interdependent to the help text at the top of the tab.

**Comment by mikeller** [comment]
@klutvott123: We do doing: betaflight/betaflight#7736

**Comment by McGiverGim** [comment]
PR added by mikeller: https://github.com/betaflight/betaflight/pull/7736

I will modify this PR to add the new filter.

**Comment by McGiverGim** [comment]
Modified to add the dterm lpf 2 type, but I need to test it with the RC1 when is out. I'm pretty confident that it will work, but who knows :)

**Comment by klutvott123** [comment]
Good stuff, guys! Thanks for taking care of this. 

@mikeller Yes, some explanation in the tab would be helpful.

**Comment by McGiverGim** [comment]
I can modify the description, but I'm out of the computer until tomorrow.

**Comment by McGiverGim** [comment]
Tested, fixed, modified the description and squashed.

**Comment by klutvott123** [comment]
@McGiverGim Looks good. The new description does make it clear how this is intended to work. I'm trying this out right now, and I'm still a little confused. I have the dynamic filters enabled, and the static gyro 1 and dterm 1 are automatically disabled as expected. In CLI I still see gyro/dterm 1 is set to 150Hz even if disabled in the filters tab. Which one is correct? The settings in CLI or in the tab?

**Comment by McGiverGim** [comment]
Both are correct. The gyro/dterm 1 are ignored if the dynamic filter 1 is enabled. The GUI shows them as zero, and not editables but internally they can have other values.

**Pull request merged**
