### PR TITLE
Further work: consider versions for unified targets

### PR DESCRIPTION
**Pull request by Docteh**
image

Right under release info, do we want to change the target? At the very least I'd like to keep the binary showing STM32F405....

Also `State:` is blank on both Dev and Release builds. I'm curious as to what goes there.

Todo
- [x] `if (bareBoard == target)` condition needs test
- [x] stop board from changing to 0
- [X] ~~add a button to throw out locally loaded config~~
- [ ] fail to flash if loaded (locally or not) config can't be used.

### CODE REVIEW

**Comment by mikeller** [comment]
This is going great, thanks for working on this @Docteh!

>Right under release info, do we want to change the target? At the very least I'd like to keep the binary showing STM32F405....

I'd probably go for

Target: <(unified) target name>
Firmware: <firmware name>

> Also State: is blank on both Dev and Release builds. I'm curious as to what goes there.

Yeah, it does not look like we are setting this: https://github.com/betaflight/betaflight-configurator/pull/1626/files#diff-7de0bc7f2c7f2754ec22f54a1b756d1bL193
We can probably just hiff it.

>￼ add a button to throw out locally loaded config

Not sure a button is the best UX here, I thought we'd do this implicitly when:
1. a different Unified Target config is loaded locally or selected from the drop down (i.e. overriding the locally loaded config);
2. a non-custom-default firmware (i.e. non-unified target or Unified Target but too old) is loaded locally or selected from the drop down (i.e. setting the config to be used to 'none', and flashing the firmware without custom defaults);
3. a Unified Target is loaded but it is not the one specified in the Unified Target configuration (this should probably also result in an error being displayed to the user).

(Re 2., from 4.1 on non-custom-default boards can be detected as having a 0 sized custom defaults area.)

This should cover pretty much every case except for wanting to flash a Unified Target without custom defaults after selecting a Unified Target configuration, and I'd think that this will be a very rare case.

As an extension of the current behaviour I'd also like to make it possible to select a Unified Target configuration from the drop down, then load a local Unified Target, and then flash the target with the custom defaults. This will make it easy for tinkerers to distribute modified firmware in the form of Unified Targets, and allow others wanting to test it to use it on any board that has a published Unified Target configuration.

The above are just my ideas, let me know what you think about them.

**Comment by Docteh** [comment]
I was going to add code to throw out the targetConfig any time the board is changed, turns out I'm already doing that unknowingly, so the new code didn't fire. Ooops.

Instead of a button, I'll make sure its clear to the user when they've loaded a config.

When a user loads a local config, we could try and switch to the correct firmware automatically.

Right now the bottom has things like
* Loaded Online Firmware: (128208 bytes)
* Loaded Local Firmware: (453126 bytes)
* Please load firmware file

I guess it needs more options/strings when a user does something unusual.
Loaded target, please load firmware file
Loaded Online Firmware, Local Target

Loaded Local Firmware, Remote Target
Loaded Local Firmware, BUMBLEBEE Target (Name the remote target?)

(Go red)Local config requests unavailable target

(Go red)Firmware does not support custom defaults


Unrelated quirk, when I download a version, like 4.1.0-RC1, and then select 4.0.6 it still says "Loaded Online Firmware"

**Comment by mikeller** [comment]
Extending the status strings sounds good. I am also wondering if it would make sense to add 2 indicator fields - one for the Unified Target configuration that is loaded (or empty if none), and one for the firmware that is loaded. And since users should not have to worry about these things, make them visible only when in expert mode.

**Comment by mikeller** [comment]
Tested again, this looks great to me now. I think from the point of view that the average user should not notice a difference between flashing a non-unified and a Unified Target when flashing a released version (which is what 95% of our users are doing) we are where we need to be.
For the special use cases like flashing a custom build, we are pretty much as comfortable as we are going to get - choosing a published Unified Target configuration and then flashing it with a custom binary we are miles ahead of where we were with non-unified targets - this will make it so much easier for developers to provide users with test builds than how it was before.

Unless you have something that you think should be improved I think we should go with this.

**Comment by Docteh** [comment]
Well, maybe something needs to be done if a user selects a legacy target and then loads a local config. Right now I haven't tested it, I think it complains when they hit flash. 

One thing I have noted down is I want to throw out the loaded unified config when the 'choose a board' is chosen.

**Comment by mikeller** [comment]
@Docteh:

> Well, maybe something needs to be done if a user selects a legacy target and then loads a local config. Right now I haven't tested it, I think it complains when they hit flash.

Maybe we can stick to a 'config needs to be selected / loaded first' approach, and forget about any loaded firmware when a config is selected / loaded, and disable the 'Flash firmware' button until a firmware is loaded (implicitly from online, or by specifying a matching one locally)?

> One thing I have noted down is I want to throw out the loaded unified config when the 'choose a board' is chosen.

Yes, that makes sense.

**Comment by Docteh** [comment]
Sounds good. What about caching? I think that the "remote load" doesn't check cache, but maybe we could check cache when a local config is loaded?

**Comment by mikeller** [comment]
> maybe we could check cache when a local config is loaded?

Yeah, good point - not having to wait for the download is nice.

**Comment by Docteh** [comment]
I think this is good enough for now. 

loading a local config, or selecting board 0 now throws out anything loaded.

The local config doesn't get looked at yet, so a user could mismatch a config/target combo.

**Comment by mikeller** [comment]
> The local config doesn't get looked at yet, so a user could mismatch a config/target combo.

I don't see this as a blocker - using local configs is a use case that will only be used by a few users. Conversely, for tinkerers working on new targets / architectures, configurator not being fussy about this match with local files will most likely be a convenient shortcoming.

**Comment by Docteh** [comment]
Let me know if anything still needs to be done to get this in. Like squash down, or remove the code from the middle of `flashingMessageLocal()` that isn't needed. I'll check back first thing in the morning PDT.

**Comment by mikeller** [comment]
Na, this looks all good to me - I think this sets us up to move to Unified Targets in a way that will not be seen as an inconvenience (or rather: not be seen at all) by users.
There are more things that we can do to make the flashing process better for users, like automatic detection of the target to be flashed based on `manufacturer_id` / `board_name`, but I think doing this in a simple way and ironing out the kinks first is a better approach.

**Pull request merged**
