### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by McGiverGim**
New round of updated translations.

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Review by Asizon — APPROVED** [review]

**Review by haslinghuis — DISMISSED** [review]

**Comment by HThuren** [comment]
I have checked the danish translation, look good, also the words witch are longer than the english conterpart.
OK from here

**Review by haslinghuis — APPROVED** [review]

**Comment by HThuren** [comment]
Verified, OK from here

**Comment by McGiverGim** [comment]
Updated and rebased.

**Review by haslinghuis — APPROVED** [review]

**Review by blckmn — APPROVED** [review]

**Pull request merged**
