### PR TITLE
Add model preview for Receiver tab

### PR DESCRIPTION
**Pull request by antstorm**
This adds a model preview to Receiver tab, reacting to receiver input and allowing to check that inputs are mapped correctly.

### CODE REVIEW

**Comment by borisbstyle** [comment]
Is this really needed? I mean we already have one in PID tab

**Comment by mikeller** [comment]
@borisbstyle: Sorry, that was me suggesting it be available in the receiver tab as well, so people can use it to verify that their channel mapping is correct before they try it on real hardware. My idea was to have the 3D model in a separate window, and have buttons in the PID and receiver tabs to open that window.

**Comment by borisbstyle** [comment]
@mikeller 
I would also suggest to have receiver calibration there so everybody can set his endpoints correctly by just going though some kind of wizzard.
But Ok lets add it in there

**Comment by mikeller** [comment]
@borisbstyle 

> I would also suggest to have receiver calibration there so everybody can set his endpoints correctly by just going though some kind of wizzard.

Totally agree that the  RX - specific settings should be moved from the 'general config' to the receiver tab.

Not sure about the 'wizard' thing - I personally normally find wizards to be more annoying than useful, and prefer to have a simple list of settings that I can edit. But that's just me.

What I could see would be a 'check receiver settings' 'wizard', that would ask you to move your throttle to min and max, and then, based on the readings, would tell you if your settings look good, or give you hints like 'you should increase min_check'.

**Comment by antstorm** [comment]
@borisbstyle a bit like Taranis stick calibration? That could be interesting…

**Pull request merged**
