### PR TITLE
Fixed broken check for to migrate to version 1.3.1 (cleanflight).

### LINKED ISSUE #609: Restore migrates config to old version
I'm using Configurator 3.2.1 and backed up my config because i needed to to a full chip erase.
After the erase, i wanted to restore my configuration - which did pretty much nothing.

I noticed this in the log:
```
2017-08-12 @ 19:49:29 -- Migrating configuration file generated by configurator: 3.2.1
2017-08-12 @ 19:49:29 -- Migrated configuration to configurator: 1.3.1
2017-08-12 @ 19:49:29 -- Configuration migration complete, migrations applied: 2
```

I'm not sure why Configurator 3.2.1 would want to migrate a config from Configurator 3.2.1 down to a config for Configurator 1.3.1?

Even if it's just a typo: it doesn't work! =(

### PR DESCRIPTION
**Pull request by mikeller**
Fixes #609.

### CODE REVIEW

**Comment by mikeller** [comment]
Since the version you are using (3.2.1.) was released on 07/08, and this fix was made on 01/09, how do you expect it to be fixed in your version?

You'll have to wait for the next release of the configurator, or download it from GitHub and install locally.

**Comment by MagicHand1968** [comment]
Hi Mikeller, Thank you for the information. I will dowload from GitHub the new version. Btw when will come the new release?

**Comment by mikeller** [comment]
I don't know, @borisbstyle does the releases.

**Comment by MagicHand1968** [comment]
Hi Mikeller, 

I tested Setup/restore function of the 3.2.2 version localy on my laptop.
(downloaded from github)
2017-10-15 20_05_29-betaflight - configurator

I got the following prottocol:
2017-10-15 @ 19:59:12 -- Migrating configuration file generated by configurator: 3.2.1
2017-10-15 @ 19:59:12 -- Configuration migration complete, migrations applied: 1

BUT then nothing is changed on the configuration. :-( 
Should this already working in the new version. Or I'm wrong?
Do you have any idea, what should I do to restore my original configuration?

Best Regards: G.

**Comment by mikeller** [comment]
@MagicHand1968:

> BUT then nothing is changed on the configuration.

What exactly do you mean by this? The actual migration of previous configurations is only supported for older versions of cleanflight. The Backup / Restore buttons do just that, but do not support a migration of the configuration between different versions of Betaflight or of the configurator.

**Comment by MagicHand1968** [comment]
Thank you for looking my comment.

> What exactly do you mean by this?

I have some working (previously with backup stored) Betaflight configuration files. All have the version 3.2.1. (I put 2 example JSON files renamed as TXT 
[BTFL_backup_X220S-01_20170928_141612_fly.txt](https://github.com/betaflight/betaflight-configurator/files/1385792/BTFL_backup_X220S-01_20170928_141612_fly.txt)
[btfl_backup_dezx_20170903_081634_ORIG.txt](https://github.com/betaflight/betaflight-configurator/files/1385793/btfl_backup_dezx_20170903_081634_ORIG.txt)
into this comment as attachment)  

Unfortunatelly I cant't load them with the "Restore" button, because nothing is changing in the configaration. E.g. the "Modes" Tab remains empty.

Thank you and Best regards: G.

**Comment by mikeller** [comment]
@MagicHand1968: Ok, will look into this. For now, use the CLI backup / restore for backups.

**Comment by KF-M** [comment]
Is there a fix for this.  Trying to follow these threads just end up with "it still is not working".

The ability to restore a configuration is the most basic requirement for a firmware loader.  Can you start a new clean thread that clearly states if this is fixed or not.

And if not, is there a clear work around to the problem. 

And if not - a WARNING not to use and depend on this feature.

**Comment by KF-M** [comment]
I am using the same BF version and simply trying to RESTORE a BACKUP configuration.

It does nothing.

**Pull request merged**
