### PR TITLE
[Chore] apply lexical scoping to stm32usbdfu

### PR DESCRIPTION
**Pull request by haslinghuis**

### CODE REVIEW

**Comment by haslinghuis** [comment]
16 sonar issue to go :)

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by McGiverGim — APPROVED** [review]

**Comment by haslinghuis** [comment]
Rebased.

**Comment by nerdCopter** [comment]
`6957f334` - flashed FOXEERF405, PYRDRONEF7, SKYSTARSF405AIO without issue.

**Review by nerdCopter — APPROVED** [review]

**Pull request merged**
