### PR TITLE
Added expert mode. Moved FAILSAFE feature back into failsafe tab.

### PR DESCRIPTION
**Pull request by mikeller**
Also, some cleanup.

### CODE REVIEW

**Comment by TheAngularity** [comment]
@mikeller 
the expert mode is super resolved ... but with failsafe I remember ... imho i think it should stay in normal mode.

**Comment by mikeller** [comment]
No. Not exposing failsafe to newbie users is part of the intention of expert mode. The default settings for failsafe are the safest option. They should only be changed by experienced users.

**Comment by TheAngularity** [comment]
oh right ... was ever discussed here #142 ... my mistake ;)

**Comment by mikeller** [comment]
Fixes #143.

**Pull request merged**
