### PR TITLE
Added support for the FrSky FPort protocol.

### PR DESCRIPTION
**Pull request by mikeller**

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
@mikeller sorry, I messed it up! I thought I was on the script project. Not sure what to do now.

**Comment by mikeller** [comment]
Hehe, no sweat, this was slated to be merged anyway - I just leave my pull requests open for 24 hours or so to give others a chance to review and comment.

**Comment by basdelfos** [comment]
What is FrSky FPort protocol?

2017-11-15 1:12 GMT+01:00 Michael Keller <notifications@github.com>:

**Comment by raphaelcoeffic** [comment]
@basdelfos Top secret hot stuff :-D

**Comment by basdelfos** [comment]
I thought so, even Google doesn't give any hits. So, it must be top secret
NASA style stuff...

2017-11-15 9:15 GMT+01:00 Raphael Coeffic <notifications@github.com>:

**Comment by raphaelcoeffic** [comment]
@basdelfos at least! Well, joke aside, looking at the discussion on slack/members should give you all the details.

**Comment by basdelfos** [comment]
Yeah, I already saw the PR in the firmware. Looks promising, share one UART
with SBus and S.Port.

2017-11-15 9:55 GMT+01:00 Raphael Coeffic <notifications@github.com>:

**Pull request merged**
