### PR TITLE
[BUGFIX] Fix sliders disable input

### PR DESCRIPTION
**Pull request by haslinghuis**
Fix for filter slider input selector

@Asizon did notice sliders could be moved after being disabled. There was something wrong with the selectors.

### CODE REVIEW

**Comment by haslinghuis** [comment]
Keeps failing to get NW.JS here, that's why build is failing 😖

**Review by limonspb — APPROVED** [review]

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by ctzsnooze — APPROVED** [review]

**Comment by ctzsnooze** [comment]
Nice.  Fixes the problem on testing - Mac OSX / 4.3

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by Asizon — APPROVED** [review]
Thanks for the fix @haslinghuis  :)

**Pull request merged**
