### PR TITLE
Add vario units to the preview

### PR DESCRIPTION
**Pull request by McGiverGim**
To go with: https://github.com/betaflight/betaflight/pull/8419

Adds units to the vario OSD element:
image

### CODE REVIEW

**Comment by Jetrell** [comment]
@McGiverGim  I know it will be extra trouble for you to implement.... 
Have you seen the iNav `Vario Graph`? That uses up/down arrows, that add or reduce the number of arrows in the direction of change, as the decent or accent rate changes.
I use this feature. And it does catch your eye faster than the number values.
The new arrows 0x75 and 0x76 could be used for this. 

_Its just an idea if it didn't cross your mind. :-) But if not that's fine._

Although.... what I do suggest. Could you use 0x75 and 0x76 next to the vario value? Instead of 0x60 and 0x68. The reason being, is that these north and south arrows are 3D in Impact. and are more forward backward in orientation, and would not look right for this application.

**Comment by Jetrell** [comment]
@McGiverGim  With respect to using 0x75 and 0x76 instead of 0x60 and 0x68. 
I realize that you may want this PR to work with the V1 fonts... So I thought this might help.

Because 0x72 to 0x79 were not used in the V1 fonts.
 I relocated 0x75 and 0x77 in the V1 fonts. So their small arrows (Up/Down/Left/Right) line up with the small arrows in the V2 refactoring. 


Original V1 small arrow location
Original V1 small arrow location

Relocated V1 small arrows, to suit V2 refactoring
V1 small arrow change to suit V2 locations

V2 small arrow location
V2 small arrow location



[All V1 fonts(Up & Right small arrow relocated to suit V2 small arrow location).zip](https://github.com/betaflight/betaflight-configurator/files/3283692/All.V1.fonts.Up.Right.small.arrow.relocated.to.suit.V2.small.arrow.location.zip)

**Comment by McGiverGim** [comment]
@Jetrell my idea was to change the arrows in another PR because when I made this PR the new refactor of V2 fonts have not been merged.
It does not affect to the V1 fonts because my change is for Betaflight 4.1 and this will use only V2 fonts (only affects the preview in the Configurator).
About the iNav vario, if I'm not wrong it uses 5 vertical positions in the screen, and it needs more symbols, it merges the simple arrow with other with a double arrow to give the sensation of movement:
image
image
We will need to divide the vario into two: one for the numeric and other for the arrows (some people will not like it because is too much space 5 vertical symbols) and give the possibility of only one symbol like now to the user. At this moment I don't think it is interesting enough.

**Comment by Docteh** [comment]
Mockup of what it'd look like using 0x75 and 0x76 instead of SYM_ARROW_NORTH
image image

**Comment by Jetrell** [comment]
@McGiverGim  No problems :-) I understand what you have in mind. And understand the Vario Graph as well. It was just an idea :-)

What do you think of using 0x75 and 0x76 instead of 0x60 and 0x68 from the post #2 ?
As @Docteh gave the example of ?

**Comment by McGiverGim** [comment]
As I said, I will change them later in another PR because we need to merge this first: https://github.com/betaflight/betaflight-configurator/pull/1477 until this is merged, the little arrows are in positions 0x72 and 0x76 and I don't want to change it twice.

**Comment by McGiverGim** [comment]
Now that the refactor of fonts have been merged, I have rebased this PR and added a commit to change the arrow by the small one. I added the V1 fonts from @Jetrell with the reordered small arrows to not have to add an exception in the `osd.js` code.

**Comment by Docteh** [comment]
Why are certain ASCII characters getting reverted in the v1 fonts?

0x22 "
0x23 # <-- `My #2 quad` 
0x3F ? <-- betaflight 4.0.x VTX element actually uses this character, not spaces when the vtx status is unknown.

**Comment by Docteh** [comment]
This PR:
betaflight mcm

Current:
betaflight mcm


On the second row it looks like other symbols from #1392 got reverted, but that is fine. 

Third row matters more to me ;)

**Comment by McGiverGim** [comment]
Good catch! @Jetrell can you look at it?

**Comment by Jetrell** [comment]
@McGiverGim Sorry for the mix up..... From my conversation with you in Font Refactoring PR. I got the impression that the V1 fonts was for Pre 4.0.
And due to Pre BF 4.0 not having the firmware for the new symbols. I figured that they would not be needed. So I didn't add them. I only reverted Impact fonts, back to that standard.

@Docteh So... for me to get this right, before I updated it. You require them, because you intend to make custom firmware for your F3 gear... or something like that? :-)
That's completely understandable.

**Comment by Jetrell** [comment]
@McGiverGim Here are the fixes. They are the same as the first ones. Except the 4 small arrows are aligned with the V2 font. Plus a little cleaning like the latest V2.

I'll delete the files in post #3. That I assume were the original V4.0

Sorry for the misunderstanding guys.

fix

[V1 fix.zip](https://github.com/betaflight/betaflight-configurator/files/3288788/V1.fix.zip)

**Comment by Docteh** [comment]
@Jetrell That is aiming to be a V1 font?

0x26 and 0x27 are the crosshair with the V1 fonts

In that picture 0x7B and 0x7D look likes like the crosshair sides.
0x7B gets copied to 0x26 
0x7D gets copied to 0x27

**Comment by Jetrell** [comment]
@Docteh Then I can just leave 0x7b and 0x7d empty?

**Comment by Docteh** [comment]
@Jetrell Yup

**Comment by Jetrell** [comment]
Here they are. Sorry for the confusion.

new v1


[V1 fix.zip](https://github.com/betaflight/betaflight-configurator/files/3288983/V1.fix.zip)

**Comment by McGiverGim** [comment]
@Jetrell The idea with V1 fonts is that the symbols used in Betaflight 4.0 must remain like they were for Betaflight 4.0. Symbols NOT used can change/move, and can be positioned as in Betaflight 4.1. In this way the preview in the Configurator is easy to maintain.

When the new Configurator will be released, people will use it for:
- Flash Betaflight 4.1. They will use the V2 fonts, and the symbols must be in the positions that Betaflight 4.1 use (after all the refactors). 
- Flash Betaflight 4.0 or earlier (if they want or they have an F3). They will use V1 fonts, and the symbols must be in the positions that Betaflight 4.0 use (the old fonts before versioning).

We can play a little with unused symbols but we must pay attention to the used ones. We have some time until the release to fix any possible problem.

**Comment by McGiverGim** [comment]
Pushed the new fonts ;-)

**Comment by Jetrell** [comment]
@McGiverGim  Okay..... I just assumed that you wanted Impact fonts at the same level as the original release resource files that I got from the BF 4.0 configurator. Which is what I base yesterdays V1 font merge, on.

But I didn't know to what level, I should keep any additions we had made after 4.0. that did not interfere with with the original 4.0 and previous released firmware.

Thanks for the reply

**Comment by Docteh** [comment]
Lol that last preview from 'Max7456 Glyph Editor' has a blank 0x3F somehow. 
The files inside the .zip are perfect though. 👍 

betaflight mcm

**Comment by McGiverGim** [comment]
@Jetrell If we can't maintain them at the same level, I can add exceptions to the Configurator OSD preview code, but if we can, it will help with:
- Simplify the code in the Configurator.
- More ASCII symbols that can be used in the V1-Betaflight 4.0 (for the pilot name for example).

@Docteh the program is wrong or my pushed files are wrong ;) ?

**Comment by Docteh** [comment]
@McGiverGim the screenshot that @Jetrell posted is wrong, the files are good.

End of 4th row, nice question mark.
impact2 mcm

**Pull request merged**
