### PR TITLE
Remove custom defaults

### PR DESCRIPTION
**Pull request by haslinghuis**
Do not process Custom Defaults for API 1.46

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by limonspb — APPROVED** [review]

**Comment by haslinghuis** [comment]
@blckmn should we make this API 1.45?

**Review by blckmn — APPROVED** [review]

**Comment by nerdCopter** [comment]
what is the expected behavior for firmware master @ MSP 1.45?
i.e. firmware master at 1.45 still allows apply custom defaults which breaks serial. (TMOTORF7) -- does firmware master need to be bumped at this time, or not yet?

**Comment by haslinghuis** [comment]
This PR applies only to API >= 1.46 (firmware 4.5)

**Review by nerdCopter — APPROVED** [review]

**Pull request merged**
