### PR TITLE
Added a vendor/product id for Arduino Portenta

### PR DESCRIPTION
**Pull request by peetj**
In order for Betaflight Configurator to recognise the Arduino Portenta board, I had to update the vid/pid numbers in usbDevices object in port_handler.js

### CODE REVIEW

**Comment by McGiverGim** [comment]
Hi @peetj !! What is the objective of this? Is there some Betaflight target that supports this board?

**Comment by peetj** [comment]
> Hi @peetj !! What is the objective of this? Is there some Betaflight target that supports this board?

Yep or rather that's the idea. We are working with Arduino to build a drone based on the Arduino Portenta H7 which means building a target to support the board. This work has started but is in the early stages. Did I do something wrong?

**Comment by McGiverGim** [comment]
No, it's ok. But I doubt this PR will be accepted until the firmware part is accepted. 
I suppose we can let this open until then, maybe someone want to test it if you have some beta code available somewhere.

**Comment by mikeller** [comment]
As @McGiverGim says, adding this to configurator at this point in time does not make much sense - all it will allow users to do is to use configurator to overwrite the pre-existing firmware on their board, including DFU-emulation itself.

Do you have a link to the firmware source code for the DFU emulation that this is meant to work with?

**Comment by peetj** [comment]
> As @McGiverGim says, adding this to configurator at this point in time does not make much sense - all it will allow users to do is to use configurator to overwrite the pre-existing firmware on their board, including DFU-emulation itself.
> 
> Do you have a link to the firmware source code for the DFU emulation that this is meant to work with?

Not yet - I guess I jumped the gun on this one - sorry! We hope to have the target up and running at some point soonish. Feel free to reject the request and I'll make it again when the target exists in the firmware.

Cheers
Pete...

**Comment by mikeller** [comment]
We can leave this open for now and wait for the changes to support this board in the firmware.

**Pull request closed without merging**
