### PR TITLE
Add labels for the axis of the graphs

### LINKED ISSUE #2166: Axes labels
Hello!
Add labels for the axis of the graphs (throttle curve preview etc.) so that it is clear what value each axis displays, pls!

Very Best Regards,
Konstantin V. Suvorov

### PR DESCRIPTION
**Pull request by haslinghuis**
Fixes #2166

### CODE REVIEW

**Review by mikeller — APPROVED** [review]

**Comment by mikeller** [comment]
Looks nice!

**Comment by Asizon** [comment]
yes!sorry for late reply and test it, seems that its broken with darkmode, also the style is not so good comparing with Sensor tab :)

image

**Comment by Asizon** [comment]
@haslinghuis it also need some work to allow good Android style:

image

image

**Comment by haslinghuis** [comment]
@asizon css is not my thing if you can improve it please

**Pull request merged**
