### PR TITLE
Remove experimental backup and restore

### PR DESCRIPTION
**Pull request by haslinghuis**
As discussed on Discord removing expermental backup and restore as it was only used for virtual connection and not being maintained for the last few years.

Also bumping minimal supported version for configurator 11.0 to firmware 4.3

### CODE REVIEW

**Comment by McGiverGim** [comment]
If we are removing it totally, I suppose now we don't have a way to "define" the values for the virtual connection. So it will always have what we have now defined at some place. 
I understand that it's outdated, but I'm thinking if there's an easy way to let the user "populate" the virtual FC. Maybe simply have a "save" and "load" of the FC object in JSON format? This will work?

**Comment by haslinghuis** [comment]
At the moment we only can restore a JSON object on the virtualFC object. As we have no way to save a JSON object for some years now, how would a user create a JSON file to restore from?

**Comment by McGiverGim** [comment]
I think maybe we can dump the complete FC object when in virtual mode, edit it by hand and load it again. 
It's not perfect, and is manual, but if works, can be enough at this moment. It's only one idea.

**Comment by nerdCopter** [comment]
i feel that the msp removals should be part of #4008 , not here.

**Review by nerdCopter — APPROVED** [review]

**Review by McGiverGim — APPROVED** [review]

**Pull request merged**
