### PR TITLE
Updated package-lock.json

### PR DESCRIPTION
**Pull request by AndersHoglund**
Updated package-lock.json. Funny thing is it needed to be re-genereted twice, as if there are some circular package dependencies. Did not squash those two, keeping those two separate commits visible.

### CODE REVIEW

**Comment by mikeller** [comment]
Interesting (and annoying): When building with this `package-lock.json` after removing `node_modules/`, `package-lock.json` is changed yet again:

```
mikeller@pc:~/git/betaflight-configurator$ git diff
diff --git a/package-lock.json b/package-lock.json
index b5cba421..9515d5b7 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -5246,9 +5246,9 @@
       }
     },
     "stringstream": {
-      "version": "0.0.5",
-      "resolved": "https://registry.npmjs.org/stringstream/-/stringstream-0.0.5.tgz",
-      "integrity": "sha1-TkhM1N5aC7vuGORjB3EKioFiGHg=",
+      "version": "0.0.6",
+      "resolved": "https://registry.npmjs.org/stringstream/-/stringstream-0.0.6.tgz",
+      "integrity": "sha512-87GEBAkegbBcweToUrdzf3eLhWNg06FJTebl4BVJz/JgWy8CvEr9dRtX5qWphiynMSQlxxi+QqN0z5T32SLlhA==",
       "dev": true
     },
     "strip-ansi": {
```

What operating system and node / npm versions did you use? Mine are ubuntu 18.04, v9.11.1, 6.0.0.

**Comment by AndersHoglund** [comment]
Was done on Ubuntu 16.04LTS
$ uname -a
Linux pucko 4.4.0-124-generic #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mikeller** [comment]
@AndersHoglund: Can you try updating `npm` to 6.0.0 and see ifi this results in a different `package-lock.json`? I think they changed the dependency handling yet again after 5.6.0.

**Comment by AndersHoglund** [comment]
OK, updated `npm` and now it behaves differently. No more is package-lock.json updated, unless it is first removed and a recreation is forced. But then it is only a minor diff, not the huge total diff seen earlier. Same diff as @mikeller saw:
```
$ npm --version
6.0.1
$ git diff
diff --git a/package-lock.json b/package-lock.json
index b5cba42..9515d5b 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -5246,9 +5246,9 @@
       }
     },
     "stringstream": {
-      "version": "0.0.5",
-      "resolved": "https://registry.npmjs.org/stringstream/-/stringstream-0.0.5.tgz",
-      "integrity": "sha1-TkhM1N5aC7vuGORjB3EKioFiGHg=",
+      "version": "0.0.6",
+      "resolved": "https://registry.npmjs.org/stringstream/-/stringstream-0.0.6.tgz",
+      "integrity": "sha512-87GEBAkegbBcweToUrdzf3eLhWNg06FJTebl4BVJz/JgWy8CvEr9dRtX5qWphiynMSQlxxi+QqN0z5T32SLlhA==",
       "dev": true
     },
     "strip-ansi": {
```

I will update npm on all Jenkins executors and restart the CI jobs and see what happens....

**Comment by McGiverGim** [comment]
It seems that now we are going to use as "official" the latest `npm` version available: https://github.com/betaflight/betaflight-configurator/pull/1027

So maybe we must add this info somewhere, I suppose that in the `readme` that is where we have some kind of "instructions".
> npm i -g npm@latest

**Comment by AndersHoglund** [comment]
BFC now builds OK with `npm 6.0.1` on Jenkins without touching `package-lock.json` : http://andwho.sytes.net:8080/job/BorisB_BetaFlight_Configurator/197/
Same with log-viewer: http://andwho.sytes.net:8080/job/Borisb_Blackbox_Log_Viewer/57/
and BlHeli-Configurator:  http://andwho.sytes.net:8080/job/DieHertz_BlHeli_Configurator/7/
and blackboxtools: http://andwho.sytes.net:8080/job/Borisb_Blackbox_Tools/7/
Closing this PR.

**Comment by mikeller** [comment]
I am really torn on this re using 'latest'. But npm has had issues so many times, and updates to fix these, so I feel that fixing ourselves onto a static version is not a good idea at the moment.

If and when npm has a stable version that proves to be free of problems I am all for switching to using this version, and changing the travis builds to use it.

**Pull request closed without merging**
