### PR TITLE
Update min value for antigravity gain

### PR DESCRIPTION
**Pull request by Asizon**
To go with https://github.com/betaflight/betaflight/pull/10291

### CODE REVIEW

**Review by McGiverGim — APPROVED** [review]
Is good.
The backward compatibility is a nightmare. For a simple field of one feature we have a lot of conditionals.
Maybe in a future we can have all of this inside a Vue component, that only needs the version and the value as input.

**Comment by Asizon** [comment]
Yes @McGiverGim is really a nightmaree, we will see how the vue progresses and our adaptation knowledge, surely we can improve everything.

**Comment by Asizon** [comment]
Im thinking in rename constant to ACCELERATOR_GAIN_OFF, what do you think @McGiverGim?

**Comment by McGiverGim** [comment]
True. Maybe ITERM_ACCELERATOR_GAIN_OFF. A little large but very clear.

**Review by mikeller — DISMISSED** [review]

**Comment by mikeller** [comment]
@McGiverGim:

> The backward compatibility is a nightmare. For a simple field of one feature we have a lot of conditionals.
Maybe in a future we can have all of this inside a Vue component, that only needs the version and the value as input.

Yes, backwards compatibility is a nightmare - this applies to all projects, not just this.
Not sure if pushing these version dependencies into UI componentry is a good approach - my gut feeling tells me that this will just increase the required effort for maintenance, and proneness for bugs, as the relevant code will be spread over even more files.
For things like min / max values as in this pull request, I think moving to a self-updating data structure that contained min / max values and potentially other metadata for all configuration values, and using a centralised facility to manage the version dependencies in one place could be a better approach.
If we manage to ever get a parameter group based protocol off the block, then this could even be solved in the way of having specific commands to read all of the min values / all of the max values for a given parameter group from the firmware, and avoid having to store this information in configurator as well.

**Comment by McGiverGim** [comment]
The problem is not only max and min, we need too a "good default" for when a user enables a disabled feature, if is visible or not, etc. depending on the version.

I think we will need to see when we arrive to it. But it will depend a lot of the granularity of the components we are going to use. Only some very generic or a lot of them very specialized that extend the generic ones.

**Review by McGiverGim — APPROVED** [review]

**Review by mikeller — APPROVED** [review]

**Comment by mikeller** [comment]
@McGiverGim: Yeah, good point about defaults. But this is also some form of metadata that could be supplied for every parameter by the firmware - the reality is that we are already storing these defaults  in the firmware, just as we are storing the min / max values.

**Pull request merged**
