### PR TITLE
Small patch

### PR DESCRIPTION
**Pull request by haslinghuis**
Fixes selector (which also wrongly did target Rates Roll Center and Expo) and refactored `condition` variable to something meaningful as requested in previous PR.

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by haslinghuis** [comment]
Commit 2 was a rewrite from:
```
    const PID_DEFAULT = FC.getPidDefaults();
    const PIDS = Array.from({length: 3});
    for (let i = 0; i < 3; i++) {
         PIDS[i] = Array.from({length: 3});
    }

    for (let r = 0, needle = 0; r < 3; r++, needle += 5) {
        for (let c = 0; c < 3; c++) {
            const k = c + needle;
            PIDS[r][c] = PID_DEFAULT[k];
        }
    }
```

**Comment by ctzsnooze** [comment]
Changing the background colour of the PID numbers may have been a part of 4.2, but I think it is a bad idea.
It makes for very poor legibility in some situations...
Screen Shot 2021-10-05 at 13 42 51
Let's keep the numeric background the same; we have the warning box, and the colour behind the slider itself, that's enough.
Or at least, if we want to put them back, please make a separate PR to discuss that.
This PR should focus on bug-fixes arising from user feedback.

**Review by mikeller — APPROVED** [review]

**Review by ctzsnooze — APPROVED** [review]

**Comment by ctzsnooze** [comment]
Checked, tested.

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by limonspb — APPROVED** [review]

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> PASS
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by yngndrw** [comment]
> Changing the background colour of the PID numbers may have been a part of 4.2, but I think it is a bad idea. It makes for very poor legibility in some situations... Screen Shot 2021-10-05 at 13 42 51 Let's keep the numeric background the same; we have the warning box, and the colour behind the slider itself, that's enough. Or at least, if we want to put them back, please make a separate PR to discuss that. This PR should focus on bug-fixes arising from user feedback.

Only just seen this comment, but the slider heatmaps were added in this PR:
https://github.com/betaflight/betaflight-configurator/pull/1839
... and changes for dark mode were added in this PR:
https://github.com/betaflight/betaflight-configurator/pull/1843

The text used to be black which made the numbers far more legible.

**Pull request merged**
