### PR TITLE
Fixes clicking on helpicon affects input

### LINKED ISSUE #1635: 10.6.0 - Configuration Tab help icon failure
If i'm click on the help icon from `Motor direction is reversed` or `Bidirectional DShot` the corresponding feature is activated / deactivated. 
Further by clicking the help icon of `Motor Idle Throttle Value` and `Motor poles`, the input fields are activated.
Other help icons do not do this, which I think this is correct.

### PR DESCRIPTION
**Pull request by IvoFPV**
Fixes #1635
Clicking on helpicon in configuration and vtx tab would change the switch or select input field associated with that helpicon.
It seems like it was caused by helpicon being inside of a `<label>`

### CODE REVIEW

**Comment by IvoFPV** [comment]
Looking at this now, this fixes the helpicon probelm, but not if you click the label. It seems a lot of things are affected. I would get rid of the `<label for="">`. I think clicking on labels shouldn't change switches. For example in PID tuning tab. Clicking on the label of any I term relax, Dmin, Anti Gravity, will change the switch position. @McGiverGim Should I just remove the labels and have this not happen or was this intended to be like this?

**Comment by McGiverGim** [comment]
Sorry, I missed your second message. Yes, it's strange. At least to me clicking on the label must not change the switch.

**Comment by IvoFPV** [comment]
@McGiverGim Yeah, we should remove that, that way users can't misclick the label and change the switch, unlikely but better to avoid it if possible. @mikeller Any thoughts on this?
This could be something from the past versions, but you have also done this for the VTX tab so I guess it was intended to be like this.

**Comment by McGiverGim** [comment]
I did the VTX tab, but I did copy & paste and I didn't notice the problem ☹️

**Comment by IvoFPV** [comment]
I will go through all of them once again and remove them if that's okay.

**Comment by Docteh** [comment]
Clicking on labels is handy for tiny check boxes. Clicking on the helpicon shouldn't be changing anything though.

Motor Direction Is reversed on Configuration tab.

**Comment by mikeller** [comment]
@IvoFPV: I wasn't aware that using `<label for="">` results in the label being clickable. I think this is unintended in most cases, and should probably be removed. As @Docteh says, an exception would be cases where the control is very small, making it hard to click - but even then, if the users don't know about it they won't try clicking the label.

**Comment by IvoFPV** [comment]
@mikeller Label is used like that just for that reason so you can click the label and change the input it is related to. So this was definitely intended, probably in past versions and has stayed until now.
Not all of the smaller switches have clickable labels currently, therefore we should make everything the same. Big switches to not have clickable labels and small ones to have. Not sure if this is the best approach. I am more for all of them or neither of them.

**Comment by Docteh** [comment]
Knowing that clicking the label works comes from having poor aim. I like them.

The pid tuning tab looked a little dense. If you accidentally turn something off in there can you just turn it back on? Maybe those labels shouldn't toggle the check box?

**Comment by mikeller** [comment]
@IvoFPV: A lot of the html has been done by copy / pasting existing html, so the `<label for="">` pattern might have crept in from something where it was originally intended. I do not think that it serves much of a purpose now, so we should probably get rid of it.

**Comment by IvoFPV** [comment]
@mikeller I agree, we should remove them, but there seem to be users who prefer to have clickable labels like @Docteh and I see why they are useful. But again, some switches are not clickable and some are. This PR just takes care of helpicons which were inside `<label>` affecting switches.

One example where this is really bad: Motors tab arming enable notice which is long and affects the switch if you click on it. I know some people like to highlight things as they read them, so I see a potential problem with people activating the switch accidentally and possibly causing safety issues.

So you would remove them all then?

**Comment by mikeller** [comment]
@IvoFPV: I am not dead set on going either way. What I can see is that the way it is now in configurator is inconsistent, with some cases (like the motor tab) actually being a safety issue.
Most applications don't seem to be using clickable labels (or I just don't know as I never _try_ to click labels), so for me the most logical thing would be to remove them. The alternative would be to add them in a consistent way, except for places where this is a saftety issue. Not sure what is better.

**Comment by IvoFPV** [comment]
@mikeller I guess we could remove them for important switches like the motors tab one. It is better to have that specific switch only change when you actually click on it in any case, even if we decide to have all labels change switches to make it consistent.
Maybe I could post another poll on Slack and see if people even know about this or they use these labels as switches? Based on that feedback we could decide if it is worth keeping.

**Comment by IvoFPV** [comment]
Looking at the poll results all votes are for using a switch. In my opinion switch is big enough for the places where label is not clickable, configuration tab mostly. OSD warning and post stat elements are small switches but they have never had clickable labels so I guess we can keep it that way and remove the clickable labels from other big switches as well.

**Pull request merged**
