### PR TITLE
Add impact fonts and added some useful characters

### PR DESCRIPTION
**Pull request by McGiverGim**
As talked here: https://github.com/betaflight/betaflight-configurator/issues/1380

This PR adds two new fonts (Impact and Impact mini) and updates all the fonts changing some unused characters for others:

>0x89 - Latitude - was a "+" symbol
0x98 - Longitude - was the GYRO symbol
0x9d - Mile per hour - was the "RT" in rth symbol
0x9e - kilometers per hour - was the "TH" in rth symbol
0x7a - Temperature
0x7f - Altitude - was a dotted vertical line
0x5e - RPM - was a thick UP arrow
0x21 - " ! " - was the "100" symbol either side of "FS" in failsafe

Impact font:
image

Impact mini font:
image

Sample of the new font with all the new characters:
image

EDIT: I forgot to thank the user @Jetrell, the author of this new fonts.

### CODE REVIEW

**Comment by Docteh** [comment]
👍TH% is a lot easier to read than some of the prop spinning symbols. 

image
 @McGiverGim I'd like to draw some question marks, should I wait until this is merged, and then make my own pull request? Or something else? (I'm still new to git and github)

**Comment by McGiverGim** [comment]
Yes, it's better to wait. The MCM files can't be merged, only replaced, so we can't have two PR modifying them.

**Comment by Jetrell** [comment]
@Docteh  _TH% is a lot easier to read than some of the prop spinning symbols._

 With all respect Kyle, Understand what you mean about the throttle symbol. But this is what makes all the fonts individual and some what unique. It may also be what the author of that font wanted. What we like....someone else may not like.
 If we were to go through over time, and change each one to our liking. We would end up with all the fonts looking the same ;-)

**Comment by Docteh** [comment]
@Jetrell my intent was to both point it out, just so nobody is caught unaware that it is different but not actually complain about it. 

I didn't like the throttle symbols in vision, so I drew this for my own personal use: 0x040x05

The S in `vision.mcm` is taken from default. Would it be better to use TH%, or the one used in betaflight,bold,clarity? Over on iNav the `vision` font has its own throttle symbols, when it was imported to betaflight its throttle symbol was changed.

**Comment by atomgomba** [comment]
Would it be possible to add a blackbox symbol? Though I can imagine how much of a challenge it could be to make it look like smth that's easy to interpret.

**Comment by Jetrell** [comment]
@atomgomba  How about something like these? 
I get the impression from @mikeller That he doesn't mind what symbols are added. Just as long as they are used with the next release. Not just added and forgotten about. Which makes sense.
 
BB log 1
BB log 2

**Comment by atomgomba** [comment]
Oh, I can easily recognize what those are meant to be and having the extra benefit of showing the device type is awesome, @Jetrell! I like those!

**Comment by McGiverGim** [comment]
I think is better go by parts. Try to merge first this PR, and then try to add some new symbols in new PR. If not, we can start a discussion that if better to have only one for blackbox, or two, etc.
The fonts are a sensible theme, we don't have ways to control version, etc. so better go step by step. I like the idea of blackbox, but better wait until this merged :)

**Comment by Jetrell** [comment]
@McGiverGim  It totally agree 

@atomgomba  In the mean time, if anyone has symbol idea's. Like you had with the BB. Just mention them, and i'll draw them up and post the screen shoot, to see if people like it.

Then once this gets merged, as @McGiverGim said. We maybe able to add the accumulation of symbol idea's after that.

**Comment by mikeller** [comment]
@McGiverGim: Not entirely sure about the replacement of the 0x5E character - this is within the range where most symbols are the ASCII characters (0x20 to 0x5F). Do we have any unused characters available outside of this range? If so I think 0x5E should be replaced with a caret (`^`).

**Comment by Docteh** [comment]
Out of a set, we're only using 0x13. 

image

image

**Comment by McGiverGim** [comment]
True, I didn't notice that we only used one of them. @mikeller will be ok if we replace symbols from here?

**Comment by Docteh** [comment]
I just noticed a small error with the new fonts, 0x2A is a copy of 0x7E (crosshair center), 0x2A is the asterisk character.

**Comment by mikeller** [comment]
@McGiverGim: I can't see us implement the moving graduation marks that 0x10 to 0x15 were used for any time soon, so I think these can indeed be replaced.

@Docteh: Well spotted - in my opinion we should replace the (mostly unused) special characters in 0x22 to 0x2a with their ASCII symbols - we can reclaim the braces in 0x7b to 0x7d for the artificial horizon parts.

**Comment by Jetrell** [comment]
@mikeller 
0x22 to 0x2a, except for 0x24 are ASCII symbols. AHI crosshair parts are moved to 0x7b and 0x7d.
While 0x10, 0x11, 0x12, 0x14 and 0x15 are new. 
Black box log, Home distance, telemetry RPM, Roll and Pitch degrees.

If this is okay. I can do the same to the other fonts?

Capture

**Comment by Docteh** [comment]
Is anyone likely to use a PIPE character? looks like we're very close to having the center marker in contiguous order. Any objections to putting the center marker in like `0x10 0x11 0x12`?

Please don't forget about question marks: image image image

0x24 is a dollar sign. eg 0x24-extra_large

image

**Comment by Jetrell** [comment]
> 
> 
> Is anyone likely to use a PIPE character? looks like we're very close to having the center marker in contiguous order. Any objections to putting the center marker in like `0x10 0x11 0x12`?
> 
@Docteh  I only places 0x23, 0x25, 0x26 and 0x27 in contiguous order, to fill in the blanks. Because that was the general layout. 
I'm not sure what @mikeller has in mind for specific ASCII characters.

**Comment by Jetrell** [comment]
_Is anyone likely to use a PIPE character? looks like we're very close to having the center marker in contiguous order. Any objections to putting the center marker in like 0x10 0x11 0x12?_


@Docteh I only places 0x23, 0x25, 0x26 and 0x27 in contiguous order, to fill in the blanks. Because that was the general layout that @mikeller asked for.
I'm not sure if @mikeller has other ASCII characters in mind to replace them with?

**Comment by Docteh** [comment]
@Jetrell if we get 0x24 and 0x3F taken care of, we'll have the range of 0x20-0x5F matching ASCII. 

This is from mikeller earlier in this current PR discussion : 
> @McGiverGim: Not entirely sure about the replacement of the 0x5E character - this is within the range where most symbols are the ASCII characters (0x20 to 0x5F). Do we have any unused characters available outside of this range? If so I think 0x5E should be replaced with a caret (`^`).

I don't want to break any ASCII characters, but I would like to ask for all the symbols to be shuffled around as much as people are willing to do, so that things are easier to handle in future. Right now if someone wants to make custom crosshair they have to find out the different characters. If they were sequential that Glyph editor might let you edit more than one character at a time.

**Comment by Jetrell** [comment]
> 
> I don't want to break any ASCII characters, but I would like to ask for all the symbols to be shuffled around as much as people are willing to do, so that things are easier to handle in future. Right now if someone wants to make custom crosshair they have to find out the different characters. If they were sequential that Glyph editor might let you edit more than one character at a time.

@Docteh I agree.  But Mike wrote this to you...

_@Docteh: Well spotted - in my opinion we should replace the (mostly unused) special characters in 0x22 to 0x2a with **their** ASCII symbols - we can reclaim the braces in 0x7b to 0x7d for the artificial horizon parts._

He is the one that will approve this. So until he tells us his reasoning...Then I know as little as you do.

**Comment by Jetrell** [comment]
> 
> I don't want to break any ASCII characters, but I would like to ask for all the symbols to be shuffled around as much as people are willing to do, so that things are easier to handle in future. Right now if someone wants to make custom crosshair they have to find out the different characters. If they were sequential that Glyph editor might let you edit more than one character at a time.

@Docteh I agree.  But Mike wrote this to you...

_@Docteh: Well spotted - in my opinion we should replace the (mostly unused) special characters in 0x22 to 0x2a with **their** ASCII symbols - we can reclaim the braces in 0x7b to 0x7d for the artificial horizon parts._

He is the one that will approve this. So until he tells us his reasoning...Then I know as little as you do, about this matter.

**Comment by Docteh** [comment]
I must be missing something obvious... This is what I'm looking at. 

image

**Comment by mikeller** [comment]
@Jetrell, @Docteh: It would have been nice if we could have reserved the entire range 0x20 to 0x5f for ASCII characters, but seeing that we seem to be one special character short in the 0x01 to 0x1f and 0x60 to 0x9f range I think we can live with replacing `$` with 'max'.

**Comment by Docteh** [comment]
@mikeller  We've had 'MAX' in 0x24 since the beginning, its not part of this PR. 

2016's https://github.com/betaflight/betaflight-configurator/commit/f3bfb085f8dd798a41f4de05679f720511781cfc added this:

https://github.com/betaflight/betaflight-configurator/raw/f3bfb085f8dd798a41f4de05679f720511781cfc/resources/osd/default.mcm

image

**Comment by Docteh** [comment]
Can I have a question mark? 

https://github.com/betaflight/betaflight/blob/45daf97f2ba4ad45ff14cfbee678193d055c989e/src/main/osd/osd_elements.c#L1017-L1029

https://github.com/betaflight/betaflight/blob/42d54a94e96200d6ae70e968f50da0161189c78a/src/main/drivers/vtx_common.c#L138-L145

**Comment by mikeller** [comment]
@Docteh: I thought part of this pull request was a discussion of rearranging elements?

**Comment by Docteh** [comment]
@mikeller I reread the thread, I missed @Jetrell stating that we could try and use the MAX character in two separate instances. My apologies.

**Comment by Jetrell** [comment]
@Docteh Can I ask you a question from a constructive point of view.
Can you think of any truly useful condition, when a `?` would be used on a flight controller OSD? And is it worth including it at the expense of another special descriptive character that can be put into use now with the present code. _e.g. Speed, Altitude, Temperature, Lat, Lon, RPM, Home location, Log Capacity, Pitch/Roll angle_
That was my reasoning behind, also not include the `$` symbol, over the MAX symbol.

 I realize the need for ASCII characters. But some ASCII characters are just totally irrelevant to a flight controller OSD, and would be more suited to a word processor or cash register ;-)

**Comment by mikeller** [comment]
@Jetrell:

> Can you think of any truly useful condition, when a `?` would be used on a flight controller OSD?

Yes I can - any kind of dialog can use it for a universally understood symbol to indicate a question. Also, it can be used as a universal placeholder to indicate 'unknown value'.

But besides that there are other symbols like `$` that are probably of little value for what we are doing, and can be replaced with other things. I am probably just too idealistic when I am proposing to support a consecutive range of ASCII characters, and we do not have enough characters available to support all of the special characters that we need, and do this.

**Comment by Jetrell** [comment]
@mikeller 
If you see the true need for it Mike.  Then I can place it in 0x3f....its is empty.

**Comment by Jetrell** [comment]
Here are the changes @mikeller  with the .mcm

BetaFlight
BetaFlight
Bold
Bold
Clarity
Clarity
Default
Default
Digital
Digital
Extra Large
Extra Large
Impact
Impact
Impact_Mini
Impact_mini
Large
Large
Vision
Vision
[Mod fonts.zip](https://github.com/betaflight/betaflight-configurator/files/3130086/Mod.fonts.zip)

@Docteh notice Visions throttle...Shhhh...don't tell anyone ;-)

**Comment by McGiverGim** [comment]
Updated the PR with the latest version attached by @Jetrell. Thanks! I can't wait to see this merged... ;)

**Comment by mikeller** [comment]
Looking good. Thanks for the effort, guys!

Should we wait with mergeing until we have updated `src/main/drivers/max7456_symbols.h` to match the changed mapping?

**Comment by McGiverGim** [comment]
I think is better, yes. But at this moment I don't have time to make the PR to the firmware part, I'm very occupied with the Blackbox ;-)
If nobody does it, maybe the next week, I can get some time...

**Comment by mikeller** [comment]
@McGiverGim: I don't quite understand your last statement. What do you mean by 'prefix'?

**Comment by Jetrell** [comment]
> _EDIT: I comment this because is not only modify the symbols file, I think we need to revisit some of the osd elements (now we have prefix for some of them that before haven't)._

Thank you @McGiverGim  I'd like to help with this part. But I'm not capable at your level.

> 
> @McGiverGim: I don't quite understand your last statement. What do you mean by 'prefix'?

@mikeller I think he means prefix in the terms of....A descriptive character that can now be placed before the information on the OSD.  
e.g. Distance has Meters as a suffix a present. Now it with have a descriptive character prefix  
 before the value.

**Comment by Jetrell** [comment]
> _EDIT: I comment this because is not only modify the symbols file, I think we need to revisit some of the osd elements (now we have prefix for some of them that before haven't)._

Thank you @McGiverGim  I'd like to help with this part. But I'm not capable at your level.

> 
> @McGiverGim: I don't quite understand your last statement. What do you mean by 'prefix'?

@mikeller I think he means prefix in the terms of....A descriptive character that can now be placed before the information on the OSD.  

Thank you for approving these fonts and new symbols Michael.

**Comment by McGiverGim** [comment]
> @mikeller I think he means prefix in the terms of....A descriptive character that can now be placed before the information on the OSD.

Exactly. And we will need to adjust the preview in the Configurator too.

**Comment by mikeller** [comment]
@McGiverGim: Yes, true.

**Comment by McGiverGim** [comment]
First preview adjustment done here: https://github.com/betaflight/betaflight-configurator/pull/1413

**Comment by McGiverGim** [comment]
@Jetrell only to let her my opinion. I'm using the impact font and I like it. Good work. Only strange is that the arrows in 3D (with shadow) have a different look than the rest of symbols. I don't know if it is intentional or not.
I miss a speed symbol too to add before the speed.

**Comment by Jetrell** [comment]
@McGiverGim I went for the 3D shadowed look of the home arrow. To make it look like its pointing forward. And not just up and down on a 2D screen.
I wasn't easy to get that look. 
I did mess around with it and got half of the arrows looking even more 3D in appearance. But the angled ones just ended up looking worse, because of the low pixel density.

What do you have in mind for a speed symbol?

**Comment by mikeller** [comment]
I think the 'tachograph' one (https://user-images.githubusercontent.com/47995726/58388321-a5e56200-8060-11e9-8ca1-4cc0ec87894a.PNG) is easy to grasp.

**Comment by McGiverGim** [comment]
True, something similar to the one suggested will be great.

**Comment by Jetrell** [comment]
@mikeller What do you think of replacing 0x70 and 0x71 with @McGiverGim idea for speed. 
And maybe a symbol for the Total Distance traveled ?
Those symbols aren't assigned. And I can't see race quads getting into the hour flight times, unless a new battery chemistry emerges.

**Comment by Jetrell** [comment]
@McGiverGim  When you say.. something similar.  Those were only idea's. If you are thinking of something specific? Then we can go that way :-)

**Comment by McGiverGim** [comment]
No, nothing in mind, some kind of velocimeter. I'm sure you will find some useful symbol 😁

**Comment by mikeller** [comment]
@Jetrell: Yep, sounds good.

**Comment by Jetrell** [comment]
Here are all the fonts with the Speedometer and Total Distance symbols included.
Speedometer - 0x70
Total Distance - 0x71

I also did a bit of cleaning up in some of the fonts. A few of the earlier ones had some stray pixels here and there. 
I checked the two symbols out through the goggles... and they look good.

[new mod fonts.zip](https://github.com/betaflight/betaflight-configurator/files/3224165/new.mod.fonts.zip)

**Comment by McGiverGim** [comment]
Thanks! I will do the PR for you later.

**Comment by Jetrell** [comment]
>
> 
>@McGiverGim  WROTE - I'm using the impact font and I like it. Good work. Only strange is that the arrows in 3D (with shadow) have a different look than the rest of symbols. I don't know if it is intentional or not.
>

> @Jetrell  WROTE - I went for the 3D shadowed look of the home arrow; to make it look like its pointing forward/backwards etc. And not just up/down and flat in appearance on a 2D screen.
> I wasn't easy to get that look.
> I did mess around with it and got half of the arrows looking even more 3D in appearance. But the angled ones just ended up looking worse, because of the low pixel density.

@McGiverGim @mikeller  I spent some more time trying to perfect the 3D home arrows in the Impact fonts. To give them an even flatter 3D appearance. Its not easy with only 216 pixels. Most look better.... But 4 arrows are just pesky, because of the angle they are on. 
I think it looks better now, in the goggles.... 

Can you guys give it a go, and let me know your opinion... Whether you like it more? Or just stick with what it has?

Thanks

[impact 3D home arrow mods.zip](https://github.com/betaflight/betaflight-configurator/files/3250538/impact.3D.home.arrow.mods.zip)

**Comment by frozenskys** [comment]
If we are changing up the fonts for the 4.1 release do we want to pick back up removing the whitespace in the logo? and do we still want\need font metadata? That would give us enough space for a full ascii set and all the special chars... https://github.com/betaflight/betaflight/pull/3461

**Comment by mikeller** [comment]
@Jetrell: Yes, the arrows look better now.

@frozenskys: The thing with removing whitespace is that it would interfere with logo customisation as we have it now, so we'd have to either drop it (for a simple optimisation that uses a character-wise fixed outline for the logo), or else add support for metadata in the font, and then encode the outline for the logo into the font.

**Comment by McGiverGim** [comment]
@Jetrell I like the new arrows. I prefer them 2D and not 3D but these are far better and more consistent with the other symbols of the font, so enough.

When you have something to push tell me and I will do the PR. I don't know if you are going to clean and reorder too other symbols like I've seen in the other PR.

**Comment by Jetrell** [comment]
@McGiverGim Thank you for the feedback. :-)
At this stage... I'll wait and see what the outcome is on your other PR is. With respect to re-ordering and even the possibility of changes to the other arrow symbols, 0x72 to 0x79. 
 
I also went through all the fonts and aligned descriptive symbols with their number values.  A few in betaflight, default and extra large fonts, were a bit out of alignment. 
I figure... that I may as well do it all now, when the time is at hand.

**Comment by Jetrell** [comment]
This is the cleanup of all the fonts. With some relocations.
It has 8 arrow characters removed. With 4 generic arrows added, across all the fonts. 
The AHI center characters have all been relocated together.
And an `Over Home` symbol has been added.


1) 0x05 `up Triangle` is removed.  Replaced with `Over Home` symbol.
2) 0x7b `AH_CENTER_LINE `is relocated to 0x72  - leaving 0x7b blank 
3) 0x7e `AH_CENTER` is relocated to 0x73  - leaving 0x7e blank
4) 0x7d `AH_CENTER_LINE_RIGHT` is relocated to 0x74  - leaving 0x7d blank
5) 0x79 _previous arrow set_, has also been removed and left blank
6) 0x75 is an UP arrow
7) 0x76 is a DOWN arrow
8) 0x77 is a RIGHT arrow
9) 0x78 is a LEFT arrow

Capture
Capture1

There are 5 variants of the `Over Home` symbol that are used across the fonts, to give them individuality.
Here is a sample of 3 of them.
Hope they are okay for use in  #8372 @McGiverGim 





The 4 generic arrows that have been added, are laid out in a way, to allow them to be used individually or collectively in future developments.  
e.g. 3D throttle graph/scale or even an accelerometer graph, for showing directional motion etc.
Untitled


[Font cleanup.zip](https://github.com/betaflight/betaflight-configurator/files/3255782/Font.cleanup.zip)

If I have missed anything... let me know:-)

**Comment by McGiverGim** [comment]
Big, big work!! 😮 

To me is ok. I like the last sample of home symbol :)

I will push the PR for the upload of the font to start the discussion and let this PR alone. It was merged/closed some time ago so the discussion can be missed by others.

**Comment by McGiverGim** [comment]
Done, please continue the discussion here: https://github.com/betaflight/betaflight-configurator/pull/1477

**Comment by Jetrell** [comment]
I know this is closed. But its related, and I figured you guys have access to it.
@McGiverGim  I just downloaded the latest configurator merge, with your Alphabetical ordered OSD elements. VERY nice. So much easier to find things in :-)

After looking though the elements. The only symbols that I see that might need adding one day, are these. The rest of the mostly used elements, are now explanatory. 

 Heading
Heading indicator

Link Quality
Link Quality Indicator

dBm signal strenght
dBm

You guys have all done an awesome job over the last months, from when the upgrade first started :+1: 

If any of these seem appealing anytime later...  Then let me know at your convenience.

**Comment by Jetrell** [comment]
@McGiverGim  I was wondering if the RPM symbol 0x12, has been defined and added to the OSD?
I just remembered it, and thought it may have slipped past, but wasn't totally sure. 
As I don't have anything with ESC telemetry at this point, to check.

**Comment by McGiverGim** [comment]
No It wasn't. I'm not too sure which OSD element must use it. If you point me to the correct one I will add it.

**Comment by Jetrell** [comment]
@McGiverGim  If your not sure... I'd have no chance of finding it ;-)

@mikeller Can you help with this?  I noticed you wrote the wiki... can I also assume that you are the author of ESC telemetry?

**Comment by Docteh** [comment]
There is an OSD element called "ESC RPM"
Preview:
image


[osdElementsEscRpm()](https://github.com/betaflight/betaflight/blob/7ba8198b83fb0c7bf6f717918445973ec041dc33/src/main/osd/osd_elements.c#L751-L754) calls [renderOsdEscRpmOrFreq](
https://github.com/betaflight/betaflight/blob/7ba8198b83fb0c7bf6f717918445973ec041dc33/src/main/osd/osd_elements.c#L186-L198)

Is that what you're thinking of?

**Comment by Jetrell** [comment]
@Docteh I assume so..,  Thanks :-)

**Comment by McGiverGim** [comment]
There are two OSD elements related: one that shows the RPM and other the RPM FREQUENCY. Both are the same function. 
What is the idea? Add the symbol at the end of each line of the RPM number? Only for RPM, or for FREQUENCY too?

**Comment by mikeller** [comment]
The 'ESC RPM' element is already quite large, so I am not sure we want to make it larger by adding symbols.

**Comment by McGiverGim** [comment]
Yes, that was one of the reasons because I didn't add it. But I'm open to the people that use it.

**Comment by Jetrell** [comment]
@McGiverGim @mikeller  I agree that it is a large block of data.

What I was thinking. Was if the RPM and Frequency for each ESC could be split up and selected by the user, into individual telemetry stats...  ESC 1, ESC 2 etc
Then, for example, on the 3rd OSD screen. A user could place the stats of each ESC in the corners of the screen. 
ESC 1 top left
ESC 2 top right
ESC 3 bottom left 
ESC 4 bottom right

That would make the layout look less bulky and be easier to view at a glance. And I think the RPM symbol would be useful to distinguish motor RPM, from motor Frequency... Because they appear the same at present. 

What do you think of that idea guys?

**Comment by mikeller** [comment]
@Jetrell:
- not sure if we aren't overdesigning this - this seems to be only marginally useful to me, if a user wants to have a record of this data they should log it with blackbox;
- this will make looking at the actual output while flying real hard.

**Comment by Jetrell** [comment]
@mikeller @McGiverGim Could I convince you guys to allow the ESC symbol to be added to the code.  
I find it would make a separation on the OSD, between the RPM and Frequency. Plus I think it would just complete what is there in the fonts :-)

I know that most people many not use it. 
And most of my quads don't have ESC telemetry. But for the ones that do.. Having the ESC RPMs defined by a symbol would just finish it off.

**Comment by mikeller** [comment]
@Jetrell: Again, not sure if this is needed, and making the 'ESC RPM' data block even larger will probably just lead to less users using it...

**Comment by Jetrell** [comment]
@mikeller I do understand your point, about the size of the data block.
But I think it looks even worse at the moment. Because its just a wall of numbers... with no defining character feature.

I really think, that it would look less bulky if it has a symbol to show its purpose, at a glance.

**Comment by Docteh** [comment]
If its the one element that doesn't explain itself....

**Comment by Jetrell** [comment]
@Docteh In it simplest form. I agree, that it doesn't completely explain itself.... i.e. it doesn't tell the pilot which motor RPM is which.
But it still tells you which block of moving numbers is the `RPM` and which is the `Frequency`.
Most people would assume motor 1 is first(at the Top) and motor 4 is last( at the bottom).

There are other possibilities too. Like having only two RPM digits, x1000 RPM like a standard tacho.
e.g. `22k RPM symbol`. Because the 1000 tell the story at a glance, better than fast moving units, 10s, 100s do.

Or just having the RPM symbol user selectable in the CLI.

**Pull request merged**
