### PR TITLE
Cleaned up PID tab, made blocks show / hide properly.

### PR DESCRIPTION
**Pull request by mikeller**

### CODE REVIEW

**Comment by skaman82** [comment]
This looks good, thanks. 

One thing:
- The Angle/Horizon text is out of place (screenshot)
bildschirmfoto 2016-06-30 um 14 44 07

- The opened PIDs are still gone on refreshing

**Comment by skaman82** [comment]
@borisbstyle you merged this a bit too fast :)

**Comment by borisbstyle** [comment]
I missed checking those parts....damn it.

Anyway I also see throttle fields are broken. It was before this PR!

**Comment by borisbstyle** [comment]
image

**Comment by skaman82** [comment]
@mikeller could you do a small followup PR on this?

**Comment by skaman82** [comment]
@borisbstyle yes, noticed that too, but that has nothing to do with this PR (as you mentioned)

**Comment by mikeller** [comment]
I was going to look into throttle and the graphs tomorrow night.

@skaman82: The 'Angle / Horizon' misalignment stems from my clumsy attempt at placing the help button. Unfortunately this is about how far my html design knowledge goes, so if you could have a look at getting this title and the help button properly done?

**Comment by skaman82** [comment]
ok, will do that

**Comment by skaman82** [comment]
done in https://github.com/betaflight/betaflight-configurator/commit/b0ec88ce5adc34c248c0d09d75a48f91a2202389

**Comment by skaman82** [comment]
@martinbudden this is taken care of. Now we need to solve the second part:
- The opened PIDs are still gone again if I click in the "Refresh" button

**Pull request merged**
