### PR TITLE
Remove support for feature RX_MSP

### PR DESCRIPTION
**Pull request by KiteAnton**
RX_MSP seems a bit unsafe and a bit unnecessary..? 

This could then be removed for the configurator to clean up code base.

### CODE REVIEW

**Comment by mikeller** [comment]
I think you are misreading the code in 

https://github.com/betaflight/betaflight/blob/master/src/main/target/common.h#L61

RX_MSP is only skipped for targets with 128K or less flash.

**Comment by KiteAnton** [comment]
Yes that is true, my bad. 
However, is it anybody who uses this functionality? Seems kind of unsafe really and I can't think of a valid use case for this?

**Comment by Austinthemighty** [comment]
what exactly dose RX_MSP do, and does it affect bluetooth,

**Comment by KiteAnton** [comment]
Found the pr that added the feature but I think the purpose to have it is really vague... And IMO it doesn't seem to "outweigh" the unsafe downside with this. 
https://github.com/cleanflight/cleanflight-configurator/pull/224

**Comment by mikeller** [comment]
Well, it is no more unsafe than the motors tab. Same as there, I can't see how this could be used safely with props on. The use case I can see is to be able to verify correct functioning of pid loop and stabilised modes where a TX cannot be used or is not handy. Also, I cannot see a reason to remove this.

**Comment by KiteAnton** [comment]
Well I think it is a bit more unsafe then the motors tab since motors tab will just run at a fixed speed and with this you will actually be able to arm the copter that then will try to control the quad. Also the motors tab has a valid purpose for the user, this seems kind of unused (and for the end user the the benefit should be zero .. ? ) 
Well, first I was a bit too quick and misread the #defines in the FW so I thought it was totally unused. Now I can agree there might be less reason to remove it other than its cluttering the code. In my opinion we should always strive to keep the code as clean and valid as possible and features without end-user benefits should be cleaned up if possible. There is no reason to keep stuff around if no one uses it right ?

**Comment by KiteAnton** [comment]
@Austinthemighty this allows Rx values to be emulated from the configurator. You can set any RX channel to any chosen value.

**Comment by borisbstyle** [comment]
Rx msp should not be removed. Its rx protocol through MSP interface.

Can be very usefull when debugging and coding things around the rx code

**Comment by KiteAnton** [comment]
OK, I close this PR then. My suggestion was not to remove it from the FW, it was to remove if from the end-user configurator. IMO it would be better suited in some developer tools instead.

**Comment by borisbstyle** [comment]
Well I personally may expect it to ever be used in some RTF quads where
there is some abstraction hardware between the actual rx and the hardware
what runs the firmware.

Also with integrated hardware it may be a great choice where you can
control everything on the fc through a single interface.

If you ask me it should even become a standard. Imagine having everything
available on a single interface from telemetry to other FC functionalities.

**Pull request closed without merging**
