### PR TITLE
Added support for more baudrates to MSP.

### PR DESCRIPTION
**Pull request by mikeller**

### CODE REVIEW

**Comment by martinbudden** [comment]
@mikeller thanks for spotting this and fixing it.

I think at some point we should change the protocol to send each baud rate as a `uint32_t` - that way we avoid the problem of changing the index values altogether.

**Comment by mikeller** [comment]
All for it - the configurator already stores the baudrates as numbers internally, so that side is going to be dead drop simple.

**Comment by borisbstyle** [comment]
Its merged but now I get this by default

image

**Comment by mikeller** [comment]
Weird. I'll investigate. What does `serial` in CLI give you for this board?

**Comment by borisbstyle** [comment]
@mikeller 
Actually it works now. It was some dodgy early 3.1 fw I think. Will try again on other board

**Pull request merged**
