### PR TITLE
Fix Firmware Flash tab style bug

### PR DESCRIPTION
**Pull request by Asizon**
Fix for https://github.com/betaflight/betaflight-configurator/pull/1903

### CODE REVIEW

**Comment by mikeller** [comment]
Thanks for reporting this, but your fix is breaking existing functionality because it breaks the CSS selector.

This is how the dialog looks with your fix:

image

This is how it is supposed to look:

image

**Comment by Asizon** [comment]
Thanks for correcting me @mikeller. I had the feeling that I was not doing it right. I hope my new solution is correct.

**Comment by mikeller** [comment]
:rofl: 
It's certainly workable to wrap the `<ul>` into a list to make it not appear. I'd actually prefer to understand what is going on to make this only appear in certain circumstances.

A better solution would be this:

```
mikeller@pc:~/git/betaflight-configurator$ git diff
diff --git a/src/css/main.css b/src/css/main.css
index c602d494..3bf1c3f5 100644
--- a/src/css/main.css
+++ b/src/css/main.css
@@ -2101,9 +2101,6 @@ input {
     position: initial;
 }
 
-
-}
-
 @media only screen and (max-height: 750px) , only screen and (max-device-height: 750px) {
 
 .tab_container {
@@ -2202,3 +2199,7 @@ input {
 .noUi-connect {
     box-shadow: none;
 }
+
+#hidden {
+    display: none;
+}
diff --git a/src/main.html b/src/main.html
index 7d53cd2b..fc934332 100644
--- a/src/main.html
+++ b/src/main.html
@@ -387,7 +387,7 @@
         </div>
     </dialog>
 
-    <ul> <!-- Sonar says so -->
+    <ul class="hidden"> <!-- Sonar says so -->
         <li class="dialogReportProblems-listItem"></li>
     </ul>
```

**Comment by Asizon** [comment]
Fixed in #1917 closing this PR

**Pull request closed without merging**
