### PR TITLE
Add Km, Mi and LQ symbols to fonts

### PR DESCRIPTION
**Pull request by McGiverGim**
As discussed here: https://github.com/betaflight/betaflight/pull/8471 and provided by the user @Jetrell

0x7b - Link quality
0x7d - Km symbol
0x7e - Miles symbol

image

### CODE REVIEW

**Comment by Docteh** [comment]
image

This also updates 0x05 0x0C 0x0F on some fonts. Looks like good tweaks.

**Comment by Jetrell** [comment]
Thanks @Docteh 
I figured... Because the new Km and Mi symbols are going to appear in the same location on the OSD, as the Ft and Meters symbols.... That I better line them all up in size and height.
 
Plus... with a few of the fonts, I also thought it was a good idea to renew the older looking FT and Meters symbols. So that the `FT and Miles` and` Meters and Km` symbols have a similar look, instead of them looking totally different in appearance.

**Comment by Docteh** [comment]
With most changes being to code anyone curious can click on the "Files changed" tab and get an idea of whats going on. With these MCM files we don't get that. 

Although what I can do is note down oddly placed changed lines, divide by 64 for an approximate character number ;)

I'm just calling out changes so we can all see them.

Digital, bottom bit of the letter F is shorter.
image


Vision  
GPS symbol changed, one less signal line. Are you sure that is needed? Its not like a user needs to clearly see the line being emitted by the satellite....
image

**Comment by Jetrell** [comment]
@Docteh I have change many things in all the fonts, over the 5+ upgrades in the last few months. More than you would think.
Most are cleaning up stay pixels and rough edges. But some were cosmetic and practical, to suit the newer symbols, so they fit together better.
I see it this way.... I can either bring all the fonts up to a higher standard to suit the new symbols. Or I could have just left the older fonts looking rough and a bit crude in many cases..... which I think would have been careless, on my part.

So I used my discretion and modified each font, while still keeping its characteristic style. 
But while doing that, also made them more readable and defined, in many area's.... This was because Default, Bold, Larger and Extra Large used the same general descriptive characters. As did Betaflight and Digital... to a lesser degree. 

By cleaning them up and changing the look of the descriptive characters to suit each Letter/Number font style. It made each one look more individual. 

99% of people wouldn't even see the days of work I put into it... nor would they care. But I like to do things to the best of my ability. And I know they all look much cleaner now :-)

**Comment by Docteh** [comment]
@Jetrell I'll keep shining a magnifying glass at the fonts so more people notice. Get that down to 98.9% ;-)

**Comment by skaman82** [comment]
I like this attention to detail. Well done!

**Pull request merged**
