### PR TITLE
Add betaflight firmwares to firmware flasher

### PR DESCRIPTION
**Pull request by KiteAnton**
As discussed in #4

### CODE REVIEW

**Comment by skaman82** [comment]
@KiteAnton There something wrong with version names in the select element: Some versions are shown, some not. There is also a "null" everywhere in the labels. 

bildschirmfoto 2016-06-14 um 13 23 08
bildschirmfoto 2016-06-14 um 13 22 54

**Comment by KiteAnton** [comment]
Yes noticed this too. My suggestion is that we merge this (since it is stil better than none), and then I will create an issue to fix these. Is that ok ?

**Comment by skaman82** [comment]
I think we should remove the "null" before merging this.

Von meinem iPhone gesendet

**Comment by KiteAnton** [comment]
Ok, fixed it locally now, will push to github later tonight.

**Comment by skaman82** [comment]
@KiteAnton could you please push your change you mentioned?

**Comment by KiteAnton** [comment]
The "null" text is removed now. Please review.

**Comment by skaman82** [comment]
Looks fine to me, merging. Thank you!

**Pull request merged**
