### PR TITLE
General fonts upgrade (BF PR 7733)

### PR DESCRIPTION
**Pull request by OlivierC-FR**
... to match PR : https://github.com/betaflight/betaflight/pull/7733

Added icons for : km/h, MPH, ft/s/ home flag.
Various cosmetics fixes over all fonts.
Added blanks on free slots.
Updated charset : https://www.dropbox.com/s/t134hbayq27srxj/charset.ods

### CODE REVIEW

**Comment by OlivierC-FR** [comment]
betaflight
bold
clarity
default
digital
extra_large
large
vision

**Comment by mikeller** [comment]
All in all good work, thank you.
Not sure about removing the unused symbols - most of them are somewhat related to what we are doing, and somebody might implement an OSD element that uses one of them at some point, so leaving them in will enable users to make use of the new element without having to upload an updated font. For this reason I think it makes more sense to leave them in. And in general, the defines in `src/main/drivers/max7456_symbols.h` are used to keep track of which elements are in use.

**Comment by OlivierC-FR** [comment]
Actually, I didn't remove much, I phrased it wrong, I mostly cleaned the defines, and I kept some chars that are not actually in use, and might be usefull later. What I removed from the charset are (from memory, might be uncomplete) :
"GY"  : old part of GYRO from Multiwii OSD days I guess
The white + over black, also part of an old 2 pieces-icon forgotten a long time ago.
ON HR, FLY HR, never seen this in use anywhere, people do not fly for hours with BF.
A weird vertical dotted bar.

And maybe 1 or 2 other I forgot, will make a full check later, I'll make an exact listing of what I removed.

**Comment by OlivierC-FR** [comment]
Orange = Removed and blanked
Green = Removed and replaced by something new (km/h, mph, home flag)

betaflight_deleted

**Comment by McGiverGim** [comment]
The on hr and fly hr are used in Betaflight, there are counters of armed, and on time.

**Comment by OlivierC-FR** [comment]
@McGiverGim : No they are not, that's ON MN and FLY MN.
ON HR and FLY HR are not defined, and their dec and hex values are nowhere found in any OSD files.

**Comment by McGiverGim** [comment]
True, you are right. Sorry 😁

**Comment by OlivierC-FR** [comment]
... and that's why sometime it's good to do some cleaning ! ;)

**Comment by mikeller** [comment]
@OlivierC-FR: See my comment in https://github.com/betaflight/betaflight/pull/7733#issuecomment-470653678

**Comment by McGiverGim** [comment]
Please @OlivierC-FR don't close this! The km/h and the flag are a good addition, and the cleaning of the firmware part is good. At least this is my opinion.

**Comment by netmute** [comment]
Can we reopen this? Maybe even have little "lat" and "lng" labels instead of arrows like in iNav?

**Pull request closed without merging**
