### PR TITLE
Fix OSD preview for Android

### PR DESCRIPTION
**Pull request by haslinghuis**

### CODE REVIEW

**Comment by haslinghuis** [comment]
@McGiverGim artifacts workflow seems out of date. Perhaps we replace with https://github.com/actions/download-artifact

**Comment by McGiverGim** [comment]
> @McGiverGim artifacts workflow seems out of date. Perhaps we replace with https://github.com/actions/download-artifact

I don't understand exactly what you say, we are using these action. What action must we replace?

**Comment by haslinghuis** [comment]
I mean the artifacts have no link in the PR. (Now need to go to show all checks)

**Comment by McGiverGim** [comment]
This happens for draft.

**Review by blckmn — CHANGES_REQUESTED** [review]
@haslinghuis id prefer to delete than comment. You can always revert based on file history. 

Risk is that the commented code stays, and gets forgotten.

**Comment by haslinghuis** [comment]
Yes lazy to setup local android dev, testing display local on desktop and using the build here to test on android. Will cleanup when finished.

**Comment by haslinghuis** [comment]
For testing: There are no artifacts published so need to click Checks tab and click PR to find the artifacts

**Comment by McGiverGim** [comment]
@haslinghuis seems here is a workaround https://github.com/tonyhallett/artifacts-url-comments/issues/80

I'm out of the computer until tomorrow, so I can't do the change right now.

**Comment by haslinghuis** [comment]
OSD preview looks good on Nokia G60. Happy if you could test with your Pixel device.

**Comment by haslinghuis** [comment]
Will do a PR for 

> Update: The issue is in the  addTo: "pullandissues" if I only use  addTo: "pull" everything works as expected

**Comment by McGiverGim** [comment]
> OSD preview looks good on Nokia G60. Happy if you could test with your Pixel device.

Looks as good as possible in a phone (tested with virtual fc). I miss a little margin to the right of the preview, but for the rest is ok.

**Comment by haslinghuis** [comment]
### How to get the assets for testing this PR:

There are no artifacts published so please click `Checks` tab and click `PR` to find the artifacts

**Comment by haslinghuis** [comment]
@McGiverGim for me it shows preview on top and the other columns next to each other on the bottom. No problem with margin :)

I think this is much better as before.

**Comment by McGiverGim** [comment]
I'm talking about this left space:


On the right there is none:

**Comment by McGiverGim** [comment]
Screenshot_20230108-230330
Screenshot_20230108-230354

**Comment by haslinghuis** [comment]
At least we don't have to scroll to the right anymore to see the preview :) and it's not cutoff anymore.
Tried to minimize fixed values as much as possible. For me it looks good and on Pixel good enough.

**Comment by McGiverGim** [comment]
I scroll to the right because the preview does not fit in the page 😁

**Comment by haslinghuis** [comment]
Ok adding 528 max-width: 100% too. Let's see.

**Comment by haslinghuis** [comment]
@McGiverGim please test again

**Comment by McGiverGim** [comment]
I can't see any difference, but it's ok to me. 😉

**Comment by haslinghuis** [comment]
Ok, reverted as it didn't work.

Good to merge now.

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by McGiverGim — APPROVED** [review]

**Pull request merged**
