### PR TITLE
OSD Tab - Improve the way osd elements picker + timer section render/wrap

### PR DESCRIPTION
**Pull request by benlumley**
The OSD element picker bit looked a bit messy once the viewport is narrower and it starts to wrap so I've tidied it up a bit...

Before

Screenshot 2022-05-11 at 09 43 50

After

Screenshot 2022-05-11 at 10 31 44

### CODE REVIEW

**Comment by benlumley** [comment]
Added in the timers too - maybe not design perfection... but consistent wrapping / generally looking tidier. 

After:
Screenshot 2022-05-11 at 10 46 16

Screenshot 2022-05-11 at 10 46 22

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Review by haslinghuis — APPROVED** [review]

**Review by McGiverGim — APPROVED** [review]
Not tested, but seems good to me.

**Review by Asizon — CHANGES_REQUESTED** [review]
This should make flex only if not space available in the line:

image

**Review by Asizon — CHANGES_REQUESTED** [review]
It have alotof vertical separation now,should be smaller:

image

**Comment by haslinghuis** [comment]
@Asizon this is supposed to complement #2916 - so have to test with that PR included.

**Comment by benlumley** [comment]
> This should make flex only if not space available in the line:

OK; I've changed it - I thought it looked better always wrapped; it will now be on 1 line until it needs to wrap.

> It have alotof vertical separation now,should be smaller:

Have closed this up.


> @ Asizon this is supposed to complement #2916 - so have to test with that PR included.

His issues are valid, corrected as above. I have tested with that PR merged; and the affect is to alter the widths of the different columns at different viewport widths; but it otherwise doesn't affect this. 

---

I've left the commits broken out in case useful to anyone reviewing what I've changed. I can squash in due course for merge.

**Comment by benlumley** [comment]
Screenshots at different sizes

<details><summary>Screenshots...</summary>

Screenshot 2022-05-18 at 11 58 24
Screenshot 2022-05-18 at 11 58 34
Screenshot 2022-05-18 at 11 58 46
Screenshot 2022-05-18 at 11 58 57


</details>

**Review by Asizon — APPROVED** [review]
Thankyou @benlumley! Looks better now

**Comment by haslinghuis** [comment]
Re-run failed tasks. All builds are done.

**Review by haslinghuis — APPROVED** [review]

**Review by McGiverGim — APPROVED** [review]

**Comment by Asizon** [comment]
@benlumley thinking on this one, Could be good to have this flex in column mode and use all parametres like an option, some like this:
image

**Pull request merged**
