### PR TITLE
Ready Mode

### PR DESCRIPTION
**Pull request by jonmahoney15**
Ready Mode allows the pilot to signal they are ready. Ideal for race lines so all pilots are ready to race.

Fixes: #2874

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Comment by ctzsnooze** [comment]
There is a problem with this PR when used with the matching firmware code.
If I check 'READY' in the list of osd elements in the OSD tab, I see 'AO' where 'READY' should be, in the goggles.
If I check 'Unknown 1' at the bottom of the list of OSD elements, and un-check 'READY', I see 'READY' in the right place. 
@haslinghuis I wonder if you could help resolve this.

**Comment by ledvinap** [comment]
@ctzsnooze : Isn't it possible that the text is AG? Antigravity displays that ... 
https://github.com/betaflight/betaflight/blob/30be24b0fa304fc65553483e17440c139f94fc71/src/main/osd/osd_elements.c#L687

**Comment by jonmahoney15** [comment]
> There is a problem with this PR when used with the matching firmware code.
> 
> If I check 'READY' in the list of osd elements in the OSD tab, I see 'AO' where 'READY' should be, in the goggles.
> 
> If I check 'Unknown 1' at the bottom of the list of OSD elements, and un-check 'READY', I see 'READY' in the right place. 
> 
> @haslinghuis I wonder if you could help resolve this.

To confirm you have flashed the betaflight ready mode branch firmware and are using this branch configuration, if using this branch the tab should show ready mode instead of unknown. I will retest everything as well though.

**Comment by ctzsnooze** [comment]
@haslinghuis 
Yes I can confirm I used the 'Ready' firmware PR, and the build of Configurator from this PR.
Used together, Configurator showed both the 'Ready' checkbox and an 'Unknown 1' checkbox.
Checking 'Ready' showed 'AO' in OSD, in the correct position.
Checking 'Unknown 1' showed 'Ready' in the OSD.

**Comment by haslinghuis** [comment]
We need to merge https://github.com/betaflight/betaflight-configurator/pull/3057 before testing again.

**Comment by ctzsnooze** [comment]
Good, the cause of the problem was that display of Aux_Value data in the OSD hadn't been fixed on the Configurator side.
The 'A0' display was the default Aux_Value display.

Once #3057 is merged, which fixes the Aux_Value display bug, this PR can be applied, and should work properly.

**Comment by ctzsnooze** [comment]
I've tested this and it works properly when applied after https://github.com/betaflight/betaflight-configurator/pull/3057, which was causing the problem above.

**Review by ctzsnooze — APPROVED** [review]

**Review by limonspb — APPROVED** [review]

**Review by haslinghuis — APPROVED** [review]

**Review by sugaarK — APPROVED** [review]

**Pull request merged**
