### PR TITLE
Improved build request management

### PR DESCRIPTION
**Pull request by blckmn**
Enabling user to cancel and indicating whether actual build processing has commenced or not.

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by haslinghuis — APPROVED** [review]
image

**Comment by haslinghuis** [comment]
It is not needed to change other languages then EN.

@McGiverGim has more detail on this. IIRC workflow will invalidate language in Crowdin.

**Comment by McGiverGim** [comment]
Exactly, all the languages files will be replaced by the files downloaded from Crowdin. There is not inverse synchronization in our workflow.

**Comment by blckmn** [comment]
It was more to have it as completed as possible for any RC inclusion... if we don't include it for RC2 then all good.

**Comment by nerdCopter** [comment]
image
image

**Review by nerdCopter — APPROVED** [review]

**Comment by blckmn** [comment]
> Seems to "cancel" the UI only, as the API building seems to continue to build. Click log immediately for empty log. Wait a few seconds then refresh log will show succeeded.

This is by design. Once the build process is commenced or queued it will continue. The cancel merely relinquishes the configurator to enable the user to exit the time out process.

**Pull request merged**
