### PR TITLE
Fix custom defaults search addresses and incorrect address calculation.

### PR DESCRIPTION
**Pull request by hydra**
This PR 

1) Provides a workaround for the first issue in #3316.
2) Fixes a signed-integer bug in the address calculation.

e.g. the old code did not handle the bytes `C8 DF 1F 90` correctly, the last byte `90` caused the computed address to overflow a signed 32 bit integer.

### CODE REVIEW

**Comment by hydra** [comment]
Please don't merge this code until solutions for issues 3,4,5 in PR #3316 as this makes the end-user situation worse, as follows:

* Without this PR, the user can flash EXST firmware, and manually apply the unified target configuration themselves via the CLI.
* With this PR the configurator will throw the error, highlighted here (https://github.com/betaflight/betaflight-configurator/issues/3316#issuecomment-1419160156) and the user will not be able to flash the firmware, nor manually apply the unified target configuration themselves via the CLI.

This PR should be only merged at the same time as code to fix issues 3,4,5 are merged.  This PR is requires for anyone working on issues 3,4,5.

**Comment by haslinghuis** [comment]
/home/runner/work/betaflight-configurator/betaflight-configurator/src/js/ConfigInserter.js:

Error:   34:1   error  Trailing spaces not allowed  no-trailing-spaces
Error:   42:39  error  Trailing spaces not allowed  no-trailing-spaces

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Comment by hydra** [comment]
> /home/runner/work/betaflight-configurator/betaflight-configurator/src/js/ConfigInserter.js:
> 
> Error: 34:1 error Trailing spaces not allowed no-trailing-spaces Error: 42:39 error Trailing spaces not allowed no-trailing-spaces

fixed.  I wasn't using my usual editor...

**Pull request closed without merging**
