### PR TITLE
Added new parameters to PID tab.

### PR DESCRIPTION
**Pull request by mikeller**
@borisbstyle: This is very preliminary and will need to get styling before it's good to go. Can you please check if the functionality is what you want, and come up with a proper label and optionally tooltip?

I had to use the large slider, as the small and sleek one does not have a way to indicate scale. Alternatively we could use the small slider, and display the current value as a number next to it.

Also, what were the other values that you wanted to be added to the PID tab? I couldn't find where we'd discussed this.

### CODE REVIEW

**Comment by borisbstyle** [comment]
@mikeller Yes this was the direction I was thinking of!

Only the slider would have to be much smaller than this :D. Also add it up to 3.0 as I found 200 not being limit on my setup and will change that in the firmware.
image

**Comment by mikeller** [comment]
The problem is there display size of this slider cannot be adjusted in a sensible way. And the small slider that we use in the motors tab doesn't have an option to display scale marks and numbers.

I will go look around for a library that we can use to get a better slider.

Also, weren't there more parameters to be added to the PID tab? And should the 'Derivative Method' chooser be hidden for the Betaflight PID controller?

**Comment by borisbstyle** [comment]
@mikeller 
Lets temporarily add just fields like PIDs

**Comment by mikeller** [comment]
Will have a look tonight, if I can find something on the quick we can as well go for the sliders, otherwise I agree numbers would be fine.

**Comment by mikeller** [comment]
@borisbstyle have a look now, I spiffed it up some.

**Comment by borisbstyle** [comment]
@mikeller 
This looks amazing actually!

**Comment by borisbstyle** [comment]
@mikeller 
Or just set them below the pids so the PIDs stand out

**Comment by borisbstyle** [comment]
Also when legacy selected the options should be hidden and other way around when betaflight selected Derivative method should be hidden

**Comment by mikeller** [comment]
I was planning on introducing a normal / expert mode switch in the top bar at some stage, with 'normal' mode hiding the less important tabs and less important parameters on tabs, and this would probably take the place of making the tables collapsible. 

I think moving them to below the PIDs is a good start, will do this.

I just realised about the hiding dependent on controller, will this implement next.

**Comment by borisbstyle** [comment]
Cool! If it works properly I might release it quickly so people can play with it! I will add names and descriptions to it as well

**Comment by borisbstyle** [comment]
oh might be good idea to use 1,0 instead of 100 etc. Makes it more clear what it actually does

**Comment by mikeller** [comment]
Yeah, I think some tooltips might be helpful.

1.0 for setpoint weights?

**Comment by borisbstyle** [comment]
100 = 1.0
200 = 2.0
etc

thats what it actually is

**Comment by mikeller** [comment]
Consider it done.

**Comment by mikeller** [comment]
Done. ;-)

**Pull request merged**
