### PR TITLE
Dynamic Idle configurable

### PR DESCRIPTION
**Pull request by Asizon**
I am seeing a great effort in joelucid to improve the explanation in the wiki and social networks of how this feature works and I think it now looks better. Adding Dynamic Idle feature configurable parametre. It is a feature that depends on the pidprofile so I have linked this tab with `MSP_PID_ADVANCED`. My first idea is to show in some way that this feature belongs to the pid profile, happy to hear ideas. Also modify the function of hiding values that depend on rpm and unify it. The tooltip needs updating by @joelucid suggestions.
DynamicIdle

### CODE REVIEW

**Comment by mikeller** [comment]
@Asizon: Ignore the Sonar complaints - they are caused by me accidentally disabling, and then re-enabling some detection rules. :confounded:

**Comment by mikeller** [comment]
I think this is on the wrong tab - since it is dependent on the currently selected PID profile it should go onto the PID Tuning tab, otherwise it will be confusing and hard for users to determine which PID profile they are changing this value for, as the PID profile indicator is not shown:

image

**Comment by joelucid** [comment]
> I think this is on the wrong tab - since it is dependent on the currently selected PID profile it should go onto the PID Tuning tab, otherwise it will be confusing and hard for users to determine which PID profile they are changing this value for, as the PID profile indicator is not shown

Yeah this is a bit of a problem: logically it belongs next to dshot_idle_value, but that is on a non profile page. On the other hand dshot_idle_value would really be better suited in a profile so it can be changed according to cell count. 

Maybe dshot_idle_value should become a profile setting and both be moved to the pid page?

**Comment by mikeller** [comment]
@joelucid: Agreed, moving `dshot_idle_value` into the 'PID" profile might be useful for some use cases. The problem is that the whole profile business is a tangle, and should be re-worked to maximise usefulness. Moving individual parameters around in a piecemeal fashion will not fix this, and will make it very hard to support the different versions in configurator.

Hence I think moving the dynamic idle value into the PID tuning tab is what can be done to address this at the moment.

**Comment by Asizon** [comment]
ok then I have done it, moved to pid tuning tab :) , this is the result
dynamicidlefinal

**Comment by Asizon** [comment]
I also changed the name of the function of the tab configuration to make it more generic, it didn't occur to me when I did it a while ago. Maybe we should listen to Sonarcloud error

**Pull request merged**
