### PR TITLE
Add a few unit tests for MSP protocol

### PR DESCRIPTION
**Pull request by Benky**
## Description
This PR adds a few unit tests for MSP protocol (both `V1` and `V2`). Operation code and data for tests are randomly generated.

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Review by haslinghuis — APPROVED** [review]
image

**Comment by Benky** [comment]
Hey @haslinghuis - thanks for approval. I've removed usage of `Math.random()` to please `SonarCloud` (and it actually made a code a bit shorter).

**Comment by nerdCopter** [comment]
How do you execute a unit test? i couldn't find a gulp task.

**Comment by haslinghuis** [comment]
yarn test

**Review by nerdCopter — APPROVED** [review]

**Comment by chmelevskij** [comment]
noice

**Pull request merged**
