### PR TITLE
Replaced looptime with gyro/pid denom settings

### PR DESCRIPTION
**Pull request by KiteAnton**
As requested in #22 
Looptime is replaced by gyro/pid denom settings

### CODE REVIEW

**Comment by borisbstyle** [comment]
Excellent!

Do you think you can add rc_yaw_rate and maybe the filters into PID tab?

**Comment by KiteAnton** [comment]
@borisbstyle, do you mean MSP_SET_FILTER_CONFIG and MSP_SET_ADVANCED_TUNING ? I can have a look at it but maybe someone else are better in adjusting the layout later.

**Comment by borisbstyle** [comment]
Arent those easiest to add? Just a field like pids etc. No special logic
behind
Op 20 jun. 2016 22:25 schreef "KiteAnton" <notifications@github.com>:

**Comment by skaman82** [comment]
No worries, I can allways clean up the GUI later.

Von meinem iPhone gesendet

**Pull request merged**
