### PR TITLE
Update nodejs

### PR DESCRIPTION
**Pull request by chmelevskij**
* update node to LTS v20
* update `appdmg` package to support apple silicon

### CODE REVIEW

**Review by haslinghuis — APPROVED** [review]

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by ctzsnooze** [comment]
If all three of Configurator, Blackbox, and Betaflight.com are at the same Node version, life is easier, for Mac users at least.  Otherwise I get node version mismatch errors and must enter `nvm use nn` to match the node version to the version required by the code.

So let's please not make this change unless we are ready to do it on all three at the same time.

**Comment by haslinghuis** [comment]
Blackbox is already on 20, PR for documentation is ready to merge

Version 16 is dead.

**Review by nerdCopter — APPROVED** [review]
* approving untested as i do not have access to OSX

**Review by McGiverGim — APPROVED** [review]

**Comment by nerdCopter** [comment]
* tested both `yarn gulp debug` and `yarn build ; yarn vite` successfully on Debian 11. required `rm -r node_modules ; yarn install` first.

**Pull request merged**
