### PR TITLE
Add Betaflight Configurator as window title

### PR DESCRIPTION
**Pull request by McGiverGim**
This fixes https://github.com/betaflight/betaflight-configurator/issues/807

I've hardcoded the string, I think that this must not be in the messages file and must not be translated. I'm right?

### CODE REVIEW

**Comment by basdelfos** [comment]
Well, you are probably right that the window title is not prone to be translated (although, 'Configurator' could be translated).
As a lot of hardcoded text is lately moved from code to the locales file, I would do the same for this. For the sake of consistency.

**Comment by McGiverGim** [comment]
I can move the string to the messages file as a placeholder (and in this way don't let people translate it) or as a normal string, and let each translation team to see if must be translated or not.

**Comment by McGiverGim** [comment]
Added to the messages file, added too a description to the translators @mikeller what do you think about description? Is a good idea to include them in future strings?

**Comment by mikeller** [comment]
@McGiverGim: Yes, using the descriptions makes sense, because the translations are a team effort, and it's valuable to add commentary to ensure the end result is consistent across different languages.

And I fully agree that the name of the application should not be translated. Microsoft Windows isn't 'Microsoft Fenster' in German...

**Comment by McGiverGim** [comment]
@mikeller I've uploaded this file to the OneSky app... and it seems to not understand the `description` tag. It shows two strings to translate, and not one string and a "note" for it. I've "hide" the description by the moment.
I will ask to the OneSky support, to see if I made something wrong, but we cannot upload strings with description by the moment :(

**Comment by mikeller** [comment]
@McGiverGim: Thanks for looking into this. At the moment, not having descriptions is not a big deal, since we only have one phrase that needs one. But it would be nice if they could make it work in the future.

**Pull request merged**
