### PR TITLE
Update JQuery to 3.5.1 and other libraries to the last minor

### PR DESCRIPTION
**Pull request by McGiverGim**
Better to go to the "latest" stable version of JQuery, maybe fixes some bug and we have time to find bugs now.

The major part of dependencies of `package.json` that we have are defined to use any patch (~) or minor (^) version. Maybe is good to do the same here or we are going the inverse way and is better to remove from the others?

### CODE REVIEW

**Comment by mikeller** [comment]
Good idea.
I think standardising on the version specification that we are using makes sense - I think some of the packages that we are using have breaking changes (for us) in minor releases, so `~` is probably the best to standardise on.

**Comment by McGiverGim** [comment]
The theory is that the minor releases must be compatible backwards, so to me the best solution is:
- Use minor releases by default
- If some of the libraries are known to give problems to us, change them to patch releases
In this way we are more updated, but the problem is that we must be aware of the problems and change them manually.

**Comment by McGiverGim** [comment]
Looking at the actual libraries, it seems we are using minor almost for all:
https://github.com/betaflight/betaflight-configurator/blob/be8d59e26f506b769f1702dd901a6055fe9bba71/package.json#L44-L95

Only `inflection`, `jbox`, `jquery` and `jquery-ui-npm` specify exactly the version.

**Comment by McGiverGim** [comment]
After doing some tests, changing this libraries to the next minor, only changes one library:

> jbox from 1.0.8 to 1.2.0

The rest remains unchanged. So I changed the PR to minor for all of them. If finally we decide to change to patch, I can change all the libraries.

**Comment by McGiverGim** [comment]
In the three.js PR https://github.com/betaflight/betaflight-configurator/pull/2091 I used the patch ~ because the library only works until version 0.98.0. Is an easy way to see what libraries are blocked because they need work on our side and which not and can be upgraded or tested to be upgraded to next major.

**Comment by mikeller** [comment]
Still not sure that standardising on auto-updating minor versions is the right way to go. Normally patch versions are what _must_ be updated because they contain fixes and security updates, whereas minor versions are non-breaking functional updates, and these updates are optional.
Also, if we say we want to go for `^` we should be doing this for all libraries and not just for some.

**Comment by McGiverGim** [comment]
Almost all our libraries but three use the `^`. I was thinking of add  `^` to these three and test them too but I was waiting to see what we decide here.

To me is not a problem to change them for `~` but this can lead to failing dependencies easy if other libraries use them and require a different version than ours. This is specially true with jquery that is used by a lot of the others. We will need to "maintain" them more or less manually.

This is the reason why I think to use `^` is the correct way: is how we have it now in the major part, and usually we don't have problems, and we can use `~` only for those we know are incompatible and need changes after testing (like `three.js`).

**Comment by McGiverGim** [comment]
Sorry, I forgot this PR, rebased!

**Pull request merged**
