### PR TITLE
Added new filters to MSP.

### PR DESCRIPTION
**Pull request by mikeller**
To go with https://github.com/betaflight/betaflight/pull/990

### CODE REVIEW

**Comment by KiteAnton** [comment]
This works on 3.1.0 but not on 3.0.0
Instead of L685 `if (semver.gte(CONFIG.apiVersion, "1.20.0")) {`
it could be changed to check the length of data, via byteLength.
I.e. `if (data.byteLength > 5) {`then it will work for both versions.

**Comment by borisbstyle** [comment]
Yeah data length check would be better indeed.

**Comment by mikeller** [comment]
Oh, I thought the new filter MSP code had gone into master and development?

Length check is problematic, as it only works for `MSP_SET_...` but not for `MSP_...`, and I'd rather have identical checks for both commands for one data group.

**Comment by KiteAnton** [comment]
I'm not sure I follow what you mean with not work on MSP_..? Isn't checking length more robust? Since it will only try to read data that is actually there?

**Comment by borisbstyle** [comment]
I think its only also needed in MSP_SET. MSP read should work I believe?

Yes its added on both development and master

**Comment by mikeller** [comment]
Yes, I put it the wrong way round, msp set will not know about length.

I'll fix it later on.

**Comment by KiteAnton** [comment]
I haven't tested but will not the fw be able to work the same, i.e.  If the configurator will send more data in msp then the fw expects it will just read what is expected and throw away the rest?  If so then will the MSP_SET really need to have the same version check or can it just send it all?

**Comment by mikeller** [comment]
As far as I can tell the firmware is not that flexible, and needs to be fed the correct amount of data for every command. Also, since what we are trying to achieve is to get one release of the configurator to be able to talk to all different versions of the firmware, but not the other way round, I'd rather put the smarts into the configurator.

**Comment by mikeller** [comment]
@KiteAnton:

> This works on 3.1.0 but not on 3.0.0

What exactly does not work for you for 3.0.0? I just tested with 3.0.0 on a Naze32, and it seems to work just fine.

**Comment by KiteAnton** [comment]
I tested this also with a Naze and you get error messages when using the pid tab. It complains about trying to read at an offset out of bounds for the dataview.

**Comment by mikeller** [comment]
Is this with latest, or with one of the RC's?

**Comment by KiteAnton** [comment]
This was with Naze loaded via the configurator from online, it was RC7 I think. I guess if the MSP was added in the FW later than that it will work.

**Comment by KiteAnton** [comment]
So guess it works with latest 3.0 then. But anyway, since there would probably be users using an earlier RC I think it should check the byteLength instead of apiversion, then it will never try to read data that doesnt exist.

**Comment by mikeller** [comment]
Yeah, that's the story with RC builds, there is no way we can keep them supported once they have been superseded.

**Comment by mikeller** [comment]
As I said before, checking the byteLength only works for reading the values from the firmware, not for sending them. I think doing it one way for reading and in a different way for writing will only make the whole process even more brittle than it already is.

**Comment by KiteAnton** [comment]
Ok it needs to be tested/verified but I think it is safe to send more data to the FW than it expects. It will just never be read. 
As long as you never delete, rearrange or alter and parameters that has been sent in a certain msp command it should be quite safe to add new parameters at the end, it doesn't need to be synced versions for this ?

**Comment by mikeller** [comment]
@KiteAnton Please keep in mind that we are trying to support talking to older versions of the firmware with this code, so, unless we go back and check for all versions, this is not a safe thing to do.

In addition to this, I am quite much in favor of doing this API by specification, i.e. defining 'version X does Y' and then implementing the specified behaviour on both sides. Doing an API like this by best effort will only hurt us in the long run.

**Comment by KiteAnton** [comment]
Ok I agree somehow but I still think it is unfortunate to break RC1-7 for this. 

General the sender of data should be aware of what the receiver expects but I think it would be more robust if the receiver wouldnt break if corrupt data is received.

**Comment by mikeller** [comment]
Yes it is unfortunate, but this is more due to the development process we are using than due to this particular problem. Ideally, once we were at the stage of putting out release candidates, we would have stopped development on the upcoming release, and the only changes between the rcs and the release would be bugfixes, with all new features (like MSP specification changes) going into a later release.

Well the receiver does not break, it just knows what correct data looks like for every version, which makes it more robust than just assuming what extra data will mean, without caring about versions.

**Comment by mikeller** [comment]
@borisbstyle Are you ok with this being merged?

**Pull request merged**
