### PR TITLE
OSD Font "Clarity" - cosmetic fix to the "mAh used" label

### PR DESCRIPTION
**Pull request by tigert**
* Align the "mAh" label with the font style better, slightly bolder tiny characters
* Ran the font through dos2unix to keep mcm-tools happy - the java-charwizard seems to create different line endings to the ascii font file, which made mcm-tools grumpy. Luckily dos2unix solved that.

### CODE REVIEW

**Comment by mikeller** [comment]
Thanks for the update, @tigert. Is it possible to get images / screenshots of the label before / after the change, to make reviewing easier?

**Comment by tigert** [comment]
Sure.

Current style of "Clarity" small labels:
image

Old mAh: 
image

New to match the font style:
image

**Comment by AndersHoglund** [comment]
Nice, but it should preferably be "mAh" not "mAH", i.e. lower case "h" for "hours". 
For example something like this:
clarity_mah_mod

**Comment by mikeller** [comment]
Agreed with @AndersHoglund. I'd probably remove the white pixel at the top of the bow in the 'h', to make it look more unambiguosly like a 'h' and not 'k'.

**Comment by tigert** [comment]
I will need to test this in practice, but I agree the lowercase is a good idea, if it is readable.

**Comment by tigert** [comment]
Yeah, it makes sense and works in practice. Updated to be like this:

image

**Comment by mikeller** [comment]
That looks very readable now. Can you rebase / squash into one commit please?

**Comment by tigert** [comment]
Okay, I was not exactly sure how to do that in an elegant way, so I took my git --butcher-axe and force pushed a new branch from scratch over this one - hopefully it works?

**Comment by AndersHoglund** [comment]
Thnx, that one looks so much better than my suggestion. 
And as a back grounder, this is not really about looks. We should stick to SI scientific unit symbols, even though "hour" is not a SI unit. But still, SI specifies how it should be written: https://physics.nist.gov/cuu/Units/outside.html

**Comment by mikeller** [comment]
Looking sharp now, @tigert.

Re squashing, you will have to use --butcher-axe (a.k.a. `git push --force-with-lease`) at the end of rebasing / squashing anyway, to tell git to overwrite your earlier commits.
Normally it's easier if, instead of re-creating the branch, you do a `git rebase -i`, and then follow the instructions in the file popping up, selecting `pick` for the first of your commits, and `squash` for the rest.

**Pull request merged**
