### PR TITLE
Added requirement for node version 10.

### PR DESCRIPTION
**Pull request by mikeller**

### CODE REVIEW

**Comment by Docteh** [comment]
Is the engines section just for users? or for yarn/npm? I notice I'm still able to use nwjs 0.40.1 with this PR, and that ships with node 12.8.0

**Comment by Docteh** [comment]
Looks like its just used by yarn/npm
`yarn --ignore-engines` if you still have node v8 😉

**Comment by mikeller** [comment]
@Docteh: This is only used at build time at the moment. But you are making a good point that it would be better to detect the node runtime that comes with the version of NW.js that is used, and fail the build if it does not match the expectations.
On the other hand, considering that our runtime is web ready (to make it work as a Chrome web app), I think there is much less potential for JS version related problems to crop up at runtime.

**Comment by Docteh** [comment]
@mikeller ci.betaflight.tech says it has node `8.16.0` see https://ci.betaflight.tech/job/BetaFlight_Configurator/274/console

it also says it still has a `package-lock.json` file

**Comment by mikeller** [comment]
@Docteh: I've notified @wind0r about this, we'll see what can be done. The `package-lock.json` is probably a remnant of previous builds, and should be deleted.

**Pull request merged**
