### PR TITLE
ci.yml - workflow_dispatch

### PR DESCRIPTION
**Pull request by nerdCopter**
* allow manual trigger of github workflow action `ci.yml`.
* allows fork-owners to easily build all OS versions via actions tab.
* useful for fork-owner testing prior to making PR's.

image

### CODE REVIEW

**Comment by nerdCopter** [comment]
mistakenly closed, looking for a way to re-open....

**Comment by ASDosjani** [comment]
> mistakenly closed with force-push; looking for a way to re-open....

Push a new commit to this branch and a button will appear here to reopen this PR.

**Comment by nerdCopter** [comment]
iv'e opened a new one.  i had followed a how-to and it still did not show :P

**Comment by ASDosjani** [comment]
> iv'e opened a new one. i had followed a how-to and it still did not show :P

They won't accept the new. Try to reopen this.

**Comment by nerdCopter** [comment]
?? https://github.com/betaflight/betaflight-configurator/pull/3043

**Pull request closed without merging**
