### PR TITLE
Add current info to motors tab

### PR DESCRIPTION
**Pull request by McGiverGim**
Adds the voltage, current and current drawn to the motors tab:
image

This fixes https://github.com/betaflight/betaflight-configurator/issues/965 and replaces PR https://github.com/betaflight/betaflight-configurator/pull/967

### CODE REVIEW

**Comment by LightningStalker** [comment]
For some reason git does not know about this code.

    $ git checkout 0cfeb3bbdc82b2985ec15dc4f66ab2bff99bae4f
    fatal: reference is not a tree: 0cfeb3bbdc82b2985ec15dc4f66ab2bff99bae4f

**Comment by LightningStalker** [comment]
Anyone calibrating a current sensor is really going to appreciate this.

**Comment by jflyper** [comment]
How about providing per motor current (and voltage) display capability when ESC_SENSOR is selected? (May require layout change.)

**Comment by McGiverGim** [comment]
Sorry, I don't have hardware to test it, but I would let the total data where it is, and maybe this info can be shown inside each motor picture or between the picture and the slider.

**Pull request merged**
