### PR TITLE
Added introduction to Unified Targets.

### PR DESCRIPTION
**Pull request by mikeller**
Not the prettiest thing I've ever done:

image

### CODE REVIEW

**Comment by mikeller** [comment]
@McGiverGim: One thing I think we should be doing for the next configurator release is to rework the flashing tab. Some ideas that I have are:
- split the tab into multiple subtabs (like the PID Tuning tab) and use them as 'steps': 1. subtab: select target source, show information about different sources / channels, warnings, recovery information, load buttons; 2. subtab: display release notes for the selected / loaded target, configure flashing settings, flash button;
- reorganise how targets are selected (1. subtab). Put selection of firmware channel (release / release candidate / development) _after_ selection of the board. Reorganise board listings by manufacturer (full name), searching for manufacturer / board name;
- (stretch goal) allow 'rich' information like manufacturer logo, board image, board specific release notes to be displayed.

So the tooltip is just fixing the lack of information to enable users to make an informed choice of what target to choose for now, but we should look into changing this into a better form after 10.6.0.

**Comment by Docteh** [comment]
Do we want that tool tip to be wider? I saw the code that initializes jBox, and its odd enough to warrant a look just anyways.

https://github.com/betaflight/betaflight-configurator/blob/0648e5d927289caeb8dc17dea32cb6f68480a87f/src/js/gui.js#L347-L363

**Comment by mikeller** [comment]
@Docteh: I didn't even look that far when I added the text. If there's an easy way to override width for this tooltip only then that sounds reasonable. If not I would not want to refactor this this late in 10.6.0.

**Comment by Docteh** [comment]
I'll see if I can dig something acceptable up. 
image

Need to flag this one tooltip differently, somehow.

**Comment by Docteh** [comment]
@mikeller take a look, and judge.
image
<details><summary>diff for this</summary>

```diff
diff --git a/src/css/main.css b/src/css/main.css
index f7abdf22..3f60857f 100644
--- a/src/css/main.css
+++ b/src/css/main.css
@@ -1961,6 +1961,9 @@ button.active {
     max-width: 180px;
 }

+.jBox-Widetip {
+    max-width: 300px;
+}

 @media only screen and (max-width: 1055px) , only screen and (max-device-width: 1055px) {

diff --git a/src/js/gui.js b/src/js/gui.js
index b6cc0bba..3c1aeb4d 100644
--- a/src/js/gui.js
+++ b/src/js/gui.js
@@ -360,6 +360,21 @@ GUI_control.prototype.content_ready = function (callback) {
             outside: 'x'
         });

+        new jBox('Tooltip', {
+            theme: 'Widetip',
+            attach: '.cf_tip_wide',
+            trigger: 'mouseenter',
+            closeOnMouseleave: true,
+            closeOnClick: 'body',
+            delayOpen: 100,
+            delayClose: 100,
+            position: {
+                x: 'right',
+                y: 'center'
+            },
+            outside: 'x'
+        });
+
     });

     if (callback) callback();
diff --git a/src/tabs/firmware_flasher.html b/src/tabs/firmware_flasher.html
index d3e3d911..a675307d 100644
--- a/src/tabs/firmware_flasher.html
+++ b/src/tabs/firmware_flasher.html
@@ -26,7 +26,7 @@
                         <td><select name="board">
                                 <option value="0" i18n="firmwareFlasherOptionLoading">Loading ...</option>
                         </select></td>
-                        <td><span class="description" i18n="firmwareFlasherOnlineSelectBoardDescription"></span><div class="hel
picon cf_tip" i18n_title="firmwareFlasherOnlineSelectBoardHint"/></td>
+                        <td><span class="description" i18n="firmwareFlasherOnlineSelectBoardDescription"></span><div clas
s="helpicon cf_tip_wide" i18n_title="firmwareFlasherOnlineSelectBoardHint"/></td>
                     </tr>
                     <tr>
                         <td><select name="firmware_version">
```
</details>

We should definitely do something about creating a jBox object on every tab change, later.

**Comment by mikeller** [comment]
@Docteh: Thanks for the suggestion - makes it look a lot better, and it's additive, so it's low risk.

**Comment by McGiverGim** [comment]
> @McGiverGim: One thing I think we should be doing for the next configurator release is to rework the flashing tab.

Yes, we need to do something with it. With the new unified configs, divided by brand, etc. the actual selection has not too much sense. We can talk about it after the release.

**Pull request merged**
