### PR TITLE
Fixed profile switching in the CLI.

### PR DESCRIPTION
**Pull request by mikeller**

### CODE REVIEW

**Comment by KiteAnton** [comment]
What is the motivation for this change? Also can't test this now but is it more or less time added for profile switching compared to current solution?

**Comment by mikeller** [comment]
The motivation is to fix it, as the title says. ;-)
More time is added, since `'profile'.substring(1, 7) === 'rofile'`. Even with that fixed, the original code doesn't add a constant delay, since `timer_needle` is incremented for every line in the block. This value then gets doubled if 'profile' is found. (Probably if `timer_needle` was called `delayFromNow`, this would be less confusing.)

**Comment by mikeller** [comment]
Nah, I just can't live with doing it in this loopy way. Will rewrite it to send blocks line by line with promises. (Also, this use of fixed delays between line starts seems to be causing long lines to be cut off...)

**Comment by KiteAnton** [comment]
Well yes you are correct, I don't know how it ended up like that (it was added by me so no one else to blame :) ) 
Yes a more robust solution will be much better, current solution is more assumption based.

**Comment by mikeller** [comment]
No problem. The way the original code does this is so convoluted, it took me a while to get my head around it too.

**Pull request closed without merging**
