### PR TITLE
Add capacitor android

### PR DESCRIPTION
**Pull request by McGiverGim**
This is a PR trying to add Capacitor support to the Configurator.

I make it in a draft state because I was trying to make Serial working and I'm having problems to debug it. I've been trying to debug with an FC connected. I have tried wifi debug without luck with a real device, and usb passthrough with the emulator without luck neither. Maybe other with more knowledge (or luck) can give it a try.

I have three commits, to try to let the things clear and be able to divide this PR in parts in the future:
- The first adds Capacitor to the Configurator with Android support. The major part of files are created by Capacitor.
- The second one removes some lines that make the app crash (there is not `chrome` var here)
- The third one adds one library for usb-serial to the app, but I can't advance because the problems to debug explained. Look at the `webSerial.js` file, is where I was trying to do some tests.

To test this PR you need to have Android Studio installed. You need some Virtual emulator created (or a real device connected in debug mode). I've added some commands to the `package.json` to make this easier. The steps are:
0. Execute a `yarn install` to update the packages.
1. Build the vite app with `yarn build` 
2. Sync the contents of the vite app with the Android app with `yarn cap:sync` 
3. Start the Android app in the emulator with `yarn cap:android` (you can use too the `npx cap open android` command to open Android Studio with the app and execute from there).

Alternativelly to test this faster I've added a `yarn android` command that does the steps 1-2-3 above in one. The hot deploy is not working in this version, it's in the todo list.

### CODE REVIEW

**Comment by McGiverGim** [comment]
Rebased against master

**Comment by haslinghuis** [comment]
Would love a solution which not only includes Android but also IOS support

**Comment by McGiverGim** [comment]
True. I don't have Mac or Iphone devices, so other must do this work. But yes, the library selected for serial must be compatible with both systems to simplify things.

**Comment by McGiverGim** [comment]
@haslinghuis rebased.

If we plan to move forward with this, I think we need to merge this as is. I've tried to make this work (Betaflight in Android), but I was not able to make hot reload working with capacitor on Android. The app crashes. And without this, it's a nightmare to develop against this (I tried to add a serial library but without hot reloading it's very difficult and slow).

I think is better to merge, and let others try with little PRs to make this advance. If for some reason we decide to remove this later, it's as easy as remove the `Android` folder, the `capacitor.config.json` and revert the changes in the `package.json` of this commit.

I've added a little of branding with Betaflight icon to this PR, but it does not work too well, but for a first version it's ok while we make this work.

**Comment by McGiverGim** [comment]
Rebased again against master...

**Comment by McGiverGim** [comment]
I think I have it working with "live reload", so it's a first step. The problem is that it needs some "manual" changes, that I can't push.
Maybe someone knows how to automate it as an "alternate" build/run.
I detail here the changes:
- Start the vite server with `yarn dev --host`. This will publish the server with a "private" address appart of the habitual `localhost:8000`.
- Add to the `capacitor.config.json` the server url of the previous step:
```
  "server": {
    "url": "http://192.168.100.15:8000"
  }
```
- Add permission for clear text traffic to the `AndroidManifest.xml`:
```
android:usesCleartextTraffic="true"
```
- Now you can start it with `yarn android`

**Review by haslinghuis — APPROVED** [review]

**Comment by McGiverGim** [comment]
Added new commit with "basic" reload.
Instructions:
- Start the server with `yarn dev --host`
- Copy the IP of the server (not the localhost one) to the `capacitor.config.dev.json`
- Execute a `yarn android:dev`

I will try to make the copy IP step automatic, but I don't know if I will be able.

**Comment by McGiverGim** [comment]
Sorry, it seems the --configuration parameter only works with the ionic command, not with the npx one. So I need to rethink this...

**Comment by McGiverGim** [comment]
I reverted the latest change. We will need to do the live reload  manually at this moment.

The documentation says that the config file can be a .ts file, so it can be generated dynamically. I don't know if this can be a good approach.

**Comment by McGiverGim** [comment]
I've added some very basic instructions for Android to the README, only development at this stage, because it's not functional, but can help if someone want to give it a try.

**Comment by nerdCopter** [comment]
this PR on android 14 phone, Chrome :
image

**Comment by nerdCopter** [comment]
i had to `chmod +x ./android/gradlew` as per 
```
 Running Gradle build - failed!
[error] gradlew file does not have executable permissions. This can happen if the Android platform was added on a
        Windows machine. Please run chmod +x ./android/gradlew and try again.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

afterward, i could not continue the entire `yarn android:dev` because i do not have SDK installed.

**Comment by McGiverGim** [comment]
The result using PWA it's the same than with this PR if you build it. The problem it's the web serial, fails and crashes the loading. 
We need to clean and unify all the serial implementations and then add another one for Android.
This PR only adds the base to start with the Android work.

**Review by nerdCopter — APPROVED** [review]
- may need another rebase :( i saw flashing bar not on bottom; otherwise still works on PC.
- approving for the workflow

**Comment by RdXuanQi** [comment]
I set up the environment and tried to build Betaflight Configurator for Android, but checkWebSerialSupport() doesn't work on Android, USB, Serial Port, and Bluetooth
checkWebBluetoothSupport()
checkWebUSBSupport()
all return false,

I am using a Xiaomi Mi 10
Do I need to do some additional configuration?

549fdba550c09962d8c7b4a01d1df61d

**Pull request merged**
