### PR TITLE
Restore experimental backup and restore only for virtual and fw below 4.3

### PR DESCRIPTION
**Pull request by haslinghuis**
Restores
- JSON `restore` for virtual connections
- JSON `backup` for firmware version below 4.3
- Arming flags were hidden

Further `cleanup` of semver below API_VERSION_1_41.

### CODE REVIEW

**Review by blckmn — APPROVED** [review]

**Comment by KarateBrot** [comment]
Why do we want to restore this? Afaik, it is broken and doesn't work. It should have been removed a long time ago, no?

**Comment by McGiverGim** [comment]
It works, for the virtual fc. It's not up to date, but works.

**Comment by haslinghuis** [comment]
@KarateBrot It's hidden from firmware 4.3 and above. Added again for virtual.

We can look at the analytics is the functions are still used.

**Comment by KarateBrot** [comment]
I don't understand why we still need this. For the virtual FC there is no config you need to save.

This functionality is repeatedly being "misused" by beginners to save the FC settings when actually it doesn't save all settings. It's not a good idea to have these deprecated buttons in the configurator for ages now without proper support. If the buttons are supported on 4.0 (or some old version) maybe we should just hide them on newer BF versions?

**Comment by haslinghuis** [comment]
Actual agree as the backup button was removed in 4.3 / 10.8 there is no use for restoring and old backup from a older firmware version as there were no complaints about being removed. Also there are no migration rules since a long time.

With this in mind it's best to remove it after all.

**Comment by McGiverGim** [comment]
The idea was to try to help people at distance. Someone sends the backup to other, and the other can load it in the virtual fc and see how it looks. And try to help suggesting changes.

**Comment by haslinghuis** [comment]
Ok, let's leave it for virtual as it doesn't exist for current firmware and beyond. 

Just pushed a sonar fix. @McGiverGim please approve.

**Review by McGiverGim — APPROVED** [review]
Approved. If someone is able to load a backup into the virtual fc at some moment, I will be happy to remove it.

**Review by KarateBrot — APPROVED** [review]

**Pull request merged**
