### PR TITLE
Moved yaw jump prevention to separate row. Added help text.

### LINKED ISSUE #99: Move Yaw D out of the PID tuning section
Since Yaw D is now yaw jump prevention, I would suggest moving it out of the PID tuning section table and appropriately labeling it as "yaw jump prevention".  There continues to be confusion about this parameter relocating it and renaming it should help.  I think it should stay on the PID Tuning tab - just not in the PID values table.

### PR DESCRIPTION
**Pull request by mikeller**
Fixes #99.

### CODE REVIEW

**Comment by borisbstyle** [comment]
Dont merge this yet. I am still working to investigate alternative ways to do this

**Comment by mikeller** [comment]
@borisbstyle What do you want to do with this one now?

**Comment by borisbstyle** [comment]
Remove yaw D on betaflight pidc.

For legacy it can be yaw jump prevention perhaps?

**Comment by mikeller** [comment]
To make sure I get this right:

- remove yaw D from the 'Yaw PID' row (this PR does this)
- show old Yaw D in a 'Yaw jump prevention' row if legacy PID controller is selected (this PR, plus hide row for Betaflight controller)

**Comment by borisbstyle** [comment]
Yeah something like that.

**Comment by mikeller** [comment]
@borisbstyle: Done. Please check if good to go now.

**Comment by borisbstyle** [comment]
yes checking right now

**Comment by borisbstyle** [comment]
Kind of reversed way lol :dancer:

**Comment by mikeller** [comment]
So just to make sure I get it right this time: 

'Yaw jump prevention' row should *not* show if the legacy PID controller is selected? ;-)

(And in this case, should the yaw d parameter be available as Yaw D if the legacy PID controller is selected?)

**Pull request merged**
