### PR TITLE
use-select2

### PR DESCRIPTION
**Pull request by haslinghuis**
As requested by @limonspb

### CODE REVIEW

**Comment by limonspb** [comment]
> As requested by @limonspb

i see its not a complete revert of the initial PR, why is that?

**Comment by haslinghuis** [comment]
Why?

Don't you like the added feature:

image

**Comment by limonspb** [comment]
> > i see its not a complete revert of the initial PR, why is that?
> 
> * This only reverts the use of select2.
> * Sort has been improved in the mean time - so using that.
> * Also don't you like the added feature:
> 
> image

Yeah all good as long as debug mode allows typing in :) thanks sir

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by limonspb — APPROVED** [review]

**Review by McGiverGim — APPROVED** [review]

**Review by nerdCopter — APPROVED** [review]
tested good on one FC

**Comment by HThuren** [comment]
@haslinghuis , looks good. What is the differenece between multiple_select and select2 ?

**Comment by haslinghuis** [comment]
select2 adds a search box afaik but it's just a different implementation:

https://multiple-select.wenzhixin.net.cn/
https://select2.org/

**Pull request merged**
