### PR TITLE
Osd altitude version gated

### PR DESCRIPTION
**Pull request by mikeller**

### CODE REVIEW

**Comment by borisbstyle** [comment]
OSD tab is broken. Just tested on existing 3.0

image

**Comment by mikeller** [comment]
Any exceptions in the console?

**Comment by borisbstyle** [comment]
image

**Comment by mikeller** [comment]
Are you sure the firmware you are using has OSD support enabled? This is the same exception that was always there when enabling the OSD feature in firmware without support for OSD.

**Comment by borisbstyle** [comment]
Yes it works without this PR! I am not changing anything on the FC when switching back and fourth to master

**Comment by borisbstyle** [comment]
The master
image

**Comment by mikeller** [comment]
Have you changed the MSP version to 1.21?

**Comment by borisbstyle** [comment]
No I didnt change anything on my FC

I am testing the backwards compatibility ;)

**Comment by mikeller** [comment]
So you are testing with 3.0.0 as released?

**Comment by borisbstyle** [comment]
exactly!

**Comment by mikeller** [comment]
Ok. Looks like simple feature gating of the MSP changes is not enough to stop this from breaking. Remote debugging this way could take forever, so we probably better wait until somebody who can debug locally can have a look at this.

**Comment by nathantsoi** [comment]
sweet. nice work guys. i'll merge, test and update as necessary

**Pull request merged**
