### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by McGiverGim**
Update of translations.

This has a lot of changes because:
- The automatic integration between Crowdin and Betaflight is broken, and I don't have permissions to fix it. So now I upload them manually. It was broken since end of november.
- A lot of phrases have changed, a little type, little reword, etc. and this removes the current approved translation. The translators need to do it again, which is a huge work.

This is the current state of the translations:
image

So this release of Configurator will have very few translations.

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Review by Asizon — APPROVED** [review]
@McGiverGim did you contact directly to mikeller and ask for permisions?

**Comment by McGiverGim** [comment]
I tried in the general chat without luck. I will try a private.

**Review by DusKing1 — APPROVED** [review]

**Review by haslinghuis — APPROVED** [review]

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Review by ctzsnooze — APPROVED** [review]

**Pull request merged**
