### PR TITLE
Fix broken link in messages.json

### PR DESCRIPTION
**Pull request by fkoran**
USB flashing instructions have moved from

https://betaflight.com/docs/wiki/archive/Installing-Betaflight

to

https://betaflight.com/docs/development/USB-Flashing

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Comment by haslinghuis** [comment]
Oops. you did not create a development branch.

**Review by nerdCopter — APPROVED** [review]

**Comment by haslinghuis** [comment]
@nerdCopter this PR is based on master instead of development branch.

**Comment by nerdCopter** [comment]
@fkoran , pull-request template states: 

_

> 2. Pull requests will only be accepted if they are opened against the `master` branch of our repository. Pull requests opened against other branches without prior consent from the maintainers will be closed;

_

please create a development-branch based from master to create a pull-request from.

**Pull request closed without merging**
