### PR TITLE
Add open source disclaimer to landing page

### PR DESCRIPTION
**Pull request by jflyper**
Probably need a brush up in the text and the formatting.

### CODE REVIEW

**Comment by mikeller** [comment]
Hmm, this is all messing up the facebook group advertisement and logo at the bottom:

image

**Comment by jflyper** [comment]
@mikeller I'm actually not good at doing this. @McGiverGim ?

**Comment by McGiverGim** [comment]
Ok, I will look into it

**Comment by McGiverGim** [comment]
@jflyper there is a similar message at the right of the page:
image

So we can:
- Update the message in the right with your text
- Remove the message in the right

What do you think?

**Comment by mikeller** [comment]
Good find, @McGiverGim! :laughing: 

I think we should just update the message on the right to include the 'without warranty' part.

**Comment by McGiverGim** [comment]
@jflyper do you want to update this PR? Or do you prefer to close it and that I open once new? Is only to modify this line:
https://github.com/betaflight/betaflight-configurator/blob/2cec389916abbdf8c52062de64853dd476aede9f/locales/en/messages.json#L534-L536

**Comment by TheIsotopes** [comment]
@mikeller @McGiverGim imo as here it looks good
zwischenablagebild

**Comment by McGiverGim** [comment]
@TheIsotopes push your PR if you want, I will close this then.

**Comment by McGiverGim** [comment]
@jflyper I close this, has been fixed in https://github.com/betaflight/betaflight-configurator/pull/1138

**Pull request closed without merging**
