### PR TITLE
Make serial connection timeout dynamic

### PR DESCRIPTION
**Pull request by haslinghuis**
As a long time request this PR makes the serial reconnection timeout dynamic with a timeout of 10 seconds.
The PR makes sure we have a new connection on reinitialization and waits for the connection to be ready and fixes the bug connecting to soon with a predetermined timeout now verified by timestamp.

image

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by ctzsnooze** [comment]
The commit does several things...

- removes the fixed 'settling time' of 0.1s that previously applied when auto-reconnecting (plugging in a board with auto-connect switch enabled)
- when a re-connect is required, eg after changing ports when a reboot is needed, the re-connection is now dynamic, taking only as long as is needed
- this removes the need for a manual re-connection time delay (which used to be set under 'Options' tab)

Here is a console log after clicking 'Save' in Ports, where it took 3.1s to reconnect

```
Settings Saved in EEPROM
serial_backend.js:832 Reintialising Connection
MSPHelper.js:1687 Arming disable
serial.js:249 serial: closed connection with ID: 2, Sent: 36597 bytes, Received: 463632 bytes
port_handler.js:129 PortHandler - Removed: [{"path":"/dev/cu.usbmodem0x80000001","displayName":"Betaflight STM32F411","vendorId":1155,"productId":22336},{"path":"/dev/tty.usbmodem0x80000001","displayName":"Betaflight STM32F411","vendorId":1155,"productId":22336}]
port_handler.js:169 PortHandler - Found: [{"path":"/dev/cu.usbmodem0x80000001","displayName":"Betaflight STM32F411","vendorId":1155,"productId":22336},{"path":"/dev/tty.usbmodem0x80000001","displayName":"Betaflight STM32F411","vendorId":1155,"productId":22336}]
port_handler.js:276 Porthandler detected device Betaflight STM32F411 on port: /dev/tty.usbmodem0x80000001
serial_backend.js:67 Connecting to: /dev/tty.usbmodem0x80000001
serial.js:119 serial: connection opened with ID: 3 , Baud: 115200
serial_backend.js:246 Requesting configuration data
serial_backend.js:849 Serial connection available after 3.1 seconds
```

Tested, works well.

**Review by ctzsnooze — DISMISSED** [review]

**Comment by Asizon** [comment]
Seems a new improvement not a bug fix, weneed to release 10.8.0 this year

**Review by ctzsnooze — APPROVED** [review]

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by limonspb — APPROVED** [review]

**Pull request merged**
