### PR TITLE
Add switchable dark mode

### PR DESCRIPTION
**Pull request by IvoFPV**
FR #1306 Add switchable dark mode

### CODE REVIEW

**Comment by IvoFPV** [comment]
sensordark
setupdark
configdark

**Comment by IvoFPV** [comment]
Still WIP. Yellow color on tab titles and elsewhere was used to try and stay in original theme, but after discussing with others, more contrast is preferred. Possibly adding an option to change the accent color when in dark mode.

**Comment by binlan** [comment]
i like the dark mode so far. there is just one glitch in the osd tab. if i hover over the elements in the preview screen, the elements in the left table get highlighted - but backround white with white font colour. furthermore, on the right side totally wrong elements in the summary screen table were highlighted. but thats a different bug i think.

**Comment by IvoFPV** [comment]
@binlan Hey, thanks for pointing that out. I haven't had time to work on this lately, so this is just a first version. Do you have any other suggestions maybe if you have been using it?

**Comment by binlan** [comment]
@IvoFPV i am very happy with the current state. didnt recognized any other issues beside the one i described above.

**Comment by mikeller** [comment]
@IvoFPV: So this is done and ready for review now?

@McGiverGim: What is your opinion on this?

**Comment by mikeller** [comment]
@McGiverGim: Yes, I agree, making the accent colour choosable (and no other colour) does not seem to make much sense - we should decide for one and then go with it.

All in all the dark theme still seems to be having a number of rough edges:

image

Also, I agree re maintainability - after all the configurator is an utility, and focus and effort should go into functionality more than styling.

**Comment by IvoFPV** [comment]
@mikeller There are still some rough edges which I wanted to fix. Users seem to have not liked the yellow betaflight theme so I added the accent color setting. It could be removed easily if we wanted to stick to just this one. Other then those small styling issues you pointed out, there seem to be no other issues.

**Comment by IvoFPV** [comment]
I removed it and fixed a couple of small issues. This should now be ready.

**Pull request merged**
