### PR TITLE
Move GPS configuration to GPS tab

### PR DESCRIPTION
**Pull request by haslinghuis**

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by McGiverGim** [comment]
Thanks! This is a good move. As always, it will be great some text and some screen capture in the PR ;)

**Comment by haslinghuis** [comment]
image

image

**Comment by haslinghuis** [comment]
@McGiverGim I might be wrong but after looking at io/gps.c in firmware autobaud and autoconfig are only applicable for UBLOX protocol.

Should we hide autobaud and autoconfig for NMEA. Not sure about MSP as this could use both protocols.

**Comment by KarateBrot** [comment]
I think it would be best to put the GPS configuration first. Example layout:

```
| Configuration       | GPS                  |
----------------------------------------------
| GPS Signal Strength | Current GPS Location |
```

**Comment by haslinghuis** [comment]
image

**Comment by haslinghuis** [comment]
> I might be wrong but after looking at io/gps.c in firmware autobaud and autoconfig are only applicable for UBLOX protocol. Should we hide autobaud and autoconfig for NMEA. Not sure about MSP as this could use both protocols.

**Comment by McGiverGim** [comment]
> I might be wrong but after looking at io/gps.c in firmware autobaud and autoconfig are only applicable for UBLOX protocol. Should we hide autobaud and autoconfig for NMEA. Not sure about MSP as this could use both protocols.

I think you are right. I think remember some PR to add the feature for NMEA but maybe I'm wrong.

**Comment by KarateBrot** [comment]
I think a grey divider line would be nice here (like in the original configuration window in the "Configuration" tab)

grafik

**Comment by haslinghuis** [comment]
image

**Comment by nerdCopter** [comment]
Config-tab's GPS, OSD, LED_STRIP, Transponder not only enable the feature, but also tell the configurator to display the tab as well.  With this change, it changes the paradigm.  and the GPS tab will always be visible, even on non-GPS builds.  Is this wanted? Would the other features follow the new pattern?

**Comment by haslinghuis** [comment]
The GPS feature is driven by the ports tab sensor input field.
Disabling the feature on the GPS tab leaves the port setting in tact and removes the GPS tab.
To re-enable GPS we have to save and reboot on the Port tab.

Only need to fix when the feature is disabled we don't return to the GPS tab while it's no longer in the menu.

**Comment by McGiverGim** [comment]
For this reason I recommended enable and disable features in the "firmware" part and not in the configurator part. If this was done in the firmware part, enable it when GPS selected in the ports tab, and removed when not, we would simply need to remove the toggle from the tab. Now is more difficult, because the user can let the things incoherent if uses CLI or preset to configure some port.

Maybe we can try to remove the toggle from the GPS tab, hopping that any user that wants GPS configures it from the ports tab and not CLI or presets. But this will bit us later or soon.

**Comment by haslinghuis** [comment]
Moving the feature switch from GPS to configuration tab seems to be most consistent.

For future work thinking about replacing features with port functions but also like to do something with the build config.

image


image

**Comment by KarateBrot** [comment]
> @haslinghuis 
> Moving the feature switch from GPS to configuration tab seems to be most consistent.

That makes a lot of sense because GPS is a feature in the BF firmware. It fits right in. 👌

grafik

**Comment by KarateBrot** [comment]
@haslinghuis I think there is a bug. My GPS tab won't show up even if GPS is activated:

grafik

**Comment by haslinghuis** [comment]
@KarateBrot have you enabled GPS on ports tab?

**Comment by haslinghuis** [comment]
image

**Comment by KarateBrot** [comment]
Yes I haveGPS enabled in the ports tab. I don't have a GPS receiver connected but it should still show me the GPS tab, no?

**Comment by haslinghuis** [comment]
Windows, Linux, OSX ???

Have tested these scenario's with and without GPS on Linux. Cannot reproduce on Linux ?

**Comment by KarateBrot** [comment]
Oh, sure, sorry. It's Windows...

**Comment by haslinghuis** [comment]
K will check there too, but it's has a much slower processor :)

**Comment by haslinghuis** [comment]
Working on Windows too (without GPS attached).

Did you build from github?
Did you flash with GPS build option enabled?

**Comment by HThuren** [comment]
Maybe more alignment
image

**Comment by haslinghuis** [comment]
@HThuren - check `NMEA` and the box resizes as less options are available.

**Comment by KarateBrot** [comment]
> @haslinghuis 
> Working on Windows too (without GPS attached).
> 
> Did you build from github? If so might need to clean cache, dist, debug and node_modules. 

I cleaned all these and built again using
```
yarn install
yarn start
```
but it still doesn't show up in the tabs. Weird...

> Did you flash with GPS build option enabled?

Yes, I did. Otherwise the GPS switch would turn off automatically again and would not stay activated.

Maybe this solves itself at some point. Don't worry about it. Otherwise I will probably hassle you about it sometime in the future. 😀

**Pull request merged**
