### PR TITLE
Add DEBUG2 OSD element

### PR DESCRIPTION
**Pull request by haslinghuis**
- adds DEBUG2 OSD element introduced in https://github.com/betaflight/betaflight/pull/13800

image

### CODE REVIEW

**Comment by nerdCopter** [comment]
code looks good, but i'm getting it as `unknown`. :man_shrugging: 
image

**Comment by nerdCopter** [comment]
`55218226`:
image
image

**Review by nerdCopter — APPROVED** [review]

**Comment by nerdCopter** [comment]
maybe it's misaligned by a character?

**Comment by haslinghuis** [comment]
We could add one space to DEBUG  to compensate

**Review by KarateBrot — APPROVED** [review]

**Pull request merged**
