### PR TITLE
Added dmg-background.psd Photoshop file

### PR DESCRIPTION
**Pull request by basdelfos**

### CODE REVIEW

**Comment by mikeller** [comment]
@basdelfos: What is this used for?

**Comment by basdelfos** [comment]
This is the source file for the DMG image background. If someone wants to update the background image, e.g. new logo, they can use this PSD file to edit the image.
The actual image that is used in the DMG lives in `./images/`.

**Comment by mikeller** [comment]
Ah. Good idea to stick it in here. Since it is not clear what this is used for from the scripts, I think there should be a mention of it in the README.

**Comment by basdelfos** [comment]
Yes, will add that to the README

**Pull request merged**
