### PR TITLE
CF new LED strip port

### PR DESCRIPTION
**Pull request by gaelj**
Addresses #8

### CODE REVIEW

**Comment by skaman82** [comment]
@gaelj if the LED 0 ist configured ONLY as Color or Modes & Orientation all other LEDs don't work correctly (larson scanner stops, gui changes are not updated a.s.o.). As soon I add throttle, warnings  or any other mode under the main mode, it works again.

**Comment by gaelj** [comment]
Strange. On my side, setting LED 0 to color only doesn't break anything. Could you post your complete LED config dump ?

**Comment by skaman82** [comment]
@gaelj This results in first LED being red and the second two lighting yellow (larson not working).



bildschirmfoto 2016-06-25 um 22 08 01


# led
led 0 0,0::C:2
led 1 1,0::CO:4
led 2 2,0::CO:4
led 3 0,0::C:0
led 4 0,0::C:0
led 5 0,0::C:0
led 6 0,0::C:0
led 7 0,0::C:0
led 8 0,0::C:0
led 9 0,0::C:0
led 10 0,0::C:0
led 11 0,0::C:0
led 12 0,0::C:0
led 13 0,0::C:0
led 14 0,0::C:0
led 15 0,0::C:0
led 16 0,0::C:0
led 17 0,0::C:0
led 18 0,0::C:0
led 19 0,0::C:0
led 20 0,0::C:0
led 21 0,0::C:0
led 22 0,0::C:0
led 23 0,0::C:0
led 24 0,0::C:0
led 25 0,0::C:0
led 26 0,0::C:0
led 27 0,0::C:0
led 28 0,0::C:0
led 29 0,0::C:0
led 30 0,0::C:0
led 31 0,0::C:0


# color
color 0 0,0,0
color 1 0,255,255
color 2 0,0,255
color 3 30,0,255
color 4 60,0,255
color 5 90,0,255
color 6 120,0,255
color 7 150,0,255
color 8 180,0,255
color 9 210,0,255
color 10 240,0,255
color 11 270,0,255
color 12 300,0,255
color 13 330,0,255
color 14 0,0,0
color 15 0,0,0


# mode_color
mode_color 0 0 1
mode_color 0 1 11
mode_color 0 2 2
mode_color 0 3 13
mode_color 0 4 10
mode_color 0 5 3
mode_color 1 0 5
mode_color 1 1 11
mode_color 1 2 3
mode_color 1 3 13
mode_color 1 4 10
mode_color 1 5 3
mode_color 2 0 10
mode_color 2 1 11
mode_color 2 2 4
mode_color 2 3 13
mode_color 2 4 10
mode_color 2 5 3
mode_color 3 0 8
mode_color 3 1 11
mode_color 3 2 4
mode_color 3 3 13
mode_color 3 4 10
mode_color 3 5 3
mode_color 4 0 7
mode_color 4 1 11
mode_color 4 2 3
mode_color 4 3 13
mode_color 4 4 10
mode_color 4 5 3
mode_color 5 0 9
mode_color 5 1 11
mode_color 5 2 2
mode_color 5 3 13
mode_color 5 4 10
mode_color 5 5 3
mode_color 6 0 6
mode_color 6 1 10
mode_color 6 2 1
mode_color 6 3 0
mode_color 6 4 0
mode_color 6 5 2
mode_color 6 6 3
mode_color 6 7 6
mode_color 6 8 0
mode_color 6 9 0
mode_color 6 10 0

**Comment by skaman82** [comment]
could you maybe build me a SPRacing F3 test he? Having some troubles again compiling I guess. Just tried my latest hex of your branch on another board and it is not booting at all.

**Comment by gaelj** [comment]
I see the problem. When only "fixed" modes exist, LEDs never get updated.

**Comment by borisbstyle** [comment]
@gaelj 
Also this uses newer CF MSP api version than the current betaflight one. Did you check for other changes in the MSP version? 

I am afraid we have to postpone this till 3.x versions.

**Comment by gaelj** [comment]
The bug is solved, I'll be looking intp other MSP changes and solving the conflicts.

**Comment by gaelj** [comment]
@borisbstyle why these conflicts ? i've based the branch on the Betaflight branch, should I rebase on development ?

**Comment by gaelj** [comment]
Doing so locally doens't generate any conflict either.

**Comment by borisbstyle** [comment]
no rebase on master

**Comment by gaelj** [comment]
It should merge with master.

**Comment by martinbudden** [comment]
@borisbstyle , is anything holding up this PR?

It would be good to get it merged in, so that the betaflight LED changes can also be merged in.

**Comment by gaelj** [comment]
Only one thing: `js/backup_restore.js` lines 615 ety 625 must be adapted to the BFC version it will be realesed on.

**Comment by borisbstyle** [comment]
@gaelj 
I assume I can merge this?

**Pull request merged**
