### PR TITLE
Disable video modes that are not in the firmware

### PR DESCRIPTION
**Pull request by haslinghuis**
Disable elements not included in the build instead of hiding them.

See also https://github.com/betaflight/betaflight/pull/13320#issuecomment-1907224847

Recommendation is either use `OSD_SD` or `OSD_HD` not both as switching elements is not accounted for in firmware.

### CODE REVIEW

**Comment by haslinghuis** [comment]
Trying with https://github.com/betaflight/betaflight/pull/13308 but still canvas stays on 30x13

**Comment by haslinghuis** [comment]
@SteveCEvans this sets `vcdProfileMutable()->video_system = VIDEO_SYSTEM_HD` but `osdConfigMutable()->displayPortDevice = OSD_DISPLAYPORT_DEVICE_MSP` is not set in firmware - even without condition.

Was looking in a way to revert back to analog if user decides to do so as we now only switch to HD

**Comment by mituritsyn** [comment]
OSD_Hd has only one option at the moment, so the whole 'Video Format' section could be hidden.

**Comment by nerdCopter** [comment]
i rather see the section to know the configurator is setting it correctly.  at least in this iteration, maybe 11.0 can hide the section once it is known to 100% work.

**Comment by nerdCopter** [comment]
are config.h's loaded by the time target.h is processed?
if yes, then maybe 
```
#if (defined(SOFTSERIAL1_TX_PIN) && defined(SOFTSERIAL1_RX_PIN) ) || (defined(SOFTSERIAL2_TX_PIN) && defined(SOFTSERIAL2_RX_PIN) ) 
#define USE_SOFTSERIAL
#endif
```
???

**Comment by mituritsyn** [comment]
> Hence there is a lot more work to go here.

maybe we need a simple solution for release and subsequent refactoring of the whole subsystem

**Comment by ctzsnooze** [comment]
Mark, the OSD tab display must follow the `vcd_video_system` value.  It simply doesn't.

If I have an FC with pure HD-only firmware, but the canvas dimensions are SD at the start, there is no way in configurator, other than changing the canvas values manually in CLI, to get the canvas values correct.

When I click 'SAVE', and when `vcd_video_system = HD`, the screen should change size and the `OSD_CANvAS` values should be set to HD values, if they are not already.

So we need a check of the canvas dimensions when entering the OSD tab, and on saving the OSD setup.  I don't mind if the check is in firmware or in Configurator.  

But in Configurator, we could say, if canvas width is <35, then it is SD.  And then, if the user wants HD with `vcd_video_system = HD` and  if `canvas width < 35`, we set canvas width and height to HD default values.  

It is possible that the user has customised their HD OSD width and height, but it is not likely they would intend to use a width <35.  So if the width and height were previously set to a non-SD range, the above check would not remove their HD screen dimension customisations.

If the `vcd_video_system` is AUTO, and the build is HD_ONLY, then the above applies.

If the `vcd_video_system` is AUTO, NTSC or PAL, then if the canvas width is > 35, we reset the canvas to appropriate values according the the video system user selection.

With this PR, in an HD-only build, the canvas is locked at 30x16, despite `vcd_video_system = HD`; it can only be updated manually in CLI by entering width and height numbers.

Users will not swap rapidly from one mode to the other, so for now don't worry about re-positioning elements.

Just get the canvas width and height to honour the user selected video format.

**Comment by ctzsnooze** [comment]
PS about PAL and NTSC...

PAL(720 x 576) is 20% 'taller' than NTSC  (720 x 480) in 'pixels'.  If all pixels were 'square', the NTSC width:height ratio would be 1.5:1, and for PAL 1.25:1.  

Interestingly on the old analog TV's, both NTSC and PAL pixels were non-square.  NTSC pixels are taller than wide, ratio 1:0.906, whereas PAL pixels are wider than they are tall, 1:1.06.  If we consider the non-square pixels, the old analog TVs ended up with almost exactly the same screen ratios, 1:1.36 for NTSC and 1:1.38 for PAL.

But if we stick to 'pixels' and draw them 'square', the ratios are quite different, and NTSC images end up being more of a wide-screen, with fewer vertical pixels.

in display.h I see:
```
#define VIDEO_COLUMNS_SD          30
#define VIDEO_LINES_NTSC          13
#define VIDEO_LINES_PAL           16
```

These ratios don't quite match the pixel ratios of either NTSC or PAL. That explains why I often had to make manual adjustments.

So I guess we need a way in Configurator to detect whether the user wants to use HD or SD.

If they select HD, and the values for canvas are in the SD range, ie width <35, we should use apply HD values, and vice versa.

Otherwise, unless the user changes their video system selection, we should NOT modify the user's canvas settings, which may have been carefully customised.

**Comment by limonspb** [comment]
I think hiding unused OSD modes should be separated and go in 10.11 or 11.0.
If there are issues with the current osd tab, of course we should solve them for 10.10, but separately from improvements.

**Comment by HThuren** [comment]
You can make a Build with both OSD_SD and OSD_HD, something to take into consideration or maybe change.

**Comment by SteveCEvans** [comment]
We don’t just need to consider `vcd_video_system`, but also `osd_displayport_device`. HD is only supported for MSP.

Alas WS and DJI don’t send the `MSP_SET_OSD_CANVAS` command to invoke https://github.com/betaflight/betaflight/blob/42267349db0c92a0e1063bd1d07633a3322dfb07/src/main/msp/msp.c#L4318

When switching to HD the canvas size gets initialised at
https://github.com/betaflight/betaflight/blob/42267349db0c92a0e1063bd1d07633a3322dfb07/src/main/msp/msp.c#L4183

Rather that hiding the video resolution selection on the configurator, wouldn’t it be better to just grey out the options which aren’t available?

That said, do we have a big enough issue here for this to be classified as a bug and thus worthy of inclusion in 4.5/10.10?
The configurator should mess with the canvas size, but should pick up what the firmware tells it.

**Comment by haslinghuis** [comment]
Hiding video option is not the issue - as it reflects what is configurable in the build. Would be the same as gray out options for me.

`MSPCodes.MSP_SET_OSD_CANVAS` does not fire as `MSP_SET_OSD_CONFIG` already sets video_system correctly. So this call does nothing at the moment.

**Comment by ctzsnooze** [comment]
PR still fails this test:
- flash a board with OSD_HD option only, full chip erase
- connect to Configurator, go to OSD, note that `HD` is selected in Video Format (indeed it is the only option)
--> BUG: OSD screen view shown in SD dimensions, cannot be configured properly
- click `Save`
--> BUG: OSD view is still in SD dimensions, cannot be configured properly

**Comment by haslinghuis** [comment]
Did you use https://github.com/betaflight/betaflight/pull/13311 in testing?

**Comment by ctzsnooze** [comment]
There shouldn't be a need for all that MSP code.  This should be fixed in Configurator, shouldn't it?

**Comment by ctzsnooze** [comment]
The alternative is to use Presets to configure the relevant setups, or a drop-down that can apply 'snippets' to suit the video system, eg a snippet that sets SD-PAL, one for SD_NTSC, one for HDZero, one for DJIO3, one for Walksnail.

What I guess I'm thinking is that rather than complex MSP code, we just let the user configure it here in Configurator, like we do all the other configuration stuff.

**Comment by ctzsnooze** [comment]
The simplest fix would be to retain "Auto" in the list of Video Format options, even in HD-only builds.

The HD-only build would default to Auto.  All the user has to do is select HD and save, and that will work.

Just leave out PAL and NTSC.

**Comment by haslinghuis** [comment]
Updated the firmware PR.

It now initializes correctly when only OSD_HD is included after you setup the required MSP DisplayPort in ports tab.

My recommendation is to make OSD_SD and OSD_HD mutually exclusive.

@SteveCEvans is looking into the switching part.

**Comment by nerdCopter** [comment]
> Rather that hiding the video resolution selection on the configurator, wouldn’t it be better to just grey out the options which aren’t available?

i agree on this point.

**Comment by nerdCopter** [comment]
> My recommendation is to make OSD_SD and OSD_HD mutually exclusive.

i feel that both vendors and pilots would disagree.

**Comment by haslinghuis** [comment]
As this started with adding `MSP_OSD_SET_CANVAS` this PR is no longer required.

**Comment by nerdCopter** [comment]
hex with both:
image

hex with SD only:
image

hex with HD only:
image

i did not test/check any cli settings.

**Review by nerdCopter — APPROVED** [review]

**Comment by nerdCopter** [comment]
do we need to test 4.4 and prior?

**Comment by haslinghuis** [comment]
Prior versions won't have the `FC.CONFIG.buildOptions`.

@atomgomba is working on a change for build options to store a flag in firmware instead of relying on cloud options.

**Comment by haslinghuis** [comment]
@nerdCopter you were right about prior versions - added semver statement.

**Review by nerdCopter — APPROVED** [review]

**Comment by ctzsnooze** [comment]
@haslinghuis how do you mean by "mutating the mid column setting" ?

**Comment by haslinghuis** [comment]
@ctzsnooze Switching mode does not account for the midcol setting used in firmware for centering elements.

**Comment by nerdCopter** [comment]
- i think `9b1cda4a` is good and safe as-is. 
- essentially it just blocks pilot from selecting options that are invalid

**Comment by nerdCopter** [comment]
**bug found.**

local build without build-key - `make FOXEERF405 EXTRA_FLAGS="-D'RELEASE_NAME=4.5.0-zulu' -DCLOUD_BUILD -DUSE_CAMERA_CONTROL -DUSE_DSHOT -DUSE_EMFAT_AUTORUN -DUSE_EMFAT_ICON -DUSE_EMFAT_TOOLS -DUSE_GPS -DUSE_GPS_PLUS_CODES -DUSE_LED_STRIP -DUSE_LED_STRIP_64 -DUSE_MAG -DUSE_OSD -DUSE_OSD_SD -DUSE_PINIO -DUSE_SERIALRX -DUSE_SERIALRX_CRSF -DUSE_TELEMETRY -DUSE_TELEMETRY_CRSF -DUSE_VTX"`

cannot select PAL/NTSC
image

will test, other customs and edit comment.

**Comment by nerdCopter** [comment]
:rocket:  `2c8f4b72`  seemingly fixed for local builds _without_ build-key.  
SD-only hex: selecting HD, will auto pop-back to another SD.
HD-only hex: selecting an SD will pop-back to HD.
both in hex: works as expected.

did not re-test cloud-built hex.

**Review by nerdCopter — APPROVED** [review]

**Comment by ctzsnooze** [comment]
@haslinghuis 

With a local build using these settings:
```
make FOXEERF722V3 EXTRA_FLAGS="-D'RELEASE_NAME=4.5.0-zulu' -DCLOUD_BUILD -DUSE_DHOT -DUSE_GPS -DUSE_GPS_PLUS_CODES -DUSE_TELEMETRY -DUSE_TELEMETRY_CRSF -DUSE_OSD -DUSE_OSD_SD -DUSE_MAG -DUSE_LED_STRIP"
```
I see AUTO, PAL, NTSC and HD options in the OSD tab.  Selecting HD drops back to the previous selection.

With a cloud build and the OSD_SD option only, I get the same result.  The string is the same.

Is that what is supposed to happen?  I thought that if only SD options were included in the build, the I would not see the HD option any more.

What should I expect?

PS I'm using the 7401d32 build downloaded from here dated 26 January.

**Comment by haslinghuis** [comment]
Instead of hiding - we disable radio buttons which are not included in the build - so if user only use OSD_SD or OSD_HD it won't affect centering of elements.

**Comment by ctzsnooze** [comment]
Would it be possible to 'grey' the text associated with the option as well as the little circle for the option?  eg in the above image, not just make the little circle grey, but also make the text 'HD' grey?

That would be really good I think.  A bit confusing at the moment.

Definitely works very nicely for cloud builds, I tested both SD only and HD only.  For both SD and HD, behaviour is OK also, just the screen moves around, that's OK.

If the text could be grey, that would be awesome!

**Comment by haslinghuis** [comment]
image

**Comment by haslinghuis** [comment]
image

**Comment by haslinghuis** [comment]
Look @ctzsnooze we have colors now - please pick one to use :+1: 

Could not get it to work with css so while adding the text we can add color too. Choose red but gray would be more acceptable?

**Comment by haslinghuis** [comment]
@ctzsnooze changed to 

image

**Comment by HThuren** [comment]
@haslinghuis @nerdCopter @ctzsnooze I had trouble to flash with the BF PR, I may have better luck next time

**Comment by limonspb** [comment]
> Recommendation is either use `OSD_SD` or `OSD_HD` not both as switching elements is not accounted for in firmware.

i think now it is being accommodated in the firmware after https://github.com/betaflight/betaflight/pull/13320

**Pull request merged**
