### PR TITLE
Add rpm filter snippet apply dialog

### PR DESCRIPTION
**Pull request by IvoFPV**
As requested by @joelucid. This provides a way to apply rpm filter specific dynamic notch settings when enabling dshot bidir. Also when disabling it offers to apply default dynamic notch settings.
This eliminates the need for users to go to the Wiki and copy the current snippet.
This dialog is just a recommendation which you can apply or you can discard it and set everything up yourself.
image

### CODE REVIEW

**Comment by mikeller** [comment]
I think we really need to put careful consideration as to how many hacks we want to add just to support individual features - adding hacks like this for stuff that user might or might not want will just make configurator harder to use and maintain.

**Comment by IvoFPV** [comment]
I agree, I don't like what I did here either, this is just a workaround for something that should have been done in the firmware few weeks ago. @joelucid had an idea to have dynamic notch settings auto adjust based on if rpm filter is enabled/disabled, but it is too late now.
This is the only thing left for users to do to have rpm filter work as expected out of the box, needing no snippets from the wiki. I guess we could just do that for 4.2 in the firmware and not use this workaround at all. I'll keep this open until it is decided in the future then.

**Comment by joelucid** [comment]
Thanks @IvoFPV! This will greatly help users to avoid ending up with deficient notch filter settings or motor poles settings after switching bidir on. @mikeller I agree the bar should be high for explicit assistant type functionality like this in configurator. It seems that dshot bidir is one of the few cases where this does make sense.

**Comment by spatzengr** [comment]
It should just be handled in the Configurator when you turn on BiDirectional and enable the RPM notches.  Between now and then, I'll make sure to cover the DN tweaks when you enable RPM in content.

**Comment by joelucid** [comment]
@spatzengr - yeah, the dialog needs to come up when you enable or disable bidir. When you enable it offers to modify the dynamic notch settings and motor poles. When you disable it it offers to reset the dynamic notch settings. Rpm filter is on by default when bidir is enabled so no extra magic is needed to decide when to bring up the dialog.

**Comment by spatzengr** [comment]
That sounds like a good solution.  If remains targeted for 10.7 we have 4-months though.  It is not unsafe to not adjust.  Just doesn't optimize performance.  So OK either way.  I will make sure to cover in content.

**Comment by joelucid** [comment]
@spatzengr the problem is that we have now made everything very simple: you can enable bidir just using a switch, no snippets necessary. blheli32 will have support for bidir built in. Filter configuration is now just a matter of moving a slider.

In this context keeping the dynamic notch configured for the non rpm case where it's function is primarily to move with the motors and filter out motor noise is a significant issue. On the one hand it will lead to over-filtering since the motor noise is already taken out. On the other the defaults for the dynamic notch don't let it go low enough to remove frame resonances which are the main issue once the rpm takes motor noise out - and thus prevent the user from moving the sliders up high enough to get the full benefit of rpm.

The problem is just as significant moving back from rpm to no rpm. If you stick with your rpm filter optimized dynamic notch settings you might well encounter a flyaway.

It has been clear for some weeks that something like this is needed. We have not introduced the dyn_notch_mode=auto feature in bf to avoid introducing risk.

@ctzsnooze, I would appreciate your feedback on this issue. How important is it for us to deliver this with 4.1?

@mikeller, I would appreciate if you could reconsider delaying this until 4.2.

**Pull request closed without merging**
