### PR TITLE
Add images to the MCM fonts

### PR DESCRIPTION
**Pull request by McGiverGim**
This is for discussion:
- The MCM files can't be compared easily between versions, so I created a png image from them to let compare between versions easily.
- The only drawback is that we must ask to the developer that modifies a font that he must modify the png associated image too.

If it matter, I used this web page to make the dump easy: https://www.mylifesucks.de/tools/max7456/

### CODE REVIEW

**Comment by mikeller** [comment]
Good idea.
We already have the code to turn the fonts into images built into the configurator - we could maybe extract it and build a little node app that can be added to the repository and then used to automatically convert all fonts into the images whenever the fonts are updated.

**Comment by Docteh** [comment]
Any thoughts on the way inav is handling osd fonts? They are using a tool written in go https://github.com/fiam/max7456tool to assemble the .mcm fonts from .png files in the repository. The tool can take in a directory of images like this: https://github.com/iNavFlight/inav-configurator/tree/master/resources/osd/vision

max7456tool will also take a sprite sheet like this as input and crank out an .mcm file
tektite

**Comment by mikeller** [comment]
@Docteh: Yeah, that is kind of the inverse of what I'd proposed, but sounds even better, as then we'd only have to store the fonts once (as images), and create the .mcm files as an intermediary step.

**Comment by McGiverGim** [comment]
Yes, is the best way, but they need to have a tool in the path to build it. Another step for the user to build the Configurator.

**Comment by mikeller** [comment]
@McGiverGim: As I said, the tool could be constructed from what we've already got in configurator, and made to be run from gulp. So it will be a bit of work to get there, but once done it won't change the requirements for the build system.

**Pull request merged**
