### PR TITLE
Chore/run prettier all files

### PR DESCRIPTION
**Pull request by chmelevskij**
This runs the prettier and eslint on all the files to align the formatting/code styles.

### CODE REVIEW

**Comment by blckmn** [comment]
Not sure I like the output here...

**Comment by HThuren** [comment]
Automatic reformatting may destroy intended formatting by programmer, not always wanted.

**Comment by haslinghuis** [comment]
sonarcloud does normally only scan parts of the code. This PR touches a lot so sonarcloud is in overdrive :)

@HThuren - you never worked with COBOL :)

**Comment by HThuren** [comment]
> sonarcloud does normally only scan parts of the code. This PR touches a lot so sonarcloud is in overdrive :)
> 
> @HThuren - you never worked with COBOL :)

well, in fact I have worked with COBOL, but very fast changed to C, but get your point :-)

**Comment by chmelevskij** [comment]
> Automatic reformatting may destroy intended formatting by programmer, not always wanted.

This is lesser of two evils IMO. We are writing code, not designing magazines for people to read. Uniformity in this case is a win. As Ford said, they can have any car colour they want as long as it's black.

I fine example of why such tools are needed.
image

This project is literally driven by volunteers. If people have to spend time catching spacing and formatting, that's a waste of precious developer time which we get for free. pretty much. And spending time back and forth on adding spaces is pointless.

Similar how in electronics you don't come up with your own layouts so often and use standard parts or in mechanical engineering you don't just do any random sizes for things especially in a same product. But for some reason this project has 20 different styles of code. It's easily fixable and automated.

If there is some issues with the code style/formatting it should be discussed with the team, decision is made as a team and that should be encoded with automation/linting/tooling, not people chasing PRs and leaving comments.

Different formatting also makes it super hard to work on big picture work. I've spend fair amount on trying to get modules working and improve overall health of the project and one of the biggest pain points is literally this. You have to keep searching for `all_the-possibleCombinations_of_namesS`. Intended formatting works when you work on isolatted features maybe, but it makes it harder to work on overall architecture of the app.

**Comment by chmelevskij** [comment]
@blckmn any specific things? We can adjust the rules for our liking, I've just added the most generic setup here.

Personally don't care about the formatting if it doesn't have specific problems associated with it. As long as it's uniform.

**Comment by HThuren** [comment]
@chmelevskij, right, you have good points, specially regarding the team way of making proper code.
Like you Ford story, but this are reallly not the team way :-)

**Comment by blckmn** [comment]
> @blckmn any specific things? We can adjust the rules for our liking, I've just added the most generic setup here.
> 
> 
> 
> Personally don't care about the formatting style. At least if it doesn't have specific problems associated with it.
> 
> As long as it's uniform and applied everywhere.

I prefer the one line for the tag. I feel it would result in less modifications by the auto formatter.

**Comment by chmelevskij** [comment]
@blckmn can disable that for html. But have a question. HTML is essentially a structured data format. Similar to JSON.

In it's essence it's just and object similar to js objects like [FC](https://github.com/betaflight/betaflight-configurator/blob/master/src/js/fc.js#L64-L83) for example. Why is is better to have it on one line?

This amount of formatting would be applied only the first time, afterwards it would be way much smaller and would almost always just come together with new code.

**Comment by blckmn** [comment]
For me it's either all on one line or none of it.

Also leaving it on one line will result in less immediate change.

Breaking it up now provides little to no benefit.

**Comment by blckmn** [comment]
@chmelevskij don't get me wrong I really like the idea of prettying up the codebase, and I am totally appreciative of the effort (you saw how quick I fixed those errors found) - so am grateful to get started with this.

I just think we can utilise the existing formatting for the most part and modify as needed where it makes sense.

**Comment by chmelevskij** [comment]
> I just think we can utilise the existing formatting for the most part and modify as needed where it makes sense.

But we don't have formatting, that's the thing 😄 we have 5 linter rules added and that's it.

I like the explanation on [prettier](https://prettier.io/docs/en/comparison.html) website how linting (eslint) and formatting are different.

Anyways these 2 PRs are for discussions and to show how code/result would look like if we use such tooling. I'm not expecting them to even be accepted (I strongly wish for it though)

Thing is, this size of PR would be done only once. After that I doubt you'd even notice this as formatter/linter is integrated with the workflow.

**Comment by blckmn** [comment]
> > I just think we can utilise the existing formatting for the most part and modify as needed where it makes sense.
> 
> But we don't have formatting, that's the thing 😄 we have 5 linter rules added and that's it.
> 
> I like the explanation on [prettier](https://prettier.io/docs/en/comparison.html) website how linting (eslint) and formatting are different.
> 
> Anyways these 2 PRs are for discussions and to show how code/result would look like if we use such tooling. I'm not expecting them to even be accepted (I strongly wish for it though)
> 
> Thing is, this size of PR would be done only once. After that I doubt you'd even notice this as formatter/linter is integrated with the workflow.

What I would be keen to see is for us to adopt a standard, add it to the PR process, and reject the PR for merging if the files changed are not within the formatting expected.

For formatting I would like to see tags on one line (if empty, or within word wrap limits, then the closing tag on the same line), spaces for indentation.

That way we can clean up the formatting as we go, and identify any issues we may have with the particular formatting. Rather than having to review an automated reformat that affects all the code.

**Comment by blckmn** [comment]
image

If I look at this example (body.html) there are the following:
1. line 1 is not wrapped, assuming it is short enough to not warrant it.
2. line 2 is wrapped, but only has two elements, and presumably is too long now (i.e. wrapping length is set to somewhere between line 1 length and line 2 length.
3. line 6 is not wrapped.
4. lines 7, 12, 17 are wrapped.
5. line 23 is not wrapped.
6. line 24 is not wrapped.
7. line 25 is wrapped - is it affected by indentation to decide wrapping?
8. line 31 is not wrapped.

See for me this is a level of considerable variation that is an annoyance, presumably due to an arbitrary line length setting. I have a 38 inch monitor, and none of those lines would need wrapping. I am not doing coding for the configurator on a mobile device, so to me the wrapping is unnecessary. 

Perhaps I would be more amenable to a whole of code change IF this wrapping was not to occur. I suspect far fewer file changes needed if that were the case.

**Comment by chmelevskij** [comment]
Wrapping default is set at 80, two reasons for that:

1. well, funny one, legacy terminal width was 82 or 84 characters:
2. Optimal line length or column width for body text is 40–70 characters. After that it's unnatural for comprehension.

Not everybody uses 38" monitors though. I personally code on 14" laptop most of the time, occasionally switch to 27" display.

Personally I'd prefer to just always wrap html with more than 1 property. This is how ussually seen and worked in react/vue/js land.

TBH, I can exclude HTML all together, especially if we are moving to Vue which has it's own defaults/suggestions.

**Comment by McGiverGim** [comment]
Yes, 80 is very small. We need to support minimum 120, but better 160.

**Comment by chmelevskij** [comment]
Reconfigured and re-run the formatter.

About line width [prettier recommends 80 as well](https://prettier.io/docs/en/options.html#print-width) it's not a hard limit there.

Currently set line width to 120. Run only on vue/js/css/less files.

**Pull request closed without merging**
