### PR TITLE
Add all 8 debug values in sensors tab and only show active debugs

### PR DESCRIPTION
**Pull request by haslinghuis**
<details><summary>Spoiler</summary>Once a debug != 0 it will show up persistent.</details>

### CODE REVIEW

**Comment by haslinghuis** [comment]
[BTFL_BLACKBOX_LOG_GPSM10.zip](https://github.com/betaflight/betaflight-configurator/files/12114304/BTFL_BLACKBOX_LOG_GPSM10.zip)

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by limonspb — APPROVED** [review]

**Review by limonspb — COMMENTED** [review]
Does it work ok, if old firmware is connected with 4 values only?

**Comment by nerdCopter** [comment]
> Does it work ok, if old firmware is connected with 4 values only?

that's a fair question , i see some other MSP use `for (let i = 0; i < data.byteLength; ...`

tested: presuming it works -- sensors tab on firmware 4.3.2 shows only 4 debugs (0,1,2,3)
image

**Comment by nerdCopter** [comment]
hmmm, 4.5 also show only 4 🤷‍♂️

**Comment by haslinghuis** [comment]
I guess only some DEBUG sets contain all 8 values. Try GPS_UNIT_CONNECTION (testing with [#12799](https://github.com/betaflight/betaflight/pull/12799)

**Comment by nerdCopter** [comment]
i'm going to delete all my comments, although i told my CLI to checkout PR 3522, it did not and i did not notice such.

**Comment by nerdCopter** [comment]
retested. 
#3522 shows 8 debugs on sensors tab no matter what firmware. (0-7).

**Comment by haslinghuis** [comment]
Change was made in [#12445](https://github.com/betaflight/betaflight/pull/12445) so it should only apply to API 1.46 and above.

**Comment by haslinghuis** [comment]
Ok did it :)

**Comment by nerdCopter** [comment]
i will test 40bc6e3 when i can, i was working on something as well, but upon failure, i quit.
this does not work, but may show where i was aiming: [diff.txt](https://github.com/betaflight/betaflight-configurator/files/12131433/diff.txt)

**Comment by nerdCopter** [comment]
please check on older firmware e.g. 4.3.2
image
also found some to not show any, when expecting some.

image
image

**Comment by haslinghuis** [comment]
Fixed :)

**Comment by nerdCopter** [comment]
image

**Comment by haslinghuis** [comment]
Forgot the `.gte` after refactoring the line from an if statement.
```
sensors.debugColumns = semver.gte(FC.CONFIG.apiVersion, API_VERSION_1_46) ? 8 : 4;
```

**Comment by nerdCopter** [comment]
* i believe this is working as expected.  (as coded)
* i do see a strange beahavior, maybe it is desired. where if there is no data, it will not display.
 - example: i have no baro, set debug = baro; no graph
 - example: set debug = antigravity; no graph 0,1, but shows graph 2,3

**Comment by haslinghuis** [comment]
Yes that's the dynamic part. Only when there is data the column is enabled for the whole session to hide inactive debug data (only 0)

**Review by nerdCopter — APPROVED** [review]
* tested 4.5 master
* tested 4.3.2
* seems as expected
* maybe request other testers as well (have them enable console)

**Comment by haslinghuis** [comment]
Rebased on master

**Review by ctzsnooze — APPROVED** [review]

**Comment by ctzsnooze** [comment]
Not sure that the logic within only show active debugs is totally reliable, but having all 8 is awesome!

**Pull request merged**
