### PR TITLE
Add Home Flag symbol to Home Distance OSD element

### PR DESCRIPTION
**Pull request by McGiverGim**
To go with https://github.com/betaflight/betaflight/pull/8246

I don't know if we must complicate the code adding verification by version. What do you think? Usually in the OSD elements we don't do it, but some of them have code for this.

### CODE REVIEW

**Comment by Docteh** [comment]
I think verifying the layout on goggles is important anyways. 

I feel that too much code keeping track of subtle tweaks would be more trouble than its worth.

**Comment by mikeller** [comment]
I think instead of going over board with version detection, adding a warning like 'the layout of individual elements may look different when older versions of the firmware are used - please check the look through you goggles before flying.' should be sufficient.

**Comment by mikeller** [comment]
@McGiverGim: Can you rebase please?

**Comment by McGiverGim** [comment]
@mikeller rebased!!!

**Pull request merged**
