### PR TITLE
Enable/Disable all button for OSD screen

### PR DESCRIPTION
**Pull request by mosvov**
As described in  #560
switch all

### CODE REVIEW

**Comment by mikeller** [comment]
I tried to test this, but when using the 'Switch all' switch, a number of errors are thrown:

image

Please fix!

**Comment by mosvov** [comment]
Fixed

**Comment by mikeller** [comment]
Thanks for fixing this.

This works as intended now, and I will merge it. But one small remark that you could probably address in another pull request: Even when no elements at all are active, the 'Switch all' checkbox defaults to 'on' when the OSD tab is loaded. It would improve the user friendliness if the initial state of the checkbox was dependent on the majority of the switches, i.e. if a majority was off, the switch should be off too:

image

**Comment by mosvov** [comment]
Thanks. 
I will add new PR for 'Switch all' checkbox default position

**Pull request merged**
