### PR TITLE
Fix OSD (HD) display overflow on Android

### PR DESCRIPTION
**Pull request by haslinghuis**

### CODE REVIEW

**Comment by haslinghuis** [comment]
image

**Comment by McGiverGim** [comment]
Now it works as expected, it fits nicely... Buy is almost impossible to use it in HD mode 😉
Here and example with one element only... Where is it? 😋

Screenshot_20230113-194502

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by haslinghuis** [comment]
@McGiverGim any suggestions? As this tab should really switch to portrait mode.

**Review by blckmn — APPROVED** [review]

**Comment by McGiverGim** [comment]
It's prettier with this PR, but more useful being bigger and scrolling.
Maybe we can add a button to make it bigger or not only for Android? Something like a zoom button.

**Comment by haslinghuis** [comment]
@McGiverGim please check now :yum:

**Comment by McGiverGim** [comment]
Good idea, but:
- Strange to see the button in the toolbar. 
- the vertical space between the top bar and the bottom is ridiculous ☹️
Screenshot_20230115-081833

**Comment by McGiverGim** [comment]
I think a simple button, maybe just next to the font combo, to modify the css and change the rule changed in this PR to the old one and viceversa?

**Comment by haslinghuis** [comment]
@McGiverGim now it's merged have to start a new PR. Have to do more research.

**Comment by McGiverGim** [comment]
I don't understand why merge this. We add a button in the RC4 that the most probably is that we remove one version later.

We will not find any "perfect" solution, because the screen is small and the OSD preview is not, but we must let something "usable". If we want to give a preview that fits in the screen as default, it's ok to me, but we must let a bigger option to ubicate the components.

I will try to do the change of adding a checkbox myself and will open a new PR to test how it works... ;)

**Pull request merged**
