### PR TITLE
Removed link to empty development builds

### PR DESCRIPTION
**Pull request by KiteAnton**
Link to "Latest development builds" changed. Previous link was to travis, new link is to andwho.sytes.net site.

### CODE REVIEW

**Comment by mikeller** [comment]
I think andwho.sytes.net is running on somebody's personal machine. Not sure if we want to send more traffic their way? @borisbstyle would know more.

**Comment by KiteAnton** [comment]
The wiki is already pointing to that site. https://github.com/betaflight/betaflight/wiki
Also the old link pointed to travis, where no build artifacts is available anyways. 
Maybe the link should be removed instead ?

**Comment by KiteAnton** [comment]
So, should we merge this? Current link in configurator points towards travis, wiki is already pointing towards jenkins site. 
@AndersHoglund is it ok if we also change the link in the configurator towards your jenkins site?

**Comment by AndersHoglund** [comment]
Well, OK by me. But as stated before, it's a private machine with absolutely no guaranties on uptime nor availability.  Also unsure if BFC really should refer to any development builds, but rather only released stuff on github.

**Comment by KiteAnton** [comment]
Well ok, I agree with you. Originally just replaced the old link to travis with this one but I update the PR now to remove the link entirely instead.

**Comment by mikeller** [comment]
Probably best not to point non-developers to nightly builds, they are not likely to understand that there is no guarantee whatsoever for them to be safe to fly.

**Pull request merged**
