### PR TITLE
Move FC global vars inside FC object

### PR DESCRIPTION
**Pull request by McGiverGim**
This is a BIG and RISKY pull request.

- Moves all the global vars defined in the `FC.js` file inside the FC object. This helps to produce cleaner code and removes a lot of global variables.
- Fixed most Sonar issues of `FC.js` too.

The IDE helped with the change, but it was unable to find all the references, so I needed a regexp, with a test and error process to find the rest, so there is a risk of a forgotten one or a bad replaced one, but now that we are far from the next release and we have time to find some bug I think is the moment to do it.

### CODE REVIEW

**Comment by McGiverGim** [comment]
Sorry for the continuous force PR. It needed a rebase and it seems each rebase will probably break it.
This PR needs to be merged soon if accepted, if not it will become a nightmare of fixes and more risk after each rebase.
The Sonar issues are from old places that have nothing to do with this PR, I can fix them if we want, but I prefered to let it out.

**Comment by mikeller** [comment]
@McGiverGim: All good. Happy to go with this at this point in time. We'll give it the usual stand-down for merges, but I can hold off on other merges until this is done.

**Comment by McGiverGim** [comment]
No problem. If you merge some other before, I can verify the code of the merged one and see what MSP commands are modified. But if this can be merged soon after the 24h revision time, it will be great.

**Comment by mikeller** [comment]
@McGiverGim: Ok, I've merged the pull requests that fix problems, the rest can wait.

**Pull request merged**
