### PR TITLE
[WIP] Responsive for raspberry pi screens

### PR DESCRIPTION
**Pull request by orneryd**
I am trying to use my raspberry pi to connect to drones in the field rather than having to lug around a laptop. I added some media queries to handle the 800x480 screens on the 7" display.

### CODE REVIEW

**Comment by timothyswt** [comment]
I'm wondering what f most of this can be applied to the BLHeli configurator. I can check but does anyone know if the CSS classes are the same?

**Comment by mikeller** [comment]
@timothyswt: Can you please rebase this one?

**Comment by timothyswt** [comment]
Sure, I think I want to work on the design a little more to make it more touch-friendly. Right now it's difficult to adjust certain values and this could be reworked a little bit more. I think i'll flag it WIP

**Comment by mikeller** [comment]
Sure thing, let us know when you think it's ready. Also, can you please test any changes you make on a screen? This is still how the majority of users uses their device.

**Pull request closed without merging**
