### PR TITLE
Make the 'Update Firmware' buttom more consistent

### PR DESCRIPTION
**Pull request by Docteh**
I figure the 'Update Firmware' button should be red any time we're looking at the Firmware Flashing tab

### CODE REVIEW

**Comment by Docteh** [comment]
Before: click 'Update Firmware' and tabs would disappear, now:
image

**Comment by mikeller** [comment]
Noice!

**Comment by Docteh** [comment]
We could always add: 
- [ ] Hide the big firmware button

**Comment by mikeller** [comment]
@Docteh:

> Hide the big firmware button

Do you have any suggestion on how to do this, and not force users back into the 'disconnect at the top right, then select firmware flasher at the bottom left' UX nightmare of a way to get into the firmware flasher?

**Comment by Docteh** [comment]
Hi, I was sarcastically suggesting this:
image

**Pull request merged**
