### PR TITLE
Removed adjustment range slots from the UI.

### PR DESCRIPTION
**Pull request by mikeller**
Look ma, no slots:

image

(follow-up for betaflight/betaflight#8369)

### CODE REVIEW

**Comment by McGiverGim** [comment]
I have not tested it, but I think remember that there is a test explaining the slots. I don't see any change in the messages file. Is there such test? I'm out of a computer to looking into it myself.

**Comment by mikeller** [comment]
@McGiverGim: Good point, I had searched `src/` but not `locales/`. I will amend these.

**Comment by McGiverGim** [comment]
I'm not too sure about the change. We are showing or hiding the slot column depending on the version of the user. But we are removing all the info in the instructions ignoring the user version. If I'm not wrong, users of older versions of Betaflight (4.0 or earlier) will have a Slot column without any info about it.

**Comment by mikeller** [comment]
Not sure what is better here - having these help texts conditional will add clutter, and my assumption is that new users will use the latest version that is not restricted by the slots any more, and existing users will know what the slots mean.

**Comment by mikeller** [comment]
@McGiverGim: Found a way to get most of the information back without too much DOM wrangling.

**Pull request merged**
