### PR TITLE
Add native apps build via nwjs

### PR DESCRIPTION
**Pull request by sebsx**
This builds native apps via NW.js, shamelessly stolen from iNAV. Thanks!

A few points:

* Linux build is disabled since there unmet dependencies on some distro (Debian failed on a libgconf mismatch for example). I'll have to figure out what's going on.
* Window geometry and position is fixed. Saving window state is possible, but it needs some work.
* On Mac the menubar entry is ugly (i.e. 'betaflight-configurator' instead of 'Betaflight Configurator'). I'll fix this in another pull requests since I need to determine if it can be done via metadata in package.json or via code.

### CODE REVIEW

**Comment by sebsx** [comment]
I'm installing Fedora, Ubuntu and Mint VMs over the weekend (in addition to the Debian I have) and I'll test out both the build process and app compatibility. Ideally I should make sure the build process is flawless in a CI/CD environment if possible, but assuring compatibility with a few major distros should work as well. Stay tuned.

**Comment by mikeller** [comment]
Thanks. One more thing I noticed when trying to build the apps in Ubuntu 17.10: Setting the Windows icon does not seem to work, even thoug I've got wine installed:

```
err:mscoree:load_mono Could not load Mono into this process
Error building NW apps:Error while updating the Windows icon. Wine (winehq.org) must be installed to add custom icons from Mac and Linux.
```

**Comment by sebsx** [comment]
Not sure about Ubuntu, but on my Debian 9.1 I had to make sure I have at leaste wine 2.0, then I had to grab `winetricks` and run `winetricks install dotnet20`. I'm uploading a zip file with the Windows package to Slack in a couple of minutes.

Also, since Ubuntu is probably more popular I'm, going to install 17.10, make sure the build succeeds then update the README with a prerequisites section.

**Comment by mikeller** [comment]
Ok, installing `dotnet20` seems to have fixed it on Ubuntu 17.10 (or else it was the fact that this installation forced me to convert my wine setup to 32 bit from 64 bit). Also, this shows me once more that wine does a good job of bringing all the bad aspects (dll hell, binary fully contained installers, ...) of Windows to linux. Is there no way to perform this installation step without having to use wine? (Also thinking of continuos integration, and the pain that it will cause to have to run wine as part of it.)

**Comment by sebsx** [comment]
We can skip wine if we choose to not have the proper icon applied on the `.exe` file and pplying the icon is done via a binary called `rcedit.exe` (by the Electron project if I'm not mistaken) which requires wine. Maybe call the `exe` via a preconfigured Windows shortcut (with a proper icon)?

The repository is located here https://github.com/electron/rcedit and it appears to be Windows only, unfortunately.

**Comment by mikeller** [comment]
Would this be an option: https://github.com/erocarrera/pefile

(Sad to see that there does not seem to be a proper cross platform PE editor out there.)

Also, if I remember correctly, another way to get resources into an exe with some build environments is to supply all the resources in a `.res` file, that is then merged into the exe. I don't know if the toolkit that you are using is supporting this.

**Comment by sebsx** [comment]
I will have to look into it.

**Comment by mikeller** [comment]
@sebsx: Is this ready to be merged, or are you still working on it? If there's more you want to do on it, but don't have time now, we can always merge this and you can submit more pull requests with your future changes.

**Comment by sebsx** [comment]
@mikeller not yet, I have one more fix to commit then squash and update the pull request (unfortunately did not have much free time in the last few days). Later on I will make improvements and add improvements as we see fit.

**Comment by mikeller** [comment]
@sebsx: All good, no hurry. I just wanted to make sure you weren't waiting for me to merge.

**Comment by sebsx** [comment]
This should be ready to merge now. I squashed all the commits and merges into one.

Next I'll work on polishing the whole thing up.

**Comment by mikeller** [comment]
Just tested again, Windows works like a charm (can't test MacOS). Getting linux to work would be appreciated!

**Comment by basdelfos** [comment]
I’m using the mac app since the first time you released a downloadable
version.
It works perfect, the app responses faster than the chrome app.

Now only the same thing has to be done to the Blackbox Explorer app ;)

2017-11-04 19:13 GMT+01:00 Michael Keller <notifications@github.com>:

**Pull request merged**
