### PR TITLE
Fix dual telemetry in receiver tab for local builds

### LINKED ISSUE #3920: Telemetry slider appears twice
### Describe the bug

image

### To Reproduce

Flash SPRacingH7RF binary, view receiver tab.

The exact binary used for testing was the one from the SPRacingH7RF with PixelOSDSupport from here: https://github.com/betaflight/betaflight/pull/13603#issuecomment-2082342485

### Expected behavior

Only one slider for telemetry.

### Configurator version

`master` - `cd25abfa033e2979102f57e601e0a2d109bc0980`

### Flight controller configuration

```txt
# version
# Betaflight / STM32H730 (SP7R) 4.5.0 Apr 29 2024 / 12:01:30 (17c4fe0c6a) MSP API: 1.46
# config rev: 53c4a3c

# start the command batch
batch start

board_name SPRACINGH7RF
manufacturer_id SPRO

# aux
aux 0 40 0 1300 1700 0 0

# master
set osd_vbat_pos = 2443
set osd_rssi_pos = 353
set osd_link_quality_pos = 2369
set osd_rssi_dbm_pos = 2401
set osd_tim_1_pos = 2433
set osd_ah_sbar_pos = 2254
set osd_ah_pos = 2126
set osd_current_pos = 2411
set osd_craft_name_pos = 2121
set osd_altitude_pos = 2421
set osd_core_temp_pos = 2456
set debug_mode = RX_EXPRESSLRS_SPI
set vtx_band = 1
set vtx_channel = 8
set vtx_power = 1
set expresslrs_uid = 0,0,68,83,145,153

profile 0

rateprofile 0

# end the command batch
batch end
```

### Add any other context about the problem that you think might be relevant here

_No response_

### PR DESCRIPTION
**Pull request by haslinghuis**
- Fixes #3920

### CODE REVIEW

**Review by McGiverGim — APPROVED** [review]

**Comment by hydra** [comment]
Still broken:
image
image

Firmware built using:
```
make CONFIG=SPRACINGH7RF
```

**Comment by hydra** [comment]
Maybe this screenshot helps?

image

There's duplicate data in `self._features` at the time `FC.FEATURE_CONFIG.features.generateElements(featuresElement);` is called from `recieiver.js`

**Comment by hydra** [comment]
image

The feature is already present in the list, and then some code which looks at `buildOptions` (which I'm not familiar with) adds it again.

**Comment by haslinghuis** [comment]
@hydra 

In 4.4 we used build API to retrieve build information to retrieve options included
In 4.5 we can retrieve them directly from firmware.

As for 4.5 the telemetry options are not available in firmware so have added them afterwards in software to display telemetry in receiver tab.

Details: https://github.com/betaflight/betaflight/pull/13333#issuecomment-1924116708

**Comment by hydra** [comment]
> @hydra
> In 4.4 we used build API to retrieve build information to retrieve options included In 4.5 we can retrieve them directly from firmware.
> As for 4.5 the telemetry options are not available in firmware so have added them afterwards in software to display telemetry in receiver tab.
> Details: [betaflight/betaflight#13333 (comment)](https://github.com/betaflight/betaflight/pull/13333#issuecomment-1924116708)

Thanks for the info.

I'll leave the fix up to you guys, you should have all you need to replicate the issue and verify the fix, if not let me know.  Please ping me if there's an updated fix for me to try.

**Review by nerdCopter — APPROVED** [review]
- approving untested as i cannot reproduce source issue.

**Comment by haslinghuis** [comment]
Was able to reproduce with local build.

**Comment by hydra** [comment]
thanks for the fix @haslinghuis

**Pull request merged**
