### PR TITLE
Bump multipleSelect to 1.6.0

### PR DESCRIPTION
**Pull request by HThuren**
I have a good conversation with [wenzhixin](https://github.com/wenzhixin) to update to more language, resulting in version 1.6.0

### CODE REVIEW

**Comment by HThuren** [comment]
@haslinghuis did you recall this, only version are changed in package.json ?

**Comment by McGiverGim** [comment]
The yarn.lock did not change? Maybe it was at this version?

**Comment by haslinghuis** [comment]
You need to add the dependency using `yarnpkg add multiple-select`

Seems 1.5.2 is the latest but on npm.com it's 1.6.0
https://www.npmjs.com/package/multiple-select

**Comment by HThuren** [comment]
No, yarn.lock still point to 1.5.2, but the 1.60 package was fetched well (locally)

**Comment by McGiverGim** [comment]
The yarn install must update the yarn.lock file 🤔

**Comment by HThuren** [comment]
> You need to add the dependency using `yarnpkg add multiple-select`
> 
> Seems 1.5.2 is the latest but on npm.com it's 1.6.0 https://www.npmjs.com/package/multiple-select

Yes, I did some PR to MultipleSelect and @wenzhixin was kind to merge and do an update to 1.6.0
Now update yarm.lock

**Comment by haslinghuis** [comment]
Do not edit the lock file manually - it will be overwritten next time

**Comment by HThuren** [comment]
> Do not edit the lock file manually - it will be overwritten next time

Rright, didi not, but now updated by yarnpkg add multiple-select

**Comment by HThuren** [comment]
but still no sucess :-(

**Comment by haslinghuis** [comment]
Build is broken currently - do you have OSX ?

**Comment by HThuren** [comment]
Anything I can do to help ?

**Comment by haslinghuis** [comment]
We have a workaround in #3462 but we need to test OSX

**Comment by HThuren** [comment]
Ok, I do nothing

**Review by McGiverGim — APPROVED** [review]

**Review by haslinghuis — APPROVED** [review]

**Pull request merged**
