### PR TITLE
Update ROLL, PITCH, GPS LAT and LON OSD symbols

### PR DESCRIPTION
**Pull request by McGiverGim**
We forgot to update the GPS LAT and LON symbols when we upgrade the fonts.

### CODE REVIEW

**Comment by McGiverGim** [comment]
I have observed we have other fields without updating. I will update this PR with more commits...

**Comment by McGiverGim** [comment]
Done! I think we have all of them now.

**Comment by mikeller** [comment]
@McGiverGim: Do we need to make these changes in the firmware as well?

**Comment by McGiverGim** [comment]
No, they are already in firmware. We simply forgot to include them here.

**Pull request merged**
