### PR TITLE
Few CSS fixes for firmware flasher -> build configuration

### PR DESCRIPTION
**Pull request by limonspb**
just a few fixes for CSS for dark and white theme for build configuration

image

image

### CODE REVIEW

**Comment by limonspb** [comment]
looks like Linux build is failing but the reason is unrelated to this PR
ready to merge is passes review.

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Review by haslinghuis — APPROVED** [review]

**Review by blckmn — APPROVED** [review]

**Comment by HThuren** [comment]
Sorry, but at my build it seems that the frame for Custom are a bit longer
image

**Comment by limonspb** [comment]
> Sorry, but at my build it seems that the frame for Custom are a bit longer image

good catch, addressed here:
https://github.com/betaflight/betaflight-configurator/pull/3091

**Pull request merged**
