### PR TITLE
Added disabling of runaway takeoff prevention.

### PR DESCRIPTION
**Pull request by mikeller**
Complementary to betaflight/betaflight#5172.

@etracer65: Can you test please? My debug rig doesn't work due to #922.

### CODE REVIEW

**Comment by etracer65** [comment]
@mikeller I don't have an environment set up to build the configurator.  I can only test either a compiled app for OSX or a Chromium build (loaded as an unpacked extension in Chrome).

**Comment by mikeller** [comment]
@etracer65: Here you go: [betaflight-configurator_10.2.0_chromeos.zip](https://github.com/betaflight/betaflight-configurator/files/1719993/betaflight-configurator_10.2.0_chromeos.zip)

**Comment by etracer65** [comment]
@mikeller Testing completed - everything worked as expected.  Bench testing in the configurator worked without runaway takeoff triggering.  Disconnecting from the configurator (with battery still connected) resulted in arming being re-enabled and runaway takeoff prevention active.

One unrelated thing I stumbled on is an edge case with the ARMING_DISABLED_MSP.  If enable the safety switch -> arm -> motors start spinning, turning off the safety switch (without disarming) will result in arming disabled warning beeps but the motors will keep running (quad still armed).  Maybe in the firmware we need to check the arming status and disarm when an MSP_ARMING_DISABLE message is received.

**Comment by etracer65** [comment]
Added https://github.com/betaflight/betaflight/pull/5185 to check the arming status and disarm when the configurator sets `ARMING_DISABLED_MSP`.

**Comment by DanNixon** [comment]
> One unrelated thing I stumbled on is an edge case with the ARMING_DISABLED_MSP.

IMO this is expected functionality. The arming disable feature does not prevent being in the armed state, it prevents entering the armed state.

This distinction really should be more obvious.

**Comment by etracer65** [comment]
@DanNixon But what's the use case for when someone would want the quad to stay armed when turning off the safety switch?  It's already armed so preventing arming is moot.  Also turning off the switch sets the `ARMING_DISABLED_MSP` arming disabled reason which starts the beeper pattern although the motors are still spinning.

In my opinion the meaning of the switch has changed to "the motors aren't going to spin" unless the safety switch is turned on.

**Comment by DanNixon** [comment]
Yes, I think this is probably a special case.

There are some conditions (RX loss and failsafe are the ones that spring to mind) where the fact it is the transition (and not the state) that is disabled is required.

**Pull request merged**
