### PR TITLE
Style: Fix graph layout in Sensors tab

### PR DESCRIPTION
**Pull request by VitroidFPV**

### CODE REVIEW

**Comment by haslinghuis** [comment]
Sensor tab does not show up using netlify preview :upside_down_face: 

image

**Comment by VitroidFPV** [comment]
That's odd, it shows for me just fine

**Comment by VitroidFPV** [comment]
Turns out I only made these in the dev tool editor and forgot to bring them back to the actual CSS 😅 But that shouldn't affect the tab (not) showing in preview builds

**Comment by haslinghuis** [comment]
Same on windows 10 laptop. Out of the office until next week so cannot check my main machines now. Tethered logging tab is not showing either. Could be a netlify issue ?

**Comment by VitroidFPV** [comment]
It shows on my end with the netlify preview... could you try clearing all the site data?

**Comment by haslinghuis** [comment]
Checking out PR locally and build it shows :)

**Review by haslinghuis — APPROVED** [review]

**Comment by haslinghuis** [comment]
Even resetting chromium and removing all data does not help

**Review by blckmn — APPROVED** [review]

**Pull request merged**
