### PR TITLE
AUX modes updated in help tips and virtuelFC, also sort of LinkedTo option list at Mode tab

### PR DESCRIPTION
**Pull request by HThuren**
Add all modes found in betaflight msp/msp_box.c
(And sort the list to find the missing elements)

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Comment by haslinghuis** [comment]
Sorting the list is not as strait forward as in other tabs.

**Review by haslinghuis — APPROVED** [review]

**Comment by HThuren** [comment]
no, I working on sort of the modes list, but not that easy due to special treatment of ARM mode. But hopefully succed
The LinkedTo are sorted in my branch

**Comment by HThuren** [comment]
I believe this PR need no more development.
(Sort of modes will come in another PR, quite difficult not handle)

**Comment by HThuren** [comment]
Discovered AIRMODE are split in msp_box.c, ie. "AIR MODE"

**Review by nerdCopter — APPROVED** [review]
* approving untested; visual inspection only

**Pull request merged**
