### PR TITLE
Revert marked version update

### PR DESCRIPTION
**Pull request by Asizon**
Fix issue on Firmware flasher tab loading release notes.

### CODE REVIEW

**Review by McGiverGim — APPROVED** [review]
It will have a better fix but being in RC phase the revert is better.

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by haslinghuis — APPROVED** [review]

**Comment by McGiverGim** [comment]
@Asizon now that I look at it closely, it seems you have created the commit by hand. For this situations is better to use the revert of Git, applied to the merge that created the problem. In this way there is some traceability of the problem.

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by haslinghuis** [comment]
Supersedes by https://github.com/betaflight/betaflight-configurator/pull/2824

**Pull request closed without merging**
