### PR TITLE
feat: drop jquery debounce for local implementation

### PR DESCRIPTION
**Pull request by chmelevskij**
Drop minimized jquery debounc library from `libraries` in favour of local implementation

### CODE REVIEW

**Comment by McGiverGim** [comment]
What fixes this? A little of more background will be great.

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Comment by chmelevskij** [comment]
@McGiverGim I've started into looking running configurator in the browser. `jquery` has bunch of plugins which expect different global variables to exist and when using modules and this was throwing `jQuery is not defined`.

This could be as easily replaced with something more solid like `lodash.debounce`, or what I've done since it's non-trivial thing to implement.

**Comment by McGiverGim** [comment]
Ok. I wanted to know the reason, is good to have it explained at the text of the PR, to anyone that wants to consult it.
My personal preference is to have always something extern to have less code to maintain, but it's ok both ways.

**Comment by blckmn** [comment]
Failing on account of the missing LF at the EOF.

**Comment by chmelevskij** [comment]
@McGiverGim `ba-throttle` is actually stored as minified file in this repository, so it's worst of both worlds 😄 Technically we maintain it and it's minified so it's not even possible to fix it.

**Comment by chmelevskij** [comment]
Replaced handrolled debounce with `lodash.debounce` now.

**Review by McGiverGim — APPROVED** [review]

**Review by haslinghuis — APPROVED** [review]

**Pull request merged**
