### PR TITLE
update NW.js to latest stable

### PR DESCRIPTION
**Pull request by TheIsotopes**
also fixed [this issue](https://github.com/betaflight/betaflight-configurator/pull/1893#issuecomment-589936165)

command line switch ` --disable-gpu` is not needed anymore

### CODE REVIEW

**Comment by McGiverGim** [comment]
@mikeller what do you think? I think that if upgrading the version fixes the problem with the gpu is a good idea to upgrade. We are going to start the RC so I think we have time to test it in this period.

I don't have the problem of the gpu so I can't test it.

**Comment by mikeller** [comment]
@McGiverGim: I am honestly not thrilled about changing the NW.js toolkit version this late in the game - this is often resulting in bugs due to breaking changes. I don't think it is a good idea to risk to have to prolong the RC phase because we have to switch NW.js version s in the middle of it.
I was never able to reproduce the error on Windows 10 that @TheIsotopes reported (I just tried again), and nobody else has reported this error, so my working theory is that this is a graphics driver issue - like pretty much all of the 3D model related problems we are seeing. A uninstall / reinstall of the graphics drivers would probably solve this as well.

**Comment by McGiverGim** [comment]
I was with you: a driver problem. But if upgrading the nw version fixes the problem without touching the drivers, then maybe is not totally a driver problem, and more a nw and driver problem.

But if you prefer not to risk at this moment, we can merge this after the final version. Any people with the problem can then install the nightly version if they want.

**Comment by mikeller** [comment]
@McGiverGim: Let's do that then. Another reason is that I normally try to keep the NW.js version between configurator and blackbox log viewer the same, so that we are not having to deal with quirks from different versions at the same time.

**Comment by TheIsotopes** [comment]
@mikeller the current rc1 runs great with the latest nw.js, why wait until 10.8.
I would be surprised if no one else reports the same problem.

>  A uninstall / reinstall of the graphics drivers would probably solve this as well.

i have the computer complete new installed but with the 0.44.2 nw.js the problem was not solved, update to 0.45.4 and the problem was solved.

**Comment by Docteh** [comment]
We may be in a loop where we upgrade NWjs to fix one bug, and then a few months later we want to upgrade it again to fix another bug that cropped up since the last NWjs upgrade. 

Flashing F7's on macs has come up at least once in relation to NWjs versions. One or two versions of NWjs got blacklisted by some virus scanners. We might want to maintain a list of things that have glitched with various versions

**Comment by mikeller** [comment]
@TheIsotopes: Out of interest, what GPU and what GPU driver version does the machine that this is happening on have?

**Comment by TheIsotopes** [comment]
@mikeller 

gpu_information

**Comment by mikeller** [comment]
@TheIsotopes: Thanks. The driver (which is the latest available) is from 2016. I can see how NW.js could be struggling with this. But at the same time the percentage of users stuck on this particular driver is probably small.
I know this is not what you want to hear, but since we've often had various things go wrong and break as a consequence of a NW.js update we are not going to do this now, but wait until after the release, unless we get problem reports from users with different hardware as well.

**Comment by mikeller** [comment]
Seems to be changing every two weeks...

**Comment by Asizon** [comment]
Maybe we should rethink introduce this and good test it in RC2? I can see how users look for patches to be able to use the Configurator 10.7.0.

**Comment by mikeller** [comment]
@Asizon: Do we know what hardware is affected? From the report above the only thing we know is that users with GPUs that were end of support 4 years ago are affected. If it's only that then I think the risk of breaking all users with unknown bugs outweighs the benefit of supporting the 3D models for a small number of users.

Also, the fix for this on affected hardware is simple - run configurator with the `--disable-gpu` option.

**Comment by Asizon** [comment]
@mikeller Yes, it is true that the users affected by this are very few, but I could see that the buttons to navigate between tabs are also affected. I don't know to what extent this implementation can create new bugs, but you can always go back if they are detected in the RC

**Comment by Asizon** [comment]
Maybe it's too late now, but it would have been perfect to have it from RC1 to test it :)

**Comment by mikeller** [comment]
@Asizon: No, testing things in an RC that have led to users being broken many times in the past is definitely wrong - most users do not have an appetite to download a 100 MB update half a dozen times just because somebody wants to experiment with them.

**Comment by mikeller** [comment]
I think this has been superseded by #2074, which updates the NW.js version in lock-step with the version used in the blackbox Explorer (see betaflight/blackbox-log-viewer#449). This should be revisited when NW.js version 46 becomes usable for the blackbox Explorer

**Comment by Asizon** [comment]
But @mikeller after some test, 0.44.6 doesnt solve the users gpu issue, seems that only 0.46 works for this. In the other hand I have doing test with 0.46.2 and it also changes some styles around configurator. Really he is improving the stytles for us :)

IMG_20200704_092534_022
image (2)
image (1)

**Comment by mikeller** [comment]
@Asizon: Feel free to open a pull request that updates blackbox Explorer to 0.46 as well, and we can merge both of them to keep the versions in synch.

**Comment by Asizon** [comment]
@mikeller i have read all discussions for it yes, not simple to maintain ffmpeg libraries I know :(

**Comment by Asizon** [comment]
Maybe we can go with it now  in version 0.47.0 :)
https://github.com/betaflight/blackbox-log-viewer/pull/455

**Comment by TheIsotopes** [comment]
superseded by #2130

**Pull request closed without merging**
