### PR TITLE
Translate hardware status info

### PR DESCRIPTION
**Pull request by HThuren**
Translate hardware status info, reorder a bit
image

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Comment by haslinghuis** [comment]
@HThuren please change the order of mag and baro to be the same as the order of the icons.

**Comment by HThuren** [comment]
> @HThuren please change the order of mag and baro to be the same as the order of the icons.
> 
> Maybe also rename `Acc` to `Accel`.
> 
> `Disabled by user` covers disabled in configuration tab or not powered up states but currently we cannot distinguish between the two, so maybe we rename it to `Not detected`.
> 
> Thoughts?
reordered and acc changed

**Not detected** maybe changed to **Not configured** , I planned the last in my translation, what do you think ?

**Comment by haslinghuis** [comment]
On my board I need lipo to power some sensors and would show `Not configured` otherwise.

`Not detected` is more neutral imho then `Disabled by user`

**Comment by HThuren** [comment]
what about the order of info, change to Instruments, System info, Sensor info, GPS, Sonar, Firmware info ?

**Comment by HThuren** [comment]
Here we go

**Review by haslinghuis — APPROVED** [review]

**Review by nerdCopter — APPROVED** [review]
* approving untested. code looks good by eye.

**Comment by haslinghuis** [comment]
Thanks!

**Comment by haslinghuis** [comment]
image

**Pull request merged**
