### PR TITLE
Change failsafe delays units to seconds in UI

### PR DESCRIPTION
**Pull request by limonspb**
Changing three elements to seconds instead of 0.1s on the Failsafe tab:

image

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by McGiverGim — APPROVED** [review]
I'm not too sure about this. Is a lot more clear to work in seconds, but maybe we send the message that is a "good idea" to put a 2 or 3 seconds as failsafe... a quad can move a lot in 2 or 3 secods.
But for the rest, is ok to me.

**Review by haslinghuis — APPROVED** [review]

**Review by klutvott123 — APPROVED** [review]

**Comment by limonspb** [comment]
> I'm not too sure about this. Is a lot more clear to work in seconds, but maybe we send the message that is a "good idea" to put a 2 or 3 seconds as failsafe... a quad can move a lot in 2 or 3 secods. But for the rest, is ok to me.

could you please elaborate? the PR is only changing the units, it does not change any default values.

**Comment by McGiverGim** [comment]
> could you please elaborate? the PR is only changing the units, it does not change any default values.

Yes, I know it. The user can let the same values than always. But unconsciously the newbie user is affected by the unit, and when changing it, maybe it changes the value by 1 or 2 (seconds). In the earlier version it changes by 1 or 2 (tenths).
As I say, is a unconsciously thing. It can use it as always if he things what he is doing.

**Comment by limonspb** [comment]
> > could you please elaborate? the PR is only changing the units, it does not change any default values.
> 
> Yes, I know it. The user can let the same values than always. But unconsciously the newbie user is affected by the unit, and when changing it, maybe it changes the value by 1 or 2 (seconds). In the earlier version it changes by 1 or 2 (tenths). As I say, is a unconsciously thing. It can use it as always if he things what he is doing.

The steps of the inputs are changed to 0.1 now too. Is that what you thinking about? Or that someone might directly input "10" meaning "1 second"?

**Comment by McGiverGim** [comment]
Yes, something like the second. But it's not a problem, I prefer seconds as unit.

**Pull request merged**
