### PR TITLE
Replace Stale bot by action

### PR DESCRIPTION
**Pull request by McGiverGim**
The stale bot is not working reliable.

This replaces the old stale bot by the new that uses a github action.

Two different things about the old bot:
- This executes daily at 4:30 (configurable). The old I think executed once at hour. I don't know if we want to do the same.
- This new bot has not the equivalent to `exemptMilestones: true` so we need to manually add the `Pinned` tag if needed.

### CODE REVIEW

**Review by mikeller — COMMENTED** [review]
Ok, first of all stale bot has started working again, so there is not so much pressure any more on getting this changed.
Secondly, one difference is that stale bot is configured to exclude pull requests with a Milestone associated from becoming stale: `exemptMilestones: true`. Can we do this with this action as well?

**Comment by McGiverGim** [comment]
As I said in my message the is not an equivalent command for this. There are several requests in the original repo, so maybe en un future...

**Comment by mikeller** [comment]
Sorry, I had overlooked this. Since stale bot is working again for now I'd opt to stay with it for now, and see if there will be a fully featured action based replacement in the future - using Milestones to 'pin' pull requests to a certain release is convenient.

**Comment by McGiverGim** [comment]
It's ok for me. I will check the action bot from time to time to see if finally it gets implemented.

**Comment by McGiverGim** [comment]
One thing more: the stale bot seems not reliable again. We have several PR that must be closed and they are not, for example: https://github.com/betaflight/betaflight-configurator/pull/2224

**Comment by mikeller** [comment]
@McGiverGim:

> One thing more: the stale bot seems not reliable again. 

:crying_cat_face: 

Ok. But if we are switching to the Action I'd propose that we also add a label 'Has Milestone' to `exempt-pr-labels:`, in order to make it immediately obvious if a pull request has been genuinely pinned, or is only exempt because it has a Milestone.

**Comment by McGiverGim** [comment]
I will update it to add this new label, but my comment was only to let you know, maybe is there a way to fix the old stale bot.

**Comment by mikeller** [comment]
@McGiverGim: I don't think there is much we can do to fix stale bot - this is offered by a third party and run on their resources. And I suspect that they probably have little incentive to fix / improve it, as GitHub itself seems to be positioning Actions as the way forward for things like this. So updating this pull request and then going ahead with it is probably the best option that we have.

**Comment by McGiverGim** [comment]
Added the `Has Milestone` tag to the issues and pr exempt label (I think we can use it in both.

**Review by mikeller — APPROVED** [review]

**Comment by McGiverGim** [comment]
This PR is closed, but only to not forgot, it seems that it now accepts some kind of exempt milestones:
image

And a PR is in progress to exempt all milestones: https://github.com/actions/stale/pull/291

**Pull request merged**
