### PR TITLE
Add OSD_EFFICIENCY element

### PR DESCRIPTION
**Pull request by DavidBoone**
Adds the new efficiency OSD element to the configurator.

https://github.com/betaflight/betaflight/pull/9601

### CODE REVIEW

**Comment by McGiverGim** [comment]
The code is OK, but if you can fix the Sonar issues it will be great:

https://sonarcloud.io/project/issues?id=betaflight_betaflight-configurator&pullRequest=1922&resolved=false&types=CODE_SMELL

I know your code is copying other parts, but we are trying to make the code better in new PR.

**Comment by McGiverGim** [comment]
I forgot that the OSD elements are ordered in alphabetical order. Maybe is better to make it like:

Battery efficiency

Or similar. In this way it will go with the others battery elements. Is only a suggestion.

**Comment by mikeller** [comment]
@McGiverGim: Yes, sorry, forgot about that - we should really look into doing this in a better way (a tree structure with expand / collapse comes to mind).

@DavidBoone: Do you mind opening another pull request to rename this?

**Comment by etracer65** [comment]
Missed on the original PR but a chance to correct here. Can you update the element description to include information that the element requires the GPS to be enabled and functioning so that speed can be calculated. Otherwise I fear that we'll have a lot of support issues by people enabling this element and then not see it appear in their OSD.

**Pull request merged**
