### PR TITLE
Updated NW.js to 44.6.

### PR DESCRIPTION
**Pull request by mikeller**
To go with betaflight/blackbox-log-viewer#449.

### CODE REVIEW

**Comment by mikeller** [comment]
@McGiverGim: I think it makes sense to keep the NW.js versions for configurator and blackbox log viewer the same, like we always have - this way we won't have to find bugs twice.

**Comment by McGiverGim** [comment]
Ahhhh! Maybe we have the same chrome/nw bug that in Configurator? Then we need to fix it in the Blackbox first. Right?

**Comment by mikeller** [comment]
Yes, a lot of the bugs are the same, but blackbox log viewer normally takes longer to update because we have to wait for the ffmpeg libraries to become available - at the moment, 44 is the latest version actually working with the ffmpeg libraries.

**Comment by McGiverGim** [comment]
I was talking about this https://github.com/betaflight/betaflight-configurator/pull/1982

**Comment by McGiverGim** [comment]
I didn't remember the ffmpeg libraries... Good catch!

**Comment by mikeller** [comment]
I was bitten too often by forgetting then, and then having to roll back - it's taught me.

But yes, we will have to look into this for blackbox log viewer as well, I feel that moving to NW windows is the way forward. And seeing the announced end date for support of Chrome Web apps, it probably makes sense to axe this now - we only have all of 159 users for it anyway.

**Comment by McGiverGim** [comment]
Only as curiosity: I think the developer only publishes a new version when it is not compatible or there are changes. For this reason sometimes there are versions for linux but not for windows, etc.
I have updated (and we published it) sometimes the nw.js version with older ffmpeg libraries (because there were not a new one) and it worked.
If you want I can test if this is true with the latest version.

**Comment by mikeller** [comment]
@McGiverGim: I have already tested the current and the latest versions of the ffmpeg libraries against NW.js 0.45 and 0.46 - all without success. :-(

**Pull request merged**
