### PR TITLE
App Build - disable push AWS on forks

### PR DESCRIPTION
**Pull request by nerdCopter**
fixes (on forks):
image
image

### CODE REVIEW

**Comment by nerdCopter** [comment]
- needs verification. pretty certain it's correct. 
- `draft` until verified. welcome to remove draft and merge if found good.

**Comment by nerdCopter** [comment]
or maybe it should go under `name:` fro the entire workflow :shrug:

**Comment by nerdCopter** [comment]
`362a387` technically worked, but will investigate higher-level as well.
image

**Comment by nerdCopter** [comment]
Okay, which would ya'll prefer for forks:

1) Tests and Building, but not push to AWS?
2) Skip all?

skip all is gray, skip push to AWS is green:
image

**Comment by blckmn** [comment]
Skip all for forks. It should only be on PR here. We don't need to be concerned with commits to forks.

**Review by blckmn — APPROVED** [review]

**Pull request merged**
