### PR TITLE
Removed non-published builds from the Azure pipeline.

### PR DESCRIPTION
**Pull request by mikeller**

### CODE REVIEW

**Comment by mikeller** [comment]
@McGiverGim: Happy to switch to publishing the win64 version. But I do not think we should be publishing both - it will just complicate support for no benefit.

Looking at the status of things, most Windows applications seem to be published as win32 (installed into `C:\Program Files(x86)`), with only a minority being published as win64 (`C:\Program Files`). So for now win32 seems to be the safe bet.

Are you aware of any benefits that we'd get out of switching to win64?

**Comment by McGiverGim** [comment]
> Are you aware of any benefits that we'd get out of switching to win64?

No, I don't think we get any benefit in the Configurator. I simply want to promote all the apps to win64, the win64 is with us since a long time ago, but I understand your decision. I will continue generating my own version.

**Comment by mikeller** [comment]
@McGiverGim: I am humming and harring about switching to releasing 64bit Windows builds - it's the same as with ChromeOS, some users will be affected because they have a 32bit Windows system. These were sold for a long time in the form of Windows tablets, which make for good field kit, just the same as Chromebooks.
The problem is that in this case we don't have a way to figure out how many users are affected until we stop supporting them and get complaints.

**Comment by frozenskys** [comment]
I use a Win64 build, just because I can basically, but until Microsoft stop supporting WoW64 (if ever) I would suggest that keeping the Win32 build is probably the way to go for 99% of users...

**Pull request merged**
