### PR TITLE
Fix require modules with Cordova

### PR DESCRIPTION
**Pull request by WalcoFPV**
This fixes the importation of modules with `require` with Cordova (#2246)

### CODE REVIEW

**Review by mikeller — APPROVED** [review]

**Comment by mikeller** [comment]
This was less involved to browserify than I expected. :sweat_smile:

**Comment by McGiverGim** [comment]
@WalcoFPV can you confirm that the Android build is not totally fixed with this? I suppose that the `require` error is fixed, but we were using it to load a node module that uses the `fs`, so I suppose that this has not fixed it. I'm right?

**Comment by WalcoFPV** [comment]
@McGiverGim Yes `node fs` still doesn't work and also loading modules with `import` doesn't work as well.

**Comment by McGiverGim** [comment]
With this PR pending the `import` does not work neither? https://github.com/betaflight/betaflight-configurator/pull/2255

I think we have two big "open" themes for Android support:
1. We need to support modules in Android. This PR makes the `require` work, and the https://github.com/betaflight/betaflight-configurator/pull/2255 maybe makes the `import` work (waiting for your confirmation).
2. We need to find a node api wrapper (if exists) that works with Cordova, as commented in https://github.com/betaflight/betaflight-configurator/pull/2255 . If we can't find such wrapper, we need to revert the PR https://github.com/betaflight/betaflight-configurator/pull/2245 and search for another solution. We will then need to limit to non node modules.

We need the answer to this two themes first and after that, in a future, we can recommend to use simple wrapper for common operations (filesystem, clipboard, etc.) that can help to maintain the Node/Cordova compatibility. We will need to be cautious with this type of inclusions because we are seeing that we can break Cordova fast...

**Comment by mikeller** [comment]
@WalcoFPV, @McGiverGim: Should we merge this, or do we want to keep hacking away at a better solution for Cordova?

**Comment by McGiverGim** [comment]
If we are going to accept the require way of adding modules (no restrict to import), I think we need to merge it. I will revert the fs backend module in the next days to make Android work again.

**Pull request merged**
