### PR TITLE
Change blackbox debug

### PR DESCRIPTION
**Pull request by haslinghuis**

### CODE REVIEW

**Comment by ctzsnooze** [comment]
Brilliant - the blackbox mode selector works MUCH better now than before!
Thank you!

**Review by ctzsnooze — APPROVED** [review]

**Comment by nerdCopter** [comment]
i'm not sure what the changes at src/js/tabs/onboard_logging.js line `352` does.

**Comment by haslinghuis** [comment]
On request from Chris I have removed select2.
The NONE param keeps that value on top while sorting the remainder of the list.

**Review by nerdCopter — APPROVED** [review]

**Comment by ctzsnooze** [comment]
Absolutely fantastic.  Works great!

**Pull request merged**
