### PR TITLE
Update README to remove building with nw.js

### PR DESCRIPTION
**Pull request by McGiverGim**
Updates and completes the README to make clear that we are moving to PWA, updates the "master" snapshots URL and the instructions for building.

### CODE REVIEW

**Review by haslinghuis — APPROVED** [review]
image

**Comment by McGiverGim** [comment]
I didn't notice it... moved upper and updated.

**Review by haslinghuis — APPROVED** [review]

**Comment by nerdCopter** [comment]
i noticed that https://app.betaflight.com/ and https://master.dev.app.betaflight.com/ are at the same commit (after browser refresh)
will there be a separation of stable vs master at some point @blckmn ?

**Comment by nerdCopter** [comment]
maybe the new PWA information should be top of readme with "note" alert/admonition syntax.

https://github.com/orgs/community/discussions/16925

**Comment by McGiverGim** [comment]
The idea of this PR is to create a transition readme, for this reason I have not added the future stable URL.
For the same reason I restricted the PWA information to where is needed, to not confuse non developers users. For this reason I think it's good at this point not add this info on the top.

**Review by nerdCopter — APPROVED** [review]

**Pull request merged**
