### PR TITLE
Append craftname

### LINKED ISSUE #3636: re-implement craft_name within output file names (as option?)
### Is your feature request related to a problem? Please describe

I have needed to maintain multiple different configurations on the same FC target.

In this use case having the craft_name within the Diff/Dump/Backup file names has been more helpful than target name when finding the correct configuration file(s) .

### Describe the solution you'd like

Append "_craft_name" within output file names when not empty.

eg:
BTFL_cli_backup_20231117_123456_BETAFLIGHTF4**_craft_name**.txt

### Describe alternatives you've considered

Because craft_name is contained within the file contents (if set) I can not think of any good reason this should not be the default option. However, if there is a good reason to set craft_name within config and not include craft_name in the file name maybe we should add a user option to the configurator?

### Other information

For now I have been appending craft_name manually in order to save time and prevent error when searching the file contents to find/re-load the correct config.

### PR DESCRIPTION
**Pull request by haslinghuis**
Fixes #3636

### CODE REVIEW

**Review by nerdCopter — APPROVED** [review]
* tested successfully.
* love it 
image

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by PacificTrade** [comment]
Previously craft name was before date_time. Is there some reason why it shouldn't go back to that? Made it easy to sort by name
image

**Comment by PacificTrade** [comment]
image
Perfect! Came on here a few hours ago expecting to post an issue and it's already fixed. You guys are too fast.

**Review by McGiverGim — APPROVED** [review]

**Pull request merged**
