### PR TITLE
Fixed wrapping with Artificial Horizon

### PR DESCRIPTION
**Pull request by dronejunkie**
This PR is to fixing an existing issue with artificial horizon wrapping in some situation.  I did some regression testing as well with other single char elements like sidebar and stick overlay.  No issue.

### CODE REVIEW

**Comment by dronejunkie** [comment]
I think we should able to use one logic to apply to all osd elements:string, array of char and array of strings.
String can be represented using array of string and its xMin, yMin is zero,   xMax is the length of the longest element and yMax is the length of the array. Below can be the logic.

Proc OnDrop() {
    Let x and y be the co-ord for the osd element, which is the left top corner. 
    Let x' and y' be the mouse cursor co-ord. 
    x'= position MOD osd.width
    y'= position/osd.width
    x = x' + xmin - element.x
    y = y' + ymin - element.y
   
    if ( y < 0 ) {
        y = 0
    }
    if ( y + element.height > OSD.height )  {
        y = y - element.height 
    }
    if ( x < 0 ) {
        x = 0              
    } 
    if ( x + element.width ) > OSD.width ) {
        x = OSD.width - element.width
    } 

}


OSD element of type string can be use array of string, whose  its xmin and y min is always 0.  xMax is length of the longest string. yMax is number of strings.

**Comment by mikeller** [comment]
@dronejunkie: Yes, that sounds about right - what is neglected in the current code is proper calculation of the mouse cursor position relative to the element.

**Comment by dronejunkie** [comment]
Sorry Michael,  hopefully I will get sometime next week to completed this.

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - Github identifies PR as mergeable -> FAIL
 - PR is not in draft -> PASS
 - Assigned to a milestone -> PASS
 - cooling off period lapsed (19/02/2021 21:42:25) -> PASS
 - commit count less or equal to three (1 commits) -> PASS
 - 'Don't merge' label NOT found -> PASS
 - 'Needs coordination with betaflight' label NOT found -> PASS
 - At least one 'RN:' label found -> PASS
 - 'Tested' label found -> FAIL
 - assigned to an approver (None) -> FAIL
 - approver count at least three (0 approvers) -> FAIL

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - Github identifies PR as mergeable -> FAIL
 - Assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - 'Don't merge' label NOT found -> PASS
 - At least one 'RN:' label found -> PASS
 - 'Tested' label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Comment by haslinghuis** [comment]
Closing as inactive. Can be reopened when @dronejunkie decides to continue his work.

**Comment by ctzsnooze** [comment]
@dronejunkie - Hi Jack - any chance you can review this again?  It would be great to fix this for 4.3.

**Comment by dronejunkie** [comment]
Hi Chris,

Due to work and other commitments I do not have time anymore. Sorry about
that.

J.

**Comment by nerdCopter** [comment]
is this still required, or is master working as expected now that  HD was done? if still required, need rebase from master and continued testing.

**Pull request closed without merging**
