### PR TITLE
Sort and translate font name at OSD tab

### PR DESCRIPTION
**Pull request by HThuren**
- Translate font name
- Sort optionlist for fonts at OSD tab by translated name

Now:
image
image

Before:
image
image

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Review by haslinghuis — APPROVED** [review]

**Comment by nerdCopter** [comment]
i dont think this is necessary. it separates Large and Extra Large and it also moves Default from the top. (only looking at screencap, did not test.)
image

**Comment by HThuren** [comment]
@nerdCopter 
Default are placed in top by the sort function.
And I rename Extra Large to "Large Extra", that will do

**Comment by nerdCopter** [comment]
well Default not on top of list for Preview.  but is correctly first for Font manager.
image


If this PR is importatnt, then maybe a suggest, remove `Font `-text from selections, and instead insert the word `Font` into the HTML in from of the drop-down list. :man_shrugging:   However such may require more i18n language entries.

Mockup:
image

**Comment by HThuren** [comment]
I give it a try :-)

**Comment by HThuren** [comment]
Now 
image

**Comment by HThuren** [comment]
@nerdCopter approval ? :-)

**Review by nerdCopter — APPROVED** [review]

**Review by haslinghuis — APPROVED** [review]

**Pull request merged**
