### PR TITLE
Chore/use modules

### PR DESCRIPTION
**Pull request by chmelevskij**
Trying to move more of the parts to ESM modules

### CODE REVIEW

**Review by mikeller — APPROVED** [review]

**Comment by McGiverGim** [comment]
@chmelevskij why is this in draft? It needs more testing? Are you planning to move more files to modules (I recommend to do it in other PR, and let this small)?

**Comment by chmelevskij** [comment]
it's in Draft because I didn't had proper FC to verify it actually works.

This is about the size it will be, doing all in single go will be crazy, I've already tried it. There is to much going on and sonar cloud would go mental.

**Comment by chmelevskij** [comment]
Done some smoke testing, seems to be working.

**Comment by Asizon** [comment]
@chmelevskij  There is some issue parsing hex after this, unable to flash firmware.

**Comment by chmelevskij** [comment]
Hmm, I guess something in common.js is not exposed properly. What is the exact issue?

If it's a util function maybe it's worth just copy pasting it into firmware flasher part.

**Comment by mikeller** [comment]
The problem is in `hex_parser.js`, which is used as a Worker in a separate thread - I think this will never play well with modularisation.

**Comment by chmelevskij** [comment]
Ahh, ok. It will eventually, but there will be growing problems.

TBH, I think easiest would be to just copy that function to there, it's a simple function and would allow moving forward

**Pull request merged**
