### PR TITLE
Moved profile selection into PID Tuning tab. Did some visual cleanup.

### PR DESCRIPTION
**Pull request by mikeller**

### CODE REVIEW

**Comment by KiteAnton** [comment]
Good work. Works as expected.

**Comment by mikeller** [comment]
Thanks for checking, @KiteAnton. Unfortunately, when trying this morning in the office with my 'office quad', the PID Tab did not update when changing the profile. Will investigate more tonight.

**Comment by KiteAnton** [comment]
I tried it and if seemed to work.  Changed some values for one profile, saved,  then switched to the other profile and that profile values were loaded.

**Comment by mikeller** [comment]
My bad. Turns out the quad was set to two profiles/rateprofiles that have exactly the same values, hence I did not see any change when switching profiles. Just goes to show rateprofile switching needs to be added to the GUI.

**Pull request merged**
