### PR TITLE
Fix3dshot

### PR DESCRIPTION
**Pull request by rotcehdnih**
minor fix to #674 - when in the slider hits bottom the disarm value was being sent this makes it so the user can test full range without disarming

### CODE REVIEW

**Comment by mikeller** [comment]
This is intentional, to make sure that the motors are stopped when the sliders are at the bottom of the range (just like it is for OneShot, when the ESCs are properly calibrated).

What is wrong with this behaviour in your opinion?

**Comment by rotcehdnih** [comment]
the behavior of 3d mode with oneshot in the motor tab use to range from throttle min to throttle max with 3d neutral being the disarmed output , likewise with dshot 1500 is stop so when a user goes to test in the motor tab you want the slider to start in the middle and when the user enables the motors and moves the slider all the way to the bottom it should be sipping at max not disarmed

**Comment by mikeller** [comment]
Ah, now I see. It wasn't clear to me that your comment only applies to  3D. Considering we are emulating the Dshot 3D idle behaviour on the flight controller side already, I think this should better be done there as well. I.e. the translation will completely move the idle / disarmed point to 1500 for 3D.

**Comment by rotcehdnih** [comment]
I'm not sure i get what you mean by do it on the flight controller , my understanding is the FC is working as expected so if in the configurator 1001 = 1047 then i feel that should be the value of rangeMin when 3D mode is active.

**Comment by mikeller** [comment]
@rotcehdnih: 'A PR says more than 1000 words', as they say ;-): betaflight/betaflight#4202

Can you please test if this, in conjunction with #674 has the desired effect in 3D mode?

**Comment by rotcehdnih** [comment]
arha i see , yea that looks good 👍 . gota head to work but ill test tonight when i get home :)

**Comment by mikeller** [comment]
Thanks!

**Comment by mikeller** [comment]
@rotcehdnih: Ok to close this now, since betaflight/betaflight#4202 is implementing the same change on the flight controller side.

**Comment by rotcehdnih** [comment]
yep happy as :)

**Pull request closed without merging**
