### PR TITLE
Removed support for 32 kHz gyro mode.

### PR DESCRIPTION
**Pull request by mikeller**
Related to betaflight/betaflight#7567.

### CODE REVIEW

**Comment by McGiverGim** [comment]
I'm not too sure about the solution. Maybe I'm wrong, but I think is easier:
- Let all the MSP stuff unmodified. The firmware has been modified to send 0 always in the 32K capable, so it will work as is, and the code is simpler.
- Hide the slider for MSP version bigger than 1.41.0, it has no sense to have it if not supported by the firmware.
Maybe is there something more that I'm not taking into account?

**Comment by mikeller** [comment]
@McGiverGim: It's potentially easier, but I think also making sure we're not inadvertently sending values that enable 32kHz gyro is cleaner - especially now as the versions of 4.0 that are out there still support this mode.

**Comment by McGiverGim** [comment]
This "old 4.0 versions" can enable the 32Khz mode in CLI, so there will be always a way, and I don't see this different to other values that we have removed. The backwards compatibility in the configurator makes the code complicated so if we can simplify some things I think we must do it.

The only problem can happen if some user activates the 32Khz in a development version, and then uses the "final" version of the configurator without erasing all the data, but I don't know if we must complicate the code only thinking in this situation.

**Comment by mikeller** [comment]
I don't think that this is adding too much complexity, compared to the risk of accidentally enabling 32 kHz for a user's config, and then not showing it in the UI, leaving him with incorrect values for loop frequencies.

**Pull request merged**
