### PR TITLE
Remove font-awesome

### PR DESCRIPTION
**Pull request by Docteh**
I've done my best to look for any references to font awesome, and I don't see any. 

Its possible that the icons on the left were initially from font-awesome.

### CODE REVIEW

**Comment by Docteh** [comment]
Here is a rendering of their trash icon in internet explorer to rememeber it by. 
image
Github wouldn't let me upload the .svg, so I figured I'd oversell trashyness.

**Comment by McGiverGim** [comment]
@Docteh maybe this reference was forgotten in this PR?

https://github.com/betaflight/betaflight-configurator/blob/55df431247fab16913507f4a6cf7eacf030c0e9d/gulpfile.js#L233

**Comment by Docteh** [comment]
Cock. 

Can you add that deletion to #1800?

**Comment by McGiverGim** [comment]
I'm out of the computer, I can do another PR tomorrow.

**Comment by Docteh** [comment]
@McGiverGim I rolled out of bed and submitted #1801 so its good now, thanks for noticing

**Pull request merged**
