### PR TITLE
Dogcom logo: light and dark theme

### PR DESCRIPTION
**Pull request by KarateBrot**
Replaces the current logo with themed images.

Don't merge yet or the Dogcom logo will not display in the sponsors tab

### CODE REVIEW

**Review by nerdCopter — APPROVED** [review]
- approving for when ready

**Review by blckmn — APPROVED** [review]

**Comment by nerdCopter** [comment]
lol
image

**Comment by blckmn** [comment]
Bugger I needed the logos for the configurator

**Comment by nerdCopter** [comment]
current status:
image
image

**Pull request merged**
