### PR TITLE
Translate labels at reciever signal graph

### PR DESCRIPTION
**Pull request by HThuren**
Making possible to translate Roll, Pitch, Yaw and Throttle
image

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Review by McGiverGim — COMMENTED** [review]
What is the letter inside the brackets? At the beginning I thought it was some kind of shortcut, but looking at them they form AERT, so is a relation with the TX command, usually used for planes. Has some sense to maintain it here? The Roll, Pitch, Yaw and Throttle I think is enough informative. What others think?

**Comment by nerdCopter** [comment]
Please check Sonar-Cloud about surrounding `<li>` items.
Concur with @McGiverGim , sentiment. looks good, but no clue what servo users expect.

**Comment by HThuren** [comment]
The cloud issue are now fixed. 
I agree, the letters, looks like AERT order of transmitter pins. There are no logic in code regarding the pin in use.
I found the same setup -also in reciever.js - for         
```
// generate bars
        const bar_names = [
            i18n.getMessage('controlAxisRoll'),
            i18n.getMessage('controlAxisPitch'),
            i18n.getMessage('controlAxisYaw'),
            i18n.getMessage('controlAxisThrottle'),
        ];

```

**Comment by haslinghuis** [comment]
AETR is the default order. We should not translate these letters.

**Comment by HThuren** [comment]
Agree, then there also are no changes to this PR.
I my danish translation I translate ex "Pitch [E]" to "Højderor [E]" to keep relation to AETR

**Review by haslinghuis — APPROVED** [review]

**Pull request merged**
