### PR TITLE
Added STICK_COMMAND_EXECUTED beeper condition.

### PR DESCRIPTION
**Pull request by zvonler**
First time contributor, these are changes to make available an optional beep when stick commands are executed. I did my best with the localization to mimic the grammar of the existing messages in the non-English locales.

BF changes to add feature: https://github.com/betaflight/betaflight/pull/13069

### CODE REVIEW

**Comment by McGiverGim** [comment]
You don't need to make the translations. They will be lost when we pull the translations files from Crowdin. Only English messages must be part of any PR.

**Comment by zvonler** [comment]
> You don't need to make the translations. They will be lost when we pull the translations files from Crowdin. Only English messages must be part of any PR.

Ah, that makes sense. I'll take out the other languages.

**Review by McGiverGim — APPROVED** [review]
Sorry, I forgot this. It's ok!

**Comment by nerdCopter** [comment]
do we want to gate this with some `USE_` ? @haslinghuis @blckmn 
and if so how to account in Configurator?

**Comment by zvonler** [comment]
Should still be viable.

**Comment by haslinghuis** [comment]
Closing as firmware PR got stalled.

**Pull request closed without merging**
