### PR TITLE
Fix mag declination

### PR DESCRIPTION
**Pull request by haslinghuis**
Fixes: https://github.com/betaflight/betaflight-configurator/issues/3761

### CODE REVIEW

**Review by nerdCopter — APPROVED** [review]

**Comment by HThuren** [comment]
There are something with puncation. I can only write and have accepted z.y , but display show z,y (english language choosen)

**Comment by haslinghuis** [comment]
Shows a point here (using system default = English)

image

**Comment by HThuren** [comment]
yes, I see, my system default are DA = ',', but I think this issue are bigger than this PR. I will approve.

**Review by HThuren — APPROVED** [review]
See bug described in issue in elder version, and no bug in this PR

**Pull request merged**
