### PR TITLE
Fix Android receiver tab (replace MD5 library)

### PR DESCRIPTION
**Pull request by haslinghuis**
Fixes ELRS UUID in receiver tab for Android as the tab was not loading before by replacing MD5 library with an ESM version resulting in a smaller build.

### CODE REVIEW

**Review by sugaarK — APPROVED** [review]

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by chmelevskij — APPROVED** [review]

**Comment by limonspb** [comment]
i think this PR breaks receiver tab on Windows @haslinghuis 
I did a loong bisecting and it came down to this commit. The error in console:
`Uncaught (in promise) TypeError: Failed to resolve module specifier "crypto-es/lib/md5.js". Relative references must start with either "/", "./", or "../".`
receiver tab shows "loading data with the circle"

**Comment by haslinghuis** [comment]
You have to build in a new folder because of library update. It's working here on Linux and Windows.

**Comment by limonspb** [comment]
> You have to build in a new folder because of library update. It's working here on Linux and Windows.

"in a new folder", you mean clean DIST and DEBUG folder? I just did, still doing the "waiting" and error.

**Comment by haslinghuis** [comment]
Master still works for me - even on Windows and Android
You also need to `rm -rf node_modules/ cache/ release/`

**Pull request merged**
