### PR TITLE
Remove flickering when fix is unstable

### PR DESCRIPTION
**Pull request by McGiverGim**
Fixes https://github.com/betaflight/betaflight-configurator/issues/1309

### CODE REVIEW

**Comment by McGiverGim** [comment]
No, I forgot to add and alternate icon or similar... now it simply does not move... I will look into it a little more...

**Comment by mikeller** [comment]
@McGiverGim: Good point. But even without that stopping the flickering makes it a lot more usable, so if you don't have time to look into the icon I think we should merge it as it is.

**Comment by McGiverGim** [comment]
Done, I'm not a good icon designer, so no problem if someone wants to make it better ;)

**Comment by mikeller** [comment]
Looks good to me. I think having the question mark go on and off is all that's really needed.

**Pull request merged**
