### PR TITLE
Hide Motor PWM Speed Separated from PID Speed when DSHOT selected

### PR DESCRIPTION
**Pull request by mosvov**
As described in #603

### CODE REVIEW

**Comment by mikeller** [comment]
Fixes #603.

**Comment by mikeller** [comment]
@mosvov: Thank you for your contribution.

Unfortunately this does not yet work as it should: If 'Motor PWM speed is separate from PID speed' is selected prior to Dshot being selected:

image

then 'Motor PWM frequency' is showing after Dhshot has been selected:

image

Please fix!

**Comment by mosvov** [comment]
Fixed

**Comment by mikeller** [comment]
Unfortunately your fix is invalid:
- `use_unsynced_pwm` to off when Dshot is selected is wrong. If a user has unsynched PWM enabled with a PWM protocol, then switches to Dshot, and then back to PWM, unsynched PWM should be in the same state as it was before the user switched;
- if Dshot is selected in the CLI, the PWM frequency input still shows:

image

**Comment by mosvov** [comment]
Now should work as expected

**Comment by richard-scott** [comment]
I can close #603 once this is merged :-)

**Comment by mikeller** [comment]
Working fine now, thanks!

**Comment by mikeller** [comment]
@richard-scott: Too late! :stuck_out_tongue_closed_eyes:

**Comment by richard-scott** [comment]
lol :-)

**Pull request merged**
