### PR TITLE
Configurator rebranding

### PR DESCRIPTION
**Pull request by skaman82**
bildschirmfoto 2016-06-12 um 18 27 26
bildschirmfoto 2016-06-12 um 18 27 23

### CODE REVIEW

**Comment by skaman82** [comment]
@borisbstyle what do you think?

**Comment by Yamaford** [comment]
Nothing short of amazing Albert

**Comment by borisbstyle** [comment]
Awesome!

When I get back from holiday I want to start implementing betaflight
specific configuration to it.
Op 12 jun. 2016 21:44 schreef "Yamaford" <notifications@github.com>:

**Comment by skaman82** [comment]
@borisbstyle Great, I merge this then!

**Comment by borisbstyle** [comment]
I really love it. Thanks man.

So next things to change are these:
Remove rate stuff in rx tab
Add those in PID tuning tab behind each axis.
For example:
Pitch pids and behind that Pitch rc rate, pitch rate and pitch expo.

In the configuration tab. Oneshot125 feature has to be removed too and
preferably be replaced by a slide where you can choose between all fast pwm
protocols.
Op 12 jun. 2016 22:15 schreef "Albert Kravcov" <notifications@github.com>:

**Comment by blckmn** [comment]
Looks so good! :)

**Comment by skaman82** [comment]
Thanks! Also the first thing to do is to change the firmware source in the Firmware-Flasher Tab to support betaflight flashing directly through the app

**Comment by mikeller** [comment]
> Remove rate stuff in rx tab
Add those in PID tuning tab behind each axis.
For example:
Pitch pids and behind that Pitch rc rate, pitch rate and pitch expo.

Working on this now. @borisbstyle I assume you want identical values displayed for pitch / roll rc rates and rc expo?

**Comment by borisbstyle** [comment]
yes all same for pitch roll and yaw, but all seperately configurable.

pid controller selection has to go. There will be just one pid controller.
Op 14 jun. 2016 14:16 schreef "Michael Keller" <notifications@github.com>:

**Comment by mikeller** [comment]
> but all seperately configurable.

Where should the fields be bound to? I can only find rc rate / yaw rc rate / rc expo, and not separate ones for pitch / roll / yaw.

Also, shouldn't we wait with removing the PID controller selection until all but one PID controller has been removed?

**Comment by borisbstyle** [comment]
i will add seperate rc rate and rc expo for each axis later on in
betaflight firmware. Dont worry about that.

Also there is floating point pid controller and integer based one. F1
boards will use integer math (rewrite) and F3 boards will use float version
(luxfloat)
Op 14 jun. 2016 14:53 schreef "Michael Keller" <notifications@github.com>:

**Comment by borisbstyle** [comment]
Also I would like to have a rate calculator graph in the gui
Op 14 jun. 2016 15:14 schreef "Boris B." <dreambb1982@gmail.com>:

**Comment by mikeller** [comment]
Ok, will work on this more when the fields can be bound.

**Comment by mikeller** [comment]
How should the rate calculator work?

**Comment by skaman82** [comment]
@mikeller please be careful with adding new stuff. It should not break compatibility with older versions. If should work depending on api version. New version = new GUI layout, old version = old GUI layout. Also be advised that every new element should be included in the backup/restore routine

**Comment by borisbstyle** [comment]
Yes I agree, but we are practically starting the "first" version :)

But backwards compatibility with older versions would be nice.
Op 14 jun. 2016 15:45 schreef "Albert Kravcov" <notifications@github.com>:

**Comment by mikeller** [comment]
@skaman82: Totally agreed, that's why I won't be adding fields for features that do not yet exist in the firmware.
For now, I'll just move the existing rc rates / expo fields from the receiver tab to the PID tab, as having them and the rates split between two tabs makes configuration tedious.

**Comment by skaman82** [comment]
@borisbstyle Technically yes, but there are sure some people around flying BF 1.5.x and want to stick to it for a while. The new configurator should work for them too without any hickups.

**Comment by mikeller** [comment]
Also, re backup / restore, I would be tempted to implement dumping / restoring of master_config, and add this in properly encoded form to the backup file that is stored. This way, at least when restoring to the same firmware version, getting all settings included would be a breeze. @borisbstyle, what do you think?

**Comment by skaman82** [comment]
@mikeller see also https://github.com/betaflight/betaflight-configurator/issues/9

**Comment by mikeller** [comment]
Scratch my earlier comment (and sorry for using githb as my rubber ducky). I'll just add two buttons 'CLI Backup' and 'CLI Restore' to the CLI tab, and presto, backup done, including between different versions. And nobody needs to get their hands dirty in the CLI.

**Comment by skaman82** [comment]
@mikeller I know, this might be a EASY solution but is is far from ideal one. The main Problem with a CLI dump restore is that may advanced setting (that only few users play with) like filter settings are changing through different versions. Applying a cli dump for restore just set back those defaults to an earlier version. In ideal world there should be an option for restoring (normal user/GUI settings) AND a full dump restore.

**Comment by mikeller** [comment]
@skaman82: I can see what you mean, but I do not think this is a CLI vs GUI issue.

Default settings change, irrespective of being available in GUI and CLI, or CLI only. (Think of the recent changes to rates / rx rates defaults for example.) So only backing up all the values available in the GUI will not actually solve this, as this will still overwrite new defaults with old defaults for values that are available in the GUI.

What we really need to solve this is a way to only back up the values that have been changed away from the default values. I don't know how much work this is to do for the GUI backup (you are the expert there), but I will look into adding a `dump changes` command to the CLI.

And yes, totally agreed that having to use the actual CLI to do dumps / restores is archaic and less than ideal. That's why I proposed to add 'Backup' and 'Restore' buttons to the CLI tab, make them work much like the 'Backup' / 'Restore' buttons in the first tab, but under the hood call the CLI functions to dump and restore.

**Comment by skaman82** [comment]
@mikeller I never said that this is a CLI vs GUI issue. I have no problem with CLI, I just don't want to use it. CLI has its purpose but I just think it shouldn't be used for backups and we need a better backup function in the GUI that makes life easier and leave the CLI for config only.

**Comment by nathantsoi** [comment]
its nice to be able to dump / restore the text b/c you can diff it easily
to keep changes you want and throw out those that you dont. it would be
cool if we had a diff-tool type ui to merge changes after an upgrade

**Comment by mikeller** [comment]
@skaman82:

> @mikeller I never said that this is a CLI vs GUI issue :). I have no problem with the CLI, I just don't want to use it.

That's exactly why I proposed adding buttons for a CLI - based backup to the GUI. ;-)

@nathantsoi:
Totally. I keep my configs in version control, just to be able to easily diff them. 
The GUI backup files are JSON these days, so diffing them should be possible as well (albeit they should have proper line breaks added for this to not be a pain).
With respect to having to do a manual diff and sorting out the values you actually want to keep (I know the pain), having a command to dump only the values that are **not** default values should make this somewhat better I think, and I will look into this when i get around to it.

**Comment by skaman82** [comment]
Somehow this is hard to convince people of this - it is maybe because it has been this way from beginning and devs get used to it or even like it. Honestly, I don't know why. Everybody I talk to (who is not a dev) hates the CLI and don't uses it at all for config. So if we make a GUI for Backup&Restore that works BETTER and stores your backups in the configurator and has a export function for backups (and maybe even a select tool what to restore), soon nobody would even remember the old dump stuff.

**Comment by skaman82** [comment]
@mikeller "That's exactly why I proposed adding buttons for a CLI - based backup to the GUI. ;-)" This is a good idea, but why don't go further than this?

**Comment by mikeller** [comment]
@skaman82:

> So if we make a GUI for Backup&Restore that works BETTER and stores your backups in the configurator and has a export function for backups (and maybe even a select tool what to restore), soon nobody would even remember the old dump stuff.

I really can't see why you are so opposed to keeping the CLI and CLI dumps around. But there are a bunch of use cases that are not or are badly covered by what you are proposing:

- people want to use the configurator on more than just one machine. Storing configs locally in the configurator won't help them (unless we make the configurator store them in the cloud).
- people like to compare configs in text form ('what did I change back then?') and use snippets of them to discuss things online or submit bug reports

> Are we making this for devs or for other people out there?

In my opinion clearly for both. ;-)

I never said you should not work on your improvements for the GUI backup. But I can not see why we should not keep both ways to backup / restore around, and let every user decide for themselves which one is the one they prefer?

> @mikeller "That's exactly why I proposed adding buttons for a CLI - based backup to the GUI. ;-)" This is a good idea, but why don't go further than this?

That's simple: What I am proposing is already the optimal solution for my requirements. :-P

**Comment by skaman82** [comment]
@mikeller Agreed. Let's try to do both to make everybody happy. I am willing to do the HTML/CSS work for the new backup tab but really need help for the rest of the way. I don't know JS and I guess there would be some firmware changes necessary too.

**Comment by mikeller** [comment]
@skaman82: With respect to GUI, what I thought I'd do was to add two buttons 'Backup' / 'Restore', and potentially a 'only backup changes' checkbox, either above the terminal window, or at the bottom of the tab. Plus maybe a help text explaining that this backup is different to the backup in the first tab, to keep people from trying to restore GUI backups in CLI and vice versa.
I am also happy to help improving the GUI backup, so let me know if you need js / FC changes done.

**Pull request merged**
