### PR TITLE
Add Vue devtools to the debug mode

### PR DESCRIPTION
**Pull request by McGiverGim**
Adds the Vue devtools to the `yarn start` command. It does not add it to other "similar" commands like `gulp debug`, maybe we can look to do the environment injection in the gulp file and not in the package to achieve the same.

This PR uses `cross-env` to fix the problem of environment variable in windows, but maybe is better to use this other solution: https://github.com/betaflight/betaflight-configurator/pull/2226 based on `script-os`. So first we need to decide which of them we take before merging this.

### CODE REVIEW

**Comment by mikeller** [comment]
To be fair I prefer `script-os`, as it works at a lower level (i.e. it can be used to make things in yarn targets other than environment variables platform dependent.

**Review by mikeller — DISMISSED** [review]
I think making this work for the `yarn...` invocation is entirely sufficient - this is the correct way to invoke gulp, as calling `gulp...` directly will call the `gulp` binary in the path, which may or may not end up using the version of gulp that is specified in `package.json`.

**Comment by McGiverGim** [comment]
> To be fair I prefer script-os, as it works at a lower level (i.e. it can be used to make things in yarn targets other than environment variables platform dependent.

Perfect, I will rebase this after the other PR is merged.

**Comment by McGiverGim** [comment]
Rebased and ready to be merged!!!

**Review by mikeller — APPROVED** [review]

**Pull request merged**
