### PR TITLE
Added buttons for reboot into boot loader and MSC modes.

### PR DESCRIPTION
**Pull request by mikeller**
To go with betaflight/betaflight#6365.

### CODE REVIEW

**Comment by McGiverGim** [comment]
The code is good. What I'm not too sure is about the MSC button. Maybe in the blackbox tab is where a user will look into it. But in the setup tab is the first that loads so not bad neither.

**Comment by mikeller** [comment]
@McGiverGim: Good point, will think about that.

**Comment by flint723** [comment]
I also think it should be in Blackbox tab, next to "save to file" button.

**Comment by mikeller** [comment]
@McGiverGim. @flint723: Yeah, on close consideration, the blackbox tab is the best place for this button. Will change.

**Comment by flint723** [comment]
#1058

**Comment by mikeller** [comment]
Fixes #1058. Thanks @flint723.

**Pull request merged**
