### PR TITLE
feat: use modules instead of global bindings

### PR DESCRIPTION
**Pull request by chmelevskij**
* Remove things attached to `window` global object.
* Use esm imports for some of the `node_modules`.
* Add new eslint rules. `no-undef` and `no-duplicate-imports`.
* Move some of the helpers into their own files to avoid circular deps.
* Fix few bugs which were using un existing variables.

### CODE REVIEW

**Comment by haslinghuis** [comment]
Tested. Upon opening OSD tab:

```
osd.js:3234 Uncaught (in promise) TypeError: $(...).jBox is not a function
    at HTMLDivElement.<anonymous> (osd.js:3234:56)
    at Function.each (jquery.min.js:2:3003)
    at S.fn.init.each (jquery.min.js:2:1481)
    at osd.js:3233:35
```

**Comment by chmelevskij** [comment]
@haslinghuis fixed now

**Comment by haslinghuis** [comment]
:upside_down_face:  getting same error :yum:

**Comment by blckmn** [comment]
I'd like to get this in and release RC5 ASAP (for the motors tab issue).

@chmelevskij I think this should be the last one done for 10.9. Anything else needs to be done in the next version please.

**Comment by blckmn** [comment]
@chmelevskij in addition your new files are named using Snake Case. Please update to Camel Case. The bulk of the files are Camel Case already and you should maintain consistency. 

For the next release I will update all files to be Camel Case.

**Comment by chmelevskij** [comment]
Update file names. I'll be doing things you can merge them whenever it's ready for next release.

**Comment by haslinghuis** [comment]
Problem is on 3rd line: `uncaught (in promise) TypeError: $(...).jBox is not a function`

```
                    // Generate tooltips for OSD elements
                    $('.osd_tip').each(function() {
                        OSD.data.tooltips.push($(this).jBox('Tooltip', {
                            delayOpen: 100,
                            delayClose: 100,
                            position: {
                                x: 'right',
                                y: 'center',
                            },
                            outside: 'x',
                        }));
                    });
```

**Review by blckmn — APPROVED** [review]

**Review by haslinghuis — APPROVED** [review]

**Comment by wKich** [comment]
Wow, that's awesome change!

**Pull request merged**
