### PR TITLE
i18n final statistics from OSD

### PR DESCRIPTION
**Pull request by McGiverGim**
i18n the final statistics of the OSD.

Again, I have modified the texts to group them when reordered by alphabetical order. It will be great if someone with better English knowledge can check them to see if they are correct. I paste a capture to simplify the review:
image

### CODE REVIEW

**Comment by McGiverGim** [comment]
I have observed this comment:

https://github.com/betaflight/betaflight-configurator/blob/7f452d9c96db5b09685531dadce371e64ca67daa/src/js/tabs/osd.js#L1506

Is ok to reorder in alphabetical order, or is better like they are on the screen? With the number growing and growing, I prefer alphabetical order but maybe others don't think the same.
- In the first case I can clean a little removing the old reordering code
- In the second case I need to remove the alphabetic reorder of this PR

**Comment by mikeller** [comment]
@etracer65: What do you think?

**Comment by McGiverGim** [comment]
I have seen that the code in the Configurator reorders it, because it was necessary to be in the same order than the MSP command, that I suppose is the same order than the screen. It was changed in version 1.39.0 of MSP. So there is nothing to clean in the code, only decide if we want to maintain the screen order or use an alphabetic order.

**Comment by etracer65** [comment]
I've always advocated they be presented in the configurator the same way they're ordered in the OSD. That was the reason for the original reordering. Subsequent changes have broken that by applying what is thought to be a more logical order in the OSD by grouping things that are related (like keeping the ESC stats together, or the GPS things in a group). The problem is that anytime we want to change the order in the configurator we have to change the bit order for the enabled stats since thats the way the configurator works. Changing the bit order then will break saved settings. So it's a mess no matter what.

At a high level I'd advocate for more logical function grouping rather than alphabetical. The problem with alphabetical is that even a simple renaming of an element would change its ordering.

What we really need to do is disconnect the presentation order from the storage. The stats flags need to remain fixed and the presentation order is variable. Ideally then we could even extend this to let the user reorder their personal OSD stats screen by dragging the order in the configurator.

**Comment by McGiverGim** [comment]
It's not totally true that the Configurator order depends on the storage. This PR changes that, ordering it in alphabetical way without changing the storage order. We can do it in other ways, specifying an order number in the Configurator but we need a way for the user to find the exact element easy in the list, specially because it grows a lot version to version, and to me it is the alphabetical way, specially after translations.

It's clear that it will be ideal to have them grouped by a "descriptor" or similar, but at this stage, this is an easy way to do it. If you look at the image, the name of the statistic has "changed" from the real on screen menu. It starts by the word that lets group it (for example, battery). 
If we use later a real group descriptor, we need to orden them inside the group in some way. An alphabetic order is the more logic option and works for all languages.

**Comment by McGiverGim** [comment]
@mikeller @etracer65 some final decision about this? I have other PR pending that will conflict with this, so I prefer to get this merged before.

**Comment by etracer65** [comment]
I think that by renaming (or at least altering) the OSD stat name for better alphabetical sorting we further increase the potential confusion. Now not only is there no relationship to the settings vs. output order, the different naming makes it even more difficult to relate the items to the settings.

Extending the configurator to allow a sorting different then the bit order is a good step. I just think the ordering should be driven by the firmware. I think we need to disconnect the bit position from the ordering so that the setting storage remains unchanged. This then opens up the possibility to reorder the output without corrupting the settings and also pass this ordering through MSP to support the display. Later this could potentially be extended to allow the user to reorder the statistics (some UI in the configurator and send back the order for each stat via MSP).

**Comment by etracer65** [comment]
I can work on making the stats display order driven by the firmware (from an array rather then in the code) and pass the order through MSP so that the Configurator can display the stats in the same order. For example, adding to the end of the `MSP_OSD_CONFIG` message:
```
        // API >= 1.42
        // Post-flight stats display order
        for (int i = 0; i < OSD_STAT_COUNT; i++) {
            sbufWriteU8(dst, osdStatsDisplayOrder[i]);
        }
```
` osdStatsDisplayOrder[]` will contain the `osd_stats_e` values that define the permanent stats entry that correspond to the bit position in the storage.  So for now ` osdStatsDisplayOrder[]` will be a `const` array that defines the order and the OSD rendering will respect that. The Configurator can use the ordering info and also present the elements in the same order. Later if we want to add user configurability then `osdStatsDisplayOrder[]` could become a variable array that can be altered and its elements stored as a parameter (probably using the `MODE_ARRAY` settings type).

Just in working out how to do it I have most of the work done. Just need to test.

**Comment by McGiverGim** [comment]
When translated, the firmware name of the stat will not be the same than the feature in any way. I understand that for English is better to be close to reality (ignoring the limiting space of the goggles, of course, in the Configurator can be larger).

We have 27 statistics at this moment. And this will grow. When showing them in the OSD is not a problem, you show six or eight elements and the user can see them easily. But in the Configurator it has all of them. Near 30 elements (and in a future they will be more, 40, 50...) and if the user wants to enable some, it needs and easy way to find the element. 

I understand that you want to order them in the same order than the firmware in the Configurator, if you produce a good order, it will help a little, at least they will be grouped, but it will complicate the things. To do this is better to pass one bit enabling or disabling the statistics, and 7 bits for specifying the order (and deprecating the old way of enabling statistics).

We have ordered now the OSD elements, and the Warnings in alphabetic order. So to me it produces a better and consistent UI have all of them in similar way.

To me:
- Alphabetic order in Configurator
- In English, we can modify the firmware to show the texts in the same way that in the Configurator if we want.
- If we want, we can modify the order in the firmware to be "alphabetic" too (in manual way). But to me is not a problem. As I say, there are very few elements on the screen.

I think we have different opinions and visions, yours more from the firmware part, mine more from the Configurator part. I don't think we can get to an agreement. Someone will need to decide the final solution (I can put a switch to order in both ways in the Configurator, but I don't think this is a good idea).

**Comment by etracer65** [comment]
Created https://github.com/betaflight/betaflight/pull/8452 to disconnect the display order from the storage bit position. Turns the `osd_stats_e` enumeration into permanent ID's that will always identify the particular stat (and is tied to its storage position). The actual display order is a separate array that contains `osd_stats_e` entries in the desired  display order. This display order is added to the `MSP_OSD_CONFIG` message for use by the Configurator.

@McGiverGim - there are currently 24 post-flight stats. There won't be more than 32 without other significant changes as the underlying flag storage is a `uint32_t`.

By using the supplied ordering the Configurator will always remain synchronized to the firmware. Once implemented subsequent changes to the ordering in the firmware will not require any changes to the Configurator. Additionally display order changes will have no impact on the storage or user settings. Basically the display ordering can be changed as needed/desired with no knock-on effects.

**Comment by etracer65** [comment]
And just to reiterate - I don't see what benefit having the stats presented in alphabetical order brings. With the names having to be mangled (and different than the firmware presentation) to imply some artificial ordering to enable some kind of "like" stats grouping. Then further to have the order completely change for other languages due to the translation and the now different alphabetical order (and resulting corruption of the implied grouping).

The consistent item is the presentation order in the firmware. By using this ordering we additionally give the user a "preview" of how the stats will be displayed. The Configurator options will match the stats presented in the OSD and the ordering will be unaffected by the translation.  If desired, we could even implement a "hide disabled stats" switch to only show the enabled stats - this would make the selections exactly match the OSD display as a further preview.

And as mentioned previously, the foundation is now in place to extend functionality to allowing user-configurable ordering if we want.

**Comment by McGiverGim** [comment]
If you think at any list you look at, all of them have some kind of order to let you search at them. Maybe by date, alphabetical or by some field. Here we only have ONE field. The name of the statistic.

Me and any other user that, for example, wants to enable some battery statistic, prefer to have all the battery statistic near and at a place that can be found directly, and not to have to read all 27 elements searching which of them is a battery statistic and which is better. The same for RSSI or GPS based statistics. This is the benefit and is evident. Look at the OSD elements now in the configurator, I'm sure you can find any of them faster than with the old version that does not order them.

If we want an OSD Statistics preview, we can add them as we did with the OSD elements. I think is better than hide some unordered elements, but I haven't did it before because I don't think the effort will pay the result and is difficult to fit in the screen for some small resolution users. The OSD preview scrolls with the page so I can't simply put it under the other.

As I said, we both have different opinions and visions totally differents, so I see difficult to get to a common solution. Both of us have good reasons for it.

**Comment by etracer65** [comment]
> Me and any other user that, for example, wants to enable some battery statistic, prefer to have all the battery statistic near and at a place that can be found directly, and not to have to read all 27 elements searching which of them is a battery statistic and which is better. The same for RSSI or GPS based statistics. This is the benefit and is evident. Look at the OSD elements now in the configurator, I'm sure you can find any of them faster than with the old version that does not order them.

Exactly - and they should also be logically grouped together in the display order. The problem is that previously it was extremely difficult to change the display order - causing a settings reset and requiring changes to the Configurator. It's been done various times and is always painful. The PR I made fixes that. It allows "logical" grouping without having to mangle the names to indirectly induce the grouping through alphabetic sorting. The grouping is intentional, direct, and consistent. And having the naming causing a grouping by alphabetical ordering is problematic with other translations and they're clearly going to order differently.

Note that the PR doesn't yet change the ordering - just creates the framework to make it easy. A subsequent discussion about what the grouping should be will need to take place. But that change will be trivial.

**Comment by mikeller** [comment]
Mergeing this as it is a first attempt to improve on the 'historical order' that we have now. We can always explore better options (grouped) in further pull requests.

**Pull request merged**
