### PR TITLE
add firmware version to top bar

### PR DESCRIPTION
**Pull request by wind0r**
also adding firmware version to top bar, since most users just look there
image

"sorry" for the white space changes, just add ?w=1 to the diff to ignore them.
e,g https://github.com/betaflight/betaflight-configurator/pull/697/files?w=1

### CODE REVIEW

**Comment by mikeller** [comment]
Nice.

Can we make the target type explicit? (Like
```
Configurator: 10
Firmware: BTFL 3.2.0
Target: BJF4
```

This makes it easier for users to answer if they are asked: 'What target are you using?'

Also, should we remove the now redundant information from the status bar?

**Comment by wind0r** [comment]
I need to raise the topbar height if target is in a new line and then the connect button side looks strange.
Maybe a smaller font size or the logo a little higher would help but i didnt wanted to change the css so much. (since i am not fimilar with that stuff :D )

I think the redudant information at the status bar doesnt hurt.

**Comment by mikeller** [comment]
Or maybe just add `versionText += '('target: ' + hardwareId + ')'`?
(We should change the status bar to say 'target' instead of 'board' as well, there are enough users complaining 'but I've got a <board cloning SPRACINGF3> and not an SPRACINGF3'...)

**Comment by wind0r** [comment]
Changed to:
image

**Pull request merged**
