### PR TITLE
Remove outdated languages

### PR DESCRIPTION
**Pull request by McGiverGim**
Some languages have been "abandoned" by the translators. This PR removes languages with less than 50% of phrases translated and approved.

The languages are:
- Croatian
- Hungarian
- Indonesian
- Latvian
- Swedish

This PR can be merged now, or wait until the release of this version of the Configurator to give time to the translators to fix the problem before the next release.

### CODE REVIEW

**Review by haslinghuis — APPROVED** [review]
😭

**Comment by McGiverGim** [comment]
@haslinghuis what do you think? Wait until the next release? Maybe we can ask for help at discord to see if someone want to take the translators job of some of this languages?

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Comment by haslinghuis** [comment]
Does translation for the language stay in crowdin as we remove them here? So when contributors start working we can reintroduce. With such a low translation rate we should remove them before release.

**Comment by McGiverGim** [comment]
Yes, the translations remain in Crowdin.

**Review by blckmn — APPROVED** [review]

**Pull request merged**
