### PR TITLE
Fix missing GPS Laptimer OSD elements

### PR DESCRIPTION
**Pull request by haslinghuis**
image

### CODE REVIEW

**Comment by haslinghuis** [comment]
@SpencerGraffunder please check

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by SpencerGraffunder** [comment]
https://discord.com/channels/868013470023548938/1019022739044057128/1116834722191003658

If someone else could officially add, that would be great. I won’t have time for a few weeks.

**Comment by haslinghuis** [comment]
image

**Review by nerdCopter — APPROVED** [review]

**Comment by SpencerGraffunder** [comment]
[lap_timer_mcm.zip](https://github.com/betaflight/betaflight-configurator/files/12015625/lap_timer_mcm.zip)

**Comment by nerdCopter** [comment]
@SpencerGraffunder , any font changes would have to be done to all font variations.  Also, vendors already flash "default" font.  All pilots would need to update to use any new changes.
image
fonts have been stable for no less than 4 years: https://github.com/betaflight/betaflight-configurator/tree/master/resources/osd/2

not opposed to changes, just informing.

**Review by chmelevskij — APPROVED** [review]

**Pull request merged**
