### PR TITLE
Add metered connection and usability check

### LINKED ISSUE #4165: Slow or delayed connection during weak internet connection
### Describe the bug

Connect to a very slow or weak internet connection and try to connect to the drone via the com-port (I tried on Windows). It freezes often and does not go to the dashboard. But the port successfully opened.
If I disable the internet completely - it becomes much faster.

### To Reproduce

Connect to a very slow or weak internet connection and try to connect to the drone via the com-port

### Expected behavior

Fast response.

### Configurator version

10.10.0

### Flight controller configuration

```txt
N/A
```

### Add any other context about the problem that you think might be relevant here

_No response_

### PR DESCRIPTION
**Pull request by haslinghuis**
- fixes #4165
- reference: https://wicg.github.io/netinfo/

- adds option for user to disable connection when on metered or slow connection
image

- indicator on firmware flasher tab
image

- connection info on setup tab
image

- for future improvement we could add an icon for connection status.

### CODE REVIEW

**Comment by nerdCopter** [comment]
image
but seemingly inaccurate
image

**Comment by haslinghuis** [comment]
image

image

image

**Comment by haslinghuis** [comment]
@nerdCopter had tried to make it more intelligent, but will add too much code and state tracking. So instead of using inaccurate measurements just let the user decide to disable in app internet communication

**Comment by nerdCopter** [comment]
on the taskbar, where you had `ISP: Online`, can you revert to a online/offline so that is a visible state?

**Comment by haslinghuis** [comment]
@nerdCopter Moved connection info to setup tab

image

Would like to reserve the taskbar for something else.

**Comment by nerdCopter** [comment]
hmmm, okay, but but maybe user should know status when not connected :shrug: 
 for example flash-tab disabled, thus user thinks "why?" with no indicator.

**Comment by haslinghuis** [comment]
@nerdCopter Would really like a icon as indicator, but struggling finding svg in correct size and putting it in place.

Was playing with

[Screencast from 19-09-24 18:30:00.webm](https://github.com/user-attachments/assets/8b26d272-6539-4698-9789-bdb73c02dde9)

**Comment by haslinghuis** [comment]
Yes tried fontawesome snippets already - not showing up :confused: 

image

**Comment by haslinghuis** [comment]
We already have an indicator :joy: 
image

**Comment by flyasky** [comment]
translations for RU & UA:
UA: "Не підключатись до інтернет (для платних або повільних з'єднань)"
RU: "Не подключаться к интернет (для платных или медленных подключений)"

**Review by nerdCopter — APPROVED** [review]
LGTM

**Comment by nerdCopter** [comment]
there is a SonarCloud however.

**Comment by haslinghuis** [comment]
@nerdCopter remaining issues are html and css related and just extends existing code which needs overhaul anyway.

**Review by nerdCopter — APPROVED** [review]

**Review by VitroidFPV — APPROVED** [review]

**Pull request merged**
