### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by McGiverGim**
Update translations.

Thanks to rpargana for the help with Portuguese.

### CODE REVIEW

**Review by haslinghuis — DISMISSED** [review]
Obrigade

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Review by haslinghuis — APPROVED** [review]
Merci

**Review by haslinghuis — APPROVED** [review]
Спасибо

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Review by Asizon — APPROVED** [review]

**Review by haslinghuis — DISMISSED** [review]

**Comment by McGiverGim** [comment]
Added a lot more of Portuguese and German translations...

**Review by haslinghuis — APPROVED** [review]

**Review by Asizon — APPROVED** [review]

**Review by haslinghuis — APPROVED** [review]

**Comment by McGiverGim** [comment]
The translations are in constant evolution, I think we need to merge them faster to let the users verify them in nightlies.

**Review by haslinghuis — APPROVED** [review]

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Comment by DusKing1** [comment]
Zh_cn are ready to go, zh_tw still need some work, I just can't squeeze more at this time.

**Comment by McGiverGim** [comment]
I will update the PR this week 😄 it seems this never will have three approval...

**Comment by haslinghuis** [comment]
@McGiverGim we will hassling around to get it in 😁 attached to the project so we don't forget

**Review by blckmn — APPROVED** [review]

**Review by Asizon — APPROVED** [review]

**Pull request merged**
