### PR TITLE
OSD: combined ON/ARM timer

### PR DESCRIPTION
**Pull request by krzysztofmatula**

### CODE REVIEW

**Comment by krzysztofmatula** [comment]
It that OK, or should be synchronised with the betaflight version?

**Comment by Docteh** [comment]
I'll give it a go. The main concern with version is it shouldn't like crash the board to choose a wrong option.

**Comment by Docteh** [comment]
Works fine on stock 4.0.0, displays 00:00 on the OSD 👍

**Comment by krzysztofmatula** [comment]
> Works fine on stock 4.0.0, displays 00:00 on the OSD 👍

Can you also check if CMS on 4.0.0 won't crash when ON/ARM is set in configurator?

**Comment by Docteh** [comment]
image
 Looks funny, I was able to change it back in CMS.

**Comment by krzysztofmatula** [comment]
It's not quite good - CMS uses string from outside of allocated array. Could have crashed.
Actually, it is not configurator problem, as likely same timer config could have been provided in CLI.
I think the FW should be patched.

**Comment by krzysztofmatula** [comment]
Fix proposal: https://github.com/betaflight/betaflight/pull/8016

**Comment by McGiverGim** [comment]
You need to add a timer preview to: 

https://github.com/betaflight/betaflight-configurator/blob/00423a8829483f8d66973a93319de71fb49234d1/src/js/tabs/osd.js#L271-L281

With the symbol you want to use, if any. Is there a symbol that you can use for this?

**Comment by krzysztofmatula** [comment]
> With the symbol you want to use, if any. Is there a symbol that you can use for this?

The timer uses SYM.ON_M while not armed and SYM.FLY_M when armed.
For the purpose of configurator I'll simply use SYM.ON_M.

**Comment by mikeller** [comment]
@krzysztofmatula: The new timer should be added to the `switch` statement that @McGiverGim pointed out then.

**Comment by krzysztofmatula** [comment]
Correct. Will do this later today :)

**Pull request merged**
