### PR TITLE
Hide firmware version dropdown for virtual mode

### PR DESCRIPTION
**Pull request by haslinghuis**
when connected.

### CODE REVIEW

**Comment by McGiverGim** [comment]
I think it's better to control this using port handler variables and Vue, like we do for other things.

**Comment by haslinghuis** [comment]
@McGiverGim only adding `$('#firmware-version-dropdown')` here to existing code.

**Comment by nerdCopter** [comment]
i dont mind it visible TBH, but maybe disable/enable when connect/disconnect.

**Comment by McGiverGim** [comment]
> @McGiverGim only adding `$('#firmware-version-dropdown')` here to existing code.

Yes, but I don't think it's a good idea to change the behaviour / state of a Vue component with jquery or similar.

Better to do something like this:
https://github.com/betaflight/betaflight-configurator/blob/e6a48ceb2c461449192e46e3c5673a2b8643b3f5/src/components/port-picker/PortPicker.vue#L19C8-L20

**Review by blckmn — APPROVED** [review]

**Review by chmelevskij — APPROVED** [review]

**Pull request merged**
