### PR TITLE
Add EZLANDING debug

### PR DESCRIPTION
**Pull request by haslinghuis**
See https://github.com/betaflight/betaflight/pull/12094

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by blckmn — APPROVED** [review]

**Comment by prognesubis** [comment]
Why is it so dam complicated?

**Comment by prognesubis** [comment]
All this crap I have to look at. Just give me Betta Flight,

**Comment by nerdCopter** [comment]
@prognesubis https://betaflight.com/docs/wiki/release/Betaflight-4-5-Release-Notes#12-ezlanding

please don't post off-subject in github. TY

**Pull request merged**
