### PR TITLE
WebSerial unsupported alert

### PR DESCRIPTION
**Pull request by nerdCopter**
- maybe not the best solution, but simple enough.
- could not find a way to close the tab, as the internet alludes not possible in some browsers or rather not possible without custom (about:config) settings.
image

### CODE REVIEW

**Comment by haslinghuis** [comment]
Was working on this but did not push, as I had some questions

- i18n was not working.
- need something simular for bluetooth.
- would it be possible to enable browser features using an user gesture?
- please try

```bash
import { i18n } from "../localization";
import $ from 'jquery';

export  function checkBrowserCompatibility() {
    const compatible = "serial" in navigator;

    if (!compatible) {
        // const errorMessage = i18n.getMessage("pwaNonCompatibleBrowser");
        const errorMessage = "Betaflight app requires chrome, chromium, edge or vivaldi browser.";
        const newDiv = document.createElement("div");

        $('body')
        .empty()
        .css({
            "height": "100%",
            "display": "grid",
            "background-image": "url(../images/osd-bg-1.jpg",
            "background-size": "cover",
            "background-repeat": "no-repeat"
        })
        .append(newDiv)
        
        $('div')
        .append(errorMessage)
        .css({
            "font-size": "16px",
            "background-color": "var(--surface-200)",
            "color": "var(--text)",
            "padding": "1rem",
            "margin": "auto",
            "border-radius": "0.75rem",
            "border": "2px solid var(--surface-500)",
        });

        throw new Error("No compatible browser found.");
    }
}
```

**Comment by haslinghuis** [comment]
image

**Comment by nerdCopter** [comment]
i'll close this. you have nicer works :)

**Comment by nerdCopter** [comment]
>     * need something simular for bluetooth.

bluetooth is still a subset navigator.serial, no?

**Comment by haslinghuis** [comment]
Needs bluetooth in navigator and certain [experimental] browser flags to be enabled. Think got it documented in the bluetooth PR

**Pull request closed without merging**
