### PR TITLE
Remove Azure Pipelines

### PR DESCRIPTION
**Pull request by mathiasvr**
This removes the Azure Pipelines configuration, as GitHub Actions will now be used instead.

Before merging we should:
- [ ] Update the branch protection settings for pull requests to require the GitHub Action steps instead of the Azure Pipelines steps
- [ ] Add environment secret named `REPO_TOKEN` with a token having (at least) public_repo privileges
- [ ] Confirm that nightly builds works

### CODE REVIEW

**Comment by mathiasvr** [comment]
I changed the nightly build release step to fail the job on errors. Before, I considered the main task of the job that builds the master branch to be testing and building the branch, but now the naming suggests it is to release a nightly build, so I think it makes sense to report a failed release.

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Review by McGiverGim — APPROVED** [review]
It's ok to me 😉
@blckmn will you make the configurations to the repo?

**Review by haslinghuis — APPROVED** [review]

**Review by blckmn — APPROVED** [review]

**Comment by McGiverGim** [comment]
@mathiasvr I've seen that until now we prepend the date to the tag in the release. Can we continue doing in this way? Now this nightly release is lost under a lot of older releases...

**Comment by McGiverGim** [comment]
I think is here:

https://github.com/mathiasvr/betaflight-configurator/blob/36944e7616af6e560a1cc35f9cb49d560116453e/.github/workflows/nightly.yml#L44

The "correct" tag will be: "vYYYYMMYY.#", like this:

image

I'm out of the computer at this moment, but until we fix this, the release is at bottom in the nightlies and it does not appear in the Configurator.

**Comment by mathiasvr** [comment]
@McGiverGim alternatively if someone can push a new empty commit to the nightlies repo, the new tags will be linked to that and should show up in order. Both the annotated tag and release has a date, so I thought we don't also need it in the name?

**Comment by McGiverGim** [comment]
I think is useful to know the date of a nightlies. The tags are ordered by tag, I doubt an empty commit will change anything.

**Comment by mathiasvr** [comment]
Yes the date is useful but as mentioned it's already displayed in the release. Are you willing to try adding the commit or should I change the tag name? I think tagging a new commit to separate the azure builds from the GitHub Actions can be useful either way.

**Comment by McGiverGim** [comment]
I think we need to change the tag name in the action to use the same format that until now.

**Comment by McGiverGim** [comment]
Another thing, it seems the changes are empty?

https://github.com/betaflight/betaflight-configurator-nightlies/releases/tag/build-49

**Comment by mathiasvr** [comment]
Ah good catch, I forgot to change that back when I changed the event from workflow run to push.

I really hope we can try adding a new commit and try this tag naming since I think just basing it on build numbers is nice and is similar to how the nightlies on Jenkins are referenced. Also as mentioned the proper date timestamps to use by API should be the ones from tag or release, not the one hard coded into the name. If it's just for consistency that's fine but not the best argument for me since I obviously think the current approach is wrong. My best guess is that it was used as a hack to order releases. I will try to experiment more with it to see why it wouldn't work like this.

**Comment by McGiverGim** [comment]
The biggest problem is that the releases are ordered by name and not by date: https://github.com/betaflight/betaflight-configurator-nightlies/releases

Try you find yours here 😁

**Comment by mathiasvr** [comment]
If you use the GitHub app it's the top one lol. But yes I know it's different on web, however I think a new commit will fix this and begin and order by name from that point will still work with incremental build numbers.

**Comment by McGiverGim** [comment]
I like too the configurator version and a build number. But as you say we need to put something that goes later than the letter v to be sure that it will go in order.
I will think a little over it. But if you have time, please open the PR with the fix in the changes and we can discuss there all of this. This PR is closed and people usually does not see it

**Pull request merged**
