### PR TITLE
Fixed issue with failing to download internal dataflash (Blackbox)

### PR DESCRIPTION
**Pull request by basdelfos**
Fixed issue with failing to download internal dataflash (Blackbox) on non-vcp flightcontrollers.

The blocksize of 4096 was to big, reduced the blocksize to 512 which seems to be the maximum. Blocksizes of 1024 and higher fail after a few packets.

### CODE REVIEW

**Comment by AndersHoglund** [comment]
I am not sure this is a "fix". More hiding a problem. Will this not affect download performance negatively also?
Is this maybe target specific? Flip32SPI according to slack posting. 
I tested two SPRF3, one real and one Flip32F3, downloaded  more than 5Mbyte from both without a hiccup. Bf3.1.3 on both, BFC1.9.1 on Win10. Two different hosts.

**Comment by borisbstyle** [comment]
I would rather see this configurable

What do you think @mikeller?

**Comment by mikeller** [comment]
Making it configurable is a step in the right direction I think. Just reducing it seems to be too restrictive, since it seems to be working fine for most people, and only occur for a few.
Since this time, the problem does not cause the FC to lock up, I am also thinking about simply retrying to download the same block again if a download fails.

**Comment by AndersHoglund** [comment]
There are a couple of guys on FaceBook with Xracer FCs also having BB download problem. Reverting to 3.0.1 seems to solve the issue, at least for one. (Howto link a FB post here?)

**Comment by basdelfos** [comment]
Reverting back to 3.0.1 also solves the issue for me. I'm currently downloading a 16MB dataflash. It even failed with 512 blocksize after aprox 20%. Have now reduced the blocksize to 256 and it downloaded the whole 16MB.
I think something else is causing this issue, probably something what changes between 3.0.1 and 3.1.0.
Conclusion is that the current "fix" does not work either for bigger downloads.

**Comment by etracer65** [comment]
The problem is being caused by CRC errors in the msp packets.  I'm working on a patch to retry failed packets.  In testing this completely resolved the problem.  Reducing the block size isn't a permanent solution as I've seen CRC errors with even small block sizes.  Reducing the block size dramatically slows the download so I'd like to avoid this.

**Comment by etracer65** [comment]
Betaflight Configurator pull request https://github.com/betaflight/betaflight-configurator/pull/420 will resolve this - no need to reduce the block sizes.

**Comment by basdelfos** [comment]
Perfect, I will test #420 tonight and report back. If it fixes the issue, this PR can be closed.

**Comment by borisbstyle** [comment]
superseeded with 
https://github.com/betaflight/betaflight-configurator/pull/420

**Pull request closed without merging**
