### PR TITLE
Add APM32 DFU Bootloader to USB Devices' filters

### PR DESCRIPTION
**Pull request by Chaos-fpga**
APM32 Devices are register-level compatible with STM32, thus their VendorID and ProductID are different and cannot pass the USB Devices filter. APM32 DFU vendor ID: 12619, product ID: 262.

### CODE REVIEW

**Comment by Chaos-fpga** [comment]
APM32 is a high quality domestic 32-bit general purpose MCU based on Arm® Cortex®-M0+/M3/M4F core, featuring low power consumption, high performance, high integration and quick migration. With excellent system performance, rich co-processing function and flexible users experience, it helps users to shorten product design time, reduce development cost and optimize product performance. At present, it is widely used for smart homes, high-end consumer electronics, automotive electronics, industrial control, smart energy, and communication facilities.
For more information, view https://global.geehy.com/

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Comment by Asizon** [comment]
@Chaos-fpga we are working now on Artery CPU support, can you point us flightcontroller that is using apm32 recently?

**Review by haslinghuis — CHANGES_REQUESTED** [review]

**Comment by Chaos-fpga** [comment]
> 

To my knowledge, Flight controller HAKRC F405(based on STM32F405) is using APM32F405RGT6 & AT32F435RET7, but neither of their DFU bootloader is supported by BF Configurator, hopefully the modest change can get approved & merged to the next version.

**Comment by haslinghuis** [comment]
@Chaos-fpga please rebase the PR to resolve conflicts.

**Pull request closed without merging**
