### PR TITLE
TPA clarification - % and μs

### LINKED ISSUE #3844: Change TPA rate and Breakpoint to Percentages for ease of understanding
### Is your feature request related to a problem? Please describe

For newer pilots TPA rate and breakpoint are somewhat obscure. It's not always clear to them that throttle goes from 1000 to 2000 as this isn't really the case any more with Dshot. 

TPA rate is clearer but might make even more sense as a percentage attenuation. 

### Describe the solution you'd like

Presenting TPA rate and TPA breakpoint as percentages (and perhaps converting to 1000-2000 behind the scenes) and adding a tooltip explaining TPA would resolve this problem.

image

1350 would become 35%.
0.65 would become 65%.

### Describe alternatives you've considered

I don't see the need to change anything in BF I think this could just be a configurator tweak.

### Other information

_No response_

### PR DESCRIPTION
**Pull request by nerdCopter**
- resolves #3844
- will need Crowdin translations

image

### CODE REVIEW

**Review by haslinghuis — APPROVED** [review]

**Review by HThuren — APPROVED** [review]

**Comment by ChrisRosser** [comment]
Incoming pedantry. 🤣

0.65 is not a % value. We need to multiply the number by 100 as well.
I'm not sure us makes this more understandable. If one is using Dshot then the breakpoint is not a microsecond value at all but rather a value between 0 and 2000 I think.

**Comment by nerdCopter** [comment]
@haslinghuis , should we revert Configurator? i'm fine with such.

correct, but humans will read 0.65 as 65% quite easily. pardon any break-point mishaps :frowning_face:

**Comment by haslinghuis** [comment]
tpa breakpoint is a pwm value between 750 and 2250
tpa_rate is between 0 and 1

Take 2: https://github.com/betaflight/betaflight-configurator/pull/3851 :smiley:

**Comment by HThuren** [comment]
in fact a good change

**Pull request merged**
