### PR TITLE
More i18n

### PR DESCRIPTION
**Pull request by McGiverGim**
More strings passed to the messages file for i18n.

Some things that I've seen that maybe remains:
- The console log, some strings are in the messages file, others not. I don't know if the objective is to i18n these strings or is better to let them in english.
- Some values of the combos. I don't know if we must pass this to the messages file, but maybe in other PR.
- The tethering logging.

The other words/phrases are now, with this PR, more or less, in the messages file. Maybe I missed some string, but the vast majority are now ready to be translated.

### CODE REVIEW

**Comment by mikeller** [comment]
@McGiverGim:

> The console log, some strings are in the messages file, others not. I don't know if the objective is to i18n these strings or is better to let them in english.

Is this the (debug) console log, or the log that is shown in the console that is part of the main configurator window?

**Comment by McGiverGim** [comment]
The log shown in the upper of the window.

**Comment by mikeller** [comment]
@McGiverGim:

> The log shown in the upper of the window.

I think that one should be translated, since it's information that is intended for the user. If we want to log events for debugging, they should be sent to the debug log in untranslated form.

**Comment by McGiverGim** [comment]
Do you want that I modify this PR, or can I make it in another PR?

**Comment by mikeller** [comment]
@McGiverGim: Another PR please.

**Comment by McGiverGim** [comment]
Perfect! I will do it tomorrow 😉

**Pull request merged**
