### PR TITLE
cli output save button

### PR DESCRIPTION
**Pull request by charlch**
Adding a save to file button to the cli console:

This should make it easier to do things like saving a dump.

### CODE REVIEW

**Comment by skaman82** [comment]
It would be much better if the save button would be in the same location as in other tabs and styled alike

**Comment by mikeller** [comment]
Nice! Thanks @charlch.

**Comment by mikeller** [comment]
@skaman82: Agreed, the styling should be consistent with the other tabs. Can you please do your styling magic?

**Comment by skaman82** [comment]
@mikeller I was hoping @charlch would take care of that before we merge this but sure, I can do it myself.

**Comment by charlch** [comment]
@skaman82 I'm more than happy to address styling issues if you could give some guidance on what would fit in with other tabs.

**Comment by mikeller** [comment]
@skaman82, @charlch: Sorry, I did not want to shift work from @charlch to @skaman82, but the functionality in itself is definitely worth having, so I've merged it. I'll leave it up to you as to who wants to do the styling.

**Comment by skaman82** [comment]
@charlch no problem, already done in https://github.com/betaflight/betaflight-configurator/pull/508

**Pull request merged**
