### PR TITLE
Fix button behaviour

### PR DESCRIPTION
**Pull request by haslinghuis**
Fixes buttons in firmware flasher as the backup process interrupted previous behavior.

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by asizon** [comment]
How i can reproduce it @haslinghuis ? currently im making backup and it continues flashing process as expected

**Comment by haslinghuis** [comment]
This PR disable buttons when applicable (more earlier) to prevent double clicks (debouncing the buttons),
Also turned into functions instead.

**Comment by asizon** [comment]
Tested but now after backup, it starts flashing and some buttons reamins enabled
image

**Comment by haslinghuis** [comment]
@asizon please test again

**Review by nerdCopter — APPROVED** [review]

**Comment by nerdCopter** [comment]
* tested good; i only tested one FC, one flash w/ backup-clicked.

**Review by asizon — APPROVED** [review]

**Review by McGiverGim — APPROVED** [review]
Not tested, but seems good.

**Pull request merged**
