### PR TITLE
Add APM32 Serial Device Support

### PR DESCRIPTION
**Pull request by MorroGeek**
# Add APM32 Serial Device Support

## Description
This merge request introduces support for APM32 serial devices manufactured by Geehy Semiconductor. Specifically, it adds identification and support for devices with a Vendor ID (VID) of `0x314B` and a Product ID (PID) of `0x5740`.

## Changes
- Updated the `serial_devices.js` file to include the new device identification information.
- Added support for devices with Geehy Semiconductor's VID (`0x314B`) and PID (`0x5740`).

## Purpose
The purpose of this update is to expand our hardware support, enabling our software to be compatible with APM32 series serial devices. This will provide our users with a broader range of hardware options.

## Testing
- Verified the correct update of the `serial_devices.js` file.
- Conducted practical tests with an APM32 device having the specified VID and PID to ensure correct identification and functionality.

Betaflight_Configurator_Geehy

### CODE REVIEW

**Review by haslinghuis — COMMENTED** [review]
- APM32 is already recognized as F40X.
- What udev rules are needed to be able to flash APM32?

image

**Comment by nerdCopter** [comment]
- someone recently added this to another project as well (decimal coded though) -- `{'vendorId': 12619, 'productId': 262} // APM32 DFU Bootloader` 
- was told it is binary compatible to stm32

**Comment by haslinghuis** [comment]
Already have this in `46-stdfu-permission.rules` but does not allow flashing.

`VendorId`: 314b (12619)
`ProductId`: 106 (262)

**Comment by nerdCopter** [comment]
* unsure if was tested on Linux: ref: https://github.com/emuflight/EmuConfigurator/pull/524
* maybe @Alden-wrk  willing to test/contribute to Betaflight as well.

**Comment by Alden-wrk** [comment]
8065cfff31250a09116b96d69b961f4
d3bfc2ba5ad356d91d8588c134a31ca
> * unsure if was tested on Linux: ref: [ADD APM32 MCU USB_DFU emuflight/EmuConfigurator#524](https://github.com/emuflight/EmuConfigurator/pull/524)
> * maybe @Alden-wrk  willing to test/contribute to Betaflight as well.
I am a team with @MorroGeek and we are working on adding the SDK for APM32 to Betaflight and we have now finished the native build and successfully run it on the PCB I designed. Now that we need to merge the added SDK into the main branch, please allow our merge request.

**Comment by Alden-wrk** [comment]
@haslinghuis @nerdCopter This Pull requests Merging is blocked,How do I pass this Pull request?

**Comment by McGiverGim** [comment]
To merge this PR it needs to be approved by several people. No problem with that, but the firmware part needs to be approved and merged first.
Until then, if someone wants to test it, the netlify link above can be used.

**Review by nerdCopter — APPROVED** [review]

**Review by haslinghuis — APPROVED** [review]
https://github.com/betaflight/betaflight/pull/13709

**Comment by haslinghuis** [comment]
@MorroGeek this PR is based upon `master` :roll_eyes:

**Comment by MorroGeek** [comment]
> @MorroGeek this PR is based upon `master` 🙄
> 
> EDIT: made a new PR to fix.

Excuse me for the oversight with the PR being based on the master branch. I understand the importance of keeping the master branch clean and stable. For the next PR, I will create a new branch for development and submit the PR from there to ensure compliance with [Betaflight PR rules](https://betaflight.com/docs/development#using-git-and-github).

Thanks for bringing this to my attention, and I appreciate your understanding.

https://github.com/betaflight/betaflight/pull/13709

**Pull request closed without merging**
