### PR TITLE
Fix debug modes (GHST)

### PR DESCRIPTION
**Pull request by haslinghuis**
Fixes debug modes.

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by ZzyzxTek** [comment]
Just ran through a bunch of different debug modes from low/mid/high in the set, and everything works great now (I had originally reported this on discord). Thanks!

**Review by McGiverGim — APPROVED** [review]
Approved. Why GHST does not have the O? The name of the protocol is without O?

**Review by ctzsnooze — APPROVED** [review]

**Review by ctzsnooze — APPROVED** [review]

**Comment by haslinghuis** [comment]
Yes same in firmware.

**Review by klutvott123 — APPROVED** [review]

**Pull request merged**
