### PR TITLE
Fix Port Dropdown Width

### PR DESCRIPTION
**Pull request by haslinghuis**
Fixes: #2388

### CODE REVIEW

**Comment by haslinghuis** [comment]
Screenshot from 2021-02-19 16-30-15

**Comment by klutvott123** [comment]
Can't we just not specify the width and let the dropdown adjust itself?

**Comment by haslinghuis** [comment]
@Asizon ???

**Comment by haslinghuis** [comment]
@klutvott123 Yes we can :smile:

**Comment by mikeller** [comment]
Looks like resize does not expand to the full size that is required on MacOS:

Screen Shot 2021-02-22 at 12 04 35 AM

**Comment by haslinghuis** [comment]
Very strange it's not working on Mac OS, if I can't do it dynamically without fancy libraries I can take two approaches, guess the font-size with some correction which works great. Or we have to hardcode the length of a i18n translation (virtual) to be the minimum size and depend on the css `ch` element. Using `px` seems working on differerent resolutions. I prefer the latter method.

**Comment by mikeller** [comment]
@haslinghuis: Yeah, not sure what is causing this. I wanted to test on MacOS as the device names are quite long there. But It does not expand at all, not even as much as it does on linux. :confused:

**Comment by klutvott123** [comment]
Well that sucks. I tested it on windows and it works perfectly there

**Comment by haslinghuis** [comment]
@klutvott123 Yeah it worked really well. I found another method. Maybe this works on Mac OS too
If this does not work on Mac OS (cannot verify) have to resort to guesswork but the guesswork implementation should be close, but I have only 3 samples to test. Also tried @Asizon suggestion to use width: `fit-content;`  in CSS only but it has about 4 or 5 spaces on the right I can't get rid off. 

[ref1](https://stackoverflow.com/questions/55174282/adjust-the-width-of-dropdown-according-to-the-length-of-the-text)
[ref2](https://css-tricks.com/almanac/properties/w/width/)

**Comment by haslinghuis** [comment]
@klutvott123 Yeah it worked really well. I found another method without using canvas method. Maybe this works on Mac OS too.

If this does not work on Mac OS (cannot verify) can make exception for Mac OS to resort to guesswork implementation witch should be close, but I have only 3 samples to test. Also tried @Asizon suggestion to use `width: fit-content;`  in CSS only but it has about 4 or 5 spaces on the right I can't get rid off. @Mike as I don't have a Mac could you confirm?

[ref1](https://stackoverflow.com/questions/55174282/adjust-the-width-of-dropdown-according-to-the-length-of-the-text)
[ref2](https://css-tricks.com/almanac/properties/w/width/)

**Comment by etracer65** [comment]
Seems like we could change the baud rate to not be the same size as the port drop-down. Doesn't have anything to do with this issue, but it's starting to look a little goofy being so wide.

**Comment by haslinghuis** [comment]
Agree - there is enough room to move it right to the port-picker - not sure about Android

**Comment by etracer65** [comment]
Or maybe keep it where it's at but size it appropriately and right-align with the ports drop-down? Could even move the auto-connect switch up to the baud rate row and use the space freed up by shrinking and right-aligning the baud drop-down.

**Comment by haslinghuis** [comment]
Screenshot from 2021-02-22 01-16-59

**Comment by haslinghuis** [comment]
Ready for testing. I left out the dynamic stuff for Mac OS to be sure.

**Comment by etracer65** [comment]
I tested (MacOS10.13.6) and it didn't really work. The elements were moved by the port drop-down was still too small.

Screen Shot 2021-02-23 at 3 23 31 PM

Screen Shot 2021-02-23 at 3 26 03 PM

**Comment by haslinghuis** [comment]
@etracer65 thanks for confirming. On Windows and Linux it works. Very weird.

**Comment by haslinghuis** [comment]
@etracer65 thanks for confirming. On Windows and Linux it works. Very weird.
I have now made the default width 100px more and static on MacOs for now as I have no hardware to develop this on.

**Comment by etracer65** [comment]
I debugged a little and something is wrong here:
```
let width = getWidthofText(findMaxLengthOpt(this.selectList)) + correction;
```
The width is always calculated to be 208 whether I have the board connected or not.

So the same for this:

Screen Shot 2021-02-23 at 7 46 19 PM

vs. this:

Screen Shot 2021-02-23 at 7 46 51 PM

Is the width calculation getting based on the selection with the max character length? If so then this won't work with non fixed-width fonts.

**Comment by haslinghuis** [comment]
@etracer65 the code is working perfect on Windows and Linux. Without access to a Mac I can't see why its behaving different. For now can you check if 320px is enough for a static value on MacOS?

**Comment by etracer65** [comment]
`findMaxLengthOpt(this.selectList)` is always returning the first element.

**Comment by haslinghuis** [comment]
Aha, not on other platforms. Did check the size of the value it returns. 😕

**Comment by etracer65** [comment]
The size looks correct for the first element in the select list  - but that's not the longest one.

Screen Shot 2021-02-23 at 7 46 51 PM

Here's some debugging with the `maxLength` element captured. Note that it's the first element.

Screen Shot 2021-02-23 at 8 07 07 PM

**Comment by haslinghuis** [comment]
@etracer65 Don't know what to say without having access to MacOs it's hard to check for me. The code is working on Windows and Linux. I'm really curious what's the underlying problem here.

**Comment by etracer65** [comment]
Well the problem is definitely here:
```
    function findMaxLengthOpt(selectEl) {
        return [...selectEl.options].reduce((result, o) => o.textContent.length > result ? o.textContent : result, 0);
    }
```
As this is always returning the text of the first element of the select. I'm not really sure what this is doing - maybe basing the size on the existing rendered size of the element and finding the largest? Not sure this will work on MacOS base don how the dropdown displays. It pops-up much larger when you click on it. Like:

Screen Shot 2021-02-23 at 8 21 30 PM

Maybe you need to iterate through the options and call `getWidthofText()` for each and find the max from that.

**Comment by haslinghuis** [comment]
@etracer it's returning the size of the longest entry in the list. Changed the function for MacOS to use each to iterate over the objects to select the one we are after.

**Comment by etracer65** [comment]
While the `findMaxLengthOptVal()` function now works to find the "longest" entry, as I said before - this logic is flawed for determining the width of the element. The element uses a proportional font. You cannot base the determination of the widest entry in pixels on the one with largest number of characters. As an example, both of these are 10 characters but obviously not the same width in pixels.

"1111111111"
"0000000000"

**Comment by etracer65** [comment]
I simplified the logic and removed the MacOS dependency. This seems to work correctly:
```
PortHandler.setPortsInputWidth = function() {

    function getWidthofText(text) {
        const canvas = document.createElement('canvas');
        const context = canvas.getContext('2d');

        context.font = getComputedStyle(document.body).font;

        return Math.ceil(context.measureText(text).width);
    }

    function findMaxOptWidth(selectEl) {
        let max = 0;
        $(selectEl.options).each(function () {
            const textSize = getWidthofText(this.textContent);
            if (textSize > max) {
                max = textSize;
            }
        });
        return max;
    }

    const correction = 24; // account for up/down button and spacing and size of chars.
    let width = findMaxOptWidth(this.selectList) + correction;

    width = (width > this.initialWidth) ? width : this.initialWidth;

    const portsInput = document.querySelector("div#port-picker #portsinput");
    portsInput.style.width = `${width}px`;
};
```

Needs testing on Linux and Windows as I'm not set up to build/test these.

**Comment by etracer65** [comment]
Working examples:

Screen Shot 2021-02-24 at 8 18 34 AM

Screen Shot 2021-02-24 at 8 19 24 AM

Only remaining comment is that the baud rate select could be a fixed size rather than scaling to 50% of the ports select.

**Comment by etracer65** [comment]
From a purely aesthetic opinion I'd suggest making the second row of the auto-connect slider and baud rate a fixed widths and right-aligned with the ports select. That way they won't jump around when the ports select changes size.

**Comment by haslinghuis** [comment]
@etracer65 `getWidthofText` uses the document's body font to draw it on canvas to determine the width of the port select, but the the OS dependency was indeed redundant. Code is working as expected. Will make additional changes to html / css later.

**Comment by haslinghuis** [comment]
Screenshot from 2021-02-24 20-08-55

**Comment by haslinghuis** [comment]
Screenshot from 2021-02-24 20-11-37

Screenshot from 2021-02-24 20-11-56

**Review by etracer65 — APPROVED** [review]
Tested on MacOS and looks good.

**Comment by mikeller** [comment]
@haslinghuis:

> The code is working on Windows and Linux. I'm really curious what's the underlying problem here.

That was because the ordering of elements in the list always had the longest element first in your test cases. :stuck_out_tongue: 

> Don't know what to say without having access to MacOs it's hard to check for me.

You can actually get MacOS to work inside a VM: https://www.wikigain.com/install-macos-catalina-on-virtualbox-on-windows/

**Review by mikeller — APPROVED** [review]

**Pull request merged**
