### PR TITLE
Feature/advanced tuning and filters

### PR DESCRIPTION
**Pull request by nathantsoi**
i think this should complete https://github.com/betaflight/betaflight-configurator/issues/39 and  https://github.com/betaflight/betaflight-configurator/issues/28

screen shot 2016-06-24 at 2 35 47 am

(tested and working, ready to merge)

### CODE REVIEW

**Comment by borisbstyle** [comment]
Thanks. I will check it out and finish where needed.

**Comment by nathantsoi** [comment]
for sure, i did not do the other ui elements for the fields in the `ADVANCED_TUNING` msp request. if you tell me where you want those though, im be happy to add them.

```
currentProfile->pidProfile.rollPitchItermIgnoreRate
currentProfile->pidProfile.yawItermIgnoreRate
currentProfile->pidProfile.yaw_p_limit
currentProfile->pidProfile.deltaMethod // done
masterConfig.batteryConfig.vbatPidCompensation
```

**Comment by borisbstyle** [comment]
Thats fine @nathantsoi. Thos are less important for now.

I would like to add ability to disable sensors as well.

**Comment by borisbstyle** [comment]
https://github.com/betaflight/betaflight/commit/6f28ba0f56be30735778b97a6b109b478fb2d2ba

**Pull request merged**
