### PR TITLE
Sort build options

### PR DESCRIPTION
**Pull request by haslinghuis**
Sort build options.

Before:

image

After:

image

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by blckmn** [comment]
This can be done in the API if you like?

**Comment by haslinghuis** [comment]
For sure. Was going to ask :)

**Comment by haslinghuis** [comment]
Order will be tackled in build system.

**Pull request closed without merging**
