### PR TITLE
Adjust some OSD fields length

### PR DESCRIPTION
**Pull request by McGiverGim**
Adjust some OSD fields to the right size/format in the OSD.

### CODE REVIEW

**Comment by McGiverGim** [comment]
If I'm not wrong the symbols for lat and lon are reversed... the lon must point to east and the lat to north. 

This was done in this way in the firmware. Change this for all here or only to detected newest versions? I have a PR pending to fix the symbols of lat and lon (at this moment the firmware does not show them). To me this is a bug, so I think is better to simply change them for all versions here.

**Comment by mikeller** [comment]
> If I'm not wrong the symbols for lat and lon are reversed... the lon must point to east and the lat to north.

Yes you are correct. I didn't even look that closely.

**Comment by McGiverGim** [comment]
Modified the PR to fix the symbols. @mikeller I don't know if you want that I take into account old Betaflight versions to put the "wrong" symbols. I don't know if we must maintain the bug (it was used until now) or not.

**Comment by mikeller** [comment]
Na, this preview / setup screen is best effort, and the usability won't be affected if the symbols don't match. At a pinch we could just use 'XXXXXXXX' for the fields, and the users could still use it to configure their OSD.

**Pull request merged**
