### PR TITLE
Rates preview for the PID Tuning tab

### PR DESCRIPTION
**Pull request by antstorm**
Hey guys,

Here's a new feature for the PID tuning tab — 3D model preview of the rates. It gets the signal from receiver and animates 3D model rotation at configured rates. Makes it much easier to setup rates.

This is reusing the 3D model from the Setup tab, extracting it into a separate lib file.

Currently the curve and the actual rates are not accurate, since I'm not sure how to calculate deg/sec from all the settings. Apart from that it all works, but needs the scales to reflect the current curve. Would really appreciate some help on getting this right (might also include superexpo indication).

I've also noticed that PID tuning tab is getting a bit too overcrowded, so there might be a room for a new "Rates" tab.

### CODE REVIEW

**Comment by antstorm** [comment]
@borisbstyle wow, thanks, that was quick! I know you're busy, but can you please comment on the stuff that I wrote? :)

**Comment by mikeller** [comment]
Wow, good stuff, @antstorm. Re splitting rates and PIDs, @borisbstyle specifically wanted rates to be on the same matrix as the PIDs, and I think it is less confusing for users, and less prone to losing data if we move all profile dependent settings into one tab.

How about moving your model into the receiver tab? That one is starting to look a bit empty anyway, with all the rates gone...

**Comment by antstorm** [comment]
@mikeller that might make sense, yes, but you probably want the model next to where you can setup rates, so you can do this with TX in hands, testing the outcome…

**Comment by mikeller** [comment]
Fair enough. And I can see your point about not having to switch tabs. How about a popup with the craft model? I think that would be a pretty good user experience as well. Probably works better than just adding it to the tab, and forcing users to scroll between seeing the rates and seeing the model. Also, if it's a popup, we can make it available in the receiver tab as well, so users can use it to check that their channel mapping is right and the craft will do what they think it should do.

**Comment by antstorm** [comment]
@mikeller so by popup you mean a separate smaller window, right? So you'd be able to resize these and view both at the same time? That could work, but I don't think it's a great user experience… we can just make things a bit smaller on the same tab (and add model to receiver tab, which I think makes for a very good use case).

Another crazy idea — top tabs inside PID Tuning tab, switching between PIDs and rates? :)

**Comment by mikeller** [comment]
@antstorm: Yes, I thought a separate window for the model, that opens when a user clicks a button in the PID tab or the receiver tab. 

Re switching between PIDs and rates: I think @borisbstyle is right, and there is value in being able to see  PIDs and rates at the same time, particularly now that with the new rates the level of interconnectedness is quite high.

**Comment by antstorm** [comment]
@mikeller yeah, that makes perfect sense. I think we can make all the charts on that page smaller, what do you think?

As an example, here's the rates tab of KISS configurator:



It's quite small and has all 3 axis shown separately.

**Comment by mikeller** [comment]
Yeah, that looks feasible. The PID / rates matrix on the left side is visually quite sparse, that could probably be compressed to only take up half of the tab width. That would give us the other half for graphs and the model.

Re graphs, I am looking into redoing them and using different colours to draw multiple expo graphs into the same diagram. That should free up some space.

I still think it would be helpful to have the moving model available from the receiver tab. That's where novices will go to check if they've set up their TX / RX the right way, and the model will help them with that.

**Comment by antstorm** [comment]
@mikeller sounds great. Should I add the model to receiver tab while you're redoing the charts?

Would also appreciate some help on calculating the right TX signal to rotation mapping. I guess this can be used when plotting charts.

**Comment by mikeller** [comment]
@antstorm: Sounds like a plan. I will leave the redesign of the UI layout into something more compressed to somebody like @skaman82, as my UI skills are quite basic.

**Comment by antstorm** [comment]
@mikeller sure! I'm also thinking of adding some kind of grid framework (something responsive and really lightweight) that will allow people to easily add/move things, otherwise it's quite a mess at this point. I wonder what are your thoughts on this?

**Comment by nathantsoi** [comment]
yes! we need a frame work in general, like mdl or bootstrap :)

**Comment by antstorm** [comment]
@nathantsoi great, I'll look into adding it.

**Comment by mikeller** [comment]
@antstorm: Totally for it, the current way of doing things is a mess. I am not deep enough into UI work to be able to make a recommendation on what to use.

**Pull request merged**
