### PR TITLE
Fixed box content refresh in battery tab.

### PR DESCRIPTION
**Pull request by mikeller**
@basdelfos: This should fix the display of the meter type specific data in the Battery tab. Can you please test?

### CODE REVIEW

**Comment by basdelfos** [comment]
Looks good. Only thing I noticed is that when the user has changed one or more setting of the sensors and then change one sensor type, all changed settings are reset to the old value. The user probably doesn't expect that the voltage settings are reset when he changes the amperage sensor type.

**Comment by mikeller** [comment]
Good point, I will change that. Thanks for testing.

**Comment by mikeller** [comment]
@basdelfos: I fixed the problem with values getting lost, can you please check again?

**Comment by basdelfos** [comment]
Yes, works great now. The changed values are even restored when changing the voltage sensor type back again (without pressing save in the process).

**Comment by mikeller** [comment]
Fixes betaflight/betaflight#4003.

**Pull request merged**
