### PR TITLE
Bump NW.js to 59.0

### PR DESCRIPTION
**Pull request by haslinghuis**
Bumps NWjs from 0.54.1 to 0.59.0.

Needs testing and hopefully resolves some OSX issues :crossed_fingers:

### CODE REVIEW

**Comment by haslinghuis** [comment]
@kevinsummer ?

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by ctzsnooze** [comment]
Again, last minute changing nw.js should only be considered for 4.3 timeline if it definitely fixes a bug.  Let's find out if it does fix things, otherwise it should be on a 4.4 time line.

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by ctzsnooze** [comment]
Checked, runs on Mac OSX Mojave.
Doesn't solve the Hide issues, so we must keep converting hide to minimise.

**Review by ctzsnooze — APPROVED** [review]

**Review by McGiverGim — APPROVED** [review]

**Comment by haslinghuis** [comment]
Are we sure we don't want to add this to 10.8.0

**Comment by Asizon** [comment]
If it doesnt solves any issues, i think is best to put i next releases to be sure doesnt break anithing, since we are in the teamline.

**Review by limonspb — APPROVED** [review]

**Pull request merged**
