### PR TITLE
feat: add basic offline pwa support

### PR DESCRIPTION
**Pull request by chmelevskij**
Add basic pwa support for offline use.

https://github.com/betaflight/betaflight-configurator/assets/7774918/fe1b3652-3435-4f61-ab96-abaad302e1f0

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by nerdCopter** [comment]
looks good, but i dont know how to build PWA executable for testing.

**Comment by chmelevskij** [comment]
@nerdCopter `yarn dev` starts web build, visit http://localhost:8000/ and it should have basic configurator build.

Though, for full offline it needs to be https. So will look into better local setup to actually test offline. For now we'll only be able to fully test this once it's up on https://nightly.app.betaflight.com/ or https://app.betaflight.com/

**Review by haslinghuis — APPROVED** [review]

**Comment by nerdCopter** [comment]
> @nerdCopter `yarn dev` starts web build, [...]

okay , i know about `yarn dev` (same as `yarn vite`).  but it seemed though you launched an "app" in the video.

i ran `yan vite` fine the other day, so i will approve it.

**Review by nerdCopter — APPROVED** [review]

**Comment by chmelevskij** [comment]
@nerdCopter if you visit https://nightly.app.betaflight.com/ in the top right in url bar there is install button.

https://github.com/betaflight/betaflight-configurator/assets/7774918/bfd8bc9d-338d-4d87-a7f0-1dc2c68764aa

After clicking that you will need to wait for all the request to finish in the network tab

When finished you will get the following popup and that pretty much means it's ready to go

Screenshot 2024-01-10 at 06 50 58

**Pull request merged**
