### PR TITLE
Restoring ability to load local configuration for a target

### PR DESCRIPTION
**Pull request by blckmn**
Based on device auto detect, and the use of local flash files.

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Review by haslinghuis — APPROVED** [review]

**Comment by haslinghuis** [comment]
These lines can be removed now:
https://github.com/betaflight/betaflight-configurator/pull/3066/files#diff-1b3c28c855b29bc06cfb60162cffb5635dbcc23931adf8705969ccac5c48c48dR802-R803

**Comment by haslinghuis** [comment]
First push worked. Now it fails flashing:

Flashing failed: Custom defaults area too small (-284364798 bytes), 2751 bytes needed.

**Review by ctzsnooze — DISMISSED** [review]

**Comment by ctzsnooze** [comment]
Tested, works properly when flashing an OmnibusSD F405 and a Nox F411 board

**Review by ctzsnooze — DISMISSED** [review]

**Comment by ctzsnooze** [comment]
Tested on F405 (OmnibusSD board) and F411 (Nox).  Works normally.

**Comment by haslinghuis** [comment]
image
image

**Comment by haslinghuis** [comment]
When trying to flash a commit I get:

image

**Review by haslinghuis — DISMISSED** [review]

**Pull request merged**
