### PR TITLE
Adding custom define input box

### PR DESCRIPTION
**Pull request by blckmn**
For development purposes add ability to put in custom defines.

Note the prefix USE_ is not to be used as it is added by the build platform.

### CODE REVIEW

**Comment by haslinghuis** [comment]
We need a list of valid defines

https://build.betaflight.com/api/builds/4.4.0/MATEKH743/58920be0-aacc-4a7e-d712-15551443943b/log

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by sugaarK — DISMISSED** [review]

**Comment by blckmn** [comment]
> We need a list of valid defines
> 
> https://build.betaflight.com/api/builds/4.4.0/MATEKH743/58920be0-aacc-4a7e-d712-15551443943b/log

I didn't want to restrict it at all... it is only for testing and debugging. The user should have some knowledge of whats going on!

**Review by KarateBrot — APPROVED** [review]

**Review by KarateBrot — APPROVED** [review]

**Review by haslinghuis — APPROVED** [review]
Tested: https://build.betaflight.com/api/builds/4.4.0/MATEKH743/ab9950a5-8f04-6719-3060-69cd56a9e5e7/log

**Review by haslinghuis — APPROVED** [review]

**Review by KarateBrot — APPROVED** [review]

**Review by ctzsnooze — APPROVED** [review]

**Pull request merged**
