### PR TITLE
Fix map loading

### PR DESCRIPTION
**Pull request by McGiverGim**
Fixes https://github.com/betaflight/betaflight-configurator/issues/874

### CODE REVIEW

**Comment by McGiverGim** [comment]
@mikeller I forgot that this PR has modified the package.json . The dependencies remains the same but I don't know if we must upload a new package-lock.json too.

**Comment by mikeller** [comment]
@McGiverGim: Yes you absolutely must. As we've found out before, `package-lock.json` is ignored if it's timestamp is older than `package.json`, causing the package versions to be re-evaluated on every build.

**Comment by McGiverGim** [comment]
Strange, it seems that my lock file has not changed. Maybe it only takes in account the dependencies and not the rest of the file? I will recheck it again, only to be sure...

**Comment by mikeller** [comment]
Even if the contents of the file itself do not change, `npm install` takes into account the file timestamp, and if `package-lock.json` appears to be older than `package.json` it assumes it's stale, and ignores / recreates it.

**Pull request merged**
