### PR TITLE
FuriousFPV Stealth VTX support

### PR DESCRIPTION
**Pull request by MJ666**
I have no idea why the label in the dropdown box at the ports page stays empty? Not yet ready to merge. Like to get some feedback here.

### CODE REVIEW

**Comment by basdelfos** [comment]
First question; did you test this with a flightcontroller running BF 3.2 on it?

**Comment by MJ666** [comment]
Yes it is tested with an 3.2 test build containing the Furious VTX support. The menue point in the configurator is still staying blank. Not sure is i shuld up the API version or if we do this together with some other updates for 3.2?

**Comment by basdelfos** [comment]
OK, let me take a look at your PR.

**Comment by MJ666** [comment]
Many thanks for your help.

**Comment by basdelfos** [comment]
I have looked at the code and it looks ok.
After that I've pulled your PR locally and tested it and it also works at my machine. Saving and refreshing the setting also works.

image

Flight controller has the latest master from yesterday.

**Comment by basdelfos** [comment]
Requires BF PR to be merged first: https://github.com/betaflight/betaflight/pull/3609

**Comment by MJ666** [comment]
Rebased. #3609 is ready to merge. But here I still see the issue as before?

furiousvtx

**Comment by MJ666** [comment]
Now it also looks good on my side without doing any changes. Very strange behavior. Anyhow we are good to go.

**Comment by MJ666** [comment]
Closing this.

**Pull request closed without merging**
