### PR TITLE
Fix Indonesian locale

### PR DESCRIPTION
**Pull request by achmiral**

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Comment by haslinghuis** [comment]
The translations are managed from https://crowdin.com/project/betaflight-configurator
Any change done directly in the translations file will be replaced by Crowdin translations before release.
If you want to help with the translations please go there.

In the slack chat official of Betaflight there is a channel #team_translation you can find there the appropriate proofreader(s) for your language.

**Comment by McGiverGim** [comment]
@achmiral It seems the proofreader for Indonesian abandoned the project some time ago, so I have give you proofreader permissions for Indonesian, in this way you can approve translations. You need to approve them to be in the Configurator. Let me know if you have some problem.

**Comment by achmiral** [comment]
Thank you @McGiverGim

**Pull request closed without merging**
