### PR TITLE
Fix reset dialog

### LINKED ISSUE #3802: Confirm Reset dialog wrong format
### Describe the bug

see the sreenshot

image

### To Reproduce

...

### Expected behavior

...

### Configurator version

latest master

### Flight controller configuration

_No response_

### Add any other context about the problem that you think might be relevant here

_No response_

### PR DESCRIPTION
**Pull request by haslinghuis**
Fixes #3802

### CODE REVIEW

**Review by HThuren — APPROVED** [review]
Nice
image

**Review by nerdCopter — APPROVED** [review]

**Comment by HThuren** [comment]
Maybe change the prompt text 
image

**Comment by nerdCopter** [comment]
> Maybe change the prompt text 

this was changed rather recently for pilots not understanding that it resets everything.

**Comment by HThuren** [comment]
Then "Remove all settings" ?

**Comment by haslinghuis** [comment]
At this moment we should focus on bugfixes

**Pull request merged**
