### PR TITLE
Hide Esc Sensor for non digital protocols

### PR DESCRIPTION
**Pull request by Asizon**
`ESC_SENSOR` only works with digital protocols, so it should only be shown for these.

### CODE REVIEW

**Comment by mikeller** [comment]
Not sure there is much that can be done about the 'bugs' that Sonar found, as they seem to be an artefact of a dynamically generated table (@McGiverGim what do you think?). But the smells seem accurate - styling should be done in CSS.

**Comment by McGiverGim** [comment]
True. We can move in this PR the styling to css. To remove the bugs we need to change the table by other elements but maybe it's too much for this PR.

**Comment by Asizon** [comment]
Moved to CSS as requested, I am not able to move the `cellspacing` to css using `border-collapse,` so the borders are separated. Any recomendation?
cssalign

**Comment by mikeller** [comment]
I am fine with this look. @McGiverGim?

**Comment by McGiverGim** [comment]
@mikeller I will look at the problem he is commenting later to see if I can help to finish this.

**Comment by Asizon** [comment]
Done!rebased after Css fix, thanks @McGiverGim for your points, this is the result:
hideescsensor1
hideescsensor2

**Comment by Asizon** [comment]
I discovered an error that alters the borders in several parts of the configurator, it is solved with a simple `border-collapse= collapse;`. Also assign this class to the `Other features` part to fix it and share de same class

**Comment by Asizon** [comment]
BEFORE
configerrors
NOW
configerrorsnow

**Pull request merged**
