### PR TITLE
Revert "Bump Arm build to ARMv8"

### PR DESCRIPTION
**Pull request by haslinghuis**
Reverts betaflight/betaflight-configurator#2940

Fixes https://github.com/betaflight/betaflight-configurator/issues/2984

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Review by Asizon — APPROVED** [review]

**Review by McGiverGim — COMMENTED** [review]
Why not support both, armv7 and armv8? Simply renaming all the `armv8` or `armv7` methods for `arm` and add a conditional to the downloadUrl will be enough?
And add some condition to not let use armv7 and armv8 at the same time. I think this was done for linux and arm before.

**Comment by haslinghuis** [comment]
I used the revert button and can't checkout the branch locally for development. So I would have to open another PR for that unless there is another way.

**Comment by McGiverGim** [comment]
The problem is that with the revert, you have opened a branch into the betaflight-configurator repo, and not into your fork.
To not open another PR, simply make the changes to the `revert-2940-bump-arm-build` of betaflight-configurator repo or force push against this branch. I'm not too sure if you will have permissions for any of this things.

**Pull request closed without merging**
