### PR TITLE
Moved pitch / roll / yaw rate / expo / curves to PID tab

### PR DESCRIPTION
**Pull request by mikeller**
This is just a move of the existing functionality into the PID tab.

@borisbstyle: Let me know if this is how you wanted it, if yes I will start working on adding a graph for the 2.8.x rates.

### CODE REVIEW

**Comment by borisbstyle** [comment]
guys can we quickly release a new configurator to support 2.8.1 properly?

Already having issues with some stuff on cf confugurator.
Op 19 jun. 2016 09:50 schreef "Michael Keller" <notifications@github.com>:

**Comment by mikeller** [comment]
@borisbstyle: From what I can see, the configurator runs fine with <= 2.8.1-RC1, so it can be released at any time.

If you confirm that the changes in this PR are what you want for the new rates for <= 2.8.1-RC1, I can start adding support for > 2.8.1-RC1 on top of it. Might take a couple of days to add extra checking, as the '-RC1' is not properly detected in the configurator, as far as I can tell.

Can you have a look at the data in https://github.com/betaflight/betaflight-configurator/blob/development/manifest.json to make sure that things like author and version are what you want them to be?

**Comment by borisbstyle** [comment]
Can you add these
https://github.com/betaflight/betaflight/commit/8353659c73844c2336d99729c7c7a861d8b84ce2

And fix
https://github.com/betaflight/betaflight/commit/0c5ea0f5c63455ce1bf91f4f8fcf70813768d796

Basically Looptime has to go and be replaced by gyro speed selection based on gyro_sync_denom and pid_process_denom change has to be added.

Also yaw rc rate can be added now

**Comment by mikeller** [comment]
Sure. So this PR is good to be merged in then, to support betaflight <= 2.8.1-RC1?

**Comment by borisbstyle** [comment]
Yes this PR is great! Just checked! If you add that new MSP stuff it may be the first configurator release.

Just move the rc_rate a bit better in between Roll and pitch to make it more clear that its for both now.

**Comment by borisbstyle** [comment]
Quick Summary of wishlist:

- Remove ONESHOT125 feature in configuration tab
- Replace by selection for OFF, ONESHOT125, ONESHOT42, MULTISHOT (all in the new MSP command)
- Remove Looptime. Replace by gyro_sync_denom selection (8K, 4K, 2.7K, 2K, 1K)
- If possible add PID speed next to it calculated from the current selected gyro_sync_denom

**Comment by mikeller** [comment]
I think we should go with this as the initial release, before we add support for the new MSP. This way we have a baseline version to test against. Also, the Chrome Web Store seems to take a bit longer for approval for the initial release of an app than for subsequent updates, so submitting this now might make the release of the version with new MSP support a bit faster.

**Comment by borisbstyle** [comment]
I will merge this anyway

**Comment by mikeller** [comment]
@borisbstyle:

> Quick Summary of wishlist:

As a suggestion, can you add your wishes packaged up (like 'remove ONESHOT125' and 'replace with new selection') as individual issues in the issue tracker? This way individual devs can indicate the ones that they are working on, and we avoid multiple people doing the same work concurrently.

Also, what do you think about re-releasing 2.8.1 as 2.8.2? This way, we could avoid breaking the configurator for users with 2.8.1-RC1 (i.e. when they are trying to update to the new MSP), or having to add in extra checking that goes deeper than what is currently supported?

**Comment by borisbstyle** [comment]
2.8.1 works now even with CF configurator.

I will create the issues and probably start publishing the first version already

**Comment by mikeller** [comment]
I am not so much concerned about 2.8.1. breaking, but 2.8.1-RC1 (which is probably what a lot of users are using now, as it's been out there for a while, and 2.8.0 has been redrawn). 2.8.1-RC1 is recognised by the standard checks in configurator as '2.8.1', which will cause the configurator to use the new MSP commands, which are not supported in 2.8.1-RC1.

**Comment by borisbstyle** [comment]
Its published....not sure if the link works
https://chrome.google.com/webstore/detail/betaflight-configurator/kdaghagfopacdngbohiknlhcocjccjao?hl=en

**Comment by borisbstyle** [comment]
@mikeller 
I know what you mean, but RC's are not complete releases so those people will know they need to upgrade. It will take some time anyway for them all to realise there is a betaflight configurator now.
There is still compatibility with cleanflight configurator in the meanwhile anyway

**Comment by mikeller** [comment]
@borisbstyle: 

> Its published....not sure if the link works

It works! Yay. We might want to add a larger icon at some stage though:

screenshot from 2016-06-20 10-34-48

I am not sure how many users are aware of the distinction between 'RC versions' and 'release versions' for betaflight, most of them probably just use the latest version they can get whenever they update. I will look into adding some detection for MSP capabilities, as I do not like the idea of wilfully breaking stuff for some users.

**Pull request merged**
