### PR TITLE
Vue3 upgrade

### PR DESCRIPTION
**Pull request by BoldBigflank**
Upgrades to Vue3

Upgrades Storybook to Version 8

Updates ESLint rules
 - Changes to plugin:vue/vue3-recommended
 - Adds plugin:storybook/recommended
 - Adds eslint:recommended
 - Makes most existing errors into warnings
 - no-unused-vars is changed to an error with an exception to allow a function regex

NOTE: Currently Storybook loads without errors but many components are not looking like you would expect, so there's more to do to make a robust Storybook experience.

### CODE REVIEW

**Review by haslinghuis — DISMISSED** [review]
LGTM :heart:

**Comment by nerdCopter** [comment]
what CLI commands should i invoke for testing?

**Comment by BoldBigflank** [comment]
@haslinghuis I just realized I used the wrong branch, I'm gonna have to redo my PR

**Comment by BoldBigflank** [comment]
Wait, I misread and it wants the branch to NOT be named master, so we're good to go here.

**Comment by BoldBigflank** [comment]
@nerdCopter `yarn dev` to load the site (things like the Betaflight logo have the right version info, Battery icon exists, etc)
`yarn storybook` will fire up the storybook host

**Comment by BoldBigflank** [comment]
I get an error on loading the home page
```
bluetooth.js:99 Uncaught (in promise) TypeError: this.bluetooth.getDevices is not a function
    at BT.loadDevices (bluetooth.js:99:46)
    at new BT (bluetooth.js:57:14)
    at bluetooth.js:361:16
```
Can anyone confirm this is expected?

**Comment by haslinghuis** [comment]
needs experimental flags being enabled https://github.com/betaflight/betaflight-configurator/pull/4024#issue-2350887491

obvious some code is bypassing https://github.com/betaflight/betaflight-configurator/blob/643b484510ab00854e89b7971d97076190651ecc/src/js/protocols/bluetooth.js#L26-L31

**Comment by McGiverGim** [comment]
High! Thanks for this PR, it's always welcome an update to more modern versions.
This PR is very long, including changes in " by ' (I don't know if they are mandatory/recommended for Vue3) so it's difficult to review fully but at least can be tested.
Some things don't work. For example, in options, if I enable the virtual mode, the combo doesn't reflect it without refreshing the page. In the current master it changes without problem. Could you verify this?

**Comment by haslinghuis** [comment]
PortPicker is not following changes in options tab. Also baudrate default would be 115K2

image

**Comment by BoldBigflank** [comment]
Here seems to be the reason that reactivity is missing:

https://v3-migration.vuejs.org/breaking-changes/data-option#migration-strategy

> For users relying on the deep merge behavior from mixins, we recommend refactoring your code to avoid such reliance altogether, since deep merges from mixins are very implicit and can make the code logic more difficult to understand and debug.

I'm working through options to get this going again

**Comment by BoldBigflank** [comment]
I haven't figured it out and will redo the PR when it's ready

**Comment by nerdCopter** [comment]
accurate, or just junk/noise: ?
image

**Pull request closed without merging**
