### PR TITLE
Fixed dependency vulnerabilities.

### PR DESCRIPTION
**Pull request by mikeller**

### CODE REVIEW

**Comment by Docteh** [comment]
jbox still works! 👍

**Comment by mikeller** [comment]
Yep. And I held back i18next, because that has a change breaking us.

**Comment by Docteh** [comment]
what breaks in i18next? 17.0.11 seemed to work fine for me.

**Comment by mikeller** [comment]
@Docteh: I thought it was a breaking API change between 14 and 15 that kept us from updating. If they added a compatibility mode after that then we should look into updating.

**Comment by Docteh** [comment]
Maybe we had a bug? Their migration guide doesn't list anything in the version we're at.

https://www.i18next.com/misc/migration-guide

**Pull request merged**
