### PR TITLE
Hide tabs for features that are disabled.

### PR DESCRIPTION
**Pull request by mikeller**
Implements #141.

### CODE REVIEW

**Comment by TheAngularity** [comment]
wow super solved ... are you have a solution for Adjustments, Servos and Tethered Logging?
for example in the Application Options ;)

**Comment by mikeller** [comment]
@TheAngularity: I thought about that, but, if anything, I want to make it easier for newbie users, not more complicated by adding a lot of options to configure the GUI. My suggestion would be introduce a 'normal' and an expert mode, and to start off with, have the normal mode hide the less commonly used tabs. Tabs that need a feature to be enabled would show in both modes, in order to make it not too confusing.

My suggestion for tabs to be showing in 'normal' mode:

- Setup;
- Ports;
- Configuration;
- PID Tuning;
- Receiver (I'd probably swap the order of PID Tuning and Receiver though);
- Modes;
- Motors.

Currently we have the following tabs tied to a feature being enabled:

- GPS;
- LED Strip;
- Blackbox Logging;
- Transponder;
- OSD.

This would leave us with the following tabs only showing in expert mode:

- Failsafe;
- Adjustments;
- Servos;
- Sensors;
- Tethered Logging;
- CLI.

Your thoughts, guys?

**Comment by nathantsoi** [comment]
Related idea: A walkthrough option could be cool. It would be like
"beginner/normal mode" but guide the user through configuring each step.
E.g. calibration (gyro/acc), serial ports, rx, looptime, walk through
config diff if upgrading, etc. It could even do blheli flashing and
calibration at some point.

**Comment by mikeller** [comment]
I think the 'walktrough' is already almost there, if the users cycle through the tabs of 'normal mode' on after another:

- Setup;
- Ports;
- Configuration;
- PID Tuning;
- Receiver (I'd probably swap the order of PID Tuning and Receiver though);
- Modes;
- Motors.

We could probably a tooltip shown on first startup, explaining this to new users.

**Comment by TheAngularity** [comment]
@mikeller  nice idea;-)
i'm in full agreement with normal / expert mode inclusive tooltip and swap of tab PID Tuning and Receiver, a good solution

**Comment by skaman82** [comment]
@mikeller Failsafe is a mandatory tab and should be shown in normal mode. The rest ist great.

**Comment by mikeller** [comment]
@skaman82: What do you mean by 'mandatory'? Failsafe is the one tab where I wasn't 100% as to if it should be 'normal' or 'expert'. On one hand, having useful settings for failsafe is important. But for a novice user, I have my doubts that they will be able to configure anything useful for failsafe, so leaving it at the defaults is probably best to start with.

Also, the incidents caused by loss of connection that I have seen and that did not end well were all caused by the fact that the pilot had left failsafe enabled on the receiver, and hence the FC never even detected a failsafe condition. Perhaps we should add a big warning about this to the tab?

**Comment by skaman82** [comment]
With mandatory I mean that it is critical to set up failsafe right in the initial quad config. 
Therefore I think it should stay in normmal mode.


Regarding:
> Also, the incidents caused by loss of connection that I have seen and that did not end well were all caused by the fact that the pilot had left failsafe enabled on the receiver, and hence the FC never even detected a failsafe condition. Perhaps we should add a big warning about this to the tab?
> 
> 

Not all receivers transmit a throttle value under 1000 in a signal loss. And only the the system detects a failsafe event.
You have to trick those receivers out while binding with throttle trimmed down to max (many orange PPM receivers - no failsafe support by the receiver itself).  
Every receiver is different and there a more than one way to get it right.

**Comment by mikeller** [comment]
> With mandatory I mean that it is critical to set up failsafe right in the initial quad config.
Therefore I think it should stay in normmal mode.

I think the defaults (stay stabilized, reduce throttle to minimum) are fairly good, and I would think that novice pilots probably can not change much that will actually make this better (e.g. if they manage to set throttle to hold, they will be left watching their craft disappear over the horizon ;-))

For any experienced pilot, I would expect that they work in expert mode anyway.

Maybe we should call the modes 'novice' and 'normal' instead of 'normal' and 'expert'?

**Comment by skaman82** [comment]
If you have set up throttle to HOLD, this is only for the stage 1 (wait for recovery), stage two sets the throttle to 1000 then (as default setting). So this would NOT result in a flyaway. I have this set up exactly like that :)

**Comment by mikeller** [comment]
> If you have set up throttle to HOLD, this is only for the stage 1 (wait for recovery), stage two sets the throttle to 1000 then (as default setting). So this would NOT result in a flyaway. I have this set up exactly like that :)

Fair enough, I run a similar setup. But I see the '2-stage failsafe' as an advanced feature, and I definitely would not want to throw that at novice pilots. It requires the pilot to get motor output values and timings right, which is not something they would be able to do if this is the first time they set up a craft.

**Comment by skaman82** [comment]
Ok, agreed. Lets put it in advanced mode.

Von meinem iPhone gesendet

**Comment by mikeller** [comment]
Created #143 for 'novice mode'.

**Pull request merged**
