### PR TITLE
Hide telemetry protocols for CRSF, FPORT and GHST

### PR DESCRIPTION
**Pull request by haslinghuis**
image

image

Inspired after watching https://youtu.be/FMbBfef_R-g

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by nerdCopter** [comment]
i am not sure i understand here.  when i flash either a cloud-build or a non cloud-build 4.5 or 4.4, i already do not see these telemetry-protocols in `master`, or am i mistaken somehow.

**Comment by haslinghuis** [comment]
This PR hides the telemetry protocol input if CRSF, FPORT or GHST are selected here

image

**Comment by nerdCopter** [comment]
i see now, 
image

i thought it was the individual options, but it is the field/header as you explained.

**Review by nerdCopter — APPROVED** [review]

**Comment by ctzsnooze** [comment]
Yes, this has always been confusing.

I would have preferred that when CRSF was selected, the telemetry protocol would show CRSF, and not be editable.

That's the situation; telemetry is an automative part of CRSF; we do not require any extra setting to enable it, it's always there.  So a nicer display element would indicate that it was present and active - because it is.

**Comment by KarateBrot** [comment]
We should rather make it impossible to select any items in the dropdown instead of just hiding  the dropdown. That's a way cleaner approach. After that we can still hide the dropdown.

**Review by nerdCopter — APPROVED** [review]
- re-approving for new `....select2('destroy');`

**Comment by nerdCopter** [comment]
after testing, it looked different today as well
CRSF selected:
image
image

SBUS selected:
image

**Comment by haslinghuis** [comment]
All sorted.

**Comment by nerdCopter** [comment]
:rocket: 
image
image

**Comment by nerdCopter** [comment]
there is a bug. to reproduce: select IBUS, select IBUS EXTENDED.  select CRSF, seelct IBUS, seelct IBUS EXTENDED -- it will set to none.  same for other protocols.  they are removed, but not return when protocol is changed.

**Review by nerdCopter — APPROVED** [review]
`d880010b` seems to work proper.

**Comment by ctzsnooze** [comment]
Could I see a screenshot of how it looks now when the telemetry is 'included', ie when user selects CSRF?  Saying 'automatically included', or similar, in the box to the right, kind of works for me, so long as those words don't appear in the drop-down.  And I guess if it is 'included' then we don't need the drop-down to be available?

**Comment by nerdCopter** [comment]
- screenshot in description @ctzsnooze  .
- Currently says "`This Radio Protocol has Telemetry included`", but i think "`Automatically Included`" is fair as well.

**Comment by haslinghuis** [comment]
Drop down is not available when telemetry is included

**Review by nerdCopter — APPROVED** [review]

**Review by ctzsnooze — APPROVED** [review]
Thanks!  This looks really good.  Very much like to see "automatically included", much nicer than before.

**Pull request merged**
