### PR TITLE
Configurable OSD warnings

### PR DESCRIPTION
**Pull request by DanNixon**
To go with https://github.com/betaflight/betaflight/pull/3924

Adds a few extra tooltips to describe the various sections of the OSD tab.

### CODE REVIEW

**Comment by basdelfos** [comment]
Nice, I like these options for warnings. Any chance you can fix the conflicts?

**Comment by mikeller** [comment]
@basdelfos: Probably not much point doing this now, since betaflight/betaflight#3924 that has to go with it will only be going in for 3.3.

**Comment by mikeller** [comment]
Sorry @DanNixon, I just saw that this needs a rebase as well.

**Comment by mikeller** [comment]
@DanNixon: Is this still to be merged? It needs a rebase...

**Comment by DanNixon** [comment]
Yes, haven't got round to it yet as there are a lot of non-trivial conflicts and I've been away this last week. I'll have a look tomorrow.

**Comment by DanNixon** [comment]
@mikeller Done.

**Pull request merged**
