### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by McGiverGim**
Update all the translations files for the next release. Thanks to all the translators for the work.

### CODE REVIEW

**Comment by mikeller** [comment]
Yes, my heartfelt thanks as well, you guys are amazing!

**Comment by wind0r** [comment]
Excellent Work :)

**Comment by DieHertz** [comment]
Wunderbar! Do we have Russian as well?

**Comment by mikeller** [comment]
@DieHertz: It's work in progress: https://crowdin.com/project/betaflight-configurator/ru#

**Comment by hydra** [comment]
good work people

**Pull request merged**
