### PR TITLE
Refactored rate curve into file of its own, improved scaling of rate curves

### PR DESCRIPTION
**Pull request by mikeller**
Now all the rates are scaled in relation to each other. Also, the angular velocity at maximum stick is displayed for each axis, which should partially address #77.

### CODE REVIEW

**Comment by antstorm** [comment]
@mikeller nice! Once this is merged I can adjust 3D model rotation.

**Comment by borisbstyle** [comment]
Didnt test it yet, but lets merge it so @antstorm can continue.

Will check it later this evening

**Comment by borisbstyle** [comment]
also the super expo should be enabled by default as it is default

**Comment by borisbstyle** [comment]
Or even better make the button really functional and remove it from feature list in configuration tab

**Comment by mikeller** [comment]
> Or even better make the button really functional and remove it from feature list in configuration tab

I thought that was the right thing to do, just wanted to confirm with you first. Will do it as the next step.

**Comment by borisbstyle** [comment]
@mikeller 
Yes it really belongs to be there to fiddle with rates on one single location

**Comment by mikeller** [comment]
@borisbstyle: What do you think of moving the 'Profile' dropdown into the PID tab as well (and adding a 'Rateprofile' dropdown)? There are no profile dependent settings left outside of the PID tab, so I think having the profile selection only available in there will be more logical.

**Comment by borisbstyle** [comment]
Yeah sure....sounds logic to me.

**Comment by borisbstyle** [comment]
Can someone add the rate formula in 3D model? Should be really easy. It seems a lot of folks want that

**Comment by mikeller** [comment]
@borisbstyle 

> Can someone add the rate formula in 3D model? Should be really easy. It seems a lot of folks want that

You mean as in 'make the 3D model behave on stick input as if the rates were calculated with the new rates formula'?

If so, the angular velocity for the new formula can be exposed in `js/RateCurve.js` (calculated in `rcCommandRawToDegreesPerSecond`).

**Comment by antstorm** [comment]
@mikeller @borisbstyle I'll implement that change now that everything's in place

**Pull request merged**
