### PR TITLE
Remove Google Analytics

### PR DESCRIPTION
**Pull request by haslinghuis**

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by KarateBrot — APPROVED** [review]

**Comment by McGiverGim** [comment]
Why this? We don't want to have statistics of usage?

**Comment by sugaarK** [comment]
New build system gives us a LOT more data..

**Comment by McGiverGim** [comment]
I doubt it. It can give information about build options that is half of the data. But I suppose we can't have information about languages used in the Configurator, rates system selected, etc.

**Comment by haslinghuis** [comment]
As most configuration is done using presets now analytics won't be aware of changes made. Some parts were outdated suggesting it was not used a lot. We could send some metrics with cloud login - as cloud build settings could be used to preset some configuration items.

**Comment by McGiverGim** [comment]
We can send the presets used to analytics. We lost some things like languages being used, number of unique users, countries off this users, etc. But I suppose the decision has been taken.

**Pull request merged**
