### PR TITLE
Clarify GPS Signal Strength

### PR DESCRIPTION
**Pull request by haslinghuis**
Only show GPS Signal Strength when GPS is active.

Currently when having SatInfo and powering off the GPS configurator only shows last frozen state.

Resetting data won't show values - we can show an informational message like:

image

UPDATE:

image

EDIT:

image

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by nerdCopter** [comment]
Would it make more sense to re-initialize the values upon disconnect or GPS-not-powered state?

**Comment by nerdCopter** [comment]
looks good, but i cannot have no real GPS to test.

**Comment by haslinghuis** [comment]
Thinking about it perhaps we should have a second message:

1. At startup when no signal data has been received as GNSS has not been detected yet we show the message above.
2. When loosing signal after being detected we show a message like

```
The GNSS unit is no longer recognized.
```

**Comment by ctzsnooze** [comment]
This should probably be a 4.6 new feature.  It is an improvement but could introduce unexpected issues, and will require testing that would delay 4.5.

**Comment by ctzsnooze** [comment]
Hi Mark... checking this now - does it need rebasing?  Seems to work, when I test it, and the message is useful.

Perhaps the text could say:

```
Connecting...
The GPS icon lights up when Betaflight is connected to a GPS module.  This usually takes a couple of seconds.<br>
It will be red at first, then change to yellow when it gets a 3D fix.<br>
If the GPS icon does not light up, check your wiring and configuration, and confirm that the GPS module is receiving power.<br>
The CLI "status" command provides more information about the state of the GPS connection.
```

That last line is optional and perhaps unnecessary, whatever you think.

**Review by ctzsnooze — APPROVED** [review]

**Comment by haslinghuis** [comment]
Rebased on master

**Comment by ctzsnooze** [comment]
Just checking the PR again...
There is a bit of pale grey space under the 'yellow' of the 'Connecting...' note - maybe that can be removed?

**Comment by ctzsnooze** [comment]
Also, I wonder if some tiny simplifications, and wider line spacing, may improve readability:
```
The GPS icon lights up only when the connection to the GPS module is confirmed.<br>
<br>
It will be red at first, changing to yellow when the 3D fix is attained.<br>
<br>
If the GPS icon does not light up, check your wiring and configuration, and confirm that the GPS module is receiving power.<br>
<br>
The CLI 'status' command provides more information about the state of the GPS connection.
```

**Review by HThuren — APPROVED** [review]
I like the last more simple message, and for sure the idea.

**Pull request merged**
