### PR TITLE
Update NWjs to 0.83

### PR DESCRIPTION
**Pull request by haslinghuis**
Check to fix virus issues reported with current build on Windows. Previous we were not able to go up due to icon issue which seems solved now.

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by HThuren** [comment]
0.83 give same issue with worm in resourcer.exe, Also at my pc found more connections (my headset)
AND the installer exe now has the right BF icon. 
image
The worm issue when you build the debug and release application, not when you run the bf installer, nor the bf configurator after installation.
Since the touble came with node 20.10, I think #3695 can be merged, making no difference (maybe the more connections ?)

**Comment by nerdCopter** [comment]
NWjs developers often acknowledge existence of false-positive virus-checks simply as a by-product of exe generation. :(
Unsure about the icon issue. Maybe windows icon cache could be cleared as a troubleshooting step.

**Comment by HThuren** [comment]
> NWjs developers often acknowledge existence of false-positive virus-checks simply as a by-product of exe generation. :( Unsure about the icon issue. Maybe windows icon cache could be cleared as a troubleshooting step.

Windows defender discover the signature from Win32/AutoRun!pz when resourcer.exe (who do the icon change) start. Defender stop resourcer.exe, report and you have no icon shift. Since resourcer.exe are from 2009, we might can compile a new one with today runtime libs, but then we need the source and the references regarding resourcer.exe are dead. I have wrote to Felicien, if he by luck have the source, but no responce yet.
Otherwhise we need a new way to change the icon, I suppose deals with windows, mac and linux.

**Comment by ASDosjani** [comment]
Did someone try 0.85?

**Comment by haslinghuis** [comment]
Moving to PWA NWjs won't be needed anymore.

**Pull request closed without merging**
