### PR TITLE
Use locale US in PayPal donation link

### PR DESCRIPTION
**Pull request by keyser84**
Facilitate making PayPal donations by linking to the English version of the donations page.

### CODE REVIEW

**Comment by keyser84** [comment]
This is an absolutely minor change. I came across the Dutch version of the page when wanting to donate but found it easier to see the English version.

**Comment by mikeller** [comment]
@borisbstyle: Can you please check if this still works correctly?

**Comment by borisbstyle** [comment]
Works. Great. paypal generated that for and didnt know it could be changed

**Comment by mikeller** [comment]
All good. I am just *very* cautious with community PRs that request a change to things that could have financial implications. :-P

**Comment by keyser84** [comment]
Certainly reasonable to be cautious there. However, it's only the locale that has changed. Also, I successfully used that link myself yesterday.

**Pull request merged**
