### PR TITLE
Add CLI console

### PR DESCRIPTION
**Pull request by haslinghuis**

### CODE REVIEW

**Comment by nerdCopter** [comment]
recently allowed keyboard-shrotcuts, but this overrides ctrl-C.
also activates for any of `ctrl-` `win|shift|alt` `-C`

**Comment by haslinghuis** [comment]
- Was thinking about Control I - but you found the Easter egg :)
- Terrible at UX the Execute button and output window does not scale

**Comment by nerdCopter** [comment]
`ctrl-` `[shift|win|alt]` `-I` launches. shift also opens debugging.
"execute" still does not work for me, this might be preliminary/draft however.

**Comment by haslinghuis** [comment]
Output: 

image

**Comment by nerdCopter** [comment]
tested 4.6 it worked, 4.5 did not. must be a requirement i did not know, maybe semver gate it.
disconnect doe not close the dialog.
re-opening the dialog retains output.

**Comment by nerdCopter** [comment]
sometimes it works, sometimes it doe not work. i dont see pertinent any console output.

**Comment by haslinghuis** [comment]
- retaining output is fixed now.
- perhaps move the handler to serial backend (to have access to semver and connection status)

**Comment by nerdCopter** [comment]
`aac30590`
- consistently working with 4.6
- semver worked
- `ctrl-I` only working :)
- buffer clearing proper
- dialog closing on unplug

**Review by nerdCopter — APPROVED** [review]
- approving, request others to test and give opinions on overall layout.

**Comment by haslinghuis** [comment]
latest push fixes command retaining when using `save` command - moving line from response to command.

**Comment by haslinghuis** [comment]
latest push fixes command retaining when using `save` command - moving line from response to command.

**Review by VitroidFPV — APPROVED** [review]
Worked as expected for everything I tried 👌

**Pull request merged**
