### PR TITLE
Fixed the antigravity feature switch.

### LINKED ISSUE #2002: Anti-gravity section on PID tuning tab incorrectly hiding when feature is disabled
Turning the ANTI_GRAVITY feature off on the Configuration tab doesn't disable the function. Rather it causes a mode to appear on the Modes tab to allow it to be controlled with a switch (similar to how AIRMODE works).

So hiding the anti-gravity section on the PID Tuning tab based on whether the feature is enabled is incorrect. Should not ever be hidden.

### PR DESCRIPTION
**Pull request by mikeller**
Fixes #2002.

image

image

### CODE REVIEW

**Comment by McGiverGim** [comment]
@mikeller This imply that the tuning tab now is a `save AND REBOOT` always? I think this is a worst experience than before. In this tab the users play a lot, saving and changing profiles, if each change implies a reboot is an annoyance for the user.
Maybe we can detect when the user changes the feature that needs that and only reboot in this case?

**Comment by mikeller** [comment]
@McGiverGim: Good point - we could probably do something and implement it in a generic way for all features - as it is the firmware is explicitly designed to always require a reboot for feature changes to take effect.

**Comment by mikeller** [comment]
Now requires betaflight/betaflight#9875 to work, but a reboot can be avoided.

**Comment by McGiverGim** [comment]
Thinking again about this... what will happen with old firmware? I suppose it will be changed but will not take effect until a manual reboot?

**Comment by mikeller** [comment]
@McGiverGim: Good point - yes that is the case. But this is already broken now for pre-4.2 firmware, as the availability of the 'ANTI GRAVITY' box is not properly calculated because of the bug fixed in betaflight/betaflight#9779.

**Comment by McGiverGim** [comment]
Is not perfect, but good enough for me. We must decide between a perfect solution and the cost of the maintenance of the code. I think the effort needed is not justified here, so is ok for me.

**Comment by 0crap** [comment]
PID Tuning tab

Two sliders is very confusing in 10.7.0-RC2

**Comment by mikeller** [comment]
@0crap: Reading the tooltips that are on offer makes it less confusing. ;-)

Fact is we have to things that can be switched here:
- enabling / disabling Anti Gravity;
- switching between always on and controlled by a mode switch.

I think having both of these in the same place instead of spread over two tabs like before is much less confusing.

**Comment by haslinghuis** [comment]
Using the second slider only would be sufficient. In disabled state without a mode switch it would already be disabled ?

**Comment by mikeller** [comment]
@haslinghuis: This would be an option. However, this will be significantly more work, as one of the sliders is driven by a feature, and as such is auto-generated. Combining this with a third state ('all off') will require this to be done manually, and the feature excluded from automatic processing.

**Comment by haslinghuis** [comment]
@mikeller: I was not clear in mentioning the second option in my suggestion:
Replace the second slider with a dropdown menu.

**Comment by mikeller** [comment]
@haslinghuis: Same deal really - we get the slider 'for free', the drop down will have to be implemented and then maintained manually.

**Pull request merged**
