### PR TITLE
Cleanup more F3 code

### PR DESCRIPTION
**Pull request by haslinghuis**
Cleaning up code used for F3 boards

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by nerdCopter — APPROVED** [review]
seems to still work, only one FC tested.

**Comment by ctzsnooze** [comment]
Isn't VCP still supported on F4 and F7 boards, and in the firmware?
I see quite a few F4 and F7 boards in the list of boards that is being deleted by this PR.

**Comment by haslinghuis** [comment]
This table is no longer used. MSP_BOARD_INFO provides the info contained in firmware using targetCapabilities property.

See: https://github.com/betaflight/betaflight-configurator/pull/2355#pullrequestreview-560559627

**Review by ctzsnooze — APPROVED** [review]

**Pull request merged**
