### PR TITLE
Fix flash on connect

### PR DESCRIPTION
**Pull request by haslinghuis**
When using flash on connect:
- the timer was not reset - resulting in a flash loop - asking for backup again.
- we should be as quick as possible - skipping dialogs as the switch is mandatory for this behavior.

### CODE REVIEW

**Comment by ASDosjani** [comment]
Works like a charm, thank you @haslinghuis 🥳

**Review by nerdCopter — APPROVED** [review]
- worked for me, but have to allow firmware to load first before toggling.

**Comment by haslinghuis** [comment]
> worked for me, but have to allow firmware to load first before toggling.

- Never had to use this switch on my builds - so new terrain :)
- When enabled and a new port is detected flash on connect will spam the flash button - as this would require a hex ready to flash (local or online).

**Review by HThuren — APPROVED** [review]
Also worked for me, nice change

**Review by asizon — APPROVED** [review]
LGTM!

**Comment by txmonstr** [comment]
With the new BF Configurator 10.10 I'm unable to connect to the FC via the Wifi of my ExpressLRS Reciver. With BF Cofigurator 10.9 there where no problems.

**Comment by haslinghuis** [comment]
- That has nothing to do with this fix :)
- In options tab (when disconnected) enable the switch here

image

**Comment by txmonstr** [comment]
Thats interesting. I turned on the switch and it still didn't work.

**Comment by ASDosjani** [comment]
> Thats interesting. I turned on the switch and it still didn't work. It detects the board but then it closes the sereal port with this error message: "No configuration received within 10 seconds, communication failed". Do I maybe have to upgrade the FC to BF 4.5?

That's probably because of the very poor ELRS wifi antenna... Let's move this conversation to Discord, it's not related to this bugfix.

**Pull request merged**
