### PR TITLE
Fix full chip erase

### PR DESCRIPTION
**Pull request by haslinghuis**
Fixes: #3404

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by nerdCopter — APPROVED** [review]
* verified on two F's

**Comment by howels** [comment]
Verified here as well.

**Comment by howels** [comment]
@haslinghuis flash is still erased if expert mode is disabled

**Comment by haslinghuis** [comment]
Yes that's by design (only hidden now as requested by @blckmn ).

It's an expert setting as normally we want to have this enabled to minimize support issues.

**Comment by howels** [comment]
> Yes that's by design (only hidden now as requested by @blckmn ).
> 
> It's an expert setting as normally we want to have this enabled to minimize support issues.

Breaks H730 unless expert mode enabled. Why break by default? At least target the config partition specifically and do the wipe cleanly.

**Comment by nerdCopter** [comment]
H730 needs custom flash address? is this why it breaks?

**Comment by haslinghuis** [comment]
Also in the documentation for the SPRacing Flight Controllers it's stated to disable full chip erase IIRC.

**Review by blckmn — APPROVED** [review]

**Comment by blckmn** [comment]
> disable

We might need to have a disable flash erase option for some targets. Perhaps as part of the populating cloud build options we can include if it's on or off.

**Comment by haslinghuis** [comment]
2e9026046c3e219ded993c51ef5b8278

**Comment by haslinghuis** [comment]
```
mark@pc:~/Downloads$ diff 'betaflight_4.4.1_STM32H743_KAKUTEH7_2e902604(1).hex'  betaflight_4.4.1_STM32H743_KAKUTEH7_2e902604.hex 
24016c24016
< :10D9D00032313A33373A33350041707220203620E5
---
> :10D9D00031343A33353A33360041707220203620E4
24271c24271
< :10E9C000353931623200000032313A33373A33356B
---
> :10E9C000353931623200000031343A33353A33366A
```

**Comment by howels** [comment]
If the intent is to wipe configuration then the DFU command could target the erase partition only for erasure.
However, I cannot see a list of partition layouts for all targets that would enable this easily- which might be why we are simply erasing the entire flash chip.

**Pull request merged**
