### PR TITLE
Improved 'release' build script. Changed version to 10.0.0-RC1.

### PR DESCRIPTION
**Pull request by mikeller**

### CODE REVIEW

**Comment by KrickeH** [comment]
Failed to load extension from: ~\bf\betaflight-configurator
Required value 'version' is missing or invalid. It must be between 1-4 dot-separated integers each between 0 and 65536.

//K

**Comment by KrickeH** [comment]
If I edit out "-RC1" configurator loads as usual.

**Comment by basdelfos** [comment]
@KrickeH on which platform are you? MacOS, Windows of Linux?

**Comment by KrickeH** [comment]
Windows 10 64

**Comment by TheIsotopes** [comment]
> Failed to load extension from: ~\bf\betaflight-configurator
> Required value 'version' is missing or invalid. It must be between 1-4 dot-separated integers each between 0 and 65536.

> Windows 10 64 with Chrome 62.0.3202.94

@mikeller  @basdelfos 
have the same issue ... remove `-RC1` fixed it

**Pull request merged**
