### PR TITLE
fix wiki link

### PR DESCRIPTION
**Pull request by HThuren**
Link to new wiki: https://betaflight.com/docs/wiki/configurator/receiver-tab
No reference to ADC filter (not described at new wiki)

### CODE REVIEW

**Comment by haslinghuis** [comment]
@HThuren you still missed some links.

Updated all links as this should be sorted now: https://github.com/betaflight/betaflight-configurator/pull/3308

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Comment by HThuren** [comment]
> @HThuren you still missed some links.
> 
> Updated all links as this should be sorted now: #3308

Right, I didn't notice #3308, but only when receiverHelp came up in Crowdin.
I delete this PR, since covered in 3308

**Comment by haslinghuis** [comment]
Was working on the issue mentioned on Discord.

**Pull request closed without merging**
