### PR TITLE
Modify localization.js to detect crowdin

### PR DESCRIPTION
**Pull request by Docteh**
This PR modifies `localization.js` so that if the crowdin in-context translation is used, it'll set the language like it wants (ach), otherwise acts normally.
Changing the language is not recommended on translator builds, this also covers that.

### CODE REVIEW

**Comment by McGiverGim** [comment]
I'm not too sure about that. That not hurts, but with this we are adding part of the translation system in a non translation build that knows nothing about it.
The Translation version had disabled the language change. But when we change it to the first page it was added again and I missed it.
To me the correct fix is to modify only the branch that contains the changes for the Translation version, and simply commenting the click action on the languages will be enough.

Is there other reasons to do this here?

**Comment by McGiverGim** [comment]
If you have curiosity, the branch used to build the translators version is at my repo: https://github.com/McGiverGim/betaflight-configurator/tree/bf-in_context_translation

It only has a commit that I rebase with master each time. I have modified the commit to comment the language change.

Maybe it will be better to move the branch to the official repo.

**Comment by mikeller** [comment]
Not sure what the best approach is here.

Can the in-app translated version be built straight from your branch, or is does it require something like authentication to be added to be able to connect to crowdin, @McGiverGim?

If it can be build from the branch we could probably look into mergeing the change into the main repository, to make it possible for people to build their own in-app translatable version from the tip of `master`. Or we could even look into adding a CI build for it if and when we get Windows CI builds going.

**Comment by Docteh** [comment]
I was playing with the web serial implementation, and wanted to see if I could host both Crowdin and regular versions. 

For the in-app I believe only `main.html` and `js/localization.js` are modified. The `src/js/crowdin_in_context.js` is exclusive to in-app translations

Out of date
https://docteh.github.io/# - no Crowdin
https://docteh.github.io/main.html# - With Crowdin, you have to click on `language_ach.message` for it to work properly. I should have applied this PR to there. 

A Google Chrome Canary build refused to log in to crowdin a few days ago, so if you want to try webserial ~~I'd suggest installing the Beta channel.~~ https://omahaproxy.appspot.com/ 
`chrome://flags/#enable-experimental-web-platform-features`

**Comment by McGiverGim** [comment]
> Can the in-app translated version be built straight from your branch, or is does it require something like authentication to be added to be able to connect to crowdin, @McGiverGim?

It can be built directly from my branch. The authentication is asked later, when starting the app, to the user.

The changes are very simple: https://github.com/McGiverGim/betaflight-configurator/commit/0edb093dfdb49aa670a868412a6b2508c8f86f04

The only problem is that I need to rebase with master, update the ach language, and build it. It can be done automatically, but it will need some script I suppose.

**Comment by Docteh** [comment]
I think we should nuke the l10n_master branch, merge a language change into master, and then see what crowdin does. 

If we get a single commit update, we could consider merging it.

It would contain all translations, including some languages that don't have any approved strings. I don't consider that a problem, we only show a specified list of languages.

An alternative would be to fetch from the l10n_master branch: 
https://raw.githubusercontent.com/betaflight/betaflight-configurator/l10n_master/locales/ach/messages.json

The zip available on crowdin looks like it requires someone to manually "build" the project to have it updated there.

**Comment by mikeller** [comment]
> The only problem is that I need to rebase with master, update the ach language, and build it. It can be done automatically, but it will need some script I suppose.

We could add this as a build time parameter for the gulp build.

> I think we should nuke the l10n_master branch, merge a language change into master, and then see what crowdin does.

That won't work, as direct pushes into `master` are disabled as part of our review process. But we could start merging changes from `i10n_master` on a regular basis. But not sure if this ties in with making the in-app translatable version buildable from `master`.

**Comment by Docteh** [comment]
I'm a lazy hacker at heart. #1646 has a change to localization strings. When that PR gets approved, consider trashing the localization branch before merging it. 🎲 

I figure that if deleting the branch doesn't blow up in our face, we could build the in-app version from the l10n_master branch. I'm not expecting it to blow up in our face, Crowdin told me that deleting the branch would be fine.

A safer strategy, Crowdin has an API command to [export](https://support.crowdin.com/api/export/), which rebuilds the [.zip file](https://crowdin.com/backend/download/project/betaflight-configurator.zip).

**Comment by mikeller** [comment]
@Docteh:

Looking at this I am not so sure any more that adding this into the `master` code base is the best way to go about this - it adds a lot of complexity, and I think you are right and we do not want to include this in the general distribution.

Since this requires the language file updates that are pushed into `l10n_master` anyway, how about we implement this as a changeset on this branch, and make the in-app translation version buildable from this branch.

For an updated build of the in-app translation version all that will need to be done is to rebase `l10n_master` on latest `master`, and then build. We are using a similar approach with some branches for special versions like `broken-usb-rescue` in the firmware, and it is working well.

**Comment by McGiverGim** [comment]
This seems to me a better idea. If we can do a rebase It will work in a cleaner way.

**Comment by Docteh** [comment]
I agree. 

I cherry picked @McGiverGim's commit, and removed the `ach/messages.json` file from it. Stuck it up as a https://github.com/betaflight/betaflight-configurator/tree/localization 

Hopefully that saves some typing on the part of somebody else. I think we just need to copy the branch over the l10n_master branch and then have crowdin sync.

**Comment by McGiverGim** [comment]
There was a bug in my code from a rebase: the permission to Google maps is not needed, we use open Street map now.

**Comment by mikeller** [comment]
@McGiverGim: Need me to look into this?

**Comment by McGiverGim** [comment]
I don't think so, is only at my Crowdin branch, and it does not break anything. Was for @Docteh that cherry picked my commit, to let the code cleaner.

**Pull request closed without merging**
