### PR TITLE
Hide message when USE_VTX is not included in build

### PR DESCRIPTION
**Pull request by haslinghuis**
- suppress vtx note when not applicable.
- Initial issue will be addressed in https://github.com/betaflight/betaflight/pull/13329

### CODE REVIEW

**Review by blckmn — CHANGES_REQUESTED** [review]
Probably better to do this in firmware. ie when vtx not included then return an empty response from a stub function

We can start to do these things once we have a get build options from firmware, not api (given local builds are a distinct possibility).

**Comment by haslinghuis** [comment]
FYI @atomgomba is working on a MSP call to include [requested] options in firmware in a mask so we do not have to rely on internet or build.

Will test using change in firmware instead.

**Comment by haslinghuis** [comment]
We need to include defines list in firmware before this can be used.

**Comment by HThuren** [comment]
> FYI @atomgomba is working on a MSP call to include [requested] options in firmware in a mask so we do not have to rely on internet or build query. Maybe add all drivers to MSP_BOARD_INFO and features to MSP_BUILD_INFO. Any suggestions are welcome.
> 
> EDIT: Changing in firmware also works.

Maybe a setup with an value, where a mask will translate to define value (USE_OSD etc) inspiration from https://github.com/betaflight/betaflight-configurator/pull/3583
const buildMap = [
    { buildKey: 'cam',       buildOption: ['USE_CAMERA_CONTROL']},
    { buildKey: 'div',       buildOption: ['USE_ARCO_TRAINER', 'USE_DASHBOARD', 'USE_PINIO']},
    { buildKey: 'dshot',     buildOption: ['USE_DSHOT']},
    { buildKey: 'gps_mag',   buildOption: ['USE_GPS', 'USE_GPS_PLUS_CODES', 'USE_MAG']},
    { buildKey: 'led_strip', buildOption: ['USE_LED_STRIP', 'USE_LED_STRIP_64']},
    { buildKey: 'osd',       buildOption: ['USE_OSD', 'USE_OSD_SD', 'USE_OSD_HD', 'USE_FRSKYOSD']},
    { buildKey: 'serial',    buildOption: ['USE_SERIALRX', 'USE_SERIALRX_FPORT']},
    { buildKey: 'servos',    buildOption: ['USE_SERVOS']},
    { buildKey: 'telemetry', buildOption: ['USE_TELEMETRY', 'USE_TELEMETRY_SMARTPORT']},
    { buildKey: 'vtx',       buildOption: ['USE_VTX']},
];
But of couse less detail, than have them all

**Comment by nerdCopter** [comment]
`7eb1f66f`
without USE_VTX,  https://build.betaflight.com/api/builds/7793fc1250f37f7b469d392fca275a05/json
still have message
image

**Comment by nerdCopter** [comment]
but is this what we want?  if USE_VTX non-existent, may be confusing without any message whatsoever.  Would a new message about USE_VTX excluded be more appropriate?

**Comment by haslinghuis** [comment]
Yes the message should be hidden - as it works on this machine, not sure why it did not hide in the other place when adding the condition.

**Comment by HThuren** [comment]
> Yes the message should be hidden - as it works on this machine, not sure why it did not hide in the other place when adding the condition.

I had a lot of this in Categorys on mode tab, maybe  `.prop('disabled',true)` will help

**Comment by haslinghuis** [comment]
Using `$('.vtxTableNotSet').hide();` in dev console just hides the message. Something funky going on.

**Comment by haslinghuis** [comment]
Somehow with master it works now for me.

**Comment by ctzsnooze** [comment]
This is a good idea, including build flags in firmware, but it should really be a 4.6 feature I think.

**Comment by haslinghuis** [comment]
@nerdCopter using this firmware now: https://github.com/betaflight/betaflight/pull/13329

**Pull request closed without merging**
