### PR TITLE
fix missing spaces in DE locale

### PR DESCRIPTION
**Pull request by MrTucks**
fix 2 missing spaces in the Donation Notice box and the Contributing list on the welcome screen.
I hope this patch and pull request work but to be honest, I don't know how to test it.

### CODE REVIEW

**Comment by McGiverGim** [comment]
You have not changed DE, you have changed Spanish.
The translations are managed from
https://crowdin.com/project/betaflight-configurator any change done
directly in the translations file will be replaced by the Crowdin
translations before release.
If you want to help with the translations go there.

**Comment by McGiverGim** [comment]
Sorry, Google translated it to me to Spanish 😅

**Comment by MrTucks** [comment]
Sorry :)
I just re-did the fixes in Crowdin. I think someone needs to approve them

**Comment by McGiverGim** [comment]
In the slack chat official of Betaflight there is a channel #team_translation you can find there the German proofreaders.

**Pull request closed without merging**
