### PR TITLE
IMPROVEMENT: As per suggestion, one RX protocol, and one Telem protocol

### PR DESCRIPTION
**Pull request by blckmn**

### CODE REVIEW

**Comment by McGiverGim** [comment]
Why only one? I suppose the 99% of people will have enough with one, but what is the reason to limit this?

**Comment by blckmn** [comment]
> Why only one? I suppose the 99% of people will have enough with one, but what is the reason to limit this?

I am not a fan of restricting it to one personally. It has been suggested to only allow one, but I have added the for discussion label, as I think it should be discussed first.

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by McGiverGim** [comment]
@blckmn can the users, if they want, use the "custom defines" to define more than one RX protocol, as a workaround for the user who needs more than one? If they can, then this PR is ok to me.

**Comment by blckmn** [comment]
> user

Yes they will be able to do that.

**Review by haslinghuis — APPROVED** [review]

**Review by sugaarK — APPROVED** [review]

**Pull request merged**
